jdx/mise

src/cli/mod.rs, src/plugins.rs, src/test.rs, test/fixtures/Gemfile
Fixes #11
before this would read the legacy file instead of the cache file.
That was fine when I was using .node-version (since they had the same content) but Gemfiles do not.
=> fix legacy file cache

README.md, src/cli/current.rs, src/cli/direnv/snapshots/rtx__cli__direnv__envrc__test__direnv_envrc.snap, src/cli/env.rs, src/cli/ls.rs, src/cli/uninstall.rs, src/cli/where.rs, src/config/config_file/tool_versions.rs, src/config/toolset.rs, src/runtimes.rs, test/cwd/.tool-versions
Fixes #22
These both had faulty logic when fetching versions. The way it's supposed to be:
- `rtx where nodejs` – fetches either the current nodejs from tool-version, or the latest installed version
- `rtx uninstall nodejs@18` – uninstall ALL nodejs versions matching 18*
- `rtx uninstall nodejs` – uninstall ALL nodejs versions
Frankly I'm not entirely sure if the uninstall behavior is what people expect. They may think `rtx uninstall nodejs` only uninstalls the _current_ node version, but I feel in that case I'm not sure what it should do if there are installed but not current versions.
Uninstalling all seems like at least the simplest strategy for now.
=> fix `rtx where`

Cargo.toml, README.md, src/cli/render_help.rs
I like this more because it works for linux too. Because there isn't a need to untar anymore I think this is simple enough, and doesn't scare people away that `| sh` does.
=> use standalone install method as quick start

README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, src/cli/activate.rs, src/cli/deactivate.rs, src/cli/env.rs, src/cli/hook_env.rs, src/cli/render_help.rs, src/shell/mod.rs, src/shell/snapshots/rtx__shell__xonsh__tests__hook_init.snap, src/shell/snapshots/rtx__shell__xonsh__tests__set_env.snap, src/shell/snapshots/rtx__shell__xonsh__tests__unset_env.snap, src/shell/xonsh.rs
Seems to be working (it compiles, and since it's Rust, should be fine :)), installed a tool and check entering/exiting a dir with a `.tool-versions` file, did all the contributing list of checks
(though hate that the all the linters hate properly aligned code and turn ↓ tabular beauty into a ziz-zagged mess
```rs
Some(escaped_char) => escaped_string.push_str(escaped_char),
None               => escaped_string.push(ch), // ← cleaner to see the diff vs ↓
```
```rs
Some(escaped_char) => escaped_string.push_str(escaped_char),
None => escaped_string.push(ch),
```
)
Meanwhile, a few questions/comments:
- var name: I've changed the escape rules for variable values (xonsh uses Python escape rules, not unix shell's), but __NOT__ for variable names — escapes in `$KEY_VAR_with_weird_chars` won't …
=> [feat] add Xonsh shell support

README.md, completions/_rtx, src/cli/activate.rs, src/cli/args/runtime.rs, src/cli/env.rs, src/cli/global.rs, src/cli/install.rs, src/cli/latest.rs, src/cli/local.rs, src/cli/mod.rs, src/cli/render_help.rs, src/cli/uninstall.rs, src/cli/where.rs, src/config/config_file/mod.rs, src/config/mod.rs
Fixes #119
Fixes #92
This fixes a lot of bugs with the 'runtime arg' which is used throughout rtx. It's the argument used in `rtx local RUNTIMEARG`, `rtx where RUNTIMEARG`, `rtx install RUNTIMEARG`, and many more places.
Originally the intention was for this without an "@" to behave the same as "@latest", but it would _also_ sometimes use the version in `.tool-versions`.
This wasn't consistent throughout rtx and broken in several places that's hard to document fully.
What this change does is make a runtime arg like `nodejs` (without an "@"), look up the current version from `.tool-versions`. `nodejs@latest` will always use the latest available release, despite what may be installed. There were attempts to use the latest _installed_ version to avoid a situation where a new runtime is …
=> Fix runtime arg fuzzy matching

src/cli/current.rs, src/cli/direnv/snapshots/rtx__cli__direnv__envrc__test__direnv_envrc.snap, src/cli/env.rs, src/cli/ls.rs, src/cli/where.rs, src/config/config_file/tool_versions.rs, test/cwd/.tool-versions
shfmt@3.5.2 does not exist but because the plugin did not fail on invalid versions, it behaved as if it did. This uses a real version of shfmt
=> test: use shfmt@3.5.1

src/cli/ls.rs, src/config/toolset.rs, src/plugins/mod.rs, src/runtimes/mod.rs
Fixes #119
turns out `Mess` doesn't work the way I thought it did, it looks like it basically just does an alphabetic sort, not semver sort. This makes the versions sorted correctly.
Before:
```
$ rtx ls
-> golang 1.19.5             (set by ~/.tool-versions)
-> hadolint 2.10.0           (set by ~/.tool-versions)
-> java openjdk-19.0.2       (set by ~/.tool-versions)
-> jq 1.6                    (set by ~/src/rtx/.tool-versions)
-> nodejs 18.13.0            (set by ~/src/rtx/.node-version)
-> python 3.10.10            (set by ~/.tool-versions)
python 3.10.9
python 3.11.1
-> python 3.11.2             (set by ~/.tool-versions)
```
After:
```
$ rtx ls
bun 0.5.6
-> golang 1.19.5             (set by ~/.tool-versions)
-> hadolint 2.10.0           (set by ~/.tool-versions)
-> java openjdk-19.0.2 …
```
=> bug: fix semver version sorting

README.md, src/cli/activate.rs, src/cli/alias/ls.rs, src/cli/complete.rs, src/cli/current.rs, src/cli/deactivate.rs, src/cli/direnv/activate.rs, src/cli/doctor.rs, src/cli/env.rs, src/cli/exec.rs, src/cli/global.rs, src/cli/install.rs, src/cli/latest.rs, src/cli/local.rs, src/cli/ls.rs, src/cli/ls_remote.rs, src/cli/mod.rs, src/cli/plugins/install.rs, src/cli/plugins/ls.rs, src/cli/plugins/uninstall.rs, src/cli/plugins/update.rs, src/cli/settings/get.rs, src/cli/settings/ls.rs, src/cli/settings/set.rs, src/cli/settings/unset.rs, src/cli/uninstall.rs, src/cli/where.rs, src/ui/color.rs
I disabled colored help in Clap because the "Example" headers (which are manually created) would not display in color. This brings it back by manually applying the color to the headers.
=> feat: colored help

src/cli/mod.rs, src/cli/version.rs, src/main.rs
This also adds the version to error messages and makes it so config loading will show a friendlier error message unless RTX_DEBUG=1 is set.
Fixes #102
=> bug: ensure `rtx version` works even if config loading fails

README.md, completions/_rtx, src/cli/global.rs, src/cli/local.rs, src/config/config_file/mod.rs
Fixes #67
Before this change the behavior of something like `rtx local ruby` was pretty inconsistent. Generally it would set the version to what was in the global tool-versions file or just error out. Either one seemed pretty useless to me.
I was thinking this could be a "get" instead of "set" mode, so now it will display what the current value is in `.tool-versions`. This is slightly different than `rtx current ruby` because that shows what is the currently used which could be coming from any .tool-versions file (or env var or something). This _only_ shows the value from the current `.tool-versions` file.
I'm not entirely sure this behavior is good/predictable, so I may regret this decision at some point but I think it is at least better than what we have currently.
=> feat: display current tool-versions value if no version set

CONTRIBUTING.md, README.md, src/cli/exec.rs, src/cli/render_help.rs
Found via `codespell -S target,plugins -L crate,esy`
=> docs: fix typos

README.md, src/cli/render_help.rs, src/env_diff.rs, src/hook_env.rs, src/plugins/cache.rs, src/plugins/mod.rs
rather than using gzip for plugin cache, nothing for runtimeconf, and zlib for direnv, this makes everything use zlib. I feel like this may have the potential for small performance increases, but it mostly just makes things consistent.
The downside with this is everyone would need to reinstall all of their runtimes, so we'll need to find a way to migrate first.
=> chore: consolidate compression to use zlib for everything

README.md, src/cli/args/runtime.rs, src/cli/install.rs, src/cli/local.rs, src/cli/render_help.rs, src/config/config_file/mod.rs, src/plugins/script_manager.rs, src/runtimes.rs, src/toolset/builder.rs, src/toolset/mod.rs, src/toolset/tool_version.rs, src/toolset/tool_version_list.rs
Fixes #98
Fixes #120
`ref:` lets you specify a git sha to download
`path:` lets you use a custom runtime directory
`prefix:` forces prefix matching (so you can do `golang@prefix:1.19` to match any "go1.19*" version
=> feat: ref/path/prefix support

.bin/rtx, .github/workflows/rtx.yml, Cargo.toml, src/build_time.rs, src/cli/mod.rs
This will allow me to only enable self-update when
building non-package manager CLIs
=> chore: added self-update feature

src/cli/alias/set.rs, src/cli/alias/unset.rs, src/cli/settings/set.rs, src/cli/settings/unset.rs, src/config/config_file/rtxrc.rs
This uses a OnceCell to help with creating the editable document and memoizing it. It also uses a Mutex which reduces the need to making things mutable. I was using `get_edit()` and `get_or_init_edit()` as a memoizeable and non-memoizable methods, this makes it so `get_edit()` is memoized and doesn't require a mutable reference to Rtxrc
cc @roele
=> refactor: clean up rtxrc editing

justfile
that definitely should not have had "clean" set on it
=> chore: fix coverage action to reuse cache

src/cli/args/runtime.rs, src/cli/local.rs, src/cli/snapshots/rtx__cli__local__tests__local-4.snap, src/cli/snapshots/rtx__cli__local__tests__local-5.snap, src/cli/snapshots/rtx__cli__local__tests__local-6.snap, src/runtimes.rs, src/toolset/tool_source.rs, src/toolset/tool_version.rs
this also allows aliasing `prefix:` and `system`. (no idea why one might want to alias system, but I figure we can allow it)
I noticed this thread and realized people need to alias these as well:
* https://github.com/asdf-vm/asdf-elixir/pull/63
=> bug: allow specifying ref/path as an alias

.tool-versions, e2e/cd/test_bash, src/cli/direnv/snapshots/rtx__cli__direnv__envrc__tests__direnv_envrc.snap, src/cli/env.rs, src/cli/local.rs, src/cli/mod.rs, src/cli/snapshots/rtx__cli__local__tests__local_multiple_versions-2.snap, src/cli/snapshots/rtx__cli__local__tests__local_multiple_versions.snap, src/toolset/mod.rs
this also reversed the order of tool-versions so now it will export PATH that is equivalent to the tool-versions file.
e.g.: this tool-versions:
```
nodejs 18
python 3.11
```
will export:
```
PATH="~/.rtx/installs/node/18/bin:~/.rtx/installs/python/3.11/bin"
```
this shouldn't matter in nearly any case but it should fit more what people expect
=> bug: fix order of env and path when using multiple versions

README.md, src/cli/plugins/install.rs, src/cli/plugins/ls_remote.rs, src/cli/render_help.rs, src/cli/settings/snapshots/rtx__cli__settings__ls__tests__settings_ls.snap, src/cli/settings/snapshots/rtx__cli__settings__set__tests__settings_set.snap, src/cli/settings/unset.rs, src/config/settings.rs, src/env.rs, src/plugins/mod.rs, src/shorthand.rs
See #163
```
❯ RTX_DISABLE_DEFAULT_SHORTHANDS=1 rtx i nodejs@18
[ERROR] No repository found for plugin nodejs
[ERROR] Run with RTX_DEBUG=1 for more information.
[ERROR] rtx 1.14.3-DEBUG macos-arm64 (built 2023-02-22)
❯ RTX_DISABLE_DEFAULT_SHORTHANDS=0 rtx i nodejs@18
rtx nodejs ✓ https://github.com/asdf-vm/asdf-nodejs.git@c9e5df4                                     2s
rtx nodejs@18.14.2 ✓                                                                                7s
```
=> feat: added `RTX_DISABLE_DEFAULT_SHORTHANDS` config

src/env_diff.rs
THis PR adds ignoring of environment variables that are present as a result of exported bash functions and exported bash functions consisting fo multiple lines. e.g.:
```
$ env
...
BASH_FUNC_docker-update-images%%=() {  local _images;
_images=$(docker images --digests | grep -v REPOSITORY | awk '{ if ($1 != "<none>" && $2 != "<none>" && $3 != "<none>") { printf("%s:%s\n", $1, $2) } }' | sort -u);
[[ -n "${DOCKER_IMAGE_FILTER}" ]] && _images=$(echo "${_images}" | grep -E -v "${DOCKER_IMAGE_FILTER}");
for image in ${_images};
do
docker pull "$image";
done;
unset _images
}
...
```
Originaly rtx would try to export each of these lines which resulted in bash errors. e.g.:
```
-bash: export: ` _images=$(docker images --digests | grep -v REPOSITORY | awk '{ if ($1 != "<none>" && $2 != "<none>" …
```
=> fix: ignore env varibales from exported bash functions

.config/nextest.toml, .github/workflows/rtx.yml, e2e/test_plugins_install, src/cache.rs, src/cli/asdf.rs, src/cli/plugins/install.rs, src/cli/plugins/ls.rs, src/cli/plugins/uninstall.rs, src/cli/snapshots/rtx__cli__asdf__tests__fake_asdf_install.snap, src/cli/snapshots/rtx__cli__asdf__tests__fake_asdf_other.snap, src/cli/snapshots/rtx__cli__asdf__tests__fake_asdf_reshim.snap, src/cli/where.rs, src/git.rs, src/test.rs
`cargo test` now takes ~2.5s instead of ~8.5s
I'm using nextest to track slow tests now so they will fail in CI if they take longer than 200ms
most of this is moving slow operations to E2E tests
=> test: improve unit test performance

src/runtimes.rs, src/toolset/tool_version.rs
Creating this file in the installs directory causes erlang to fail to install. This change moves it to the cache directory. Not putting a test in since that will be covered by #182.
Fixes #196
Verified by running `rtx install -f erlang@25.2.1` which fails in main.
=> bug: do not put `.rtx-incomplete` file in install directory

e2e/cd/test_bash, e2e/cd/test_fish, e2e/cd/test_zsh, justfile, src/cli/plugins/snapshots/rtx__cli__plugins__install__tests__tiny.snap, src/cli/plugins/snapshots/rtx__cli__plugins__uninstall__tests__plugin_uninstall-2.snap, src/cli/plugins/snapshots/rtx__cli__plugins__uninstall__tests__plugin_uninstall.snap, src/cli/snapshots/rtx__cli__activate__tests__activate_zsh.snap, src/cli/snapshots/rtx__cli__activate__tests__activate_zsh_legacy.snap, src/shell/bash.rs, src/shell/fish.rs, src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap, src/shell/zsh.rs
Fixes #199
If you use activate in an rc file, this will make it so the binaries are available immediately, e.g.:
```
eval "$(rtx activate bash)"
jq # before this change this wouldn't work if it came from rtx
```
=> bug: immediately call hook-env after activating

e2e/test_lua, src/cli/install.rs, src/cli/snapshots/rtx__cli__install__tests__install_nothing.snap, src/env_diff.rs, src/shell/bash.rs, src/shell/fish.rs, src/snapshots/rtx__env_diff__tests__from_bash_script.snap, test/fixtures/exec-env
Fixes #210 
Lua works now:
```
rtx  multiline-env ❯ rtx activate | source
rtx  multiline-env ❯ rtx shell lua@latest
rtx  multiline-env ❯ lua -v
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
```
Before:
```
rtx  main ❯ rtx activate | source
set: package.cpath : invalid variable name. See `help identifiers`
- (line 6):
set -gx 'package.cpath ' ' package.cpath .. '\'';/Users/jdx/.local/share/rtx/installs/lua/5.4.4/lib/lua/5.4/?.so;/Users/jdx/.local/share/rtx/installs/lua/5.4.4/luarocks/lib/lua/5.4/?.so'\'''
^
from sourcing file -
called on line 17 of file -
in function '__rtx_env_eval'
called on line 40 of file -
from sourcing file -
(Type 'help set' for related documentation)
rtx  main ❯ rtx shell lua@latest
set: package.cpath : invalid variable name. See `help identifiers`
- …
```
=> bug: fix multiline env vars

src/fake_asdf.rs
shims would break if `RTX_EXE` pointed to a shim:
```
rtx  main ❯ ~/.rtx/shims/node -v
✔ Select versions to install · nodejs@18.13.0
Trying to update node-build... ok
Downloading node-v18.13.0-darwin-arm64.tar.gz...
-> https://nodejs.org/dist/v18.13.0/node-v18.13.0-darwin-arm64.tar.gz
Installing node-v18.13.0-darwin-arm64...
Installed node-v18.13.0-darwin-arm64 to /Users/jdx/.local/share/rtx/installs/nodejs/18.13.0
[WARN] Tool not installed: nodejs@18.13.0
node:internal/modules/cjs/loader:1093
throw err;
^
Error: Cannot find module '/Users/jdx/src/rtx/asdf'
at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
at Module._load (node:internal/modules/cjs/loader:934:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
at …
```
=> bug: do not use RTX_EXE in fake-asdf

README.md, src/cli/reshim.rs, src/cli/shell.rs
setting the shell version to 18 should output that node is version 18
=> README: fixed typo on `rtx shell ` example

src/cli/settings/set.rs, src/config/config_file/rtxrc.rs
Currently,
`rtx settings ls` lists `asdf_compat` in it and `rtx settings get asdf_compat` returns `false`
but
`rtx settings get asdf_compat true` and `rtx settings get asdf_compat false` fail:
```
Error:
0: Unknown setting: asdf_compat
Location:
src/cli/settings/set.rs:37
Version:
1.18.2 macos-arm64 (built 2023-02-27)
Suggestion: Run with RTX_DEBUG=1 for more information.
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
In fact, manually setting the value for it in `~/.config/rtx/config.toml` as per the README also fails (even if you are just explicitly setting it to the default of `false`):
```
Error:
0: error loading settings from [...]/.config/rtx/config.toml
1: error parsing toml
2: expected …
```
=> Fix config file and CLI setting for asdf_compat

justfile, man/man1/rtx.1, src/cli/mangen.rs
=> chore: disable colors in manpages

README.md, src/cli/render_help.rs
=> Fix readme shims_dir config name

.github/pull_request_template.md, .github/workflows/rtx.yml
This secret should be available on forks so external
contributors should now have passing E2E tests
=> chore: use GITHUB_TOKEN for E2E tests

.rtx.toml, src/cache.rs, src/cli/external.rs, src/cli/hook_env.rs, src/cli/install.rs, src/cli/plugins/install.rs, src/cli/reshim.rs, src/config/mod.rs, src/env.rs, src/fake_asdf.rs, src/git.rs, src/plugins/mod.rs, src/shorthands.rs, src/toolset/builder.rs, src/toolset/mod.rs, src/toolset/tool_version_list.rs
=> added plugin repository support in .rtx.toml

.bin/rtx, README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, src/cli/shell.rs
- better support for .rtx.toml in local/global commands
- feat: added `rtx shell --unset`
=> shell unset

src/cli/snapshots/rtx__cli__deactivate__tests__deactivate-2.snap, src/shell/snapshots/rtx__shell__zsh__tests__deactivate.snap, src/shell/zsh.rs
Turns out the existing `rtx deactivate` doesn't actually work as expected. In particular, instead of removing `_rtx_hook`, it was actually removing everything _except_ `_rtx_hook` from the `precmd_functions` and `chpwd_functions`.
This commit fixes this.
Relevant documentation from zsh (https://zsh.sourceforge.io/Guide/zshguide05.html)
> The `(r)` flag takes a pattern and substitutes the first element of the array matched [...]
and
From https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion:
> `${name:#pattern}`
> [...] If `name` is an array the matching array elements are removed
=> Fix zsh deactivation

.github/workflows/rtx.yml, justfile
This is needed for the self_update check. GITHUB_TOKEN can be rate limited, but RTX_GITHUB_BOT_TOKEN will not be available on forks
=> chore: use RTX_GITHUB_BOT_TOKEN if available for coverage tests

codecov.yml, src/env_diff.rs, test/fixtures/exec-env
Added a function to escape environment variables (see normalize_escape_sequences). It is mainly based on [ansi-c escape sequences](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences) plus some extra chars ('`', '$'), these  were escaped by bash in my current environment.
I also rewrote the bash script output parsing to escape the values after parsing (mainly  for multiline variables).
**Unit tests**
The unit test were failing in my environment due to the original escaping method. They all now succeed.
I have modified one value in 'test_from_bash_script' which looks that it was incorrectly escaped.
=> bug: fix environment variables escaping (#288)

.rtx.toml, e2e/test_bang, src/toolset/tool_version.rs
this makes it easy to express something like "I want the latest 2 lts releases of node":
```
rtx i nodejs@lts nodejs@lts!-2
```
=> feat: added new syntax for subtracting versions, e.g.: `nodejs@18!-2` to install node-16.x

Cargo.lock, Cargo.toml
This might work better for alpine
=> chore: switch to rustls-tls

e2e/.e2e.rtx.toml, e2e/test_local, src/config/config_file/legacy_version.rs, src/config/config_file/mod.rs, src/config/config_file/rtx_toml.rs, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__env-3.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__path_dirs-2.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__path_dirs-3.snap, src/config/config_file/tool_versions.rs, src/config/mod.rs, src/toolset/mod.rs
This makes it so you can add new directories to PATH in .rtx.toml. This is done by specifying PATH as an array like the following:
```toml
[env]
PATH = [
"/foo",  # absolute path
"./bar", # relative to the directory .rtx.toml is in
"$PATH" # for now this is required to be at the end
]
```
=> feat: support for PATH in .rtx.toml env vars

README.md, src/config/config_file/rtx_toml.rs
2 minor changes: allow using tilde to reference home, and documented the functionality in the README
=> feat: more work with path in .rtx.toml

src/cli/plugins/ls.rs, src/cli/prune.rs
this is helpful for running in docker or places where we have a tarball of the code and not the repo
=> test: do not require git to run unit tests

src/toolset/tool_version.rs
This re-enables a check that prevents reloading all of
the versions of a plugin if we are directly running a
specified version
=> bug: re-enable a performance check

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CONTRIBUTING.md, e2e/run_all_tests, justfile, src/cli/direnv/envrc.rs
Gave this a try but this obviously still needs work. 
```bash
cd .devcontainer
docker build -t local/rtxdevcontainer .
docker run --rm -it -v "$(pwd)"/../:/workspaces/cached local/rtxdevcontainer
```
Mounting the project caused some trouble regarding the CARGO_TARGRET_DIR that clashes with the host which might be of another architecture and therefore causes linking issues etc.
Running in VS Code Dev Containers or plain docker gives mixed results. VS Code adds some environment variables of its own which troubles some tests. Other tests are failing because of different plugin installation paths. Also E2E fail because they can't find the generated `rtx` binary (seems it does not use CARGO_TARGET_DIR/debug/rtx).
=> feat: dockerize dev setup

src/cli/local.rs
Fixes https://github.com/jdxcode/rtx/issues/363
The bug was that it did not "resolve" the versions so it thought everything was always not-installed
=> bug: fix local/global install prompts

README.md, e2e/.e2e.rtx.toml, e2e/cd/test_fish, e2e/test_local, schema/rtx.json, src/config/config_file/rtx_toml.rs, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__path_dirs-3.snap
I think this style is cleaner and does not imply that
it can be used for LD_LIBRARY_PATH or similar env vars
This is a breaking change for .rtx.toml PATH functionality,
but it is marked as experimental so we can change it with
a minor release
=> use env_path instead of env.PATH

justfile, src/cli/ls.rs
=> bug: filter not installed runtimes from ls --parseable

src/runtimes.rs
It would let the `PATH` env uncluttered with non-existent paths (similar to #361)
=> fix(runtime_bin_paths): Check system version before running plugin script

README.md
README previously stated that the plain binary Github release needed untarring. Whereas it can in fact just be installed directly without untarring.
=> docs: README: don't untar Github release

.rtx.toml, README.md, e2e/.e2e.rtx.toml, e2e/config/.e2e.rtx.toml, e2e/test_local, schema/rtx.json, src/config/config_file/rtx_toml.rs
This matches the other config. `dotenv` is still going to be supported for the forseeable future to not break anything, but will probably go away eventually.
=> use `env_file` instead of `dotenv` in .rtx.toml

src/tool.rs
if there was a symlink for a version like go1.20.3 for go1.20,
it was preventing you from installing go1.20 explicitly.
=> bug: fix bug with runtime symlinks

src/config/config_file/rtx_toml.rs, src/config/mod.rs
This could probably be better still, but it is an improvement.
Fixes #472
=> improve error message on missing env_file

README.md, man/man1/rtx.1, src/cli/current.rs
I feel this has some utility even with the changes to `rtx ls`. Without this, there is not an easy command to just get the current version of a plugin with nothing else
=> unhiding current command

.github/workflows/rtx.yml, scripts/release-aur-bin.sh
See https://github.com/jdxcode/rtx/discussions/440
This won't run until ownership of the [rtx-bin AUR package](https://aur.archlinux.org/packages/rtx-bin) has been changed to jdxcode
TODO:
* Would be good to refactor the code shared with the original `rtx` package scripts.
=> ci: Add AUR rtx-bin package

scripts/release-aur-bin.sh
Fixing an error after the first ever attempt at automated release: https://github.com/jdxcode/rtx/actions/runs/4902977788/jobs/8755243840
Error was:
```
+ git push
remote: error: invalid pkgbase: rtx, expected rtx-bin
remote: error: hook declined to update refs/heads/master
```
=> ci: Fix AUR rtx-bin .SRCINFO pkgbase

e2e/test_neovim, src/plugins/external_plugin.rs
Before, this was sending "ref:master" to the plugin which was wrong.
Fixes https://github.com/jdxcode/rtx/issues/527
=> fix ref:master versions

scripts/release-aur-bin.sh
I actually ran this locally to test it pushing an update to teh AUR package repo. So this should actually finally work.
=> ci: AUR rtx-bin use prebuilt binary download URI

docs/node.md, e2e/test_nodejs, src/cli/external.rs, src/plugins/core/node.rs, src/plugins/external_plugin.rs, src/plugins/mod.rs, src/plugins/script_manager.rs, src/tool.rs
This should make it more clear what the topics/commands are.
I also renamed nodebuild -> node-build in the core plugin which hopefully will not be too big of a problem.
Fixes #551
=> added "about" help to external commands

README.md, completions/_rtx, completions/rtx.fish, src/cli/snapshots/rtx__cli__r#use__tests__use_local_tool_versions.snap, src/cli/use.rs, src/config/config_file/mod.rs
=> `rtx use` should use .tool-versions if it exists

src/shell/bash.rs, src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap, src/shell/zsh.rs
This was cargo-cult from reading https://github.com/direnv/direnv/commit/a4632773637ee1a6b08fa81043cacd24ea941489
I don't think we actually need it and it seems to be causing #570
=> remove sigint handling

src/env.rs, src/plugins/core/node.rs, src/plugins/core/python.rs, src/plugins/external_plugin.rs
See #539
this brings the timeout from infinity down to 10 seconds—which is also configurable via `RTX_FETCH_REMOTE_VERSIONS_TIMEOUT=5s`
=> added timeout on fetching remote versions

README.md
GitHub now has it.
> ```console
> do {
>   let rtxpath = $"($nu.config-path | path dirname | path join "rtx.nu")";
>   run-external rtx activate nu --redirect-stdout | save $rtxpath -f;
>   $"\nsource "($rtxpath)"" | save $nu.config-path --append
> }
> ```
becomes
> ```nushell
> do {
>   let rtxpath = ($nu.config-path | path dirname | path join "rtx.nu")
>   run-external rtx activate nu --redirect-stdout | save $rtxpath -f
>   $"\nsource "($rtxpath)"" | save $nu.config-path --append
> }
> ```
=> Use nushell syntax highlighting in README

packaging/alpine/Dockerfile
- add plugin name to legacy file cache
- build alpine with edge
=> build alpine with edge release

README.md, e2e/assert.sh, e2e/test_nodejs, schema/rtx.json, src/cli/settings/snapshots/rtx__cli__settings__ls__tests__settings_ls.snap, src/cli/settings/snapshots/rtx__cli__settings__set__tests__settings_set.snap, src/cli/settings/unset.rs, src/config/config_file/rtx_toml.rs, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-2.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-6.snap, src/config/mod.rs, src/config/settings.rs, src/env.rs, test/fixtures/.rtx.toml
This mainly adds 2 new settings:
* disable_tools: intended to be used for disabling core plugins entirely
* legacy_version_file_disable_tools: turn off legacy version file parsing for specific tools instead of disabling all of them
Fixes #618
=> allow disabling tools

scripts/publish-s3.sh, scripts/release.sh
I believe (since I have to cut a release to fully test) this makes it so you can verify the install.sh script with the following:
```
gpg --keyserver hkps://keys.openpgp.org --recv-keys 408B88DB29DDE9E0
curl https://rtx.pub/install.sh.sig | gpg --decrypt | sh
```
=> gpg sign install.sh

README.md, SECURITY.md, src/build_time.rs, src/cli/mod.rs, src/config/mod.rs, src/duration.rs, src/env.rs, src/main.rs
These made sense when rtx was young, but I think that it is
stable enough we do not need to bother users with update messages so much.
=> remove version/outdated warnings

README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, src/cli/ls.rs, src/cli/snapshots/rtx__cli__ls__tests__ls_prefix.snap
This makes rtx somewhat compatible with asdf syntax like:
asdf list nodejs 16
More work could be done here so that syntax works as well but it's a little tricky to handle all the various ways it should be handled, e.g.:
rtx ls node@16
rtx ls node 16
And then think about how it should behave if `--plugin` is set too.
=> added --prefix flag to ls

README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, src/cli/latest.rs, src/cli/snapshots/rtx__cli__latest__tests__latest_installed.snap, src/tool.rs, src/toolset/tool_version.rs
This provides an alternative way (from #654) that closes a gap where you could not easily get installed versions matching a prefix
Fixes #646
=> added --installed option to latest command

README.md, e2e/gopath/test_gopath, e2e/test_nodejs, src/cli/args/tool.rs, src/cli/current.rs, src/cli/ls.rs, src/cli/plugins/install.rs, src/cli/plugins/link.rs, src/cli/plugins/uninstall.rs, src/cli/plugins/update.rs, src/cli/prune.rs, src/config/config_file/rtx_toml.rs, src/config/config_file/tool_versions.rs, src/main.rs, src/migrate.rs, src/plugins/core/mod.rs, src/plugins/mod.rs
=> alias nodejs -> node and golang -> go

src/shell/bash.rs, src/shell/fish.rs, src/shell/mod.rs, src/shell/nushell.rs, src/shell/snapshots/rtx__shell__bash__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__nushell__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__xonsh__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init_nix.snap, src/shell/xonsh.rs, src/shell/zsh.rs
Following the discussion: https://github.com/jdxcode/rtx/discussions/671#discussioncomment-6417337, adding a special behavior for when `rtx` is installed under the `/nix` prefix: do not add `rtx` binary to the `PATH` environment variable.
=> shells: add special nix behavior

src/env.rs, src/plugins/core/go.rs
https://github.com/jdxcode/rtx/discussions/677
for env names: `RTX_GO_REPO` `RTX_GO_REPOSITORY` `RTX_GO_DOWNLOAD_MIRROR` `RTX_GOLANG_DOWNLOAD_MIRROR`, since there is `RTX_GO_SKIP_CHECKSUM` already in [src/env.rs](https://github.com/jdxcode/rtx/blob/main/src/env.rs#L168C12-L168C32), I choose short version too.
=> feat: add envs for rtx go core plugin

src/env.rs, src/plugins/core/ruby.rs
https://github.com/jdxcode/rtx/discussions/677
=> add envs for rtx ruby core plugin

src/cli/local.rs
This makes it so if you run `rtx use node@20` that will use the latest version of node@20, not the latest installed version.
=> use latest version for `rtx use`

Cargo.lock, Cargo.toml
Fixes #714
This enables reqwests to load OS certificates.
This ensures any extra certificates installed by the user into the OS can be used by rtx.
This is important for environments that have TLS decryption proxies and the resigned CA is trusted.
=> bug: fix self-update Unknown Issuer

README.md
This addresses https://github.com/jdxcode/rtx/issues/635
But!
It should only be merged _after_ `rtx` is available in some stable Nix release. See this backport PR for Nix 23.05: https://github.com/NixOS/nixpkgs/pull/241594
=> Update Nix install instructions

CONTRIBUTING.md, README.md
Per https://manpages.debian.org/bookworm/apt/sources.list.5.en.html#THE_DEB_AND_DEB-SRC_TYPES:_OPTIONS
> The recommended locations for keyrings are /usr/share/keyrings for
> keyrings managed by packages, and /etc/apt/keyrings for keyrings
> managed by the system operator.
Some older distros may not have the dir, create it.
=> Promote /etc/apt/keyrings over /usr/share/keyrings

default.nix
This allows `rtx` to be built from the flake again, fixing #758.
One note is it doesn't use the vendored version of OpenSSL you added, as I don't know where to find those files in the context of `buildRustPackage`.
=> Nix: fix missing OpenSSL

scripts/release-aur-bin.sh
=> fix: deploy arch zsh autocompletion corrently

src/plugins/core/python.rs
it prints log like this when virtualenv not exists
```
$ cd ansible-role-rtx/
[INFO] rtx::plugins::core::python: setting up virtualenv at: /home/deploy/ansible-role-rtx/.venv
```
https://github.com/jdxcode/rtx/issues/634#issuecomment-1638679327
=> print setting up virtualenv when virtualenv not exists

src/plugins/core/python.rs
- https://snarky.ca/why-you-should-use-python-m-pip/
- https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program
Caveat: untested.
=> refactor(python): invoke pip as `python -m pip`

README.md
I have created a new port for rtx in https://github.com/macports/macports-ports/pull/19817. Now users can install RTX through MacPorts. This PR add this information to the README.
=> Add MacPorts as a new installation method

src/cli/version.rs
this hides the git sha if one is not found
=> improve version output

src/cache.rs
=> fix race condition with cache file writing

README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, e2e/run_test, e2e/test_ls_remote, man/man1/rtx.1, src/cli/args/mod.rs, src/cli/args/yes.rs, src/cli/install.rs, src/cli/ls_remote.rs, src/cli/mod.rs, src/cli/plugins/install.rs, src/cli/settings/snapshots/rtx__cli__settings__ls__tests__settings_ls.snap, src/cli/settings/snapshots/rtx__cli__settings__set__tests__settings_set.snap, src/cli/settings/unset.rs, src/config/config_file/rtx_toml.rs, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-2.snap, src/config/settings.rs, src/env.rs, src/plugins/external_plugin.rs, src/plugins/mod.rs, src/tool.rs, src/toolset/mod.rs
=> added confirmation dialog when installing plugins

src/cli/global.rs, src/cli/local.rs, src/cli/snapshots/rtx__cli__global__tests__global-2.snap, src/cli/snapshots/rtx__cli__global__tests__global-3.snap, src/cli/snapshots/rtx__cli__global__tests__global-4.snap, src/cli/snapshots/rtx__cli__global__tests__global.snap, src/cli/snapshots/rtx__cli__local__tests__local_multiple_versions-2.snap, src/cli/snapshots/rtx__cli__local__tests__local_remove-2.snap, src/cli/snapshots/rtx__cli__local__tests__local_remove-3.snap, src/cli/snapshots/rtx__cli__local__tests__local_remove.snap, src/cli/use.rs
also changed the logic slightly to find_up the nearest .rtx.toml if one does not exist
=> rtx-use: show message after setting/removing versions

src/plugins/core/go.rs
Fixes #815 
```
❯ RTX_GO_SET_GOPATH=1 GOPATH=xyz rtx x -- env | grep GOPATH=
GOPATH=/Users/jdx/.rtx/installs/go/1.20.7/packages
RTX_GO_SET_GOPATH=1
❯ RTX_GO_SET_GOPATH=0 GOPATH=xyz rtx x -- env | grep GOPATH=
GOPATH=xyz
RTX_GO_SET_GOPATH=0
❯ GOPATH=xyz rtx x -- env | grep GOPATH=
GOPATH=xyz
❯ RTX_GO_SET_GOPATH=1 rtx x -- env | grep GOPATH=
RTX_GO_SET_GOPATH=1
GOPATH=/Users/jdx/.rtx/installs/go/1.20.7/packages
❯ RTX_GO_SET_GOPATH=0 rtx x -- env | grep GOPATH=
RTX_GO_SET_GOPATH=0
```
=> help tweaks (#817)

src/shell/nushell.rs, src/shell/snapshots/rtx__shell__nushell__tests__hook_init.snap, src/shell/snapshots/rtx__shell__nushell__tests__hook_init_nix.snap
I tried to use rtx along with direnv on nushell, and found `source "~/Library/Application Support/nushell/rtx.nu"` overwrites hook from direnv.
Editing my rtx.nu like this fixes the problem on my environment.
=> stop overwriting pre_prompt and PWD in nushell.rs

packaging/standalone/install.envsubst
The behavior of the `echo` command and its handling of escape sequences, such as `\n`, can exhibit variability across different implementations of shells and utilities. This variability was evident during my experience while executing the `install.sh` script on a newly installed Fedora system:
```bash
[xander@fedora ~]$ curl https://rtx.pub/install.sh | sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  4302  100  4302    0     0  78350      0 --:--:-- --:--:-- --:--:-- 79666
rtx: installing rtx...
rtx: installed successfully to /home/xander/.local/share/rtx/bin/rtx
rtx: run the following to activate rtx in your shell:
echo "eval \"\$(/home/xander/.local/share/rtx/bin/rtx activate bash)\"" >> ~/.bashrc\n # …
```
=> Fix `install.sh` output

src/plugins/core/assets/rubygems_plugin.rb
=> do not reshim if rtx is not on PATH

src/cli/hook_env.rs, src/env.rs
Main purpose is to ensure that RTX_DEBUG/RTX_TRACE are available in plugins
=> clean up logging env var logic

docs/java.md, src/env.rs, src/plugins/core/java.rs
This is first rough draft. Which works with with `sudo`, what i currently don't like yet is that using `sudo` installs the JDK with `root` as the owner which currently fails with an unspecific error (since installation is removed before the symlink remove is attempted). Having root as owner potentially leads to other issues as well.
```
$ sudo env RTX_JAVA_MACOS_INTEGRATION=true .bin/rtx install java@corretto-20.0.2.10.1
$ /usr/libexec/java_home -V
$ sudo env .bin/rtx uninstall java@corretto-20.0.2.10.1
$ /usr/libexec/java_home -V
```
=> add support for macos integration

src/timeout.rs
If run_with_timeout hits the timeout, the mpsc receiver may be dropped, leading to a panic when the background thread later attempts to return its value.
This change simply ignores any error. Since the timeout has already been reached, reporting on this error would just be noise.
A future improvement could be to cancel the background operation, but that would require a much larger refactoring.
Part of #860
=> Avoid panic if run_with_timeout hits timeout.

src/cli/ls.rs
=> fix: Always return a list on 'rtx ls <plugin> --json'

src/cli/doctor.rs
since that's a valid way to use rtx
=> doctor: allow shims on PATH to hide inactive problem

Cargo.lock, Cargo.toml, src/http.rs
I'm not entirely sure if this works since I have no clue how to test it, reqwest seems to strip the content-encoding header
EDIT: I _think_ it is working since I see a new request in the cloudflare analytics that's smaller now that these tests are being run
=> enable http gzip compression

src/shell/bash.rs, src/shell/snapshots/rtx__shell__bash__tests__deactivate.snap
Fixes https://github.com/jdx/rtx/issues/920
=> fix deactivate with existing PROMPT_COMMAND

src/cli/alias/snapshots/rtx__cli__alias__set__tests__alias_set.snap, src/cli/alias/snapshots/rtx__cli__alias__unset__tests__alias_unset.snap, src/plugins/core/node.rs
=> added node 20 as lts

packaging/standalone/install.envsubst
:warning: I haven't figured out how to build the install.sh and test this.
https://zsh.sourceforge.io/Intro/intro_3.html
1. run `ZDOTDIR="~/.zsh" install.sh`
```
rtx: run the following to activate rtx in your shell:
echo "eval \"\$(/home/superuser/.local/share/rtx/bin/rtx activate zsh)\"" >> "~/.zsh/.zshrc"
```
```
rtx: run the following to activate rtx in your shell:
echo "eval \"\$(/home/superuser/.local/share/rtx/bin/rtx activate zsh)\"" >> ~/.zshrc
```
=> feat(zsh): added support for custom $ZDOTDIR

README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, e2e/test_purge, src/cli/plugins/install.rs, src/cli/plugins/ls.rs, src/cli/plugins/uninstall.rs, src/config/mod.rs, src/plugins/external_plugin.rs, src/plugins/mod.rs, src/runtime_symlinks.rs, src/tool.rs, src/toolset/tool_version_list.rs
this changes the behavior of uninstalls to now no longer remove installed plugins, see: https://github.com/jdx/rtx/issues/942
=> plugin-uninstall: added --purge flag

src/shell/nushell.rs, src/shell/snapshots/rtx__shell__nushell__tests__hook_init.snap, src/shell/snapshots/rtx__shell__nushell__tests__hook_init_nix.snap
Should fix https://github.com/jdx/rtx/issues/514 and https://github.com/jdx/rtx/issues/960.
My original fix was to use `extern-wrapped`, but that will be deprecated in the next release of Nushell, so I opted for [`def --wrapped` which was added in nushell 0.86 released three weeks ago](https://www.nushell.sh/blog/2023-10-17-nushell_0_86.html#unified-command-definitions).
If you want more backstory, see [this thread in the Nushell DIscord](https://discord.com/channels/601130461678272522/1167041447090991174/1167041447090991174).
=> fix(nushell): Use extern-wrapped instead of def-env and $env instead of let-env

src/cli/shell.rs, src/shell/bash.rs, src/shell/fish.rs, src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap, src/shell/snapshots/rtx__shell__bash__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init_nix.snap, src/shell/zsh.rs
=> shell: fixed --help flag, added "s" alias

src/cli/self_update.rs
=> self-update: enable zipsign signature verification

src/shell/snapshots/rtx__shell__xonsh__tests__unset_env.snap, src/shell/xonsh.rs
It was raising a TypeError:
```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
TypeError: 'method' object is not subscriptable
Exception raised in event handler; ignored.
```
I was able to build, but running the tests failed with `fatal runtime error: failed to initiate panic, error 5`. I have been using the debug build and it solves the problems.
=> fix: xonsh hook

README.md
add hint for section asdf to rtx
Since rtx main claim is to replace asdf, there should be more visible the steps a user need to change, if they have previous installed asdf.
=> Update README.md: add hint for section asdf to rtx

src/tool.rs
This filters out versions that should be ignored from prefix matches.
Fixes #957
=> ignore -SNAPSHOT versions

e2e/test_nodejs, src/main.rs, src/migrate.rs
If rtx-nodejs (or other deprecated plugins) is installed it should be removed in favor of the core plugins
See discussion in https://github.com/jdx/rtx/issues/956
=> migrate: remove deprecated non-core plugins

src/shell/nushell.rs, src/shell/snapshots/rtx__shell__nushell__tests__hook_init.snap, src/shell/snapshots/rtx__shell__nushell__tests__hook_init_nix.snap
Nushell has deprecated `def-env` in favor of `def --env`, so this PR is for making that replacement. `def-env` will be removed in 0.88, which will be released later on 12/12. I haven't actually tested this yet, though.
=> Use def --env instead of def-env for Nushell script

docs/node.md, src/plugins/core/node.rs
This ended up not being a great idea. It is confusing that it only takes place on _new_ installs
=> node: remove compilation tool opts

e2e/.gitignore, e2e/cd/test_bash, e2e/config/.e2e.rtx.toml, e2e/config/pyproject.toml, e2e/run_test, e2e/test_doctor, e2e/test_local, e2e/test_nodejs, e2e/test_poetry, e2e/test_python, src/cli/which.rs, src/cmd.rs, src/install_context.rs, src/main.rs, src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/node.rs, src/plugins/core/node_build.rs, src/plugins/core/python.rs, src/plugins/core/ruby.rs, src/plugins/external_plugin.rs, src/plugins/mod.rs, src/plugins/script_manager.rs, src/shims.rs, src/tool.rs, src/toolset/mod.rs
Possibly a cheap workaround for https://github.com/jdx/rtx/issues/393. It should make the following
possible:
rtx install python
rtx install poetry # poetry depends on python
If you were to just run `rtx install` and try to install python and
poetry at the same time it would not work, however.
=> load installed/current plugins when installing plugins

e2e/test_use, schema/rtx.json, src/cli/snapshots/rtx__cli__r#use__tests__use_local-2.snap, src/cli/use.rs, src/config/config_file/rtx_toml.rs, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-2.snap, src/config/settings.rs
it might not look like it but this actually removes a massive amount of code since it doesn't rely on `rtx local` for its implementation. I may later refactor `rtx local|global` to also be more like this.
=> use: reuse existing versions

src/cli/direnv/envrc.rs, src/cli/hook_env.rs, src/toolset/mod.rs
This is an env var that poetry/pipenv use to add VIRTUAL_ENV/bin to PATH
while not also creating shims for everything in there.
See https://github.com/jdx/rtx/issues/897
=> support RTX_ADD_PATH

Cargo.lock, Cargo.toml, src/config/settings.rs, src/env.rs
this is just an initial pass that switches over just the env var and defaults, more work will need to be done
=> switch to confique for settings management

.github/workflows/rtx.yml, README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, justfile, lefthook.yml, src/cli/alias/ls.rs, src/cli/asdf.rs, src/cli/env.rs, src/cli/env_vars.rs, src/cli/exec.rs, src/cli/implode.rs, src/cli/ls.rs, src/cli/plugins/install.rs, src/cli/plugins/ls.rs, src/cli/plugins/mod.rs, src/cli/plugins/uninstall.rs, src/cli/prune.rs, src/cli/render_completion.rs, src/cli/settings/set.rs
=> completions: fix some issues with zsh completions

src/cmd.rs
=> node: default PATH to current PATH when compiling

src/plugins/core/java.rs
Resolves https://github.com/jdx/rtx/issues/1110
=> [ISSUE-1110] handle null in java plugin

.idea/inspectionProfiles/Project_Default.xml, src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/mod.rs, src/plugins/core/python.rs, src/plugins/core/ruby.rs, src/plugins/external_plugin.rs, src/plugins/mod.rs
This should improve performance a tad and will also make rtx work better in cases where it does not have GITHUB_API_TOKEN set and is rate-limited on GitHub
=> use rtx-versions.jdx.dev to fetch remote versions

src/plugins/core/python.rs
Fixes #1134 .
According to my quick dig into python core plugin impl, `python_path()` that is used in  `PythonPlugin::install_default_package()` and `PythonPlugin::get_virtualenv()` may point outdated python path when upgrading python@latest.
With this fix `python_path()` returns path based on `ToolVersion::install_path()` to avoid pointing outdated path during upgrade.
=> (python plugin): fixes #1134

README.md, completions/rtx.bash, e2e/test_nodejs, src/cli/uninstall.rs, src/file.rs, src/plugins/mod.rs, src/runtime_symlinks.rs, src/toolset/tool_version.rs
With this change, `rtx uninstall node@20` will uninstall all node versions starting with "20". If multiple match, `--all` needs to be passed.
Fixes #1115
=> uninstall: allow uninstalling all matching

e2e/cd/test_bash, src/cli/hook_env.rs, src/env.rs, src/shell/bash.rs, src/shell/fish.rs, src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap, src/shell/snapshots/rtx__shell__bash__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init_nix.snap, src/shell/zsh.rs
With this change, if you manually run PATH="/foo:$PATH" in
your shell after activating rtx, rtx will keep "/foo" in front of its own PATH entries.
Fixes #863
=> hook-env: keep prepended PATH entries in front

src/plugins/mod.rs
this was here originally but was mistakenly moved during a refactor
Fixes #1156
=> use cache directory for incomplete marker

src/plugins/core/erlang.rs
=> erlang: allow non-version prefixes

src/plugins/core/python.rs
Fits convention in other plugins and makes it so they are what you see and not hard to find towards the start
=> python: show regular cpython versions last

src/shell/bash.rs, src/shell/fish.rs, src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap, src/shell/snapshots/rtx__shell__bash__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap, src/shell/snapshots/rtx__shell__fish__tests__hook_init_nix.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap, src/shell/snapshots/rtx__shell__zsh__tests__hook_init_nix.snap, src/shell/zsh.rs
See https://github.com/Homebrew/homebrew-core/pull/157141
=> activate: use full path to rtx

.github/workflows/rtx.yml, e2e/cd/test_bash, e2e/ruby/test_ruby, e2e/run_test, e2e/test_bang, src/cli/use.rs, src/toolset/mod.rs
e.g.: `rtx use -g node@18` if there is a local .rtx.toml with node already defined
=> use: show warning if setting a version that will not be used

justfile, src/cli/snapshots/rtx__cli__trust__tests__trust-4.snap, src/cli/trust.rs, src/config/config_file/tool_versions.rs, src/config/mod.rs
=> trust: find .rtx.local.toml files

src/cli/version.rs, src/http.rs, src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/erlang.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/mod.rs, src/plugins/core/node.rs, src/plugins/core/python.rs, src/plugins/core/ruby.rs, src/plugins/external_plugin.rs, src/plugins/mod.rs
On my machine this is a a mild performance increase, 5.4ms to 3ms.
It may have something to do with regressions seen in https://github.com/jdx/rtx/discussions/1201
=> lazy-load http client

src/plugins/core/ruby.rs
=> ruby: only warn if build tool cannot update

src/cli/uninstall.rs, src/plugins/core/erlang.rs
=> uninstall: only uninstall 1 version if exact match

README.md
Super minor change... but there was an extra `)`. This removes it.
=> docs(README): extra )

e2e/cd/test_bash, src/cli/activate.rs, src/cli/implode.rs, src/cli/self_update.rs, src/env.rs, src/fake_asdf.rs, src/plugins/script_manager.rs, src/shims.rs, src/test.rs
Direct paths cause failures when updating the CLI if the real path to the binary changes such as with homebrew that puts the version in the path.
=> linux: use argv0 to find rtx bin

src/cli/asdf.rs, src/env.rs, src/main.rs
I am trying to simplify things and take out the concept of "log level". Instead it is just verbose/quiet.
=> verbose: recommend --verbose over setting log level

Cargo.lock, Cargo.toml, README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, src/cli/upgrade.rs
=> upgrade: added --interactive

README.md, completions/_rtx, completions/rtx.bash, completions/rtx.fish, src/cli/activate.rs, src/cli/args/quiet.rs, src/cli/hook_env.rs, src/env.rs, src/hook_env.rs, src/output.rs, src/shell/bash.rs, src/shell/fish.rs, src/shell/mod.rs, src/shell/nushell.rs, src/shell/xonsh.rs, src/shell/zsh.rs, src/ui/mod.rs, src/ui/truncate.rs
Can be disabled with `rtx activate --quiet`
=> hook-env: added warning back for missing installs

README.md, src/config/mod.rs, src/plugins/external_plugin.rs
Moved the logic around to simplify the config loading process.
For now this removes the ability to have project local settings.
Fixes #735
=> config: simplify loading

README.md
RTX_EXPERIMENTAL=1 setting this in .rtx.toml fails with:
```bash
rtx expected value of env.RTX_EXPERIMENTAL to be a string or bool, got: 1
rtx Run with --verbose or RTX_VERBOSE=1 for more information
```
=> docs: correct env variable RTX_EXPERIMENTAL in README

e2e/.test-env2, e2e/test_env, src/cli/settings/snapshots/rtx__cli__settings__ls__tests__settings_ls.snap, src/cli/settings/snapshots/rtx__cli__settings__set__tests__settings_set.snap, src/cli/settings/unset.rs, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__env-5.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-2.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-6.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__path_dirs-5.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_alias-4.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_plugin-4.snap, src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__replace_versions-4.snap, src/config/mod.rs, src/config/settings.rs
This lets you set RTX_ENV_FILE=.env in order to always import a local env file if one exists.
=> env: added RTX_ENV_FILE config

src/plugins/core/java.rs
IMO easiest fix for #1329 would be to only support `tar.gz` for now. It seems all vendors ship archives in this format which also seems to support symlinks properly as opposed to ZIP (rs-zip).
=> fix(java): use tar.gz archives to enable symlink support

src/cli/plugins/install.rs, src/cli/plugins/snapshots/mise__cli__plugins__install__tests__plugin_install_invalid_url.snap
This bans plugin names with ":" in them but that _probably_ wouldn't have worked anyways.
=> fix ssh urls

README.md
Found it somewhat confusing on how [rtx got renamed to mise](https://github.com/jdx/mise/issues/1350) and what the migration path is.  https://mise.jdx.dev/rtx.html page answers a lot of my questions.  Might be helpful for others as well.
=> Update README.md to link to rtx page

src/shell/bash.rs, src/shell/snapshots/mise__shell__bash__tests__hook_init.snap, src/shell/snapshots/mise__shell__bash__tests__hook_init_nix.snap, src/shell/snapshots/mise__shell__zsh__tests__hook_init.snap, src/shell/snapshots/mise__shell__zsh__tests__hook_init_nix.snap, src/shell/zsh.rs
This did not have any technical issues except in the edge-case where the user overrides "test" such as having alias test="...". It's highly unlikely someone would do this with "[".
See https://github.com/jdx/mise/discussions/1338#discussioncomment-8014200
=> not-found: use "[" instead of "test"

src/cli/run.rs, src/cmd.rs
if colors are enabled, make sure we keep them in sub-processes
Partial fix for #1290
=> tasks: set CLICOLOR_FORCE=1 and FORCE_COLOR=1

schema/mise.json
Support tasks with a `description` key in the definition. This allows configs with a description to be validated correctly.
=> Add `description` to task object in JSON schema

src/plugins/core/java.rs
Currently the macOS integration hint is not shown for Zulu distributions since the archive does not contain the `/Contents` folder in the root directory but within a `zulu-{major}.jdk` directory.
We can simply symlink that directory and then check for a `/Contents` directory in the installation root to show the hint for all vendors that support the integration.
=> fix(java): enable macOS integration hint for Zulu distribution

e2e/test_poetry, schema/settings.json, src/cli/settings/ls.rs, src/cli/settings/set.rs, src/cli/settings/unset.rs, src/config/settings.rs, src/http.rs, src/plugins/core/mod.rs, src/plugins/core/python.rs, src/plugins/external_plugin.rs
requires `experimental=1` for now
=> python: add support for precompiled binaries

default.nix, flake.lock, flake.nix
Thank you for your awesome project. This tool is so powerful for me.
I've added some patches to fix build errors on nix flake.
- fix nix flake (fc0534ce9b7cbb3da3fb5a4698b82c71ee3f1822)
-  update lockfile (because rustc 1.70.0 or newer is required)
- resolve OpenSSL error on build
- fix a test to pass because of bash path in `test/cwd/.mise/tasks/filetask`
- add cargo crates required for tests  (9a4547b93d465b38198ee10ecec9d9a0c294b102)
=> fix: nix flake build errors

e2e/test_path_safety, src/shell/bash.rs, src/shell/fish.rs, src/shell/nushell.rs, src/shell/xonsh.rs, src/shell/zsh.rs
attempting to address #1380
After some initial reading/testing, this seems to fix the problematic cases I found, and hopefully the test is helpful.
Also, because the behavior was a bit non-obvious to me, a link to some is_relative() examples
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e806075e086f5d669ae4dfc0f0b40aa9
=> prevent adding relative/empty paths during activation

src/config/config_file/mod.rs, src/config/settings.rs
Fixes https://github.com/jdx/mise/issues/1402
=> allow expanding "~" for trusted_config_paths

src/config/settings.rs
Before this would silently ignore everything in the file.
Fixes https://github.com/jdx/mise/issues/1403
=> disallow [settings] header in settings.toml

src/plugins/mod.rs, src/runtime_symlinks.rs
this makes it possible to do the following:
```sh
$ mise alias set java corretto-17 corretto-17
$ mise install java@corretto-17
$ ~/.local/share/mise/installs/java/corretto-17/bin/javac --version
javac 17.0.9
```
With that alias in place, mise will generate just one symlink for it. We could also add aliases for java directly to the core plugin like we do for [node](https://github.com/jdx/mise/blob/main/src/plugins/core/node.rs#L254-L274).
=> loosen regex for runtime symlink generation

src/plugins/core/python.rs
This commit fixes following issues.
- python default packages are not installed when installing precompiled python (#1419)
- `get_virtualenv()` is not performed when installing precompiled python.
- typo in warning message when installing precompiled python.
=> fix(python): fixes #1419

src/plugins/core/python.rs
just use python-build to compile in this case
=> python: do not panic if precompiled arch/os is not supported

completions/_mise, completions/mise.bash, completions/mise.fish, docs/cli-reference.md, e2e/test_poetry, man/man1/mise.1, src/cli/args/env_var.rs, src/cli/mod.rs, src/cli/set.rs, src/cli/snapshots/mise__cli__env_vars__tests__show_env_vars.snap, src/cli/snapshots/mise__cli__set__tests__env_vars-3.snap, src/cli/snapshots/mise__cli__set__tests__env_vars-5.snap, src/cli/snapshots/mise__cli__set__tests__env_vars_remove-3.snap, src/cli/snapshots/mise__cli__set__tests__env_vars_remove-6.snap, src/cli/snapshots/mise__cli__set__tests__show_env_vars.snap, src/cli/snapshots/mise__cli__unset__tests__unset_remove-4.snap, src/cli/unset.rs
* Use ui::table for better formatting
* Allow viewing a single env var with `mise ev FOO`
* Added --global flag
* renamed to "set" (alias for `env-vars`, `ev` remains)
* Added `mise unset` command
See #1432
=> env-vars: improvements

src/plugins/external_plugin.rs
Some ASDF scripts need ASDF_PLUGIN_PATH to reference patches or other scripts. For compatibility, it is added to the environment variables provided to executed plugin scripts.
=> Fix missing ASDF_PLUGIN_PATH environment variable

schema/mise.json, src/cli/doctor.rs, src/cli/settings/set.rs, src/config/settings.rs, src/test.rs, test/config/config.toml, test/config/settings.toml
Fixes #1436
Moving to `settings.toml` was a regretful mistake. It turns out that having 2 config files in a CLI is just a bad idea. It's confusing to users and ultimately wasn't even necessary so we're going back to 1 file.
Sorry for the musical chairs here. I know breaking changes like that are not great and especially when they get _reverted_ it would be especially maddening. Moving back, however, should not be a breaking change.
We've taken steps to correct this from a project management perspective by setting up an advisory board: https://mise.jdx.dev/team.html You can certainly expect fewer abrupt changes in the future. A group of people able to review decisions like this before I roll out a change is exactly what this project needed.
We've gone through this together and came up with …
=> settings: read from config.toml

e2e/test_npm, src/forge/mod.rs, src/forge/npm.rs
e.g.: `mise use -g npm-prettier@3.2.0`
=> added support for installing directly from npm

src/cli/run.rs
Adds an interactive task selector as mentioned in #1274.
- adds cask `inquire`
- replaces `task not found` error with interactive selection of available tasks
Did not find an easy way to test this. Not sure if theres an easy way send user input to the console.
=> feat: add interactive selection for tasks if task was not found

src/cli/run.rs
we should probably `bail` if the user is in a directory with no taks defined
=> fix: bail out of task suggestion if there are no tasks

src/config/mod.rs
The shell is spammed with a panic message after each command if the current directory is not available, with this PR simply mise ignores/logs if that is the case instead of a hard crash.
I noticed the issue while browsing a remote snapshot directory tree that was FUSE mounted by [kopia](https://github.com/kopia/kopia).
=> fix: no panic on missing current dir

src/shell/bash.rs, src/shell/fish.rs, src/shell/snapshots/mise__shell__bash__tests__hook_init.snap, src/shell/snapshots/mise__shell__bash__tests__hook_init_nix.snap, src/shell/snapshots/mise__shell__fish__tests__hook_init.snap, src/shell/snapshots/mise__shell__fish__tests__hook_init_nix.snap, src/shell/snapshots/mise__shell__zsh__tests__hook_init.snap, src/shell/snapshots/mise__shell__zsh__tests__hook_init_nix.snap, src/shell/zsh.rs
if you type something like "--profile" in you would get a strange error
=> fix not_found handler when command start with "--"

.devcontainer/Dockerfile, e2e/test_go_install, src/forge/go.rs, src/forge/mod.rs
This mimics the NPM/Cargo functionality for Go install.
Things you should look at:
1. is that the best way to get Go into the build/test process?
2. should I be only installing the binary into the rtx path or moving the whole gopath like I am currently? The whole GOPATH benefits sandboxing I guess but would almost definitely result in duplication of libraries across similar project installs. Could alternatively set GOBIN and do an mkdir of the /bin inside the version folder.
Things I noticed while contributing:
- docs on *running* mise or tests without the devcontainer are sparse at best, couldn't figure out how to deactivate mise enough to satisfy the tests
- perhaps an option to run tests in a container would be good? Maybe stepchowfun/toast or earthly or similar?
- It is also pretty …
=> add support for installing directly with go modules

src/config/config_file/mise_toml.rs
=> tasks: fix project_root when using .config/mise.toml or .mise/config.toml

completions/mise.fish, src/shell/completions/fish_complete.rs
hopefully this is more portable. I have no clue how it works.
Fixes #1485
=> fish_completion: fix use of `tac`

src/config/config_file/mise_toml.rs
Closes #1449
These changes make it possible to configure `env` properties across multiple tables via the `[[env]]` syntax while continuing to support the preferred approach of using a single table.
To ensure consistent behavior duplicate keys cannot be specified across tables and will fail to parse with the exception of the `mise` or `_` sub-properties.
Tests could definitely be improved, but I am waiting for feedback on style first.
=> feat(config): support arrays of env tables

src/tera.rs
Adds a `join_path` filter to abstract away path separators so that path references in configuration are system agnostic.
Obviously not a high priority unless/until there is Windows support, but I think having this feature earlier could prevent a lot of unnecessary config cleanup later.
=> feat(template): add join_path filter

Cargo.toml
relevance: #1327
I looked at adding `armv7` and `armv6`.
=> add other arm targets for cargo-binstall

schema/mise.json, src/cli/run.rs
Fixes #1372
Ensures that `sources` or `outputs` defined for tasks are not implicitly matched recursively by base name even when a glob pattern is not provided.
- Special handling is included for relative and absolute paths
- Glob character detection matches [globwalk](https://github.com/Gilnaa/globwalk/blob/master/src/lib.rs#L427-L432)
=> fix(tasks): prevent implicit globbing of sources/outputs

src/cli/direnv/envrc.rs, src/cli/direnv/exec.rs, src/cli/env.rs, src/cli/exec.rs, src/cli/hook_env.rs, src/cli/run.rs, src/cli/set.rs, src/cli/watch.rs, src/config/mod.rs, src/forge/cargo.rs, src/forge/go.rs, src/forge/npm.rs, src/plugins/core/node.rs, src/plugins/core/python.rs, src/plugins/core/ruby.rs, src/plugins/external_plugin.rs, src/toolset/mod.rs
This lazy-loads the env vars from config files.
This is a prereq for #1262 and other env var changes. It will make it easier to perform the template logic in order across the env vars rather than when the file is parsed
=> refactor: env parsing

Cargo.lock, Cargo.toml, src/config/mod.rs, src/file.rs, src/task.rs
Closes #1269
These changes make it possible to define bash tasks in a nested folder structure under the predefined task directories. Tasks defined in directories below the parent `tasks` directory will have implied scope in their names by joining their relative path with `:`s.
For example a task defined at `{{config_root}}/.mise/tasks/a/b/task` will have task name `a:b:task`.
- While `walkdir` was already a transitive dependency it is now a direct dependency to provide recursive walks through the filesystem.
- If a bash script task contains the `:` character it will be replaced by `_` to prevent name collisions.
- Simple enough to test locally so I did, but some integration/e2e tests wouldn't hurt here.
=> feat(tasks): infer bash task topics from folder structure

src/cli/doctor.rs, src/shims.rs
Closes #1511 
These changes enable `mise doctor` to identify missing or extra shims and will request users to run `mise reshim` if needed.
- Quite a bit of refactoring here really just to make the changes more obvious.
- Uses `checks` rather than a warning, but can be trivially updated to warnings if desired
=> feat(doctor): identify missing/extra shims

src/cli/run.rs, src/task.rs
Follows up on #1528 
These changes make it possible to specify glob patterns for `depends` exactly like `mise run [PATTERN]`.
- Globs will now also match aliases which were only limited to matching task names before.
=> feat(tasks): unify glob strategy for tasks and dependencies

completions/_mise, completions/mise.fish, docs/cli-reference.md, src/cli/activate.rs, src/cli/hook_env.rs, src/cli/mod.rs, src/cli/settings/ls.rs, src/cli/settings/set.rs, src/cli/settings/unset.rs, src/config/settings.rs, src/logger.rs, src/shims.rs, src/toolset/mod.rs
this moves away from the hard-to-discover `mise activate --status` to a setting with more granular options
I'm going to try to default to warning but that behavior may change based on feedback.
=> added status settings

e2e/test_env_source, man/man1/mise.1, src/config/env_directive.rs
now you can source bash scripts to get the env vars they export like this:
```toml
[env]
_.source = "some_script.sh"
```
=> added `env._.source` feature

src/shims.rs
Fixes #1526 
Shim diffs were not finding executable shell scripts already present in the shim directory. This change adds proper handling for shims which are not symlinks.
=> fix: properly handle executable shims when getting diffs

src/cli/run.rs
Closed #1265 
Adds a `--show-timings` option to the `mise run` command to display elapsed time after each task.
- Should timings be shown even after failure?
- Should total time also be displayed after all tasks have run?
- What style/format would look best for the new output?
=> feat(tasks): add --timings option for run command

.github/workflows/test.yml, .mise.toml, CONTRIBUTING.md, Cargo.lock, Cargo.toml, justfile, scripts/pre-release-hook.sh, src/cli/run.rs
if a task in a config file starts with "#!" it will be saved to disk and executed as a file
note: this seems to not work correctly in linux so it's still a WIP
=> tasks: use shebang

src/config/config_file/mise_toml.rs, src/config/config_file/mod.rs, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__fixture-5.snap, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__remove_alias-4.snap, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__remove_plugin-4.snap, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__replace_versions-4.snap, src/config/mod.rs, src/task.rs
Closes #1270 
Adds a top-level config Table, `task_config`, which currently has one property `includes`. `includes` is an array of paths which can be used to alter the locations from which file tasks are loaded from.
These paths can be absolute, relative, inside/outside the project, and accepts `~` as a substitution for `$HOME`.
- `includes` is represented as a `BTreeSet` to preserve ordering, allows users to influence load ordering, and to ensure uniqueness.
=> feat(tasks): make script task dirs configurable

completions/_mise, completions/mise.fish, docs/cli-reference.md, e2e/test_tool_versions_alt, src/cli/activate.rs, src/cli/ls.rs, src/cli/settings/ls.rs, src/cli/settings/set.rs, src/cli/settings/unset.rs, src/config/config_file/mod.rs, src/config/mod.rs, src/config/settings.rs, src/toolset/mod.rs
by default this will only show when at least 1 version of the tool has been installed
=> status: make missing tool warning more granular

e2e/test_go_install, src/forge/go.rs
this is suboptimal, but a real solution using the go toolchain is blocked on https://github.com/golang/go/issues/65350
resolves #1495
=> use a bodged loop to handle go forge submodules

src/cli/run.rs, src/cli/upgrade.rs, src/ui/progress_report.rs, src/ui/prompt.rs
I didn't realize you need to give vars a name to prevent them from dropping
=> fixed ctrlc handler

src/task.rs
Deserialization of tasks inadvertently broke Task parsing for the `alias` attribute.
=> fix(tasks): fix parsing of alias attribute

src/cli/args/mod.rs, src/cli/args/tool_arg.rs, src/cli/config/ls.rs, src/cli/prune.rs, src/config/config_file/legacy_version.rs, src/config/config_file/mise_toml.rs, src/config/config_file/mod.rs, src/config/config_file/tool_versions.rs, src/toolset/builder.rs, src/toolset/mod.rs
this is arguably a wash when it comes to the code, I don't think it's that much better, but I do think it will be more reliable and most importantly it shows _much_ better error messages when parsing fails
=> use serde to parse tools

src/shell/fish.rs, src/shell/snapshots/mise__shell__fish__tests__activate.snap
=> fish: reuse existing command_not_found handler

src/config/settings.rs, src/plugins/core/go.rs
The last [patches](https://github.com/jdx/mise/commit/786220c6178625980bdcc61403c32db19d51360f) to `GOROOT` did miss to take over the `/go` suffix in the path, which ends up in various arbitrary errors when running go CLI commands.
The suffix has been added properly before: https://github.com/jdx/mise/commit/786220c6178625980bdcc61403c32db19d51360f#diff-352f25ac643733cdd2fb54a78ced508b3658cab947230ab610b968f154840413L54
=> fix(go): reflect on proper path for `GOROOT`

e2e/test_go_install, src/forge/go.rs
Fixes #1667 
Makes it possible to install a go module from SHA when no tagged versions are available.
=> fix: allow go forge to install SHA versions when no tagged versions present

e2e/test_bun, src/plugins/core/bun.rs
=> fix(bun): install bunx symlink

src/http.rs
Port 80 is blocked CI for more security so I am getting the following error:
```
Error: 
0: error sending request for url (http://mise-versions.jdx.dev/python-precompiled): error trying to connect: operation timed out
1: error trying to connect: operation timed out
2: operation timed out
Location:
src/http.rs:56
```
I added the same logic for retying with https as below which would only occur before if the server responded with an error status. Now it should retry even if the net level request fails.
=> Retry with https if request fails

README.md
Make README logo link to site.
Looks like without a wrapping anchor tag, GitHub will still render the image as a link, but the link is just to the raw image.
=> docs: make README logo link to site

packaging/standalone/install.envsubst
Inverts the logic for the musl/glibc check to ensure we are installing the right version.
Fixes #1716.
=> Fix MUSL check

src/cli/which.rs
This read like it got a tad weird when renaming from rtx to mise
=> Tiny grammar fix

src/forge/mod.rs, src/plugins/core/java.rs, tests/cli/install.rs
SDKMAN uses a different Java versioning scheme as the core plugin, therefore versions in `.sdkmanrc` are reported missing even if they're installed.
SDKMAN is using `{java-version}` ( e.g. 21.0.2) as opposed to vendor versions and different `{vendor}` strings. In most cases the `{vendor-version}` matches the Java Version with an additional build suffix. SDKMAN also supports vendors (bisheng, dragonwell, graalvm, liberica nik, mandrel, trava) that are not available/mappable in the core plugin.
ASDF: `{vendor}-{vendor-version}` (e.g. zulu-21.30.15)
SDKMAN: `{java-version}-{vendor}` (e.g. 21.0.2-zulu)
This PR is an approach to map the SDKMAN version. In case of "zulu" only the major version could be matched as we dont have the java version while matching. Other option would be to remove …
=> fix(java): sdkmanrc zulu JVMs are missing in mise

e2e/test_python, src/config/env_directive.rs
When using the 
```toml
_.python.venv = { path = "{{env.MISE_DATA_DIR}}/python/venv", create = true }
```
Syntax with nested directories, I found that `which python` would report the most globally available `.mise.toml` virtualenv python rather than the more locally specific `.mise.toml`. The `VIRTUAL_ENV` environment variable _would_ be set correctly however, causing a bit of confusion initially.
A minimal example:
```bash
❯ tree -a mise-example
mise-example
├── .mise.toml
└── sub
├── .mise.toml
└── nest
└── .mise.toml
```
```toml
[tools]
python = "3.11"
[env]
_.python.venv = { path = "{{env.MISE_DATA_DIR}}/python/venv/example", create = true }
[tools]
python = "3.9"
[env]
_.python.venv = { path = "{{env.MISE_DATA_DIR}}/python/venv/sub", create = true }
[tools]
python = "3.12"
[env] …
```
=> fix: prepend virtualenv path rather than append

src/cli/tasks/deps.rs
Add `--hidden` option for `task deps` as mentioned in #1755
=> feat(task): add option to show hidden tasks in dependency tree

src/forge/go.rs, src/plugins/mod.rs, src/toolset/tool_version.rs
Attempt to fix #1637 by removing the `v` prefix (if its the only character before the semantic version) from the `ToolVersion::version`.
For Go the prefix is stripped in `GoForge::list_remote_versions` and added for installation in `GoForge::install_version_impl`  since its required for installation.
=> fix(go): go backend supports versions prefixed with 'v'

src/default_shorthands.rs
Update shorthand for `rabbitmq` to forked variant as mentioned in #1776.
Also see https://github.com/mise-plugins/asdf-rabbitmq/pull/1
=> fix: update shorthand for rabbitmq

completions/_mise, docs/cli-reference.md, mise.usage.kdl, src/cli/ls.rs, src/cli/outdated.rs, src/cli/snapshots/mise__cli__outdated__tests__current_json.snap, src/cli/upgrade.rs, src/test.rs
=> outdated: add --json flag

.github/workflows/release-plz.yml, src/forge/cargo.rs, src/forge/go.rs, src/forge/mod.rs, src/forge/npm.rs, src/plugins/external_plugin.rs, src/toolset/mod.rs
all this does is wait to install things like python before poetry, erlang before elixir, etc. It doesn't include them by default, just waits for them to finish installing if they're in process.
This way if you run `mise install` and have python and poetry, it won't start installing poetry until python is installed and can be used as a dependency. It does require that you put these in order manually, if they're not, it just won't wait.
It's basically just calling "sleep()" if one of its dependencies is currently installing. It's far from a comprehensive dependency solution with versions and things. That said, it's a simple solution not likely to cause any problems and should solve some of the most common issues around this.
cc @travisbhartwell
These are all hardcoded for now but it would …
=> feat: very basic dependency support

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
---
- very basic dependency support (#1788) - ([7a53a44](https://github.com/jdx/mise/commit/7a53a44c5bbbea7eed281536d869ec4f39de2527)) - jdx
- update shorthand for rabbitmq (#1784) - ([d232859](https://github.com/jdx/mise/commit/d232859b5334462a84df8f1f0b4189576712f571)) - roele
- display error message from calling usage (#1786) - ([63fc69b](https://github.com/jdx/mise/commit/63fc69bc751e6ed182243a6021995821d5f4611e)) - jdx
- automatically trust config files in CI (#1791) - ([80b340d](https://github.com/jdx/mise/commit/80b340d8f4a548caa71685a6fca925e2657345dc)) - jdx
- move lint tasks from just to mise - ([4f78a8c](https://github.com/jdx/mise/commit/4f78a8cb648246e3f204b426c57662076cc17d5d)) - jdx
- **(changelog)** use github handles - …
=> Release 2024.3.4

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
---
- very basic dependency support (#1788) - ([7a53a44](https://github.com/jdx/mise/commit/7a53a44c5bbbea7eed281536d869ec4f39de2527)) - jdx
- update shorthand for rabbitmq (#1784) - ([d232859](https://github.com/jdx/mise/commit/d232859b5334462a84df8f1f0b4189576712f571)) - roele
- display error message from calling usage (#1786) - ([63fc69b](https://github.com/jdx/mise/commit/63fc69bc751e6ed182243a6021995821d5f4611e)) - jdx
- automatically trust config files in CI (#1791) - ([80b340d](https://github.com/jdx/mise/commit/80b340d8f4a548caa71685a6fca925e2657345dc)) - jdx
- move lint tasks from just to mise - ([4f78a8c](https://github.com/jdx/mise/commit/4f78a8cb648246e3f204b426c57662076cc17d5d)) - jdx
- **(changelog)** use github handles - …
=> Release 2024.3.5

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
---
- very basic dependency support (#1788) - ([7a53a44](https://github.com/jdx/mise/commit/7a53a44c5bbbea7eed281536d869ec4f39de2527)) - jdx
- update shorthand for rabbitmq (#1784) - ([d232859](https://github.com/jdx/mise/commit/d232859b5334462a84df8f1f0b4189576712f571)) - roele
- display error message from calling usage (#1786) - ([63fc69b](https://github.com/jdx/mise/commit/63fc69bc751e6ed182243a6021995821d5f4611e)) - jdx
- automatically trust config files in CI (#1791) - ([80b340d](https://github.com/jdx/mise/commit/80b340d8f4a548caa71685a6fca925e2657345dc)) - jdx
- move lint tasks from just to mise - ([4f78a8c](https://github.com/jdx/mise/commit/4f78a8cb648246e3f204b426c57662076cc17d5d)) - jdx
- **(changelog)** use github handles - …
=> Release 2024.3.6

src/default_shorthands.rs
This fixes #1767 and fixes #1762 by referencing the forked and adapted repository for `jq`.
=> fix: jq Installed Using x86_64 on Apple Silicon using mise

src/shell/snapshots/mise__shell__xonsh__tests__hook_init.snap, src/shell/snapshots/mise__shell__xonsh__tests__xonsh_deactivate.snap, src/shell/xonsh.rs
This fixes https://github.com/jdx/mise/issues/425 by porting the shell function that shadows the `mise` binary from bash/zsh to xonsh.
=> Fix the `shell` subcommand for xonsh

docs/cli-reference.md, src/cli/install.rs
A minor effort in updating the doc. I can see more venues for improvements on:
- mentioning more UX features. 
- clarifying what the default tool's version
I will leave it to future work for now. Perhaps soon! 
The text should be more intuitive for my understanding on #1711
=> Update a few phrases for mise install

src/shell/nushell.rs, src/shell/snapshots/mise__shell__nushell__tests__hook_init.snap
Fixes error when `$env.config` is null. Nu implements default behavior for missing configurations enabling minimal customization in config files.
Additional simplifications:
- save hook to variable vs repeat it
- annotate `cell-path` type vs create it with `into cell-path`
Sorry for such a quick sequel to #1763 😅
=> fix(nu): Gracefully handle missing `$env.config`

src/shims.rs
Fixes #1797.
Use regex to allow binary names such as mise-x64, mise-debug, etc.
=> fix: Apple x64 version of mise doesn't work

.mise/tasks/lint-fix, src/task.rs, test/cwd/.mise/tasks/filetask
=> fix(task): script tasks don't pick up alias from comments

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(task)** script tasks don't pick up alias from comments (#1828) - [7e9b4b7](https://github.com/jdx/mise/commit/7e9b4b7fe17530fd9f5358bb4ccbaabc58576c3a) - [@roele](https://github.com/roele)
- downgrade reqwest to fix self-update - [2f0820b](https://github.com/jdx/mise/commit/2f0820b8b0438f5224c6b2689f51f43b7f907bf5) - [@jdx](https://github.com/jdx)
=> Release 2024.3.9

.github/workflows/audit.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, default.nix, docs/cli-reference.md, man/man1/mise.1, mise.usage.kdl, packaging/rpm/mise.spec
- **(task)** extend mise tasks output by [@roele](https://github.com/roele) in [#1845](https://github.com/jdx/mise/pull/1845)
- **(self-update)** respect yes setting in config by [@jdx](https://github.com/jdx) in [b4c4608](https://github.com/jdx/mise/commit/b4c4608ff2dbbde071e10acf6931204acf6d7d40)
- **(changelog)** fix commit message for releases by [@jdx](https://github.com/jdx) in [646df55](https://github.com/jdx/mise/commit/646df55f0627c80099026849dc235a8c3076a8e3)
- **(changelog)** fix commit message for releases by [@jdx](https://github.com/jdx) in [00d8728](https://github.com/jdx/mise/commit/00d87283181467e73b01b27179c096bb08203619)
- **(changelog)** fix commit message for releases by [@jdx](https://github.com/jdx) in [c5612f9](https://github.com/jdx/mise/commit/c5612f90b4e47bdf12ee …
=> chore: release 2024.3.11

src/config/settings.rs
=> Move logic to set current directory before loading other config

src/plugins/core/python.rs
Hey :wave:
As many users, I disabled pip when outside of virtual environments, to avoid messing with my global installs, using this ~/.pip/pip.conf
```ini
[global]
require-virtualenv = true
```
Unfortunately, it means I must always install Python with `PIP_REQUIRE_VIRTUALENV=false mise install`, as pip is invoked when setting up Python with mise.
This small PR adds the environment variable in the mise command invocations.
__Before__
```
➜ mise install python@3.12.0
Downloading Python-3.12.0.tar.xz...
-> https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tar.xz
Installing Python-3.12.0...
Installed Python-3.12.0 to /Users/gabdug/.local/share/mise/installs/python/3.12.0
ERROR: Could not find an activated virtualenv (required).
mise ~/.local/share/mise/installs/python/3.12.0/bin/python …
```
=> fix(python): install python when pip is disabled outside virtualenv

docs/cli-reference.md, mise.usage.kdl, src/assets/mise-extra.usage.kdl, src/cli/uninstall.rs
=> fix(uninstall): fix uninstall completions

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(doctor)** sort missing shims by [@jdx](https://github.com/jdx) in [f12d335](https://github.com/jdx/mise/commit/f12d3359b054c9b31a785ed9fdc41e20b317ddb4)
- **(uninstall)** fix uninstall completions by [@jdx](https://github.com/jdx) in [#1869](https://github.com/jdx/mise/pull/1869)
- bump h2 from 0.3.25 to 0.3.26 by [@dependabot[bot]](https://github.com/dependabot[bot]) in [#1866](https://github.com/jdx/mise/pull/1866)
- **(audit)** removed workflow since dependabot is already doing this by [@jdx](https://github.com/jdx) in [9138e2e](https://github.com/jdx/mise/commit/9138e2e6ec09a36c7791c9a6b4e5f7ab138fcb63)
- **(mega-linter)** disable RUST_CLIPPY (slow) by [@jdx](https://github.com/jdx) in [8c64153](https://github.com/jdx/mise/commit/8c64153f7c5b3990d3b857b55fb0a94e7c11a6fc)
=> chore: release 2024.4.1

src/cli/args/forge_arg.rs
Mitigates #1904 which was introduced with #1885. 
- Cargo crates use kebab-case (or snake_case?) to they should not cause issues.
- Go packages cannot have dashes so reverting `-` to `/` fixes the issue.
- NPM backend is still problematic as scopes can have `-` and end with `/`, so reverting from for example `npm-@adobe-aio-cli` to `npm:@adobe/aio-cli` can only happen on best guess replacing first dash after the `@`.
=> fix: go backend naming inconsistency (in mise ls and mise prune)

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(doctor)** warn if a plugin overwrites a core plugin by [@roele](https://github.com/roele) in [#1900](https://github.com/jdx/mise/pull/1900)
- **(alpine)** use mise docker image by [@jdx](https://github.com/jdx) in [db65c3f](https://github.com/jdx/mise/commit/db65c3f5de1b1117bc6708b881de86f490057b68)
- go backend naming inconsistency (in mise ls and mise prune) by [@roele](https://github.com/roele) in [#1905](https://github.com/jdx/mise/pull/1905)
- update rust crate built to 0.7.2 by [@renovate[bot]](https://github.com/renovate[bot]) in [#1895](https://github.com/jdx/mise/pull/1895)
- update rust crate either to 1.11.0 by [@renovate[bot]](https://github.com/renovate[bot]) in [#1899](https://github.com/jdx/mise/pull/1899)
- **(pre-commit)** added pre-commit by …
=> chore: release 2024.4.5

src/cli/args/forge_arg.rs, src/forge/cargo.rs, src/forge/forge_meta.rs, src/forge/go.rs, src/forge/mod.rs, src/forge/npm.rs, src/plugins/external_plugin.rs
This is a follow up on #1905 attempting to move the "un-dirname" logic out of the `ForgeArg` into the `Forge` implementations.
Additionally it seems for `Go` while package names cannot have `-`, module names can and often do. So the logic for `Go` will also not work reliably. For example https://pkg.go.dev/search?q=http reveals all sorts of exceptions.
Using a `+` as separator would yield better results but i'm afraid thats not easy to change now is it?
=> refactor: use a metadata file for forges

src/default_shorthands.rs, src/plugins/core/mod.rs, src/plugins/core/zig.rs
Integrated Zig into the list of supported languages. This new addition includes functionality for fetching remote versions, downloading, installing, and verifying the Zig installation. A new `zig.rs` file was created specifically for managing Zig related tasks. The reference to this ZigPlugin was included in the core plugins list.
=> Add Zig language plugin

e2e/test_system, src/cli/exec.rs, src/toolset/builder.rs
Addresses a bug with `mise exec` where using an unversioned tool reference causes the underlying binary to not be installed on first use.
Instead we treat an unqualified tool as having tool@latest and handle that in the else clause.
Discord discussion/question:
```
What's the expected behavior for mise backends when the desired tool@version does not exist in a config file and is not installed and mise x tool@version -- ... is run? I assumed it to be like npx behavior of install if missing then run, but it isn't for most backends other than npm.
For example, if I lack cargo:eza in any of my config files nor installed and run mise x cargo:eza -- which -a eza , I see that it does not install cargo:eza + run the --command with eza install folder in the path. In that case the command fails. …
```
=> fix(exec): default to @latest version

.mise.toml, packaging/dev/Dockerfile
This is an early, draft pull request.
As discussed on discord, its purpose is to have the e2e tests passing in the dev container, and also to use this container to run all the e2e tests in CI.
=> Ensure the e2e tests pass in the dev container

src/plugins/core/zig.rs
Fixes #1956 by fetching the current version for `master` from `https://ziglang.org/download/index.json` on demand without caching (nightly build) and using the `builds` instead of `downloads` context.
cc/ @MustCodeAl
=> fix(zig): can't install zig@master from v2024.4.6

src/config/config_file/mod.rs
Fixes #1746 and fixes #1972.
Trusting a path should update the hash regardless if that file already exists or not. Otherwise changed configurations are never updated which interferes with `MISE_PARANOID`.
=> fix: mise doesn't change the trust hash file

src/cli/backends/ls.rs, src/cli/backends/mod.rs, src/cli/backends/snapshots/mise__cli__backends__ls__tests__backends_list.snap, src/cli/doctor.rs, src/cli/mod.rs, src/forge/mod.rs
Resolves #1983.
**New Command**
Adds a command `backends` with sub-command `ls` to list available backend types.
```bash
$ mise backends
cargo
go
npm
pipx
ubi
```
**New Doctor Section**
Adds a section `backends` to the `doctor` command output and filters out (installed) backends from the `plugins` section since these are shown in `toolset`.
```bash
...
backends: 
cargo
go
npm
pipx
ubi
plugins: 
bun         (core)
deno        (core)
erlang      (core)
...
```
=> feat: cli command for listing backends

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/cli-reference.md, man/man1/mise.1, mise.usage.kdl, packaging/rpm/mise.spec, src/default_shorthands.rs
- **(node)** support comments in .nvmrc/.node-version by [@jdx](https://github.com/jdx) in [5915ae0](https://github.com/jdx/mise/commit/5915ae0a23d322e37f22847be11638f8ba108c15)
- cli command for listing backends by [@roele](https://github.com/roele) in [#1989](https://github.com/jdx/mise/pull/1989)
- **(ci)** git2 reference by [@jdx](https://github.com/jdx) in [#1961](https://github.com/jdx/mise/pull/1961)
- **(docker)** Ensure the e2e tests pass in the dev container by [@Adirelle](https://github.com/Adirelle) in [#1942](https://github.com/jdx/mise/pull/1942)
- **(java)** inconsistent version resolution by [@roele](https://github.com/roele) in [#1957](https://github.com/jdx/mise/pull/1957)
- **(zig)** can't install zig@master from v2024.4.6 by [@roele](https://github.com/roele) in …
=> chore: release 2024.4.9

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(docker)** create path to cargo registry cache by [@jdx](https://github.com/jdx) in [ed91c1c](https://github.com/jdx/mise/commit/ed91c1c5f928751c6bc1ce23ac0595c063648677)
- Revert "fix(java): inconsistent version resolution " by [@jdx](https://github.com/jdx) in [#1993](https://github.com/jdx/mise/pull/1993)
=> chore: release 2024.4.10

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(self-update)** always use rustls by [@jdx](https://github.com/jdx) in [93a9c57](https://github.com/jdx/mise/commit/93a9c57ae895f1772a5ae8146d83713f631c77f1)
- **(java)** added e2e test for corretto-8 shorthand by [@jdx](https://github.com/jdx) in [#1995](https://github.com/jdx/mise/pull/1995)
- **(release)** fix cache by [@jdx](https://github.com/jdx) in [b54b25d](https://github.com/jdx/mise/commit/b54b25d06c49b5116ed37dda4c08005dfe7e6e11)
- fix clippy warnings in latest rust beta by [@jdx](https://github.com/jdx) in [#1994](https://github.com/jdx/mise/pull/1994)
- update rust crate flate2 to 1.0.30 by [@renovate[bot]](https://github.com/renovate[bot]) in [#1997](https://github.com/jdx/mise/pull/1997)
=> chore: release 2024.4.11

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(release)** use target/release dir by [@jdx](https://github.com/jdx) in [e6448b3](https://github.com/jdx/mise/commit/e6448b335cf99db6fb2bdfd4c3f49ba255c2d8de)
- **(release)** fixed the "serious" profile by [@jdx](https://github.com/jdx) in [487a1a0](https://github.com/jdx/mise/commit/487a1a0d336fed180123659ac59d1106d79f2d60)
- **(release)** added "serious" profile by [@jdx](https://github.com/jdx) in [f8ce139](https://github.com/jdx/mise/commit/f8ce139c1d0b41006dbbf1707801bf665f201ec6)
- update rust crate rmp-serde to 1.3.0 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2007](https://github.com/jdx/mise/pull/2007)
- update rust crate base64 to 0.22.1 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2006](https://github.com/jdx/mise/pull/2006)
=> chore: release 2024.5.0

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(ruby)** handle github rate limits when fetching ruby-build version by [@jdx](https://github.com/jdx) in [4a538a7](https://github.com/jdx/mise/commit/4a538a7e282de8c59ba51ec6de64bb715debe022)
- **(ruby)** attempt to update ruby-build if it cannot check version by [@jdx](https://github.com/jdx) in [9f6e2ef](https://github.com/jdx/mise/commit/9f6e2efeb03a9cfc1786f88e84ce03ed6399a304)
- prevent crashing if "latest" is not a symlink by [@jdx](https://github.com/jdx) in [91291e0](https://github.com/jdx/mise/commit/91291e09e8fd3395f8a1265c9af2bd22eff46993)
- edge case around "latest" being the "latest" version by [@jdx](https://github.com/jdx) in [33f5473](https://github.com/jdx/mise/commit/33f547357e9f082115e81ff852c523b406e5226d)
- show source file on resolve error by …
=> chore: release 2024.5.1

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(self_update)** show --version param by [@jdx](https://github.com/jdx) in [#2013](https://github.com/jdx/mise/pull/2013)
=> chore: release 2024.5.2

src/file.rs, src/forge/forge_meta.rs, src/forge/mod.rs, src/runtime_symlinks.rs
Adds some new functions to remove a directory passing in a list of files to ignore for the empty dir check. This allows to remove the (empty) backend directory despite the new hidden `.mise.forge.json` file.
Fixes #2017
=> fix: backend install directory not removed if empty

src/cli/plugins/update.rs, src/git.rs, src/main.rs
This wraps things up so there's no panic when the plugin update fails.
This isn't perfect; it'd be nice to find a way to report the underlying
cause, if possible, but it beats a panic.
``` 
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value:
0: git failed: Cmd(["git", "-C", "/Users/offby1/.local/share/mise/plugins/action-validator", "-c", "safe.directory=/Users/offby1/.local/share/mise/plugins/action-validator", "fetch", "--prune", "--update-head-ok", "origin", "main:main"]) From https://github.com/mpalmer/action-validator
! [rejected]        main       -> main  (non-fast-forward)
0:
Location:
src/git.rs:41
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets. …
```
=> Handle errors from the underlying plugin updates

e2e/.gitignore, e2e/test_env_file_glob, e2e/test_env_source_glob, src/config/env_directive.rs, src/logger.rs
This PR adds support for glob patterns in `env._.file` and `env._.source`.
Implements and fixes #1916
> [!Note] 
> I had to [explicitely disable `globset` logger](https://github.com/jdx/mise/pull/2016/files#diff-6658812715089c8241f20814aaf257dbd94a5448e01cf0010a0a2da54406f844R60) because of [this statement](https://github.com/BurntSushi/ripgrep/blob/master/crates/globset/src/lib.rs#L453-L463).
> Any `print` statement (`println!()`, `trace!()`, `debug()!()`...) called [inside the `std::fmt::Debug::fmt()` call of `Config`](https://github.com/jdx/mise/blob/main/src/config/mod.rs#L592-L620) just deadlock `mise`.
> Given [this line](https://github.com/jdx/mise/blob/main/src/config/mod.rs#L94) on init triggers a `Debug::fmt`, it triggers a deadlock on the first print. Disabling the `globset` …
=> feat(env): supports glob patterns in `env._.file` and `env._.source`

src/cli/prune.rs, src/cli/trust.rs, src/config/mod.rs, src/config/tracking.rs
Fixes #2020 by introducing an experimental `mise config prune` command to prune invalid config file references from `.local/state/mise/(tracked|trusted)-configs`.
=> feat: cleanup invalid symlinks in .local/state/mise/(tracked|trusted)-configs

src/file.rs
this change updates this error message
```bash
mise tracking config: Permission denied (os error 13)
```
to this:
```bash
mise tracking config: failed to ln -sf .../mise/.mise.local.toml ~/pule/.local/state/mise/tracked-configs/35d795b4e6c9a289: Permission denied (os error 13)
```
in my case there was a permission error on the destination link, which triggered an error for each 5 config files it was trying to link on every command. I was seeing this in my terminal, which on its own provides no context for debugging and is very noisy:
```bash
$ mise --version
2024.4.8 macos-arm64 (2024-04-23)
mise tracking config: Permission denied (os error 13)
mise tracking config: Permission denied (os error 13)
mise tracking config: Permission denied (os error 13)
mise tracking config: Permission …
```
=> include symlink error context in error message

src/cli/install.rs, src/cli/latest.rs, src/cli/ls_remote.rs, src/cli/uninstall.rs, src/cli/upgrade.rs, src/cli/use.rs, src/cli/where.rs, src/config/config_file/legacy_version.rs, src/config/config_file/mise_toml.rs, src/config/config_file/mod.rs, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__fixture-3.snap, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__replace_versions.snap, src/config/config_file/tool_versions.rs, src/forge/cargo.rs, src/forge/go.rs, src/forge/mod.rs, src/forge/npm.rs, src/forge/pipx.rs, src/forge/ubi.rs, src/plugins/core/erlang.rs, src/plugins/core/java.rs, src/plugins/core/python.rs, src/plugins/external_plugin.rs, src/plugins/external_plugin_cache.rs, src/toolset/builder.rs, src/toolset/mod.rs, src/toolset/tool_version.rs, src/toolset/tool_version_list.rs, src/toolset/tool_version_request.rs
This will make it possible to delay resolving the version until after dependencies are installed.
Relates to #2053 
Relates to #2046 
Relates to #2029 
Relates to #2028
Relates to #2000
Relates to #1999
=> refactor: move opts from ToolVersion to ToolVersionRequest struct

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(pipx)** remove unneeded unwrap by [@jdx](https://github.com/jdx) in [273c73d](https://github.com/jdx/mise/commit/273c73d15d77d42e8ff4ed732335cc418f903e0b)
- resolve bug with backends not resolving mise-installed tools by [@jdx](https://github.com/jdx) in [#2059](https://github.com/jdx/mise/pull/2059)
=> chore: release 2024.5.5

src/plugins/external_plugin.rs
`PATH` generated from this was like `/Users/user/.local/share/mise/installs/dotnet/8.0.204/.:/Users/user/.local/share/mise/installs/dotnet/8.0.204/shared:other-stuff...` which lead to executable not found.
Now with the fix, the `PATH` becomes `/Users/user/.local/share/mise/installs/dotnet/8.0.204/:/Users/user/.local/share/mise/installs/dotnet/8.0.204/shared:other-stuff...`, and the executable can be found.
This should fix #2076.
=> fix: `.` in `list-bin-paths` was taken as is to form `PATH`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- `.` in `list-bin-paths` was taken as is to form `PATH` by [@FranklinYinanDing](https://github.com/FranklinYinanDing) in [#2077](https://github.com/jdx/mise/pull/2077)
- use fd instead of find for macos compat by [@jdx](https://github.com/jdx) in [#2074](https://github.com/jdx/mise/pull/2074)
- test_java_corretto is not slow by [@jdx](https://github.com/jdx) in [92267b1](https://github.com/jdx/mise/commit/92267b1eb861357433005b26134689b0ce43a2b0)
- mark some e2e tests slow by [@jdx](https://github.com/jdx) in [99f9454](https://github.com/jdx/mise/commit/99f9454e4f062914ab4e4cd950d2f11023bd06bc)
- mark test_pipx as slow by [@jdx](https://github.com/jdx) in [ced564a](https://github.com/jdx/mise/commit/ced564ab5b8786f74d25d2a92e68c58ca488c122)
- add homebrew to e2e PATH by …
=> chore: release 2024.5.9

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, e2e/run_test, man/man1/mise.1, packaging/rpm/mise.spec
- **(exec)** do not default to "latest" if a version is already configured by [@jdx](https://github.com/jdx) in [f55e8ef](https://github.com/jdx/mise/commit/f55e8efccc2050cbf1a9b14f6396d7ee6fc20828)
- **(self_update)** downgrade reqwest by [@jdx](https://github.com/jdx) in [0e17a84](https://github.com/jdx/mise/commit/0e17a84ebe9ea087d27a6c825a0bf6840cfcd3ca)
- prompt to trust config files with env vars by [@jdx](https://github.com/jdx) in [55b3a4b](https://github.com/jdx/mise/commit/55b3a4bb1e394a3830f476594514216a4490de82)
- work with macos /private tmp dir by [@jdx](https://github.com/jdx) in [7d8ffaf](https://github.com/jdx/mise/commit/7d8ffaf2bc3341293b4884df2cdf1e14913f5eb6)
=> chore: release 2024.5.11

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- various performance tweaks by [@jdx](https://github.com/jdx) in [#2091](https://github.com/jdx/mise/pull/2091)
- only set realpath for macos by [@jdx](https://github.com/jdx) in [cdd1c93](https://github.com/jdx/mise/commit/cdd1c935f335e0119a7821b22415b792cc83109a)
=> chore: release 2024.5.12

e2e/forge/test_cargo_binstall_token, e2e/forge/test_ubi_token, src/env.rs, src/forge/cargo.rs, src/forge/ubi.rs
The environment variable GITHUB_TOKEN is passed through calls to ubi and cargo-binstall. If GITHUB_TOKEN is not defined but GITHUB_API_TOKEN is, it is passed GITHUB_TOKEN .
Resolves #2067.
=> feat: pass github token to UBI and cargo-binstall backends.

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- pass github token to UBI and cargo-binstall backends. by [@Adirelle](https://github.com/Adirelle) in [#2090](https://github.com/jdx/mise/pull/2090)
- bubble up resolve errors by [@jdx](https://github.com/jdx) in [#2094](https://github.com/jdx/mise/pull/2094)
- always build with git2 feature by [@jdx](https://github.com/jdx) in [fb51b57](https://github.com/jdx/mise/commit/fb51b57234e3227e00b1866f7ed93bf9d1bc90db)
=> chore: release 2024.5.13

src/env.rs, src/shims.rs, src/toolset/mod.rs
=> fix: hide missing runtime warning in shim context

src/plugins/core/python.rs
=> fix(python): correct flavor for macos-x64

src/cli/args/tool_arg.rs, src/cli/uninstall.rs, src/cli/use.rs, src/config/config_file/legacy_version.rs, src/config/config_file/mise_toml.rs, src/config/config_file/tool_versions.rs, src/toolset/builder.rs, src/toolset/mod.rs, src/toolset/tool_request_set.rs, src/toolset/tool_version_list.rs, src/toolset/tool_version_request.rs
=> fix: handle tool_version parse failures

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(erlang)** make erlang core plugin stable by [@jdx](https://github.com/jdx) in [d4bde6a](https://github.com/jdx/mise/commit/d4bde6a15297d693a00e7194ea3e20f399ae4184)
- **(python)** make python_compile 3-way switch by [@jdx](https://github.com/jdx) in [#2100](https://github.com/jdx/mise/pull/2100)
- raise warning instead if install default gems failed by [@jiz4oh](https://github.com/jiz4oh) in [83350be](https://github.com/jdx/mise/commit/83350be1976185dd2dd2f13e8f7a9ee940449d16)
- **(python)** correct flavor for macos-x64 by [@jdx](https://github.com/jdx) in [#2104](https://github.com/jdx/mise/pull/2104)
- warn if failure installing default packages by [@jdx](https://github.com/jdx) in [#2102](https://github.com/jdx/mise/pull/2102)
- hide missing runtime warning in shim context by …
=> chore: release 2024.5.14

e2e/forge/test_pipx_deep_dependencies, e2e/forge/test_pipx_direct_dependencies
Two E2E tests for https://github.com/jdx/mise/pull/2094
=> test: add E2E tests for plugin dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(registry)** map ubi -> cargo:ubi by [@jdx](https://github.com/jdx) in [#2110](https://github.com/jdx/mise/pull/2110)
- **(tasks)** add --json flag by [@vrslev](https://github.com/vrslev) in [#2116](https://github.com/jdx/mise/pull/2116)
- support "mise.toml" filename by [@jdx](https://github.com/jdx) in [035745f](https://github.com/jdx/mise/commit/035745f95f5f143b62e6d3cdc6cfbaa4a6d887e0)
- add rustfmt to release-plz by [@jdx](https://github.com/jdx) in [2d530f6](https://github.com/jdx/mise/commit/2d530f645b6263c6162380684ab7914efc3dce39)
* @vrslev made their first contribution in [#2116](https://github.com/jdx/mise/pull/2116)
=> chore: release 2024.5.16

Cargo.lock, src/plugins/external_plugin.rs, src/ui/prompt.rs
Fixes #2099 by introducing a new confirmation dialog with Yes/No/All options.
=> feat: confirm all plugins

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- allow install specific version from https://mise.run #1800 by [@Its-Alex](https://github.com/Its-Alex) in [#2123](https://github.com/jdx/mise/pull/2123)
- confirm all plugins by [@roele](https://github.com/roele) in [#2126](https://github.com/jdx/mise/pull/2126)
- allow ignore missing plugin by [@roele](https://github.com/roele) in [#2127](https://github.com/jdx/mise/pull/2127)
- **(pipx)** depend on python by [@jdx](https://github.com/jdx) in [89b9c9a](https://github.com/jdx/mise/commit/89b9c9a7db4e1db624019bb760ed32a76d5a7597)
- fetch transitive dependencies by [@jdx](https://github.com/jdx) in [#2131](https://github.com/jdx/mise/pull/2131)
- pass MISE_LOG_LEVEL through by [@jdx](https://github.com/jdx) in [7dea795](https://github.com/jdx/mise/commit/7dea795967ee11526af6e95a55e19bf7fdd …
=> chore: release 2024.5.17

src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/python.rs, src/plugins/core/zig.rs
Most of these were incorrect and showing warnings on nightly
=> fix: clean up architectures for precompiled binaries

.github/workflows/test.yml, .mise.toml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/registry.md, man/man1/mise.1, packaging/rpm/mise.spec, scripts/render-registry.js, src/forge/cargo.rs, src/registry.rs
- added plugin registry to docs by [@jdx](https://github.com/jdx) in [#2138](https://github.com/jdx/mise/pull/2138)
- added registry command by [@jdx](https://github.com/jdx) in [#2147](https://github.com/jdx/mise/pull/2147)
- pre-commit and github action generate commands by [@jdx](https://github.com/jdx) in [#2144](https://github.com/jdx/mise/pull/2144)
- raise error if resolve fails and is a CLI argument by [@jdx](https://github.com/jdx) in [#2136](https://github.com/jdx/mise/pull/2136)
- clean up architectures for precompiled binaries by [@jdx](https://github.com/jdx) in [#2137](https://github.com/jdx/mise/pull/2137)
- add target and other configs to cache key logic by [@jdx](https://github.com/jdx) in [#2141](https://github.com/jdx/mise/pull/2141)
- remove cmd_forge by …
=> chore: release 2024.5.18

docs/registry.md, src/cli/args/forge_arg.rs, src/cli/registry.rs, src/forge/mod.rs, src/plugins/core/mod.rs, src/registry.rs
A recent bug caused core plugins to override local ones. This is temporary to patch mise, this will be soon fixed along with some tests to verify that core plugin overriding continues to function.
=> fix: allow plugins overriding core plugins

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- toolset -> toolrequestset by [@jdx](https://github.com/jdx) in [#2150](https://github.com/jdx/mise/pull/2150)
- toolset -> toolrequestset by [@jdx](https://github.com/jdx) in [#2151](https://github.com/jdx/mise/pull/2151)
- fix core plugin registry urls by [@jdx](https://github.com/jdx) in [bb1556e](https://github.com/jdx/mise/commit/bb1556ee5a9c7806c28d9bf7472bd444ab70f35e)
- **(pipx)** use python3 instead of python by [@jdx](https://github.com/jdx) in [0ff52da](https://github.com/jdx/mise/commit/0ff52daf026d711d5001cc3af08caef0bdb4d163)
- name cache steps by [@jdx](https://github.com/jdx) in [532fe90](https://github.com/jdx/mise/commit/532fe9032a4f61c2ffbf47d29713ee3900770b55)
- fix lint-fix job by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.5.19

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(prune)** make it not install the world by [@jdx](https://github.com/jdx) in [78f4aec](https://github.com/jdx/mise/commit/78f4aeca2647c3980feb68cd3c1e299c9c56b0d6)
- added test for core plugin overloading by [@jdx](https://github.com/jdx) in [9a56129](https://github.com/jdx/mise/commit/9a5612993dc59359e0c876e8f948f2fece8ce93f)
- added shebang to e2e scripts by [@jdx](https://github.com/jdx) in [#2159](https://github.com/jdx/mise/pull/2159)
=> chore: release 2024.5.20

src/plugins/core/erlang.rs
4.1.1 supports the new OTP 27, including changes to building docs: https://github.com/kerl/kerl/releases/tag/4.1.1
=> chore: update kerl to 4.1.1

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, deny.toml, man/man1/mise.1, packaging/rpm/mise.spec, src/plugins/core/python.rs
- **(git-pre-commit)** rewrite existing git hook to pre-commit.old by [@jdx](https://github.com/jdx) in [#2165](https://github.com/jdx/mise/pull/2165)
- handle issue running `mise install` with existing tools by [@jdx](https://github.com/jdx) in [#2161](https://github.com/jdx/mise/pull/2161)
- update kerl to 4.1.1 by [@bklebe](https://github.com/bklebe) in [#2173](https://github.com/jdx/mise/pull/2173)
* @bklebe made their first contribution in [#2173](https://github.com/jdx/mise/pull/2173)
=> chore: release 2024.5.21

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- correctly use .mise/config.$MISE_ENV.toml files by [@jdx](https://github.com/jdx) in [cace97b](https://github.com/jdx/mise/commit/cace97b9fe7697a58354b93cc1109b14c9fbd30c)
- correctly use .mise/config.$MISE_ENV.toml files by [@jdx](https://github.com/jdx) in [262fa2e](https://github.com/jdx/mise/commit/262fa2e283dbd4c2fe4f44f15d81ab6eed54b79d)
- use async reqwest by [@jdx](https://github.com/jdx) in [#2178](https://github.com/jdx/mise/pull/2178)
- sign macos binary by [@jdx](https://github.com/jdx) in [88f43f8](https://github.com/jdx/mise/commit/88f43f8072a2a223d1be92504cd60b7191ef975b)
- use sccache by [@jdx](https://github.com/jdx) in [#2183](https://github.com/jdx/mise/pull/2183)
- compile on windows by [@jdx](https://github.com/jdx) in [#2184](https://github.com/jdx/mise/pull/2184) …
=> chore: release 2024.5.22

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(self_update)** explicitly set target since there seems to be a bug with .identifier() by [@jdx](https://github.com/jdx) in [#2190](https://github.com/jdx/mise/pull/2190)
- minor race condition creating directories by [@jdx](https://github.com/jdx) in [23db391](https://github.com/jdx/mise/commit/23db39146c8edf7340472302e7f498f1d89cf5b4)
- vendor libgit2 for precompiled binaries by [@jdx](https://github.com/jdx) in [#2197](https://github.com/jdx/mise/pull/2197)
- break coverage tasks up a bit by [@jdx](https://github.com/jdx) in [#2192](https://github.com/jdx/mise/pull/2192)
- updated zip by [@jdx](https://github.com/jdx) in [#2191](https://github.com/jdx/mise/pull/2191)
- bump usage-lib by [@jdx](https://github.com/jdx) in [74fcd88](https://github.com/jdx/mise/commit/74fcd8863c8668f11c …
=> chore: release 2024.5.23

src/cli/trust.rs, src/config/config_file/mod.rs
=> fix: mise trust works incorrectly with symlinked configuration file

src/cli/args/forge_arg.rs, src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/erlang.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/mod.rs, src/plugins/core/node.rs, src/plugins/core/python.rs, src/plugins/core/ruby.rs, src/plugins/core/zig.rs
my long-term goal here is to get rid of `ForgeArg::new()` and just use the FromStr version and the longer-still goal is to help support #2187 by allowing the forges to dispatch between asdf, core, and vfox plugins
=> refactor: simplify ForgeArg building

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec, test/config/config.toml
- **(pipx)** version ordering by [@jdx](https://github.com/jdx) in [#2209](https://github.com/jdx/mise/pull/2209)
- **(use)** re-use mise.toml if exists by [@jdx](https://github.com/jdx) in [#2207](https://github.com/jdx/mise/pull/2207)
- mise trust works incorrectly with symlinked configuration file by [@roele](https://github.com/roele) in [#2186](https://github.com/jdx/mise/pull/2186)
- simplify ForgeArg building by [@jdx](https://github.com/jdx) in [#2208](https://github.com/jdx/mise/pull/2208)
- resolve macros/derived-traits from crates w/ scopes rather than globally by [@donaldguy](https://github.com/donaldguy) in [#2198](https://github.com/jdx/mise/pull/2198)
- eliminate .tool-versions only used for jq by [@donaldguy](https://github.com/donaldguy) in …
=> chore: release 2024.5.24

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- rename External plugins to Asdf by [@jdx](https://github.com/jdx) in [8e774ba](https://github.com/jdx/mise/commit/8e774ba44e933eedfb999259d1244d589fc7d847)
- split asdf into forge+plugin by [@jdx](https://github.com/jdx) in [#2225](https://github.com/jdx/mise/pull/2225)
- added reset() to more tests by [@jdx](https://github.com/jdx) in [1c76011](https://github.com/jdx/mise/commit/1c760112eef92eb51ada4ab00e45568adcf62b97)
- added reset() to more tests by [@jdx](https://github.com/jdx) in [402c5ce](https://github.com/jdx/mise/commit/402c5cee97ebdbeb42fc32d055f73794d4dfdf12)
- dont clean cache on win by [@jdx](https://github.com/jdx) in [ede6528](https://github.com/jdx/mise/commit/ede6528f5fe5e5beeabf0a007997f3abc188faa5)
=> chore: release 2024.5.27

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- bump itertools by [@jdx](https://github.com/jdx) in [#2238](https://github.com/jdx/mise/pull/2238)
- migrate docs repo into this repo by [@jdx](https://github.com/jdx) in [#2237](https://github.com/jdx/mise/pull/2237)
=> chore: release 2024.6.0

src/http.rs
Fixes #2240 by using [read_timeout](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.read_timeout) rather than [timeout](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.timeout)
=> fix: mise up node fails

docs/getting-started.md
When reading the guide I was under impression that I should edit `env.nu` with the given shell script. 
Additionally, the script was mentioning `scripts` folder which did not exist in my setup so the script was failing.
=> docs: nushell installation

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/cli/index.md, man/man1/mise.1, mise.usage.kdl, packaging/rpm/mise.spec
- SPM(Swift Package Manager) backend by [@kattouf](https://github.com/kattouf) in [#2241](https://github.com/jdx/mise/pull/2241)
- mise up node fails by [@roele](https://github.com/roele) in [#2243](https://github.com/jdx/mise/pull/2243)
- fixed syntax by [@jdx](https://github.com/jdx) in [56083f8](https://github.com/jdx/mise/commit/56083f858a4ee28a020a414c1addf0c2bb7968af)
- set GITHUB_TOKEN in dev-test by [@jdx](https://github.com/jdx) in [4334313](https://github.com/jdx/mise/commit/4334313da52c13d7f87656fb0e7978e4cf1f5d2f)
- Update getting-started.md: nushell by [@chrmod](https://github.com/chrmod) in [#2248](https://github.com/jdx/mise/pull/2248)
- update rust crate demand to v1.2.4 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2246](https://github.com/jdx/mise/pull/2246) …
=> chore: release 2024.6.1

docs/.vitepress/config.ts, docs/dev-tools/backends/cargo.md, docs/dev-tools/backends/go.md, docs/dev-tools/backends/index.md, docs/dev-tools/backends/npm.md, docs/dev-tools/backends/pipx.md, docs/dev-tools/backends/spm.md, docs/dev-tools/backends/ubi.md
1. Added document to SPM backend
2. Fix backend src path in dock: `src/forge` -> `src/backend`
=> docs: add SPM backend page

src/toolset/mod.rs
Fixes #2245 by comparing semantic versions rather than checking simply for string inequality.
=> fix: after installing the latest version, mise rolls back to the previous one

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- after installing the latest version, mise rolls back to the previous one by [@roele](https://github.com/roele) in [#2258](https://github.com/jdx/mise/pull/2258)
- add SPM backend page by [@kattouf](https://github.com/kattouf) in [#2252](https://github.com/jdx/mise/pull/2252)
=> chore: release 2024.6.2

src/cli/self_update.rs
Fixes #2263 by adding a hint about GITHUB_API_TOKEN environment variable to the `self-udpate` command.
I don't see an easy way to set a more explicit error message as the underlying `self_update` crate simply throws a generic network error and the status code is lost or rather encoded in the error message.
=> fix: github API rate limiting could be handled more explicitly

src/plugins/asdf_plugin.rs
=> fix: mise plugins ls returns error immediately after install

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- github API rate limiting could be handled more explicitly by [@roele](https://github.com/roele) in [#2274](https://github.com/jdx/mise/pull/2274)
- group prefix not applied for script tasks by [@roele](https://github.com/roele) in [#2273](https://github.com/jdx/mise/pull/2273)
- mise plugins ls returns error immediately after install by [@roele](https://github.com/roele) in [#2271](https://github.com/jdx/mise/pull/2271)
- update dependency vitepress to v1.2.3 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2277](https://github.com/jdx/mise/pull/2277)
- update rust crate regex to v1.10.5 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2278](https://github.com/jdx/mise/pull/2278)
- update rust crate regex to v1.10.5 by …
=> chore: release 2024.6.3

docs/continuous-integration.md
The latest version of [actions/checkout](https://github.com/actions/checkout) is 4 and jdx/mise-action@v2 works fine, so I have updated the documentation.
=> docs: update actions/checkout version

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- Fix link to Python venv activation doc section by [@gzurowski](https://github.com/gzurowski) in [#2353](https://github.com/jdx/mise/pull/2353)
- update built to 0.7.4 and git2 to 0.19.0 by [@roele](https://github.com/roele) in [#2357](https://github.com/jdx/mise/pull/2357)
* @gzurowski made their first contribution in [#2353](https://github.com/jdx/mise/pull/2353)
=> chore: release 2024.7.1

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec, src/backend/cargo.rs, src/backend/go.rs, src/backend/npm.rs, src/cli/prune.rs
- support env vars in plugin urls by [@roele](https://github.com/roele) in [#2370](https://github.com/jdx/mise/pull/2370)
- update rust crate self_update to 0.41 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2359](https://github.com/jdx/mise/pull/2359)
- update dependency vitepress to v1.3.0 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2358](https://github.com/jdx/mise/pull/2358)
=> chore: release 2024.7.2

docs/cli/index.md, docs/dev-tools/backends/pipx.md, docs/dev-tools/backends/spm.md, docs/dev-tools/backends/ubi.md, e2e/style.sh, mise.usage.kdl, scripts/query-top-plugins.fish, src/cli/generate/github_action.rs
No affiliation with GitHub, this just unreasonably bothers me for some reason 🥲
No code changes, only docs/comment changes.
=> chore: Use correct capitalization of GitHub

Cargo.toml
this (might) make mise work with homebrew to fix https://github.com/jdx/mise/issues/2371 but I'm not sure if it will work. It shouldn't _hurt_ anything though since cargo should use the latest version of git2 if it's available
=> chore: loosen git2 requirements

src/env_diff.rs
This should not be necessary anymore now that ruby is a core plugin.
Fixes #2380
=> fix: keep RUBYLIB env var

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/registry.md, man/man1/mise.1, packaging/rpm/mise.spec, registry/README.md, registry/plugins/atlas, src/default_shorthands.rs
- added MISE_LIBGIT2 setting by [@jdx](https://github.com/jdx) in [#2386](https://github.com/jdx/mise/pull/2386)
- keep RUBYLIB env var by [@jdx](https://github.com/jdx) in [#2387](https://github.com/jdx/mise/pull/2387)
- update dependency vitepress to v1.3.1 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2376](https://github.com/jdx/mise/pull/2376)
- update docker/build-push-action action to v6 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2377](https://github.com/jdx/mise/pull/2377)
=> chore: release 2024.7.4

src/cli/use.rs
Fixes #2405 
Not quite sure if this is the correct approach. The [`LOCAL_CONFIG_FILENAMES`](https://github.com/jdx/mise/blob/b9bc7dfef5f804e5c6bb8bf474d857d74ee6eb92/src/config/mod.rs#L458) is very extensive and also contains the path of the global configuration file. So traversing up directories from a directory within user home will at some point find the global configuration. Am i assuming correctly that you could also have the path `.config/mise/config.toml` in a specific project directory?
=> fix: mise use does not create a local .mise.toml anymore

src/plugins/core/zig.rs
Currently ls-remote zig shows `master` as a valid version but this isn't actually accepted by mise and throws a somewhat cryptic error. The correct version to specify if you want nightly is ref:master so this adds a simple transformation to direct the user to the correct value.
Fixes #2403
=> fix: transform `master` to `ref:master` in ls-remote for zig

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/registry.md, man/man1/mise.1, packaging/rpm/mise.spec, registry/README.md, registry/plugins/virtualos, src/default_shorthands.rs
- mise use does not create a local .mise.toml anymore by [@roele](https://github.com/roele) in [#2406](https://github.com/jdx/mise/pull/2406)
- transform `master` to `ref:master` in ls-remote for zig by [@chasinglogic](https://github.com/chasinglogic) in [#2409](https://github.com/jdx/mise/pull/2409)
- bump openssl from 0.10.64 to 0.10.66 by [@dependabot[bot]](https://github.com/dependabot[bot]) in [#2397](https://github.com/jdx/mise/pull/2397)
* @chasinglogic made their first contribution in [#2409](https://github.com/jdx/mise/pull/2409)
=> chore: release 2024.7.5

docs/continuous-integration.md
This pull request fixes 'mise x' command snippet in the Continuous Integration documentation section. 
The link to the original documentation:
* https://mise.jdx.dev/continuous-integration.html#any-ci-provider
=> docs: Fix 'mise x' command snippet in the Continuous Integration section

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- Fix 'mise x' command snippet in the Continuous Integration section by [@mollyIV](https://github.com/mollyIV) in [#2411](https://github.com/jdx/mise/pull/2411)
- retry mise tests for docker-dev-test workflow by [@jdx](https://github.com/jdx) in [cc014dd](https://github.com/jdx/mise/commit/cc014dde3dedd1d891dab62fc37e4633dc995226)
- add BSD-2-Clause to allowed dep licenses by [@jdx](https://github.com/jdx) in [b4ea53c](https://github.com/jdx/mise/commit/b4ea53c4b2b01103ed93fc185dbca858730c3207)
- create new alpine gitlab token to replace the expired one by [@jdx](https://github.com/jdx) in [b30db04](https://github.com/jdx/mise/commit/b30db04aaa1f13ef0dcdf02e6df2f2afbdd73c94)
* @mollyIV made their first contribution in [#2411](https://github.com/jdx/mise/pull/2411)
=> chore: release 2024.8.0

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec, src/env.rs
- various windows bug fixes by [@jdx](https://github.com/jdx) in [90b02eb](https://github.com/jdx/mise/commit/90b02eb49055bc7d458cd3cbfb0de00119539dfb)
- ignore PROMPT_DIRTRIM in diffing logic by [@jdx](https://github.com/jdx) in [7b5563c](https://github.com/jdx/mise/commit/7b5563cd007edf26bc17f07e6cddabacad451e00)
- added information on rolling alpine tokens by [@jdx](https://github.com/jdx) in [bd693b0](https://github.com/jdx/mise/commit/bd693b02fb4d1060ff7a07dcea07b4a7c5584a8b)
- mark releases as draft until they have been fully released by [@jdx](https://github.com/jdx) in [508f125](https://github.com/jdx/mise/commit/508f125dcea9c6d0457b59c36293204d25adc7ef)
- fix windows builds by [@jdx](https://github.com/jdx) in [91c90a2](https://github.com/jdx/mise/commit/91c90a2b2d373998433c641962 …
=> chore: release 2024.8.1

.github/workflows/release.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- windows bug fixes by [@jdx](https://github.com/jdx) in [465ea89](https://github.com/jdx/mise/commit/465ea894f317eda025783e66a68f58ab10319790)
- made cmd! work on windows by [@jdx](https://github.com/jdx) in [c0cef5b](https://github.com/jdx/mise/commit/c0cef5b0941b476badfdbb4f46f24b117d72698d)
- got node to install on windows by [@jdx](https://github.com/jdx) in [e5aa94e](https://github.com/jdx/mise/commit/e5aa94ecb14c7700823ff7dd58a6e633ced5e054)
- windows shims by [@jdx](https://github.com/jdx) in [fc2cd48](https://github.com/jdx/mise/commit/fc2cd489babe834546424831a9613e1d0558aa7d)
- windows paths by [@jdx](https://github.com/jdx) in [a06bcce](https://github.com/jdx/mise/commit/a06bcce484ce405342e68a1ac5dbb667db376f5e)
- fix build by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.8.2

src/github.rs, src/plugins/core/deno.rs
=> fix: spm - cannot install package with null release name field

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- alpine key madness by [@jdx](https://github.com/jdx) in [a7156e0](https://github.com/jdx/mise/commit/a7156e0042cf10fc3d43723ffd6a92860b4faa0a)
- alpine github key by [@jdx](https://github.com/jdx) in [a52b68d](https://github.com/jdx/mise/commit/a52b68d024a8ce9955bd84347cc591b249717312)
- alpine github key by [@jdx](https://github.com/jdx) in [ebc923f](https://github.com/jdx/mise/commit/ebc923ff3c140c6c282bb0c1a2896ad758b4a3c2)
- spm - cannot install package with null release name field by [@roele](https://github.com/roele) in [#2419](https://github.com/jdx/mise/pull/2419)
- removed dead code by [@jdx](https://github.com/jdx) in [#2416](https://github.com/jdx/mise/pull/2416)
=> chore: release 2024.8.4

e2e/backend/test_cargo_compile_git_slow, src/backend/cargo.rs, src/backend/spm.rs, src/cli/args/tool_arg.rs, src/cli/unset.rs, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__fixture-3.snap, src/toolset/tool_version.rs, src/toolset/tool_version_request.rs
=> feat: allow installing cargo packages with `--git`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- show friendly errors when not in verbose/debug mode by [@jdx](https://github.com/jdx) in [#2431](https://github.com/jdx/mise/pull/2431)
- allow installing cargo packages with `--git` by [@jdx](https://github.com/jdx) in [#2430](https://github.com/jdx/mise/pull/2430)
- some ux improvements to `mise sync nvm` by [@jdx](https://github.com/jdx) in [#2432](https://github.com/jdx/mise/pull/2432)
- display untrusted file on error by [@jdx](https://github.com/jdx) in [#2423](https://github.com/jdx/mise/pull/2423)
- `mise trust` issue with unstable hashing by [@jdx](https://github.com/jdx) in [#2427](https://github.com/jdx/mise/pull/2427)
- use newer eza in e2e test by [@jdx](https://github.com/jdx) in [eec3989](https://github.com/jdx/mise/commit/eec3989d8602ebc10304adbd5ded0574fc2981f0)
- take …
=> chore: release 2024.8.5

docs/getting-started.md
This resolves the "Permission denied" issue when running the downloaded binary.
=> docs: add executable permission after installation

src/backend/spm.rs
=> fix: spm backend doesn't allow a GitHub repo name containing a dot

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec, src/cli/ls.rs, src/config/mod.rs, src/env_diff.rs
- spm backend doesn't allow a GitHub repo name containing a dot by [@roele](https://github.com/roele) in [#2449](https://github.com/jdx/mise/pull/2449)
- renamed tool_request_version to tool_request to match the class by [@jdx](https://github.com/jdx) in [76a611a](https://github.com/jdx/mise/commit/76a611ac0f3cfbc7ac58fdc87a528e86ef73507e)
- fix typos again by [@kianmeng](https://github.com/kianmeng) in [#2446](https://github.com/jdx/mise/pull/2446)
- add executable permission after installation by [@kianmeng](https://github.com/kianmeng) in [#2447](https://github.com/jdx/mise/pull/2447)
=> chore: release 2024.8.6

src/config/config_file/mise_toml.rs, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__env-2.snap, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__env-4.snap, src/shell/bash.rs, src/shell/fish.rs, src/shell/nushell.rs
Fixes #2453.
A single quoted `foo='line\nbreak'` results in characters `\` and `n`, while a double quoted `foo="line\nbreak"` results in character `\n`. Seems that the replacement of "\\n" in certain shell implementations causes this behaviour.
=> fix: mise treats escaped newlines in env files differently than dotenvy

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- mise treats escaped newlines in env files differently than dotenvy by [@roele](https://github.com/roele) in [#2455](https://github.com/jdx/mise/pull/2455)
- wait for spawned tasks to die before exiting by [@jdx](https://github.com/jdx) in [#2461](https://github.com/jdx/mise/pull/2461)
- update dependency vitepress to v1.3.2 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2450](https://github.com/jdx/mise/pull/2450)
=> chore: release 2024.8.7

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- split asdf into forge+plugin by [@jdx](https://github.com/jdx) in [#2226](https://github.com/jdx/mise/pull/2226)
- fix home directory for win tests by [@jdx](https://github.com/jdx) in [#2464](https://github.com/jdx/mise/pull/2464)
- update rust crate tabled to 0.16.0 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2452](https://github.com/jdx/mise/pull/2452)
=> chore: release 2024.8.8

src/backend/asdf.rs, src/backend/backend_meta.rs, src/backend/cargo.rs, src/backend/go.rs, src/backend/mod.rs, src/backend/npm.rs, src/backend/pipx.rs, src/backend/spm.rs, src/backend/ubi.rs, src/cli/args/backend_arg.rs, src/cli/ls.rs, src/cli/use.rs, src/config/config_file/mise_toml.rs, src/config/config_file/tool_versions.rs, src/plugins/mod.rs, src/runtime_symlinks.rs, src/toolset/tool_version.rs
This change makes it so when you run `mise use ubi` it saves `ubi` not `cargo:ubi` to mise.toml. It also uses ~/.local/share/mise/installs/ubi as the install path.
This is a prereq for vfox/windows support
=> feat: use registry shortname for mise.toml/install dirs

Cargo.lock, Cargo.toml, build.rs, src/backend/asdf.rs, src/backend/external_plugin_cache.rs, src/backend/mod.rs, src/backend/vfox.rs, src/cli/args/backend_arg.rs, src/cli/backends/snapshots/mise__cli__backends__ls__tests__backends_list.snap, src/cli/doctor.rs, src/cli/plugins/install.rs, src/cli/settings/ls.rs, src/cli/settings/set.rs, src/cli/settings/unset.rs, src/cli/snapshots/mise__cli__trust__tests__trust-6.snap, src/config/settings.rs, src/main.rs, src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/erlang.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/mod.rs, src/plugins/core/node.rs, src/plugins/core/python.rs, src/plugins/core/ruby.rs, src/plugins/core/zig.rs, src/registry.rs, src/shorthands.rs
this is very, very experimental. Don't try to use it. It almost certainly won't work for you yet.
=> feat: vfox backend

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- use registry shortname for mise.toml/install dirs by [@jdx](https://github.com/jdx) in [#2470](https://github.com/jdx/mise/pull/2470)
- vfox backend by [@jdx](https://github.com/jdx) in [#2187](https://github.com/jdx/mise/pull/2187)
- hide file tasks starting with "." by [@jdx](https://github.com/jdx) in [#2466](https://github.com/jdx/mise/pull/2466)
- mise prune removes tool versions which are in use by [@roele](https://github.com/roele) in [#2469](https://github.com/jdx/mise/pull/2469)
- cargo_binstall missing from set commands by [@roele](https://github.com/roele) in [#2471](https://github.com/jdx/mise/pull/2471)
- only warn if config properties are not found by [@jdx](https://github.com/jdx) in [#2472](https://github.com/jdx/mise/pull/2472)
- Asdf -> AsdfBackend by …
=> chore: release 2024.8.9

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- vendor git2 openssl by [@jdx](https://github.com/jdx) in [#2481](https://github.com/jdx/mise/pull/2481)
- python-compile setting by [@jdx](https://github.com/jdx) in [#2482](https://github.com/jdx/mise/pull/2482)
- reset test by [@jdx](https://github.com/jdx) in [000fdb8](https://github.com/jdx/mise/commit/000fdb8560b9994e7678924978cf1866bd58e623)
- reset test by [@jdx](https://github.com/jdx) in [2deb6ce](https://github.com/jdx/mise/commit/2deb6cef5bca37a5bb8e769293e4a665f533209e)
- reset test by [@jdx](https://github.com/jdx) in [385c09b](https://github.com/jdx/mise/commit/385c09b88013281af6a5adc9706a9d85e951ff61)
- update dependency vitepress to v1.3.3 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2478](https://github.com/jdx/mise/pull/2478)
=> chore: release 2024.8.12

.github/workflows/docs.yml, .github/workflows/release-plz.yml, .github/workflows/test-plugins.yml
My fork was giving me daily error messages of the release-plz job.
I went through the workflows and pinned some of the automatic stuff to just your repo. And where it seemed to make sense kept the possibility to request a manual run from a fork.
PS: When making this PR, I noticed tests are run too, even though I haven't touched any code. Maybe I can make those path dependant, if you like.
=> chore: make some gh workflows only run on jdx/mise

src/backend/cargo.rs, src/backend/go.rs, src/backend/npm.rs, src/backend/pipx.rs, src/backend/spm.rs, src/backend/ubi.rs
It seems that most backends do not respect the `MISE_FETCH_REMOTE_VERSIONS_CACHE` yet which leads to non-detected outdated tools as mentioned in #2503.
Fixes #2503.
=> fix: npm backend not finding updates

src/path_env.rs
The original submitter of Issue 2504 triggered the JoinPathsError when adding a python env in the [env] section:
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
I noticed the same error independently when using the `poetry` plugin and attempting to run `[tasks]`. Consider the following `.mise.toml` file that works fine:
```
[tools]
[tools.poetry]
version = 'latest'
pyproject = 'pyproject.toml'
[tools.python]
version = '3.11'
#virtualenv = '.venv'
[tasks.foo]
run = "echo foo"
```
Running the `foo` task works:
```
❯ mise r foo
[foo] $ echo foo
foo
```
But now if I activate that `virtualenv` config line:
```
[tools]
[tools.poetry]
version = 'latest'
pyproject = 'pyproject.toml'
[tools.python]
version = '3.11'
virtualenv = '.venv'
[tasks.foo]
run = …
```
=> fix(src/path_env.rs): Issue 2504: Fix for JoinPathsError

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/registry.md, man/man1/mise.1, packaging/rpm/mise.spec, registry/README.md, registry/plugins/glow, src/default_shorthands.rs
- **(cargo)** allow specifying features via tool options by [@jdx](https://github.com/jdx) in [#2515](https://github.com/jdx/mise/pull/2515)
- **(zig)** make dev builds installable by [@jdx](https://github.com/jdx) in [#2514](https://github.com/jdx/mise/pull/2514)
- add support for using `uv tool` as a replacement for pipx by [@antoniomdk](https://github.com/antoniomdk) in [#2509](https://github.com/jdx/mise/pull/2509)
- **(src/path_env.rs)** Issue 2504: Fix for JoinPathsError by [@mcallaway](https://github.com/mcallaway) in [#2511](https://github.com/jdx/mise/pull/2511)
- block remote versions which are not simple versions by [@jdx](https://github.com/jdx) in [ba90c3b](https://github.com/jdx/mise/commit/ba90c3bbe71bd33d628df607326da9f0cf363af1)
- npm backend not finding updates by …
=> chore: release 2024.8.14

src/cli/ls_remote.rs, src/cli/snapshots/mise__cli__ls_remote__tests__ls_remote_prefix-3.snap
=> fix: ls-remote doesn't support @sub-X style versions

e2e/backend/test_pipx_extras, e2e/backend/test_pipx_slow, src/backend/pipx.rs
Closes #2491
Some Python tools support optional features upon package installation, via `pipx install package[feature,…]`. This is used, for example, by [Harlequin](https://harlequin.sh/docs/getting-started).
This PR adds support for specifying extras via
```toml
mytool = { version = '3.10', extras = 'foo,bar' }
```
NOTE: It only works for tools published to a registry (e.g PyPI), git-based tools require a different syntax than the one already implemented. (`git+...#egg=project[...]`).
NOTE: I had some issues setting up the local docker environment (unrelated to this project), so I couldn't run the e2e tests. There may be other parts of the code that could complain if using `[, ]` in the tool name, but the PyPI resolution error is the first one that popped up when trying to use package …
=> feat(pipx): add support for specifying package extras

src/backend/mod.rs, src/cli/current.rs, src/cli/doctor.rs, src/cli/ls.rs, src/cli/outdated.rs, src/cli/uninstall.rs, src/cli/upgrade.rs, src/cli/where.rs, src/toolset/mod.rs, src/toolset/tool_request.rs, src/toolset/tool_version.rs
Previously `mise ls` could show missing runtimes, but `mise install` would report all runtimes were installed. The latter only checked if the install directory existed, which could be present if `mise install` aborted early. However, the former also checked the existence of the runtime symlink and the `incomplete` file in the cache.
To make this behavior consistent, dispatch the tool request to the backend. Exclude the runtime symlink check since this breaks the install check for `node@latest`.
Closes https://github.com/jdx/mise/issues/2257
=> fix: ensure `mise install` installs missing runtimes listed in `mise ls`

e2e/backend/test_npm, src/backend/cargo.rs, src/backend/mod.rs, src/backend/npm.rs, src/backend/pipx.rs, src/backend/ubi.rs
When installing a tool via one of the experimental backends (`npm`, `pipx`, etc), the install would fail if the backend was managed by `mise` itself. 
When setting up the paths for the installation command (`npm install tldr`) to run, `mise` wasn't making the backends specified in `get_dependencies` available to the subshell. So, they'd fail with a cryptic error:
```
No such file or directory (os error 2)
```
This was because `npm` wasn't in the path, despite it being installed. 
I restructured some existing code to make creating a Toolset for a backend's dependents simple, then prepended those paths to the resulting command. I've confirmed locally that installations commands that fail without the
I also added a line to an e2e test, but I wasn't able to get those running locally in …
=> fix: Ensure dependencies are available for alternative backends

.gitignore, schema/mise.json, schema/settings.json, src/cli/install.rs, src/cli/plugins/link.rs, src/cli/plugins/ls.rs, src/cli/plugins/snapshots/mise__cli__plugins__ls__tests__plugin_list.snap, src/cli/settings/ls.rs, src/cli/settings/set.rs, src/cli/settings/unset.rs, src/cli/snapshots/mise__cli__install__tests__install_nothing.snap, src/cli/use.rs, src/config/settings.rs, src/output.rs, src/plugins/core/python.rs, tests/cli/data/configs/.mise.toml
First draft for a very pragmatic approach on mise hints. Just adds a simple `hint!` macro with static args which respects the setting. Since i wasn't able to figure out yet how to have a multi-type setting i thought it might be handy to use `disable_hints= ["*"] ` as a way to disable all commands (IIRC we use `*` for running all tasks as well?)
It might be nicer to have something which we could pin to the run method such as `#[hint(...)]` (derive, proc_macro?). Not sure if Rust has something similar to Aspects in Java which allows you to run stuff after/before method calls etc.
Still a bit undecided about the styling. We probably should stick to a `dim` prefix like info messages but should highlight the command somehow with `bold`?
Fixes #2460
=> feat: mise hints

src/shell/fish.rs, src/shell/snapshots/mise__shell__fish__tests__activate.snap
The if statement syntax is wrong due to which __mise_fish_command_not_found function not created.
As shown in this screenshot.
=> fix: Update fish.rs for activation of mise

src/plugins/asdf_plugin.rs
=> fix: mise plugins ls command should ignore .DS_Store file on macOS

docs/cli/deactivate.md, docs/cli/index.md, src/cli/deactivate.rs
=> fix: mise deactivate zsh does not work, but mise deactivate does

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, mise.usage.kdl, packaging/rpm/mise.spec
- add global --env argument by [@roele](https://github.com/roele) in [#2553](https://github.com/jdx/mise/pull/2553)
- mise plugins ls command should ignore .DS_Store file on macOS by [@roele](https://github.com/roele) in [#2549](https://github.com/jdx/mise/pull/2549)
- mise deactivate zsh does not work, but mise deactivate does by [@roele](https://github.com/roele) in [#2550](https://github.com/jdx/mise/pull/2550)
- ignore RUSTSEC-2024-0370 by [@jdx](https://github.com/jdx) in [2de83b1](https://github.com/jdx/mise/commit/2de83b1af9e4c408886e8d756e734fa70f62e477)
=> chore: release 2024.9.1

src/plugins/core/ruby.rs
=> fix: ruby ls-remote not showing alternative implementations

Cargo.lock, Cargo.toml, src/tera.rs
I implemented these functions:
- arch
- num_cpus
- os
- os_family
- invocation_directory
- quote
- kebabcase
- lowercamelcase
- shoutykebabcase
- shoutysnakecase
- snakecase
Since there are difference from `just`, I figure it's good to check in before I continue implementing more and add documentation.
1. `PlatformInfo` provides "runtime" information as `uname`. `just` returns `target` information. I don't agree on correctness since it will break if you cross-compile. It's always a hassle for package managers. So `PlatformInfo` API provides a different output than `just`'s.
I took inspiration from [YADM's template design](https://yadm.io/docs/templates). I provide the result of `arch`, `os`, ... as is. This behavior aligns with `direnv` where `direnv` exposes no arch information. It's …
=> feat: implement a few tera functions for mise toml config

src/env.rs
The long or short arg reported by clap does not include the leading hyphens required when parsing.
=> fix: Look for `-P` or `--profile` to get mise environment.

Cargo.lock, Cargo.toml, docs/templates.md, src/config/env_directive.rs, src/file.rs, src/hash.rs, src/tera.rs
in mise I try to stick to "x64/arm64" consistently because tools, rust, operating systems all name these things differently.
I think "invocation_directory" is already available somewhere but I need to find what it is and also standardize some of the naming of directories like "project_root" and "config_root".
=> fix: some fixes for new tera template helpers

.mise/tasks/release-plz, README.md
* Removed `mise` prefix and added hash and date (whereas hash for latest version is bogus as it is not known at that time)
* Specific version has been adapted and is not replaced by the release-plz task anymore.
Fixes #2495
=> fix: wrong version in the README example when install specific version

src/backend/mod.rs, src/plugins/core/java.rs, src/plugins/core/ruby.rs
* moved `fuzzy_match_filter` to the `Backend` trait to allow core plugins to override
* `regex::escape` the  `query` to allow special chars such as `+`
Fixes #1737
=> fix: cannot install truffelruby

docs/templates.md, src/env.rs, src/tera.rs
Fixes #2049
I missed a few XDG paths and `absolute`. Ping me if we want the rest of XDG directories in mise.
For `absolute`, do we wait rust stable feature to add it? (I left a TODO in the `tera.rs`)
=> feat: add rest of tera features for templates

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec, registry/README.md, registry/plugins/atmos, src/env.rs, src/tera.rs
- support for global configuration profiles by [@roele](https://github.com/roele) in [#2575](https://github.com/jdx/mise/pull/2575)
- add Atmos by [@mtweeman](https://github.com/mtweeman) in [#2577](https://github.com/jdx/mise/pull/2577)
- add semver matching in mise templates by [@erickguan](https://github.com/erickguan) in [#2578](https://github.com/jdx/mise/pull/2578)
- add rest of tera features for templates by [@erickguan](https://github.com/erickguan) in [#2582](https://github.com/jdx/mise/pull/2582)
- fix a few tera filter error messages by [@erickguan](https://github.com/erickguan) in [#2574](https://github.com/jdx/mise/pull/2574)
- use "windows" instead of "win" by [@jdx](https://github.com/jdx) in [3327e8c](https://github.com/jdx/mise/commit/3327e8c5eca4dc39529790c4b830fdcca57ebe …
=> chore: release 2024.9.4

docs/cli/index.md, docs/cli/run.md, docs/cli/tasks/run.md, docs/tasks/script-tasks.md, mise.usage.kdl, src/cli/run.rs, src/config/mod.rs, src/task.rs
=> feat(tasks): allow mise-tasks or .mise-tasks directories

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/registry.md, man/man1/mise.1, packaging/rpm/mise.spec, registry/README.md, registry/plugins/atmos, src/default_shorthands.rs
- **(tasks)** allow mise-tasks or .mise-tasks directories by [@jdx](https://github.com/jdx) in [#2610](https://github.com/jdx/mise/pull/2610)
- **(windows)** added ruby core plugin by [@jdx](https://github.com/jdx) in [#2599](https://github.com/jdx/mise/pull/2599)
- periodically prune old cache files by [@jdx](https://github.com/jdx) in [#2603](https://github.com/jdx/mise/pull/2603)
- take npm/cargo backends out of experimental by [@jdx](https://github.com/jdx) in [5496cef](https://github.com/jdx/mise/commit/5496cef30819a3998a52a8f5e6e2d91cfa3e86b0)
- **(ruby)** fixed MISE_RUBY_BUILD_OPTS by [@jdx](https://github.com/jdx) in [#2609](https://github.com/jdx/mise/pull/2609)
- **(windows)** self_update by [@jdx](https://github.com/jdx) in [#2588](https://github.com/jdx/mise/pull/2588)
- …
=> chore: release 2024.9.6

docs/tasks/toml-tasks.md
The example in `Options` is using `arg`, this PR fixes it to use the correct `option`
=> Fix Options example in documentation

default.nix
File timestamps in nix are set to 00:00:01 1/1/1970 UTC so the test won't pass in nix.
=> fix: skip last modified time test for nix

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- task argument declarations by [@jdx](https://github.com/jdx) in [#2612](https://github.com/jdx/mise/pull/2612)
- **(windows)** node bin path by [@jdx](https://github.com/jdx) in [eed0ecf](https://github.com/jdx/mise/commit/eed0ecfb528aa1fa04efcadf44afd353db76a7c4)
- **(windows)** fixed npm backend by [@jdx](https://github.com/jdx) in [#2617](https://github.com/jdx/mise/pull/2617)
- ensure that version is not "latest" in node by [@jdx](https://github.com/jdx) in [0e196d6](https://github.com/jdx/mise/commit/0e196d6d9c0b0851148ba9894191d766c0386356)
- prevent attempting to use python-build in windows by [@jdx](https://github.com/jdx) in [e15545b](https://github.com/jdx/mise/commit/e15545bb623da98bae72a41a57fa10ec311ee881)
- skip last modified time test for nix by …
=> chore: release 2024.9.7

docs/lang/java.md
=> docs: document java shorthand and its limitations

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(node)** allow using node unofficial build flavors by [@jdx](https://github.com/jdx) in [#2637](https://github.com/jdx/mise/pull/2637)
- codegen settings by [@jdx](https://github.com/jdx) in [#2640](https://github.com/jdx/mise/pull/2640)
- release 2024.9.7 breaks configurations that were using v in version names with go backend by [@roele](https://github.com/roele) in [#2636](https://github.com/jdx/mise/pull/2636)
- add node mirror/flavor to cache key by [@jdx](https://github.com/jdx) in [#2638](https://github.com/jdx/mise/pull/2638)
- Update faq.md by [@jdx](https://github.com/jdx) in [9036759](https://github.com/jdx/mise/commit/903675950d3ccc7abb49a40d6794d75d52695e5e)
- Update configuration.md by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.9.8

docs/dev-tools/index.md, e2e/plugins/test_tiny, src/backend/mod.rs, src/config/mod.rs
=> feat: added postinstall hook

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- added nodejs to alpine build by [@jdx](https://github.com/jdx) in [550f64c](https://github.com/jdx/mise/commit/550f64cb9c0377e4102be24486491a5b9d7947f3)
- bug with exec on windows by [@jdx](https://github.com/jdx) in [#2648](https://github.com/jdx/mise/pull/2648)
- only show hints once per execution by [@jdx](https://github.com/jdx) in [#2647](https://github.com/jdx/mise/pull/2647)
- task args regression by [@jdx](https://github.com/jdx) in [#2651](https://github.com/jdx/mise/pull/2651)
- use correct xdg paths on windows by [@jdx](https://github.com/jdx) in [#2653](https://github.com/jdx/mise/pull/2653)
- added windows e2e tests by [@jdx](https://github.com/jdx) in [#2643](https://github.com/jdx/mise/pull/2643)
- added windows e2e tests by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.9.9

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- add arguments to file tasks by jdx in [1b20e09](https://github.com/jdx/mise/commit/1b20e09e1f2f5435dc133788861241a879ce92bb)
- added toml cli commands by jdx in [448f91c](https://github.com/jdx/mise/commit/448f91c88a785700144c1bc5287e55ceb069294b)
- mount tasks args/flags via usage by jdx in [1eaa731](https://github.com/jdx/mise/commit/1eaa7316c9eb30a8bba0ef5f7f3cad525d672945)
- added mise info command by jdx in [4880eb5](https://github.com/jdx/mise/commit/4880eb5df36a63d3442332574765e25c3754c2cb)
- Add tera features for the template documenation by Erick Guan in [496e964](https://github.com/jdx/mise/commit/496e96437a578fc564cde7a5e1f0e7c9731ec378)
- migrate away from deprecated git-cliff syntax by Jeff Dickey in [230897c](https://github.com/jdx/mise/commit/230897c41210502f69ed5c4270f13d …
=> chore: release 2024.9.10

docs/dev-tools/backends/index.md
`cargo` and `npm` are no longer experimental features, so I think it's okay to remove the badge.
=> docs: remove experimental badge from cargo and npm backends

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/registry.md, man/man1/mise.1, packaging/rpm/mise.spec, registry/plugins/gh, src/default_shorthands.rs
- added --type option to `toml set` by [@jdx](https://github.com/jdx) in [#2674](https://github.com/jdx/mise/pull/2674)
- added --bump option for outdated/upgrade by [@jdx](https://github.com/jdx) in [#2667](https://github.com/jdx/mise/pull/2667)
- improve task loading by [@jdx](https://github.com/jdx) in [#2664](https://github.com/jdx/mise/pull/2664)
- remove experimental badge from cargo and npm backends by [@matukoto](https://github.com/matukoto) in [#2669](https://github.com/jdx/mise/pull/2669)
- more task loading in parallel by [@jdx](https://github.com/jdx) in [#2673](https://github.com/jdx/mise/pull/2673)
- bump git-cliff by [@jdx](https://github.com/jdx) in [9e82496](https://github.com/jdx/mise/commit/9e824964d1aef9eb955d64bf6a94ab767fffde11)
- fix codesign by …
=> chore: release 2024.9.11

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- offer to chmod non-executable tasks by [@jdx](https://github.com/jdx) in [#2675](https://github.com/jdx/mise/pull/2675)
- added basic task markdown generation by [@jdx](https://github.com/jdx) in [#2677](https://github.com/jdx/mise/pull/2677)
- Lazily evaluated env template variables in path entries by [@josb](https://github.com/josb) in [#2310](https://github.com/jdx/mise/pull/2310)
- improving task docs and cli reference docs by [@jdx](https://github.com/jdx) in [#2678](https://github.com/jdx/mise/pull/2678)
- do not load symlinked config files more than once by [@jdx](https://github.com/jdx) in [eb53099](https://github.com/jdx/mise/commit/eb530995e5126787187ef221f814ebbe3cb64824)
- minor bugs with incomplete python-build by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.9.12

src/toolset/mod.rs, src/toolset/tool_version.rs
Fixes #2583 
@jdx First thought i had was, why not setting the `ref: ` in the TOML file but the cargo tool could not infer the type for installation. So i guess we're stuck with mapping these prefixes back and forth, or do you have any other ideas?
A a small side-effect Version/Requested will differ but that is not unusual as it already does for `latest`.
```
mise-debug ls
Tool                     Version                           Config Source               Requested                      
cargo:eza-community/eza  ref:a3b0c8b40ed1f4f1a12c23242bbe  ~/Downloads/mise/.mise.toml rev:a3b0c8b40ed1f4f1a12c23242bb
780c391812f3                                                  e780c391812f3                  
cargo:eza-community/eza  ref:main …
```
=> fix: tools installed via cargo:a/b@rev:012 immediately pruned

.mise/tasks/filetask, .mise/tasks/lint-fix, .mise/tasks/test/coverage, .mise/tasks/test/e2e, docs/tasks/file-tasks.md, e2e/tasks/test_task_run, src/task/mod.rs, src/test.rs, tasks.md
`# mise` style will still be accepted for now but will likely be deprecated and removed in the future
Fixes #2692
Fixes #2693
=> fix(task): more flexible parsing around `#MISE alias(es)=`, changed prefix from `# mise` to `#MISE`

docs/getting-started.md
This seems to have changed in #2653
Related: The defaults now seem to be:
```
dirs:
data: ~\AppData\Local\mise
config: ~\.config\mise
cache: ~\AppData\Local\Temp\mise
state: ~\.local\state\mise
shims: ~\AppData\Local\mise\shims
```
which seems to be a healthy mix between Windows defaults and XDG. OTOH I never knew where to put config files on Windows...
=> chore: fix shim PATH for windows in docs

docs/lang/rust.md
Added a list of cargo create packages installed by default to the documentation
I did as described in this issue and it worked, but it was not yet mentioned in the documentation.
https://github.com/jdx/mise/issues/788
=> docs: add Rust creates

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(task)** more flexible parsing around `#MISE alias(es)=`, changed prefix from `# mise` to `#MISE` by [@jdx](https://github.com/jdx) in [#2694](https://github.com/jdx/mise/pull/2694)
- ubi cargo install instruction incorrect by [@roele](https://github.com/roele) in [#2696](https://github.com/jdx/mise/pull/2696)
- troubleshooting by [@jdx](https://github.com/jdx) in [820aac4](https://github.com/jdx/mise/commit/820aac408cf47e1ace420b0c1018b5816d2b30a0)
- fix broken link by [@jdx](https://github.com/jdx) in [ec43be3](https://github.com/jdx/mise/commit/ec43be3575bf29b8d79e51e3f029fe63012d5f2b)
- add Rust creates by [@yanskun](https://github.com/yanskun) in [#2701](https://github.com/jdx/mise/pull/2701)
- reset test by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.10.0

src/cli/current.rs
* Add hint with install instruction for missing tools
Fixes #2587
=> feat: add hint about how install missing plugins

docs/getting-started.md, src/shell/nushell.rs, src/shell/snapshots/mise__shell__nushell__tests__hook_init.snap
1. The mise exe location often includes backslashes in windows, which must be escaped in nushell.
2. Nushell has a csv parser, so we can use this standardized format to pass data.
3. On my setup, "use mise.nu" doesn't work. (Module not found error) I have to be explicit about the location of mise.nu.
=> fix(windows): escape backslash in nu script & use proper csv

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec, schema/mise.json, src/config/config_file/mise_toml.rs, src/shell/nushell.rs
- added MISE_PIN=1 setting by [@jdx](https://github.com/jdx) in [9f73952](https://github.com/jdx/mise/commit/9f73952ac2a782da6c10ec6a4b36093a74b8e251)
- add hint about how install missing plugins by [@roele](https://github.com/roele) in [#2706](https://github.com/jdx/mise/pull/2706)
- task shell by [@roele](https://github.com/roele) in [#2709](https://github.com/jdx/mise/pull/2709)
- **(windows)** escape backslash in nu script & use proper csv by [@finalchild](https://github.com/finalchild) in [#2710](https://github.com/jdx/mise/pull/2710)
- update name of cargo:ubi-cli package by [@jdx](https://github.com/jdx) in [d83fe3f](https://github.com/jdx/mise/commit/d83fe3f0b1eaeb0fc464d8eef589541ddc182673)
- only upgrade versions if there is a version to upgrade to by …
=> chore: release 2024.10.1

src/plugins/core/deno.rs, src/plugins/core/mod.rs
* Made some pathname fixes that make the deno core plugin work on my windows machine.
Plus,
* Replaced GitHub deno download urls to dl.deno.land which the official installation script uses
* Replaced GitHub deno version fetch url to deno.com which includes latest rc versions
=> feat: enable deno core plugin on windows & download deno files from deno server

src/backend/ubi.rs, src/registry.rs
follow up of d83fe3f0b1eaeb0fc464d8eef589541ddc182673
---
While reading the code, I found `cargo:ubi-cli` and `cargo:cargo-binstall` are duplicated in `_REGISTRY` and `_REGISTRY_VFOX`.
As `_REGISTRY_VFOX` is merged with `_REGISTRY` here.
https://github.com/jdx/mise/blob/e34788b803b0f4817e2b8481c4ed7d94ed308d66/src/registry.rs#L48-L50
And, it seems it is assumed to contain only `vfox:` prefixed identifiers here.
https://github.com/jdx/mise/blob/e34788b803b0f4817e2b8481c4ed7d94ed308d66/src/backend/vfox.rs#L91-L101
I think these duplicates are unnecessary, so if my guess is correct, I will create a new PR to remove them.
=> fix(ubi): update ubi identifiers

src/toolset/tool_version.rs
Removed the code that skips the latest version check if the version is already installed.
I don't know the exact purpose of the code, so please double-check.
The reasoning is this:
* If latest_versions is false, we already don't fetch the remote versions.
* If latest_versions is true, we want the up-to-date version. Due to the fuzzy-matching, we can't be sure that this is the latest version even if the version is present in the installation directory. Thus, we should not skip the remote fetch.
This fixes the bug where the environment variables are not properly set when installing "latest" versions with the vfox backend on windows. (In env_hook, vfox.rs expects the resolved versions like "1.20.0" as the argument, but due to this skip mise is passing "latest". We could fix vfox.rs as jdx …
=> fix: don't skip the latest version fetch

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- enable deno core plugin on windows & download deno files from deno server by [@finalchild](https://github.com/finalchild) in [#2719](https://github.com/jdx/mise/pull/2719)
- use uv to create venv by default by [@erickguan](https://github.com/erickguan) in [#2705](https://github.com/jdx/mise/pull/2705)
- **(ubi)** update ubi identifiers by [@risu729](https://github.com/risu729) in [#2724](https://github.com/jdx/mise/pull/2724)
- use join_paths to create new_path by [@finalchild](https://github.com/finalchild) in [#2708](https://github.com/jdx/mise/pull/2708)
- issue with java@latest and metadatas (currently 23.0.0) by [@roele](https://github.com/roele) in [#2727](https://github.com/jdx/mise/pull/2727)
- several fixes/improvements for python version selection by …
=> chore: release 2024.10.2

docs/dev-tools/backends/vfox.md, src/cli/exec.rs, src/shims.rs
A follow-up to #2735 which was missing some cases
=> fix: remove shims directory from PATH when executing shims

src/path_env.rs
=> fix: do not include shims dir in path_env when reinserting

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- improve dynamic settings by [@jdx](https://github.com/jdx) in [#2731](https://github.com/jdx/mise/pull/2731)
- added --force flag to reshim by [@jdx](https://github.com/jdx) in [#2734](https://github.com/jdx/mise/pull/2734)
- added `mise settings add` by [@jdx](https://github.com/jdx) in [#2741](https://github.com/jdx/mise/pull/2741)
- improve task scheduling by [@jdx](https://github.com/jdx) in [#2743](https://github.com/jdx/mise/pull/2743)
- include ubi into mise directly by [@autarch](https://github.com/autarch) in [#2290](https://github.com/jdx/mise/pull/2290)
- allow passing arbitrary args to pipx/uvx by [@jdx](https://github.com/jdx) in [#2746](https://github.com/jdx/mise/pull/2746)
- new cross-backend registry by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.10.3

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- some bugs with vfox by [@jdx](https://github.com/jdx) in [0c90062](https://github.com/jdx/mise/commit/0c90062cf9e148bcae4f85262bd6e4883496f385)
- use ci_info to determine if running on CI by [@jdx](https://github.com/jdx) in [ac9a35b](https://github.com/jdx/mise/commit/ac9a35bc762e5679ea56b02a4ee278a88d358f78)
- enable more colors for tasks by [@jdx](https://github.com/jdx) in [f3b0e33](https://github.com/jdx/mise/commit/f3b0e33071376172142e89c010663add8365524b)
=> chore: release 2024.10.4

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- add rustic backup plugin to registry by [@jahands](https://github.com/jahands) in [#2754](https://github.com/jdx/mise/pull/2754)
- created custom logger by [@jdx](https://github.com/jdx) in [#2758](https://github.com/jdx/mise/pull/2758)
- render task help via usage by [@jdx](https://github.com/jdx) in [#2760](https://github.com/jdx/mise/pull/2760)
- replace asdf-rustic with ubi by [@jdx](https://github.com/jdx) in [#2757](https://github.com/jdx/mise/pull/2757)
- set trailing_var_arg on `mise run` by [@jdx](https://github.com/jdx) in [b1bb3d2](https://github.com/jdx/mise/commit/b1bb3d2a1e60eaccfc5e24250fc86966b6c9e69a)
- prevent loading logger multiple times by [@jdx](https://github.com/jdx) in [1b83acd](https://github.com/jdx/mise/commit/1b83acd5cfef954643f3b24519fb51c8531cf59b)
- …
=> chore: release 2024.10.6

src/backend/asdf.rs, src/backend/mod.rs, src/backend/ubi.rs, src/main.rs, src/plugins/asdf_plugin.rs, src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/erlang.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/mod.rs, src/plugins/core/node.rs, src/plugins/core/python.rs, src/plugins/core/ruby.rs, src/plugins/core/ruby_windows.rs, src/plugins/core/zig.rs, src/plugins/mod.rs, src/plugins/vfox_plugin.rs, src/versions_host.rs
before:
```
❯ mise ls-remote ubi:jdx/usage
v0.1.5
v0.1.6
v0.1.7
v0.1.8
v0.1.9
v0.1.16
v0.1.17
v0.1.18
v0.2.0
v0.2.1
v0.3.0
v0.3.1
v0.4.0
v0.5.0
v0.5.1
v0.6.0
v0.7.0
v0.7.1
v0.7.2
v0.7.3
v0.7.4
v0.8.0
v0.8.1
v0.8.2
v0.8.3
v0.8.4
v0.9.0
v0.10.0
v0.11.0
```
to make things simpler for the user, we avoid "v" prefixes whenever possible so users don't need to remember which tools have the prefix and which don't
=> fix: trim "v" prefix for ubi backend tools

docs/ide-integration.md
I added a tip explaining how to use the `TERM_PROGRAM` environment variable to conditionally use shim-based activation. 
---
For background, I use zsh and have my `.zprofile` configured to activate mise like so:
```zsh
eval "$($HOME/.local/bin/mise activate zsh)"
```
However, as these docs already mention, IDEs such as VSCode don't always function as expected unless mise is activated with `--shims`.
To get the best of both worlds, mise activation can be conditionally modified if terminal detection is used, which is what I added to the docs:
```zsh
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
eval "$($HOME/.local/bin/mise activate zsh --shims)"
elif; then
eval "$($HOME/.local/bin/mise activate zsh)"
fi
```
=> docs: add tip for conditional shims using TERM_PROGRAM

docs/profiles.md, src/config/mod.rs
=> feat: add {MISE_CONFIG_DIR}/config.{MISE_ENV}.local.toml to config lookup

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/registry.md, man/man1/mise.1, packaging/rpm/mise.spec
- add argc plugin to registry by [@rgeraskin](https://github.com/rgeraskin) in [#2790](https://github.com/jdx/mise/pull/2790)
- update markdownlint-cli2 in registry to use the npm backend by [@BurnerWah](https://github.com/BurnerWah) in [#2794](https://github.com/jdx/mise/pull/2794)
- java core plugin reports wrong latest version by [@roele](https://github.com/roele) in [#2798](https://github.com/jdx/mise/pull/2798)
- Add mold linker using ubi registry.toml by [@yodatak](https://github.com/yodatak) in [#2792](https://github.com/jdx/mise/pull/2792)
- update dependency vitepress to v1.4.1 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2780](https://github.com/jdx/mise/pull/2780)
- @yodatak made their first contribution in [#2792](https://github.com/jdx/mise/pull/2792)
- …
=> chore: release 2024.10.9

src/file.rs, src/toolset/mod.rs
=> fix: `upgrade --bump` with non-semver versions

.mise.toml, docs/cli/tasks/run.md, src/backend/cargo.rs
This just makes it so mise install cargo-binstall first and then uses it
only if it is already defined in config
=> fix: add cargo-binstall as dependency of cargo backend

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- automatically hide hints after displayed once by [@jdx](https://github.com/jdx) in [#2807](https://github.com/jdx/mise/pull/2807)
- add ubi installers for various tools by [@BurnerWah](https://github.com/BurnerWah) in [#2801](https://github.com/jdx/mise/pull/2801)
- upgrade --bump with non-semver versions by [@jdx](https://github.com/jdx) in [#2809](https://github.com/jdx/mise/pull/2809)
- parsing default task arg/flags by [@jdx](https://github.com/jdx) in [#2810](https://github.com/jdx/mise/pull/2810)
- attempt ubi installs with/without "v" prefix if they fail by [@jdx](https://github.com/jdx) in [#2813](https://github.com/jdx/mise/pull/2813)
- add cargo-binstall as dependency of cargo backend by [@jdx](https://github.com/jdx) in [#2811](https://github.com/jdx/mise/pull/2811)
- use …
=> chore: release 2024.10.10

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(registry)** add ubi as primary backend for additional tools by [@jimeh](https://github.com/jimeh) in [#2827](https://github.com/jdx/mise/pull/2827)
- **(registry)** add various new tools by [@jimeh](https://github.com/jimeh) in [#2833](https://github.com/jdx/mise/pull/2833)
- add ubi backend for eza by [@yodatak](https://github.com/yodatak) in [#2823](https://github.com/jdx/mise/pull/2823)
- added env-only plugin support by [@jdx](https://github.com/jdx) in [#2832](https://github.com/jdx/mise/pull/2832)
- make ubi installs with exe work for `mise x` by [@jdx](https://github.com/jdx) in [#2825](https://github.com/jdx/mise/pull/2825)
- add header to registry by [@jdx](https://github.com/jdx) in [2b518f9](https://github.com/jdx/mise/commit/2b518f9e0ee977a7c2c244de540877e3073c49ad)
- add …
=> chore: release 2024.10.11

default.nix, flake.lock
Ruby plugin test tries to pull the source from GitHub which is not possible when building the nix derivation.
=> test: Disable ruby plugin test as no network access to GitHub in derivation

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(registry)** Use ubi for delta, fd, gohugo, hyperfine, just, tokei, xh by [@vrslev](https://github.com/vrslev) in [#2836](https://github.com/jdx/mise/pull/2836)
- accept argument for `mise registry` by [@jdx](https://github.com/jdx) in [#2841](https://github.com/jdx/mise/pull/2841)
- allow listing all versions from github by [@jdx](https://github.com/jdx) in [#2844](https://github.com/jdx/mise/pull/2844)
- lockfiles by [@jdx](https://github.com/jdx) in [#2839](https://github.com/jdx/mise/pull/2839)
- allow passing ubi:[exe=] on the command line by [@jdx](https://github.com/jdx) in [#2843](https://github.com/jdx/mise/pull/2843)
- pass ubi config from mise.toml by [@jdx](https://github.com/jdx) in [#2842](https://github.com/jdx/mise/pull/2842)
- added ToolSource to ToolRequest by …
=> chore: release 2024.10.12

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- bring tasks out of experimental by [@jdx](https://github.com/jdx) in [#2851](https://github.com/jdx/mise/pull/2851)
- correct python ls-remote with python.compile option by [@jdx](https://github.com/jdx) in [acfd7f1](https://github.com/jdx/mise/commit/acfd7f13411faf784e585e1e489dccfd97a0de66)
- added walkthrough by [@jdx](https://github.com/jdx) in [#2848](https://github.com/jdx/mise/pull/2848)
- added source code links by [@jdx](https://github.com/jdx) in [#2850](https://github.com/jdx/mise/pull/2850)
- Revert "fix: correct python ls-remote with python.compile option" by [@jdx](https://github.com/jdx) in [f65c0b6](https://github.com/jdx/mise/commit/f65c0b67106c22686055f46d81760bb44405d663)
- fetch mise compressed in standalone installer by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.10.13

src/assets/mise-extra.usage.kdl
The complete script of `installed_tool@version` runs `mise plugins --core --user` which displays plugins instead of installed tools&versions. Considering this complete is only used by `mise uninstall` currently, I don't think it makes sense.
`mise plugins --user` also doesn't seem to make sense to me here since we want to uninstall tool versions, not plugins itself as per [uninstall documentation](https://mise.jdx.dev/cli/uninstall.html)
=> fix: installed_tool@version complete script doesn't list installed tools, but plugins

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, docs/cli/alias/ls.md, docs/cli/alias/set.md, docs/cli/alias/unset.md, man/man1/mise.1, mise.usage.kdl, packaging/rpm/mise.spec
- **(node)** update aliases for latest LTS release (jod/v22) by [@jasisk](https://github.com/jasisk) in [#2865](https://github.com/jdx/mise/pull/2865)
- **(registry)** Add cargo-insta, mprocs, killport, fzf with ubi by [@vrslev](https://github.com/vrslev) in [#2852](https://github.com/jdx/mise/pull/2852)
- added sccache as a dependency for cargo backend by [@jdx](https://github.com/jdx) in [#2855](https://github.com/jdx/mise/pull/2855)
- add zstd compression for http requests by [@jdx](https://github.com/jdx) in [612bbd0](https://github.com/jdx/mise/commit/612bbd0374bed208752cda8674ad192b5886fde9)
- Fix installed_tool@version complete script by [@miguelmig](https://github.com/miguelmig) in [#2859](https://github.com/jdx/mise/pull/2859)
- @miguelmig made their first contribution in …
=> chore: release 2024.11.0

docs/lang/ruby.md
Adding a hint/link to ruby-build dependencies (similar to python-build).
Fixes #2863
=> docs: add hint/link to ruby-build dependencies

docs/cli/prune.md, docs/mise.usage.kdl, mise.usage.kdl, src/cli/prune.rs
```
$ mise prune --help
Delete unused versions of tools
mise tracks which config files have been used in ~/.local/share/mise/tracked_config_files
[…]
```
That path hasn't been used since cf4ed1f9567e.
=> docs: Fix path to tracked-configs

settings.toml, src/shims.rs
=> fix: only run not_found_auto_install if non-tty in shims

e2e/cli/test_outdated, src/cli/outdated.rs, src/toolset/mod.rs
Since --bump is currently a bit unreliable, it's helpful to show early what exactly it's about to do.
=> feat: show bump in mise outdated and upgrade --interactive

e2e/tasks/test_task_run_toml, src/task/mod.rs
=> fix: parse task run template even if no args/flags

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(registry)** add ubi (+ go & cargo) installers for tools by [@BurnerWah](https://github.com/BurnerWah) in [#2881](https://github.com/jdx/mise/pull/2881)
- **(registry)** switch apollo-router to ubi; add apollo-rover by [@glasser](https://github.com/glasser) in [#2872](https://github.com/jdx/mise/pull/2872)
- add elvish integration by [@SolitudeSF](https://github.com/SolitudeSF) in [#2857](https://github.com/jdx/mise/pull/2857)
- add autocompletion for tasks run by [@roele](https://github.com/roele) in [#2908](https://github.com/jdx/mise/pull/2908)
- show bump in mise outdated and upgrade --interactive by [@liskin](https://github.com/liskin) in [#2892](https://github.com/jdx/mise/pull/2892)
- **(ruby)** ensure ruby-build bin exists before trying to use by [@jdx](https://github.com/jdx) …
=> chore: release 2024.11.1

docs/.vitepress/config.ts, docs/dev-tools/shims.md, docs/getting-started.md, docs/installing-mise.md, docs/walkthrough.md
As suggested in https://github.com/jdx/mise/discussions/2440, the `getting-started` page might be too intimidating for someone new to `mise`.
> 2/3rd of the page is filled up with: Alternate Installation Methods, Shells, and Uninstalling. I think it makes sense to link to this content in other pages but for the majority of users this is only adding noise and making them want to leave the docs or search for more examples.
To address this, this PR adds an `installing-mise.md` page which lists all the ways that `mise` can get installed.
> A little into the page it offers you the choice about activate vs shims vs none. Most people new to Mise won't want to make choices like this right away since it requires research to understand the consequences.
> There is very little explanation about what …
=> docs: move alternative ways to install mise to a separate page

src/backend/go.rs, src/backend/npm.rs, src/backend/spm.rs, src/shims.rs
Fixes #2260.
From #2745, there is no need to remove the shims directory from `PATH` beforehand (#2376).
I tested the infinite loop repro and it seems working fine. This should resolve the issue, but I will revert the removal commit if it's better to preserve it just in case.
=> fix(backend): include backend dependencies in paths

src/cli/run.rs, src/cli/tasks/edit.rs, src/config/config_file/mise_toml.rs, src/config/mod.rs, src/task/mod.rs, src/task/task_script_parser.rs, src/tera.rs, src/ui/ctrlc.rs
=> fix: use project_root for task execution

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(backend)** include backend dependencies in paths by [@risu729](https://github.com/risu729) in [#2893](https://github.com/jdx/mise/pull/2893)
- **(completions)** set usage cache-key by [@jdx](https://github.com/jdx) in [#2937](https://github.com/jdx/mise/pull/2937)
- **(ls)** only show symlink_path when not runtime-symlink by [@jdx](https://github.com/jdx) in [#2927](https://github.com/jdx/mise/pull/2927)
- upgrade vfox.rs with http module by [@jdx](https://github.com/jdx) in [#2934](https://github.com/jdx/mise/pull/2934)
- hide extra "mise" prefix when installing by [@jdx](https://github.com/jdx) in [#2935](https://github.com/jdx/mise/pull/2935)
- only show actual cargo-binstall versions by [@jdx](https://github.com/jdx) in [#2936](https://github.com/jdx/mise/pull/2936)
- use …
=> chore: release 2024.11.2

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- support multiple versions in lockfile by [@jdx](https://github.com/jdx) in [#2923](https://github.com/jdx/mise/pull/2923)
- use mise.toml instead of .mise.toml by default in `mise use` by [@jdx](https://github.com/jdx) in [#2818](https://github.com/jdx/mise/pull/2818)
- explode backend dependencies by [@jdx](https://github.com/jdx) in [#2945](https://github.com/jdx/mise/pull/2945)
- show install prefix in output by [@jdx](https://github.com/jdx) in [#2946](https://github.com/jdx/mise/pull/2946)
- make vfox/vendored-lua optional by [@jdx](https://github.com/jdx) in [acc674b](https://github.com/jdx/mise/commit/acc674b00c307241fb8b87ba7e27fba1f08a1a22)
- Revert "perf(shell/zsh.rs): avoid hook-env execution on Enter without command " by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.11.3

src/cli/plugins/ls.rs, src/cli/plugins/ls_remote.rs, src/config/mod.rs, src/shorthands.rs
=> fix: allow installing asdf/vfox plugins by shorthand when overridden by ubi

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- added --offline flag to ls by [@jdx](https://github.com/jdx) in [#2954](https://github.com/jdx/mise/pull/2954)
- added MISE_TASK_TIMINGS setting by [@jdx](https://github.com/jdx) in [#2957](https://github.com/jdx/mise/pull/2957)
- **(go)** remove old GOPATH bin dir by [@jdx](https://github.com/jdx) in [#2959](https://github.com/jdx/mise/pull/2959)
- allow installing asdf/vfox plugins by shorthand when overridden by ubi by [@jdx](https://github.com/jdx) in [#2956](https://github.com/jdx/mise/pull/2956)
- set docs directory in release-docs task by [@jdx](https://github.com/jdx) in [6efac79](https://github.com/jdx/mise/commit/6efac7976b2d1ebdb988baf6e50f8faa8218053b)
- added hidden --outdate option for cache clear by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.11.4

docs/registry.md, e2e/cli/test_ls_cache, src/cache.rs
Verified with: `touch -t 201007162310 ~/.mise/cache/bat/remote_versions-* ~/.mise/cache/ && m ls -v bat`
Fixes #2961
=> fix: reuse cache when old

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- show overridden tools in registry by [@jdx](https://github.com/jdx) in [#2974](https://github.com/jdx/mise/pull/2974)
- use versions host for core plugins by [@jdx](https://github.com/jdx) in [#2970](https://github.com/jdx/mise/pull/2970)
- reuse cache when old by [@jdx](https://github.com/jdx) in [#2971](https://github.com/jdx/mise/pull/2971)
- MISE_PROFILE fixes by [@jdx](https://github.com/jdx) in [#2973](https://github.com/jdx/mise/pull/2973)
- added win-e2e task test by [@jdx](https://github.com/jdx) in [#2972](https://github.com/jdx/mise/pull/2972)
- update dependency vitepress to v1.5.0 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2966](https://github.com/jdx/mise/pull/2966)
=> chore: release 2024.11.5

deny.toml, src/backend/mod.rs, src/cli/asdf.rs, src/cli/current.rs, src/cli/latest.rs, src/cli/ls.rs, src/cli/prune.rs, src/cli/uninstall.rs, src/cli/upgrade.rs, src/cli/use.rs, src/cli/where.rs, src/config/config_file/mod.rs, src/config/env_directive.rs, src/config/mod.rs, src/lockfile.rs, src/shims.rs, src/toolset/mod.rs, src/toolset/tool_request.rs, src/toolset/tool_version.rs, src/toolset/tool_version_list.rs
Prerequisite for #2979. Because backend arg will change during TV resolving, this allows me to modify backend_arg.full during resolving
=> refactor: remove backend arg from tool-version

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(backend)** add a setting to use bun in npm backend by [@risu729](https://github.com/risu729) in [#2899](https://github.com/jdx/mise/pull/2899)
- **(tasks)** add shell settings for Windows compatibility in tasks by [@rodvieirasilva](https://github.com/rodvieirasilva) in [#2967](https://github.com/jdx/mise/pull/2967)
- update tmux plugin by [@drewwells](https://github.com/drewwells) in [#2977](https://github.com/jdx/mise/pull/2977)
- remove backend arg from tool-version by [@jdx](https://github.com/jdx) in [#2980](https://github.com/jdx/mise/pull/2980)
- load core plugins when rendering registry doc by [@jdx](https://github.com/jdx) in [00ef7b4](https://github.com/jdx/mise/commit/00ef7b4d5c59047e795c0fc2476bde386decc363)
- added core plugins to registry by …
=> chore: release 2024.11.6

e2e/cli/test_use, src/config/config_file/mise_toml.rs, src/toolset/tool_version.rs
=> fix: do not add tool options to toml when they are the defaults

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- make zig non-experimental by [@jdx](https://github.com/jdx) in [#2999](https://github.com/jdx/mise/pull/2999)
- aqua backend by [@jdx](https://github.com/jdx) in [#2995](https://github.com/jdx/mise/pull/2995)
- only release fig autocomplete once per month by [@jdx](https://github.com/jdx) in [b86885a](https://github.com/jdx/mise/commit/b86885ab7855b34a776b3119dcb6526b3d8fd814)
=> chore: release 2024.11.8

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- added aliases to registry by [@jdx](https://github.com/jdx) in [#3007](https://github.com/jdx/mise/pull/3007)
- added more aqua tools by [@jdx](https://github.com/jdx) in [#3008](https://github.com/jdx/mise/pull/3008)
- default python to precompiled by [@jdx](https://github.com/jdx) in [dfb13de](https://github.com/jdx/mise/commit/dfb13de8ebc1da2542ab67ba2b81e8b26a085c20)
- consolidate tool/plugin loading to install_state.rs by [@jdx](https://github.com/jdx) in [#3015](https://github.com/jdx/mise/pull/3015)
- remove alias from test-plugins by [@jdx](https://github.com/jdx) in [7d2406b](https://github.com/jdx/mise/commit/7d2406b50e60257937a4476aed4a2a78197771f2)
=> chore: release 2024.11.10

e2e/backend/test_aqua, e2e/backend/test_ubi, src/aqua/aqua_registry.rs, src/backend/aqua.rs, src/file.rs, tasks.md, tasks.toml
=> fix(aqua): set default format for http registries

e2e/cli/test_ls, src/backend/mod.rs, src/toolset/install_state.rs
=> fix: incorrectly displaying "cargo-" as tool versions instead of "cargo:" in `mise ls`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- improve progress bar during tarball extraction by [@jdx](https://github.com/jdx) in [#3030](https://github.com/jdx/mise/pull/3030)
- added more aqua tools by [@jdx](https://github.com/jdx) in [#3031](https://github.com/jdx/mise/pull/3031)
- added `wait_for` option for tasks by [@jdx](https://github.com/jdx) in [#3046](https://github.com/jdx/mise/pull/3046)
- added `os` option to mise.toml by [@jdx](https://github.com/jdx) in [#3047](https://github.com/jdx/mise/pull/3047)
- **(aqua)** allow environment validation for arch-only matches by [@risu729](https://github.com/risu729) in [#3037](https://github.com/jdx/mise/pull/3037)
- **(java)** show verifying message on progress bar by [@jdx](https://github.com/jdx) in [8f8fc64](https://github.com/jdx/mise/commit/8f8fc64e6ca57fd24ac3ee6cd9e4a506 …
=> chore: release 2024.11.14

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- bug with task dependencies by [@jdx](https://github.com/jdx) in [#3049](https://github.com/jdx/mise/pull/3049)
- bug with task dependencies by [@jdx](https://github.com/jdx) in [235000c](https://github.com/jdx/mise/commit/235000c33298fdfde6125e7f70fba4e7bf01cb4d)
- disable 1password on non-windows by [@jdx](https://github.com/jdx) in [6c584e0](https://github.com/jdx/mise/commit/6c584e0e9000a104fc040ff5b3565015d9184b28)
- disable 1password on non-windows by [@jdx](https://github.com/jdx) in [#3051](https://github.com/jdx/mise/pull/3051)
- disable_backends on windows by [@jdx](https://github.com/jdx) in [#3052](https://github.com/jdx/mise/pull/3052)
- set GITHUB_TOKEN in release-plz by [@jdx](https://github.com/jdx) in [b02c044](https://github.com/jdx/mise/commit/b02c0440aa35d9a43defb54067 …
=> chore: release 2024.11.15

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(ruby)** send ruby-install output to stderr by [@jdx](https://github.com/jdx) in [c2918dc](https://github.com/jdx/mise/commit/c2918dc7e6131286442f637fcbd1e60325e727b5)
- bugs with `mise up` and prefix: versions by [@jdx](https://github.com/jdx) in [#3054](https://github.com/jdx/mise/pull/3054)
- prefix: on tool dependencies by [@jdx](https://github.com/jdx) in [#3058](https://github.com/jdx/mise/pull/3058)
- use cargo:cargo-binstall as dependency for cargo-binstall by [@jdx](https://github.com/jdx) in [#3059](https://github.com/jdx/mise/pull/3059)
- show MRI ruby versions last by [@jdx](https://github.com/jdx) in [#3060](https://github.com/jdx/mise/pull/3060)
- typo fix in getting-started.md by [@Guria](https://github.com/Guria) in [#3057](https://github.com/jdx/mise/pull/3057)
- …
=> chore: release 2024.11.16

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(bun)** windows support by [@jdx](https://github.com/jdx) in [#3075](https://github.com/jdx/mise/pull/3075)
- added more aqua tools by [@jdx](https://github.com/jdx) in [#3079](https://github.com/jdx/mise/pull/3079)
- added more aqua tools by [@jdx](https://github.com/jdx) in [#3081](https://github.com/jdx/mise/pull/3081)
- added `key` option for `settings ls` by [@jdx](https://github.com/jdx) in [#3084](https://github.com/jdx/mise/pull/3084)
- added more aqua tools by [@jdx](https://github.com/jdx) in [#3082](https://github.com/jdx/mise/pull/3082)
- reuse tool options on `mise use` from config file by [@jdx](https://github.com/jdx) in [#3076](https://github.com/jdx/mise/pull/3076)
- move a warning to debug in aqua by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.11.17

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- add ripgrep-all by [@yodatak](https://github.com/yodatak) in [#3083](https://github.com/jdx/mise/pull/3083)
- add vivid by [@swfz](https://github.com/swfz) in [#3089](https://github.com/jdx/mise/pull/3089)
- use global mise when running `mise use` in home dir by [@jdx](https://github.com/jdx) in [#3085](https://github.com/jdx/mise/pull/3085)
- prevent infinite recursion listing dependencies by [@jdx](https://github.com/jdx) in [#3091](https://github.com/jdx/mise/pull/3091)
- removed duplicate backend specifier from some registry tools by [@syhol](https://github.com/syhol) in [#3090](https://github.com/jdx/mise/pull/3090)
- define registry outside of build.rs by [@jdx](https://github.com/jdx) in [e4366ff](https://github.com/jdx/mise/commit/e4366ffc7f8526d57c097dc61387b793b6f7ba3a)
- …
=> chore: release 2024.11.18

src/cli/doctor.rs
=> fix: hide MISE_GITHUB_TOKEN from `mise dr`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- ignore config files after not trusting them by [@jdx](https://github.com/jdx) in [#3128](https://github.com/jdx/mise/pull/3128)
- task vars by [@jdx](https://github.com/jdx) in [#3130](https://github.com/jdx/mise/pull/3130)
- verify aqua packages with cosign and/or slsa when available by [@jdx](https://github.com/jdx) in [#3151](https://github.com/jdx/mise/pull/3151)
- added `task_skip` setting by [@jdx](https://github.com/jdx) in [#3154](https://github.com/jdx/mise/pull/3154)
- allow calling `mise settings foo=bar` as shorthand by [@jdx](https://github.com/jdx) in [#3155](https://github.com/jdx/mise/pull/3155)
- **(cargo)** added extra tool opts by [@jdx](https://github.com/jdx) in [#3144](https://github.com/jdx/mise/pull/3144)
- hide MISE_GITHUB_TOKEN from `mise dr` by …
=> chore: release 2024.11.24

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- show ubi versions starting with digit last by [@jdx](https://github.com/jdx) in [#3162](https://github.com/jdx/mise/pull/3162)
- make built-in aqua cache work on windows by [@jdx](https://github.com/jdx) in [56aae79](https://github.com/jdx/mise/commit/56aae79c97b456cb866c81940519c815e6a67064)
- added test to check for bad cargo-binstall versions by [@jdx](https://github.com/jdx) in [#3163](https://github.com/jdx/mise/pull/3163)
- bake aqua registry into bin by [@jdx](https://github.com/jdx) in [#3161](https://github.com/jdx/mise/pull/3161)
=> chore: release 2024.11.26

e2e/tasks/test_task_run_toml, src/cli/run.rs, src/config/config_file/toml.rs, src/task/mod.rs
=> fix: allow passing integers to task env

src/cli/snapshots/mise__cli__deactivate__tests__deactivate-2.snap, src/shell/bash.rs, src/shell/fish.rs, src/shell/nushell.rs, src/shell/snapshots/mise__shell__bash__tests__deactivate.snap, src/shell/snapshots/mise__shell__fish__tests__deactivate.snap, src/shell/snapshots/mise__shell__nushell__tests__deactivate.snap, src/shell/snapshots/mise__shell__xonsh__tests__xonsh_deactivate.snap, src/shell/snapshots/mise__shell__zsh__tests__deactivate.snap, src/shell/xonsh.rs, src/shell/zsh.rs
=> fix: remove __MISE_WATCH,__MISE_DIFF env vars on `mise deactivate`

schema/mise.json, src/config/config_file/mise_toml.rs
=> fix: pass boolean tool options as strings

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(env)** Allow exporting env vars as dotenv format by [@miguelmig](https://github.com/miguelmig) in [#3185](https://github.com/jdx/mise/pull/3185)
- move more tools away from asdf by [@jdx](https://github.com/jdx) in [#3184](https://github.com/jdx/mise/pull/3184)
- use aqua for cargo-binstall by [@jdx](https://github.com/jdx) in [#3182](https://github.com/jdx/mise/pull/3182)
- use shift_remove by [@jdx](https://github.com/jdx) in [#3188](https://github.com/jdx/mise/pull/3188)
- pass boolean tool options as strings by [@jdx](https://github.com/jdx) in [#3191](https://github.com/jdx/mise/pull/3191)
- move semver cmp errors to debug by [@jdx](https://github.com/jdx) in [ab4e638](https://github.com/jdx/mise/commit/ab4e638cdeda9845f3b7421a22a0d3bf71d81eae)
- disable cargo-binstall test by …
=> chore: release 2024.11.29

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- migrate wren-cli to ubi by [@jdx](https://github.com/jdx) in [#3193](https://github.com/jdx/mise/pull/3193)
- migrate more tools away from asdf by [@jdx](https://github.com/jdx) in [#3202](https://github.com/jdx/mise/pull/3202)
- automatically set `set -e` in toml tasks by [@jdx](https://github.com/jdx) in [#3215](https://github.com/jdx/mise/pull/3215)
- added MISE_ORIGINAL_CWD to tasks by [@jdx](https://github.com/jdx) in [#3214](https://github.com/jdx/mise/pull/3214)
- add ruby backend by [@andrewthauer](https://github.com/andrewthauer) in [#1657](https://github.com/jdx/mise/pull/1657)
- migrate more tools away from asdf by [@jdx](https://github.com/jdx) in [#3205](https://github.com/jdx/mise/pull/3205)
- Make Rebar backend depend on Erlang by [@eproxus](https://github.com/eproxus) in …
=> chore: release 2024.11.30

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- rust in core by [@jdx](https://github.com/jdx) in [#3219](https://github.com/jdx/mise/pull/3219)
- use tv.pathname() in `mise ls` by [@jdx](https://github.com/jdx) in [#3217](https://github.com/jdx/mise/pull/3217)
- show gh rate limit reset time by [@jdx](https://github.com/jdx) in [#3221](https://github.com/jdx/mise/pull/3221)
- add @version back into show_tools by [@jdx](https://github.com/jdx) in [fd7d8d1](https://github.com/jdx/mise/commit/fd7d8d10395f8c80a80c60c0de89bf78e31fd762)
- use pipx for yamllint by [@jdx](https://github.com/jdx) in [#3227](https://github.com/jdx/mise/pull/3227)
- remove shims directory in `mise activate` by [@jdx](https://github.com/jdx) in [#3232](https://github.com/jdx/mise/pull/3232)
- remove duplicate remote_versions_caches by …
=> chore: release 2024.11.31

docs/tasks/file-tasks.md, e2e/tasks/test_task_standalone, src/cli/mod.rs, src/cli/run.rs
Allows running tasks with `mise run ./foo` or fetching tasks via http
=> feat: standalone tasks

docs/getting-started.md
Since folks might not read the whole page before they start following the steps in the Quickstart section, I think it's helpful to mention this detail sooner.
=> docs: Mention the fish shell's automatic activation in the Quickstart section

docs/configuration.md, schema/mise.json, src/config/config_file/mise_toml.rs
=> feat: added special "_" portion of mise.toml for custom data

packaging/standalone/install.envsubst
Fixes #2276
@autarch says this is a good idea, I suppose we will see
=> fix: always prefer glibc to musl in mise run

e2e/backend/test_ubi, mise.lock, mise.toml, src/cli/args/backend_arg.rs, src/config/mod.rs, src/toolset/install_state.rs, xtasks/lint-fix
In the case where you had installed a tool with one backend and that backend changes, mise was not passing the registry tool options to the old backend.
Fixes #3262
=> fix: issue with non-default backends not getting tool options

docs/configuration.md
Thanks for fixing my previous PR. This PR addresses [@glasser's comment](https://github.com/jdx/mise/pull/2989/files#r1837006850).
=> docs: describe mise behavior when mise version is lower than min_version

docs/.vitepress/cli_commands.ts, docs/cli/en.md, docs/cli/index.md, docs/cli/run.md, docs/cli/tasks/run.md, man/man1/mise.1, mise.usage.kdl, schema/mise.json, settings.toml, src/cli/en.rs, src/cli/exec.rs, src/cli/mod.rs, src/cli/run.rs, src/shell/fish.rs, src/shell/mod.rs, src/shims.rs, src/toolset/mod.rs, xtasks/fig/src/mise.ts
@booniepepper this isn't working right but I'm curious if you have any ideas.
The problem is that it will still load your rc files, so if you do something like `export PATH="/opt/homebrew/bin:$PATH" in your rc file that will make the mise tools lower priority than homebrew so it won't use mise tools if brew provides any.
One idea I had was running `mise env` when the shell starts but I'm not sure if it's possible to have zsh (for example) load a script like that.
Technically it does _work_ though.
=> feat: added "en" command

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- respect --quiet in `mise run` by [@jdx](https://github.com/jdx) in [#3257](https://github.com/jdx/mise/pull/3257)
- added special "_" portion of mise.toml for custom data by [@jdx](https://github.com/jdx) in [#3259](https://github.com/jdx/mise/pull/3259)
- **breaking** added MISE_OVERRIDE_CONFIG_FILENAMES config by [@jdx](https://github.com/jdx) in [#3266](https://github.com/jdx/mise/pull/3266)
- added swift by [@jdx](https://github.com/jdx) in [#3271](https://github.com/jdx/mise/pull/3271)
- **(spm)** git proxy config by [@jdx](https://github.com/jdx) in [#3264](https://github.com/jdx/mise/pull/3264)
- clean up some windows error cases by [@jdx](https://github.com/jdx) in [#3255](https://github.com/jdx/mise/pull/3255)
- run `hook-env` on directory change by …
=> chore: release 2024.11.33

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- migrate more tools away from asdf by [@jdx](https://github.com/jdx) in [#3279](https://github.com/jdx/mise/pull/3279)
- remove conflicting MISE_SHELL setting by [@jdx](https://github.com/jdx) in [#3284](https://github.com/jdx/mise/pull/3284)
- simplify __MISE_WATCH variable to only contain the most recent timestamp by [@jdx](https://github.com/jdx) in [#3282](https://github.com/jdx/mise/pull/3282)
- remove unnecessary cargo-binstall test by [@jdx](https://github.com/jdx) in [0a4da7a](https://github.com/jdx/mise/commit/0a4da7a023b1cb969b732afd3ad4b3cf02c42530)
- dont require build-windows before unit-windows by [@jdx](https://github.com/jdx) in [c85e2ec](https://github.com/jdx/mise/commit/c85e2ec77193d73ff20d4ce8fb7e3787a6db223d)
=> chore: release 2024.11.35

docs/walkthrough.md
The `PATH` example from the walkthrough does not work on macos 15.x.
every shell command ends with:
```
mise ERROR Plugin directory not found: "/Users/<USERNAME>/.local/share/mise/plugins/PATH"                                                                                                                                                                                             
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```
using lowercase `path` like described [here](https://mise.jdx.dev/environments.html#env-path) fixes that.
=> fix(docs): broken path example

packaging/standalone/install.envsubst
This reverts commit 3860e953cc0f4ac705cc8cfa412e53f9efb48b69.
Fixes #1716
=> Revert "fix: always prefer glibc to musl in mise run (#3261)"

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- add black by [@scop](https://github.com/scop) in [#3292](https://github.com/jdx/mise/pull/3292)
- migrate more tools away from asdf by [@jdx](https://github.com/jdx) in [40f92c6](https://github.com/jdx/mise/commit/40f92c6b0e1fefd171dd44ee9f62f1f597ee352c)
- handle General/Complex Versioning in --bump by [@liskin](https://github.com/liskin) in [#2889](https://github.com/jdx/mise/pull/2889)
- broken path example by [@minddust](https://github.com/minddust) in [#3296](https://github.com/jdx/mise/pull/3296)
- swift path on macos by [@jdx](https://github.com/jdx) in [#3299](https://github.com/jdx/mise/pull/3299)
- do not auto-install on `mise x` if some tools are passed by [@jdx](https://github.com/jdx) in [35d31a1](https://github.com/jdx/mise/commit/35d31a1baf96fe6f0e764e26228c1b03ba24ddce) …
=> chore: release 2024.11.37

docs/.vitepress/config.ts, docs/mise-cookbook.md, docs/tips-and-tricks.md
This pull request adds a new "Cookbook" section to the documentation and provides configurations for managing Terraform projects. The most important changes include adding a link to the new section in the site navigation and creating a detailed mise-cookbook. md file with various Terraform task configurations.
Documentation updates:
* [`docs/.vitepress/config.ts`](diffhunk://#diff-3def678deb1b1d5a53948eb8491817dde4dc881e032e785fc61cc93d334eefcdR116): Added a new link to the "Cookbook" section in the site navigation.
New content:
* [`docs/mise-cookbook.md`](diffhunk://#diff-e126c7bde7dec6ffd7e2bcb21131fe001c70f55b61a4b6c7bde8b5f3b85da962R1-R47): Created a new file with configurations for managing `terraform` projects, including tasks for initialization, planning, applying, destroying, …
=> docs: add terraform recipe to the cookbook

docs/cli/settings.md, docs/cli/settings/ls.md, e2e/cli/test_settings_ls, mise.usage.kdl, src/cli/settings/ls.rs, src/cli/settings/mod.rs, xtasks/fig/src/mise.ts
Fix #3301
- Add `--json-extended` output option to `mise settings ls`
- Update `--json` output to print arrays as json arrays
- ensure only one output option can be set
=> feat: Add `--json-extended` option to settings ls 

docs/dev-tools/backends/cargo.md
If not specified, `mise` will prepend `https://github.com` automatically as demonstrated below:
```text
❯ mise use -g cargo:github.com/dummy/package@branch:main
Updating git repository `https://github.com/github.com/dummy/package.git`
warning: spurious network error (3 tries remaining): unexpected http status code: 404; class=Http (34)
warning: spurious network error (2 tries remaining): unexpected http status code: 404; class=Http (34)
warning: spurious network error (1 tries remaining): unexpected http status code: 404; class=Http (34)
error: failed to clone into: /home/tmeijn/.cargo/git/db/package-01981305c4472e03
Caused by:
network failure seems to have happened
if a proxy or similar is necessary `net.git-fetch-with-cli` may help here …
```
=> docs: fix git examples for cargo backend

docs/cli/use.md, docs/configuration.md, docs/dev-tools/index.md, docs/faq.md, mise.usage.kdl, settings.toml, src/cli/local.rs, src/cli/use.rs, xtasks/fig/src/mise.ts
It has long been the case that these commands lack functionality that `mise use` provides and they have been hidden for over a year (I think, I haven't actually looked). They exist just for users coming from asdf but have been discouraged since almost the beginning of rtx.
I have no plans to remove them at this point but also do not plan on fixing any potential future issues with them so this makes it clearer these are not to be used.
=> fix: deprecate `mise local|global`

docs/ide-integration.md
This pull request includes changes to the `docs/ide-integration.md` code snippets. The changes replace incorrect `elif` statements with `else` statements to ensure correct syntax.
Changes in `docs/ide-integration.md`:
* Corrected the conditional statement for activating the environment in zsh by replacing `elif` with `else`.
* Corrected the conditional statement for activating the environment in bash by replacing `elif` with `else`.
=> fix(docs): correct syntax error in IDE integration examples

Cargo.toml, src/plugins/core/erlang.rs
Allow erlang.rs work if compiled not on Mac, Linux or Windows.
=> fix: allow compilation not on macOS, Linux, or Windows

.prettierignore, docs/cli/activate.md, e2e/cli/test_hook_env, e2e/direnv/test_direnv, mise.usage.kdl, src/assets/bash_zsh_support/LICENSE, src/assets/bash_zsh_support/README.md, src/assets/bash_zsh_support/chpwd/README.md, src/assets/bash_zsh_support/chpwd/function.sh, src/assets/bash_zsh_support/chpwd/load.sh, src/cli/activate.rs, src/git.rs, src/shell/bash.rs, src/shell/fish.rs, src/shell/snapshots/mise__shell__bash__tests__activate.snap, src/shell/snapshots/mise__shell__fish__tests__activate.snap, src/shell/snapshots/mise__shell__zsh__tests__activate.snap, src/shell/zsh.rs
=> feat: automatically call `hook-env`

src/hook_env.rs
=> fix: skip optional env._.file files

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(registry)** use aqua for some tools by [@risu729](https://github.com/risu729) in [#3375](https://github.com/jdx/mise/pull/3375)
- allow filtering `mise bin-paths` on tools by [@jdx](https://github.com/jdx) in [#3367](https://github.com/jdx/mise/pull/3367)
- added aws-cli from aqua by [@jdx](https://github.com/jdx) in [#3370](https://github.com/jdx/mise/pull/3370)
- multiple MISE_ENV environments by [@jdx](https://github.com/jdx) in [#3371](https://github.com/jdx/mise/pull/3371)
- add mise-task.json schema by [@hverlin](https://github.com/hverlin) in [#3374](https://github.com/jdx/mise/pull/3374)
- automatically call `hook-env` by [@jdx](https://github.com/jdx) in [#3373](https://github.com/jdx/mise/pull/3373)
- **(docs)** correct syntax error in IDE integration examples by …
=> chore: release 2024.12.1

src/plugins/core/zig.rs
Sorry for pointing out the small details. I just found it while reading the code.
=> refactor: use github crate to list zig releases

src/config/mod.rs
This fixes an error while running tasks defined in toml files specified in `task_config.include`.
`$MISE_CONFIG_ROOT` used to be `None`, and it caused an error when executing tasks with `dir` from non-root directories because the task ran in the current directory instead of `config_root`.
```
[debug:tasks] $ echo $(pwd) 
/home/risu/ghq/github.com/risu729/dotfiles/worker
[debug:tasks] $ echo $MISE_ORIGINAL_CWD 
/home/risu/ghq/github.com/risu729/dotfiles
[debug:tasks] $ echo $MISE_CONFIG_ROOT 
[debug:tasks] $ echo $MISE_PROJECT_ROOT 
/home/risu/ghq/github.com/risu729/dotfiles
[debug:tasks] $ echo $MISE_TASK_DIR 
/home/risu/ghq/github.com/risu729/dotfiles
[debug:tasks] $ echo $MISE_TASK_FILE 
/home/risu/ghq/github.com/risu729/dotfiles/tasks.toml
```
=> fix(config): set config_root for tasks defined in included toml files

src/watch_files.rs
=> fix: only run watch_file hook when it has changed file

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, man/man1/mise.1, packaging/rpm/mise.spec
- **(registry)** add zls to registry by [@hverlin](https://github.com/hverlin) in [#3392](https://github.com/jdx/mise/pull/3392)
- Add --json-extended option to mise env by [@hverlin](https://github.com/hverlin) in [#3389](https://github.com/jdx/mise/pull/3389)
- **(config)** set config_root for tasks defined in included toml files by [@risu729](https://github.com/risu729) in [#3388](https://github.com/jdx/mise/pull/3388)
- global hooks by [@jdx](https://github.com/jdx) in [#3393](https://github.com/jdx/mise/pull/3393)
- only run watch_file hook when it has changed file by [@jdx](https://github.com/jdx) in [#3394](https://github.com/jdx/mise/pull/3394)
- bug with aliasing core tools by [@jdx](https://github.com/jdx) in [#3395](https://github.com/jdx/mise/pull/3395)
- remove shims …
=> chore: release 2024.12.2

docs/dev-tools/backends/pipx.md
Closes #3403. Assuming it's the docs issue.
=> docs(backend): fix git url syntax example

docs/configuration.md, docs/continuous-integration.md, docs/dev-tools/aliases.md, docs/dev-tools/shims.md, docs/environments.md, docs/faq.md, docs/lang/go.md, docs/lang/node.md, docs/lang/ruby.md, docs/rtx.md, docs/tasks/index.md, docs/templates.md, docs/tips-and-tricks.md
- remove wrong links in environment variables & tasks overview
- re-order `.tool-versions`/`mise.toml` to `mise.toml`/`.tool-versions`
- remove `shoutycamelcase` from `template` page as it's not implemented
- `.mise.toml` -> `mise.toml`
=> docs: Small documentation improvements

docs/hooks.md, schema/mise.json, src/cli/hook_env.rs, src/config/config_file/mise_toml.rs, src/hooks.rs, src/shell/bash.rs, src/shell/elvish.rs, src/shell/fish.rs, src/shell/mod.rs, src/shell/nushell.rs, src/shell/xonsh.rs, src/shell/zsh.rs
Fixes https://github.com/direnv/direnv/issues/443 ;)
=> feat: shell hooks

docs/dev-tools/backends/ubi.md
Not supplying the version results in the following error:
mise ERROR error parsing config file: ~/.config/mise/config.toml
mise ERROR TOML parse error at line 5, column 17
|
5 | "ubi:cli/cli" = { exe = "gh" }
|                 ^^^^^^^^^^^^^^
missing version
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
=> docs: example with required version

src/cli/run.rs
=> fix: hide hidden tasks in `mise run` selector UI

src/task/task_script_parser.rs
=> fix: trim run scripts whitespace

docs/faq.md, docs/installing-mise.md
jumping the gun a bit on scoop because the [PR](https://github.com/ScoopInstaller/Main/pull/6374) hasn't landed, but it looks like it should soon enough
=> docs: document new windows installers

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- make `mise trust` act on directories instead of files by [@jdx](https://github.com/jdx) in [#3454](https://github.com/jdx/mise/pull/3454)
- correctly lowercase "zsh" for shell hooks by [@jdx](https://github.com/jdx) in [035ae59](https://github.com/jdx/mise/commit/035ae59bd898a16be4fcd55b708ae8ba620c60fe)
- read MISE_CONFIG_DIR/conf.d/*.toml configs by [@jdx](https://github.com/jdx) in [#3439](https://github.com/jdx/mise/pull/3439)
- retains spm artifacts by [@jdx](https://github.com/jdx) in [#3441](https://github.com/jdx/mise/pull/3441)
- add env var for MISE_NPM_BUN setting by [@jdx](https://github.com/jdx) in [b3c57e2](https://github.com/jdx/mise/commit/b3c57e29bd26d772e2f708351a3c61bf04ee3d65)
- hide hidden tasks in `mise run` selector UI by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.12.5

docs/installing-mise.md
Previous instructions were not working on the latest version of Elvish, giving the following error:
```
Exception: wrong type: need ns, got map
```
I changed it so the namespace is updated in the `eval` callback.
I also changed the alias to use `edit:add-var` since the `fn` syntax is contained to scope, so if the previous code was in, for example, an if statement, it would not export the `mise` alias.
=> docs: fixing elvish install instructions

docs/.vitepress/cli_commands.ts, docs/cli/index.md, docs/direnv.md, man/man1/mise.1, mise.usage.kdl, src/cli/direnv/activate.rs, src/cli/direnv/mod.rs, xtasks/fig/src/mise.ts
this is not a new decision, this simply documents what has been the actual state of the world for a long time.
If people are still using and liking `use mise` I wouldn't worry, it hasn't had any real changes in a very long time so likely will continue humming along as it does today. I'm probably willing to accept PRs for it too, so it's kind of a "soft" deprecation. I won't be maintaining it myself though so this makes that position clear.
And using direnv with mise together is something I'm going to be more explicit about not supporting. mise may have some lagging feature parity gaps with direnv but I don't think there are very many and certainly not many that are heavily used.
=> fix: deprecate direnv integration

docs/cli/format.md, mise.usage.kdl, src/cli/fmt.rs, src/cli/mod.rs, xtasks/fig/src/mise.ts
This will avoid conflicting with using `mise format` as shorthand for `mise run format`
=> feat: `mise fmt` (renamed from `mise format`)

docs/cli/activate.md, docs/cli/index.md, e2e/cli/test_activate_aggressive, mise.usage.kdl, src/cli/activate.rs, src/cli/hook_env.rs, src/config/config_file/mod.rs, src/config/mod.rs, src/env.rs, src/hook_env.rs, src/shell/bash.rs, src/shell/elvish.rs, src/shell/fish.rs, src/shell/mod.rs, src/shell/nushell.rs, src/shell/xonsh.rs, src/shell/zsh.rs, xtasks/fig/src/mise.ts
* check config filetime modification in millis so scripts work better
* only warn if files are untrusted
* added a `--no-hook-env` flag for activate for debugging
=> fix: improve hook-env

.idea/mise.iml, man/man1/mise.1, src/cli/mod.rs, src/toolset/tool_version.rs
Users are confused about what this does, MISE_DISABLE_TOOLS does the same thing but is easier to understand.
=> fix: deprecate @system versions
