docs/lang/rust.md, docs/lang/swift.md, src/file.rs, src/plugins/core/rust.rs, src/plugins/core/swift.rs
Also correctly marked rust+swift as experimental. This was the case before but should have been documented.
Fixes #3462
=> fix(swift): remove clang bins

e2e/cli/test_use_retain_opts, src/cli/use.rs, src/toolset/builder.rs
=> fix: do not reuse local tool options for `mise use -g`

src/cli/doctor.rs
(don't judge me for my double `~/.local/bin` I have reasons)
```console
❯ mise doctor
version: 2024.12.6-DEBUG macos-arm64 (edc962e 2024-12-11)
activated: yes
shims_on_path: no
build_info:
Target: aarch64-apple-darwin
Features: CLAP_MANGEN, DEFAULT, NATIVE_TLS, OPENSSL, RUSTLS, RUSTLS_NATIVE_ROOTS
Built: Wed, 11 Dec 2024 16:29:39 +0000
Rust Version: rustc 1.83.0 (90b35a623 2024-11-26)
Profile: debug
shell:
/opt/homebrew/bin/fish
fish, version 3.7.1
dirs:
cache: ~/Library/Caches/mise
config: ~/.config/mise
data: ~/.local/share/mise
shims: ~/.local/share/mise/shims
state: ~/.local/state/mise
config_files:
~/.config/mise/config.toml
backends:
aqua
asdf
cargo
core
gem
go
npm
pipx
spm
ubi
vfox
plugins:
asdf-antiarchitect-asdf-helm …
```
=> feat: add the users PATH to `mise doctor`

.markdownlintignore, docs/cli/index.md, docs/cli/watch.md, mise.usage.kdl, src/cli/mod.rs, src/cli/run.rs, src/cli/watch.rs, xtasks/fig/src/mise.ts
lots of improvements to `mise watch`, effectively it works the same as `mise run` now so you don't need to use `-t` anymore. I also added all the watchexec args so they show up in docs/completions.
=> fix: improve arg parsing for mise watch

schema/mise.json, settings.toml, src/cli/exec.rs, src/cli/install.rs, src/cli/run.rs, src/toolset/mod.rs
https://github.com/jdx/mise/issues/2487
=> feat: added `task_auto_install` setting

src/cli/run.rs
I literally have no clue why this filter is there. Hopefully this will not break something
Fixes #1857
=> fix: allow directories as task source

docs/lang/python.md, schema/mise.json, settings.toml, src/config/config_file/mise_toml.rs, src/config/env_directive.rs
=> feat: add settings for python venv creation

schema/mise.json, settings.toml, src/config/settings.rs, src/plugins/core/deno.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/node.rs, src/plugins/core/python.rs, src/plugins/core/swift.rs, src/plugins/core/zig.rs, src/plugins/script_manager.rs
=> feat: added MISE_ARCH setting

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- add the users PATH to `mise doctor` by [@syhol](https://github.com/syhol) in [#3474](https://github.com/jdx/mise/pull/3474)
- feat : Add superfile with aqua backend to registery by [@yodatak](https://github.com/yodatak) in [#3479](https://github.com/jdx/mise/pull/3479)
- added `task_auto_install` setting by [@jdx](https://github.com/jdx) in [#3481](https://github.com/jdx/mise/pull/3481)
- Add yazi with aqua backend to registery by [@yodatak](https://github.com/yodatak) in [#3485](https://github.com/jdx/mise/pull/3485)
- Migrating Terragrunt asdf plugin over to gruntwork-io by [@yhakbar](https://github.com/yhakbar) in [#3486](https://github.com/jdx/mise/pull/3486)
- add settings for python venv creation by [@jdx](https://github.com/jdx) in [#3489](https://github.com/jdx/mise/pull/3489)
- …
=> chore: release 2024.12.7

README.md
Fix readme link for "more tools" to link to repository instead of plugin :)
=> docs: README "more tools" link.

docs/tasks/toml-tasks.md, docs/tips-and-tricks.md
=> docs: add explanation about shebang

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(tasks)** optional automatic outputs by [@jdx](https://github.com/jdx) in [#3528](https://github.com/jdx/mise/pull/3528)
- added quiet field to tasks by [@jdx](https://github.com/jdx) in [#3514](https://github.com/jdx/mise/pull/3514)
- show instructions for updating when min_version does not match by [@jdx](https://github.com/jdx) in [#3520](https://github.com/jdx/mise/pull/3520)
- several enhancements to tasks by [@jdx](https://github.com/jdx) in [#3526](https://github.com/jdx/mise/pull/3526)
- make bash_completions lib optional by [@jdx](https://github.com/jdx) in [#3516](https://github.com/jdx/mise/pull/3516)
- make plugin update work with libgit2 by [@jdx](https://github.com/jdx) in [#3519](https://github.com/jdx/mise/pull/3519)
- bug with `mise task edit` and new tasks by …
=> chore: release 2024.12.9

src/task/mod.rs
=> fix: parse task env vars as templates

Cargo.lock, Cargo.toml, docs/cli/config/ls.md, e2e/cli/test_ls, e2e/cli/test_upgrade, e2e/cli/test_use, e2e/config/test_config_env, e2e/config/test_config_ignore, mise.usage.kdl, src/cli/config/ls.rs, src/cli/ls.rs, src/toolset/tool_request_set.rs, src/ui/style.rs, src/ui/table.rs, xtasks/fig/src/mise.ts
I think I prefer this table library, testing it out on 1 command for now
=> chore: added comfy-table

src/http.rs, src/plugins/core/python.rs
this should make version fetching with python _way_ faster
```
❯ curl -s http://mise-versions.jdx.dev/python-precompiled | wc -c | numfmt --to iec
482K
❯ curl -s http://mise-versions.jdx.dev/python-precompiled-aarch64-apple-darwin.gz | wc -c | numfmt --to iec
1.9K
```
=> fix(python): reduce network usage for python precompiled manifests

src/cli/hook_env.rs
=> fix: include uv in path for hook-env

src/config/env_directive.rs
```console
mise is 📦 v2024.12.10 via 🥟 v1.1.38 via  v23.3.0 via 🐍 v3.13.0 (.venv) via 🦀 v1.83.0 
❯ rm -rf .venv
mise WARN  no venv found at: ~/Code/syhol/mise/.venv
mise will automatically create the venv once all requested python versions are installed.
To install the missing python versions and create the venv, please run:
mise install
mise is 📦 v2024.12.10 via 🥟 v1.1.38 via  v23.3.0 via 🐍 v3.13.0 (.venv) via 🦀 v1.83.0 
❯ vim mise.toml # <-- changing env._.python.venv.create from true to false
mise WARN  no venv found at: ~/Code/syhol/mise/.venv
To create a virtualenv manually, run:
python -m venv ~/Code/syhol/mise/.venv
mise WARN  missing: python@3.9.21
```
=> docs: better warning when venv auto create is skipped

src/config/env_directive.rs
=> fix(python): check only if first or specified python is installed for _.venv

src/shell/nushell.rs, src/shell/snapshots/mise__shell__nushell__tests__hook_init.snap
Since https://github.com/nushell/nushell/pull/14344 (4d3283e), the `++` (concat) operator does not support appending a bare value to a list.
The current nushell script will result in this error in latest nushell:
```
Error: nu::shell::type_mismatch
× Type mismatch during operation.
╭─[mise.nu:14:47]
13 │   let old_hooks = $old_config | get $field --ignore-errors | default []
14 │   $env.config = ($old_config | upsert $field ($old_hooks ++ $new_hook))
·                                               ─────┬──── ─┬ ────┬────
·                                                    │      │     ╰── record<condition: closure, code: closure>
·                                                    │      ╰── type mismatch for operator
·                                                    ╰── …
```
=> fix: concat for nushell script

src/shell/nushell.rs, src/shell/snapshots/mise__shell__nushell__tests__hook_init.snap
This should fix the bugs related to PATH in nushell:
- https://github.com/jdx/mise/discussions/3589
- https://github.com/jdx/mise/discussions/3554
- https://github.com/jdx/mise/discussions/3555 (partial)
=> fix: path is treated differently in nushell

docs/installing-mise.md
Correct doc to run bootstrapping apt statements under sudo
=> docs: use sudo for apt

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- added selector for `mise use` with no args by [@jdx](https://github.com/jdx) in [#3570](https://github.com/jdx/mise/pull/3570)
- added tool descriptions by [@jdx](https://github.com/jdx) in [#3571](https://github.com/jdx/mise/pull/3571)
- added `mise sync python --uv` by [@jdx](https://github.com/jdx) in [#3575](https://github.com/jdx/mise/pull/3575)
- `sync ruby --brew` by [@jdx](https://github.com/jdx) in [#3577](https://github.com/jdx/mise/pull/3577)
- encrypted configs by [@jdx](https://github.com/jdx) in [#3584](https://github.com/jdx/mise/pull/3584)
- added `mise --no-config` by [@jdx](https://github.com/jdx) in [#3590](https://github.com/jdx/mise/pull/3590)
- allow _.file in vars by [@jdx](https://github.com/jdx) in [#3593](https://github.com/jdx/mise/pull/3593)
- **(python)** …
=> chore: release 2024.12.11

docs/installing-mise.md
VitePress does not support `:::note`:
* <https://vitepress.dev/guide/markdown#custom-containers>
* <https://github.com/vuejs/vitepress/issues/4427>
But it supports GitHub flavored alerts, which supports `> [!NOTE]`, so I used that instead:
* <https://vitepress.dev/guide/markdown#github-flavored-alerts>
=> docs: Install on Windows - Update doc on install on Windows with Scoop and WinGet + fix NOTE section

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- Add upx,actionlint and correct ripsecret error by [@boris-smidt-klarrio](https://github.com/boris-smidt-klarrio) in [#3601](https://github.com/jdx/mise/pull/3601)
- aqua:argo-cd by [@boris-smidt-klarrio](https://github.com/boris-smidt-klarrio) in [#3600](https://github.com/jdx/mise/pull/3600)
- task tools by [@jdx](https://github.com/jdx) in [#3599](https://github.com/jdx/mise/pull/3599)
- lazy env eval by [@jdx](https://github.com/jdx) in [#3598](https://github.com/jdx/mise/pull/3598)
- added cache feature to templates by [@jdx](https://github.com/jdx) in [#3608](https://github.com/jdx/mise/pull/3608)
- added MISE_SOPS_ROPS setting by [@jdx](https://github.com/jdx) in [#3603](https://github.com/jdx/mise/pull/3603)
- respect CLICOLOR_FORCE by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.12.12

docs/environments/secrets.md
The SOPS website is on a .io, not the .com
The .com looks like it expired a few years ago:
https://www.bigdomaindata.com/whois-history/getsops.com
https://getsops.io/ looks like the right link.
=> docs: Fix Sops URL

src/env_diff.rs
`__MISE_DIFF` changes value randomly when updating if any environment variables
are set by `.mise.toml` since the keys (of `new` and `old`) are not being sorted
when serialised.
(I use the value of `__MISE_DIFF` to determine if `mise` has updated the
environment to colour my prompt)
=> fix: sort keys in `__MISE_DIFF` to make the serialised value deterministic

src/task/mod.rs
These throw errors `dir` not found.
```toml
[tasks.test]
run = "pwd"
dir = "{{ config_root}}"
```
```toml
[tasks.test]
run = "pwd"
dir = "test"
```
Run `cd test && mise run test`.
I'm quite new to Rust so please fix if something is wrong.
=> fix: resolve config_root for dir tasks option

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- `mise task add` by [@jdx](https://github.com/jdx) in [#3616](https://github.com/jdx/mise/pull/3616)
- elixir core tool by [@jdx](https://github.com/jdx) in [#3620](https://github.com/jdx/mise/pull/3620)
- elixir on windows by [@jdx](https://github.com/jdx) in [#3623](https://github.com/jdx/mise/pull/3623)
- added install_env tool option by [@jdx](https://github.com/jdx) in [#3622](https://github.com/jdx/mise/pull/3622)
- Add Powershell support by [@fgilcc](https://github.com/fgilcc) in [#3506](https://github.com/jdx/mise/pull/3506)
- improve redactions by [@jdx](https://github.com/jdx) in [#3647](https://github.com/jdx/mise/pull/3647)
- run venv after tools are loaded by [@jdx](https://github.com/jdx) in [#3612](https://github.com/jdx/mise/pull/3612)
- some improvements to `mise fmt` by …
=> chore: release 2024.12.13

src/config/env_directive/venv.rs
Activating python venv on windows uses the `venv/bin` directory, but it should actually be the `venv/Scripts` path on windows.
```console
$Env:VIRTUAL_ENV='C:\Users\xxx\.local\share\chezmoi\.venv'
$Env:Path='C:\Users\xxx\.local\share\chezmoi\.venv\bin;...'
Mode  Size Date Modified    Name
-a--- 257k 2024-12-11 11:39 .\.venv\Scripts\python.exe
```
=> fix: Can not find the bin files when using python venv on windows

docs/configuration.md, schema/mise.json, settings.toml, src/config/config_file/mod.rs, src/config/mod.rs, src/env.rs
- Adds `MISE_GLOBAL_CONFIG_ROOT` to control config_root for global config file which previously was always `env::HOME` (which remains the default, when unconfigured)
- Allows `MISE_IGNORED_CONFIG_PATHS` to specify explicit paths of config files to ignore
=> feat: Allows control of config_root for global config

docs/registry.md, registry.toml
https://github.com/aristocratos/btop
```sh
docker run -it --rm jdxcode/mise:latest mise exec ubi:aristocratos/btop -- btop --utf-force
```
Tried with aqua as wellbut it does not work:
```sh
❯ mise use -g aqua:aristocratos/btop
mise ERROR failed to install aqua:aristocratos/btop@1.4.0
mise ERROR unsupported format: tbz
```
=> feat(registry): Add btop

src/config/mod.rs
Tasks in `tasks.toml` were not rendered.
=> fix: render tasks in task files

src/toolset/mod.rs
Closes #3681.
Do not include `PRSITINE_ENV` in `env` to avoid `env_with_path` to include `PRISTINE_ENV`.
=> fix: pass pristine env to tera in final_env

docs/tasks/task-configuration.md, docs/tasks/toml-tasks.md, docs/troubleshooting.md, settings.toml
`vitepress` already checks for links but does not check for anchors. `lychee` seems to be able to catch some of the issues.
```sh
cd docs/.vitepress/dist
mise x ubi:lycheeverse/lychee -- lychee .  --include-fragments --offline  
```
=> docs: fix some broken anchor links

registry.toml, src/config/env_directive/venv.rs, tasks.md, tasks.toml
Fixes: https://github.com/jdx/mise/issues/3325
Fixes: https://github.com/jdx/mise/discussions/3630
=> fix: create venv uses absolute tool paths

docs/cli/sync/python.md, mise.usage.kdl, src/cli/sync/python.rs, xtasks/fig/src/mise.ts
Fixes https://github.com/jdx/mise/issues/3654
it does not appear this is going to be possible right now at least without a bunch of work modifying sysconfig. If someone really wants this they'll need to figure out how to get mise to patch sysconfig the same way uv does: https://github.com/astral-sh/uv/blob/main/crates/uv-python/src/sysconfig/mod.rs#L217
it is rust though, so maybe we could just copy their code? Funnily enough it seems that's what they did reading the license information in the header.
It's probably also worth pinging the uv team and asking if they have any plans around the indygreg binaries that would make this easier for mise.
=> fix: disable reverse uv syncing

e2e/tasks/test_task_run_tmpl, src/cli/env.rs, src/cli/exec.rs, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__remove_plugin.snap, src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__replace_versions.snap, src/config/env_directive/mod.rs, src/task/mod.rs, src/task/task_dep.rs, src/task/task_script_parser.rs, src/toolset/mod.rs, src/toolset/tool_request_set.rs
=> fix: add full tera context to tasks

docs/.vitepress/cli_commands.ts, docs/cli/index.md, docs/cli/install-into.md, e2e/cli/test_install_into, man/man1/mise.1, mise.usage.kdl, src/backend/mod.rs, src/cli/install_into.rs, src/cli/mod.rs, src/toolset/tool_version.rs, xtasks/fig/src/mise.ts
=> feat: `mise install-into`

src/shell/pwsh.rs, src/shell/snapshots/mise__shell__pwsh__tests__activate.snap, src/shell/snapshots/mise__shell__pwsh__tests__deactivate.snap, src/shell/snapshots/mise__shell__pwsh__tests__unset_env.snap
=> fix: powershell warning

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- unnest output when `mise run` is nested by [@jdx](https://github.com/jdx) in [#3686](https://github.com/jdx/mise/pull/3686)
- `mise rm` by [@jdx](https://github.com/jdx) in [#3627](https://github.com/jdx/mise/pull/3627)
- added *:_default task name by [@jdx](https://github.com/jdx) in [#3690](https://github.com/jdx/mise/pull/3690)
- `mise run --continue-on-error by [@jdx](https://github.com/jdx) in [#3692](https://github.com/jdx/mise/pull/3692)
- added .tool-versions -> mise.toml converter by [@jdx](https://github.com/jdx) in [#3693](https://github.com/jdx/mise/pull/3693)
- get mise sync python --uv to work by [@jdx](https://github.com/jdx) in [#3706](https://github.com/jdx/mise/pull/3706)
- `mise install-into` by [@jdx](https://github.com/jdx) in …
=> chore: release 2024.12.15

e2e/tasks/test_task_options, mise.usage.kdl, src/cli/mod.rs
=> fix: `mise run` shorthand with options

src/plugins/core/ruby.rs
Seems like noone uses `ruby_install` option 😭
=> fix(ruby): fix Ruby plugin to use `ruby_install` option correctly

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- add dotnet backend by [@acesyde](https://github.com/acesyde) in [#3737](https://github.com/jdx/mise/pull/3737)
- added ignored_config_paths to `mise dr` by [@jdx](https://github.com/jdx) in [#3742](https://github.com/jdx/mise/pull/3742)
- **(ruby)** fix Ruby plugin to use `ruby_install` option correctly by [@yuhr](https://github.com/yuhr) in [#3732](https://github.com/jdx/mise/pull/3732)
- `mise run` shorthand with options by [@jdx](https://github.com/jdx) in [#3719](https://github.com/jdx/mise/pull/3719)
- zig on windows by [@jdx](https://github.com/jdx) in [#3739](https://github.com/jdx/mise/pull/3739)
- allow using previously defined vars by [@jdx](https://github.com/jdx) in [#3741](https://github.com/jdx/mise/pull/3741)
- make --help consistent with `mise run` and `mise <task>` by …
=> chore: release 2024.12.16

src/backend/mod.rs, src/cli/completion.rs, src/cli/doctor/mod.rs, src/hooks.rs, src/toolset/mod.rs, src/watch_files.rs
This fixes a bug that we cannot use the pristine env in `tasks.*.run` templates. The bug is caused by #3708, which started using toolset's `tera_ctx` instead of that of task itself.
I added config to the args of `full_env`. If it's better to make it `Option<&Config>`, I will refactor it.
https://github.com/risu729/mise/blob/130b3e1cf8a924ddf28ce94d7cb01e52a00ea09e/src/toolset/mod.rs#L466
=> fix: include full env in toolset tera_ctx

docs/mise-cookbook/docker.md, docs/mise-cookbook/nodejs.md
Apply fixes suggested @syhol here: https://github.com/jdx/mise/pull/3718#pullrequestreview-2516031839
=> docs: Small cookbooks fixes

docs/tasks/running-tasks.md, e2e/env/test_env_template, src/backend/asdf.rs, src/cli/generate/task_docs.rs, src/cli/run.rs, src/cli/tasks/info.rs, src/cli/tasks/ls.rs, src/config/env_directive/mod.rs, src/config/env_directive/path.rs, src/config/env_directive/source.rs, src/env_diff.rs, src/path_env.rs, src/task/mod.rs, src/task/task_script_parser.rs, src/toolset/mod.rs
=> fix: set env vars in task templates

docs/cli/run.md, docs/cli/tasks/run.md, mise.usage.kdl, schema/mise.json, settings.toml, src/cli/config/set.rs, src/cli/mod.rs, src/cli/run.rs, tasks.toml
=> feat: added timed task output type

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- added a banner to `mise --version` by [@jdx](https://github.com/jdx) in [#3748](https://github.com/jdx/mise/pull/3748)
- add usage field to tasks by [@jdx](https://github.com/jdx) in [#3746](https://github.com/jdx/mise/pull/3746)
- added keep-order task output type by [@jdx](https://github.com/jdx) in [#3763](https://github.com/jdx/mise/pull/3763)
- `replacing` task output type by [@jdx](https://github.com/jdx) in [#3764](https://github.com/jdx/mise/pull/3764)
- added timed task output type by [@jdx](https://github.com/jdx) in [#3766](https://github.com/jdx/mise/pull/3766)
- dotnet backend doc by [@acesyde](https://github.com/acesyde) in [#3752](https://github.com/jdx/mise/pull/3752)
- include full env in toolset tera_ctx by [@risu729](https://github.com/risu729) in …
=> chore: release 2024.12.17

e2e/backend/test_dotnet, schema/mise.json, settings.toml, src/backend/dotnet.rs
=> feat: allow dotnet prerelease

docs/cli/generate/git-pre-commit.md, mise.usage.kdl, src/cli/generate/git_pre_commit.rs
Reverts jdx/mise#3492
this is creating a bunch of "mise.pre-commit' files that are annoying to deal with
=> Revert "fix: Use arguments for to pass staged filenames to pre-commit task"

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- use zstd in mise.run by [@jdx](https://github.com/jdx) in [#3798](https://github.com/jdx/mise/pull/3798)
- verify zig with minisign by [@jdx](https://github.com/jdx) in [#3793](https://github.com/jdx/mise/pull/3793)
- increase tarball compression by [@jdx](https://github.com/jdx) in [a899155](https://github.com/jdx/mise/commit/a8991551bd7c61d1f75a800906d2f718b4bdf7c0)
- use max threads for zstd compression by [@jdx](https://github.com/jdx) in [a3f792a](https://github.com/jdx/mise/commit/a3f792a1eb0a395c7a82a063b96d30282b6343de)
- print all tarball sizes by [@jdx](https://github.com/jdx) in [29fbc04](https://github.com/jdx/mise/commit/29fbc04e52c76b16c9a72385ead4edbfaff984fb)
=> chore: release 2024.12.19

src/plugins/core/ruby.rs, src/plugins/core/ruby_windows.rs
To avoid setting the RUBYLIB environment variable, the rubygems_plugin.rb file is now placed in the site_ruby directory within the Ruby installation. This change ensures that Ruby automatically loads the plugin.
- Updated install_rubygems_hook method to place the plugin in the site_ruby directory.
- Created the necessary directory structure if it does not exist.
- Wrote the rubygems_plugin.rb file to the site_ruby directory.
=> feat: Modify install_rubygems_hook to place plugin in site_ruby directory

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(hugo)** add extended registry from aqua and keep only one registry with all aliases by [@kilianpaquier](https://github.com/kilianpaquier) in [#3813](https://github.com/jdx/mise/pull/3813)
- build erlang with all cores by [@jdx](https://github.com/jdx) in [#3802](https://github.com/jdx/mise/pull/3802)
- Modify install_rubygems_hook to place plugin in site_ruby directory by [@zkhadikov](https://github.com/zkhadikov) in [#3812](https://github.com/jdx/mise/pull/3812)
- do not require "v" prefix in mise.run by [@jdx](https://github.com/jdx) in [#3800](https://github.com/jdx/mise/pull/3800)
- add checksum for macos-x86 by [@jdx](https://github.com/jdx) in [#3815](https://github.com/jdx/mise/pull/3815)
- Correct link to aqua registry by [@jesse-c](https://github.com/jesse-c) in …
=> chore: release 2024.12.20

mise.lock, packaging/standalone/install.envsubst
Fixes #3827 
It seems `bsdtar` on macOS requires the binary `zstd` for its support to work (as opposed to GNU tar). Unfortunately he man pages do not make that clear.
=> fix: zstd detection false positive on MacOS

docs/lang/python.md, mise.lock
As `python_create_args` and `uv_create_args` options only allow list of strings and not simple strings, we correct the examples. Current examples were causing a config loading error like:
```
invalid type: string "--without-pip", expected a sequence
```
In the future it might prove useful to only include examples snippets that are also used during testing, so they do not diverge from mise usage. With mkdocs this is possible as I did it on one or two other projects.
=> docs: fix incorrect examples that were causing 'expected a sequence' error

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(python)** force precompiled setting warning message syntax by [@scop](https://github.com/scop) in [#3850](https://github.com/jdx/mise/pull/3850)
- zstd detection false positive on MacOS by [@roele](https://github.com/roele) in [#3845](https://github.com/jdx/mise/pull/3845)
- fix incorrect examples that were causing 'expected a sequence' error by [@ssbarnea](https://github.com/ssbarnea) in [#3839](https://github.com/jdx/mise/pull/3839)
- update rust crate ubi to 0.3 by [@renovate[bot]](https://github.com/renovate[bot]) in [#3836](https://github.com/jdx/mise/pull/3836)
=> chore: release 2024.12.21

mise.usage.kdl, src/assets/mise-extra.usage.kdl
This PR fixes the colon escaping substitution, done for tasks completion, to apply to all colons rather than just the first one, by using `gsub` instead of `sub`.
To replicate:
```sh
$ mise tasks add "be:api:build" -- echo hello
$ mise be<TAB>  # completes as "be:api" with the description "build:" (even though none was provided)
``` 
*This, of course, doesn't change the manually added colon.*
=> fix: add `:` escaping for tasks with multiple colons

settings.toml
Untested, current broken link in https://mise.jdx.dev/lang/python.html#settings
=> docs(settings): fix link to precompiled python binaries

docs/dev-tools/backends/cargo.md
Using these examples results in an error - it's appending the path to `https://github.com`, resulting in `https://github.com/github.com/cross-rs/cross.git`:
```
DEBUG $ cargo install --git=https://github.com/github.com/cross-rs/cross.git --branch=main --locked cross --root /Users/tomforbes/.local/share/mise/installs/cargo-github-com-cross-rs-cross/ref-main
Updating git repository `https://github.com/github.com/cross-rs/cross.git`
```
Not sure if this is intended or not, but I figured I'd fix the examples.
=> Fix cargo install examples

docs/contributing.md
Sh code block used:
```md
:::sh
<code>
:::
```
Should've been:
````md
```sh
<code>
```
````
=> docs: `contributing.md` - Fix sh code block

e2e/cli/test_settings_unset, src/cli/settings/set.rs, src/cli/settings/unset.rs
=> fix: mise settings unset does not seem to work

docs/tasks/index.md, src/cli/run.rs
I believe the intention here was for templates but for some reason this was added to env vars. Removing as it can obviously conflict with other env vars.
Fixes https://github.com/jdx/mise/issues/3883
BREAKING CHANGE: you will need to use `{{root}}` or MISE_PROJECT_ROOT after this change.
=> fix: remove `root` env var in tasks

docs/cli/activate.md, docs/dev-tools/shims.md, docs/getting-started.md, docs/ide-integration.md, docs/troubleshooting.md, mise.usage.kdl, src/cli/activate.rs
I just moved this lower because I think it's less critical (but still important) than env vars and hooks.
I've been very aggressive with the amount of warnings I've added, feel free to push back if you want me to remove some.
=> docs: clarify shims behaviour

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- winget release PRs by [@jdx](https://github.com/jdx) in [9dec542](https://github.com/jdx/mise/commit/9dec542188e731ef357fd74339dd08ac005cb9e3)
- mise settings unset does not seem to work by [@roele](https://github.com/roele) in [#3867](https://github.com/jdx/mise/pull/3867)
- gradle aqua package by [@jdx](https://github.com/jdx) in [#3880](https://github.com/jdx/mise/pull/3880)
- **breaking** remove `root` env var in tasks by [@jdx](https://github.com/jdx) in [#3884](https://github.com/jdx/mise/pull/3884)
- syntax in `mise watch` by [@jdx](https://github.com/jdx) in [beab480](https://github.com/jdx/mise/commit/beab48029b3e7a91047012b655f3efe4fd722acf)
- Update registry link by [@bmulholland](https://github.com/bmulholland) in [#3864](https://github.com/jdx/mise/pull/3864)
- clarify …
=> chore: release 2024.12.23

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- switch back to asdf for gradle by [@jdx](https://github.com/jdx) in [cc88dca](https://github.com/jdx/mise/commit/cc88dca50e8e0dac94dbb83d0ce1ebcfc38a1ec4)
- add commented out cleanup of old CLIs by [@jdx](https://github.com/jdx) in [bb7e022](https://github.com/jdx/mise/commit/bb7e022240c0e7019a595d093a33b414119e975f)
=> chore: release 2024.12.24

e2e/cli/test_config_set, src/cli/config/set.rs
Rough draft around the discussion #3820. 
This handles the basic use-case and will behave like the following.
```
mise config set tools.node 20 --> node = "20"
mise config set tools.node.version 20 --> node = { version = "20" }
mise config set tools.node 20 --> node = "20"
mise config set tools.node.postinstall 'corepack enable' --> node = { version = "20", postinstall = "corepack enable" }
```
=> fix: panic when setting config value

docs/registry.md, registry.toml, src/cli/test_tool.rs, src/http.rs, src/toolset/install_state.rs
=> feat: use aqua for gradle

src/cli/ls.rs
=> fix: active flag for symlinked tools in `mise ls --json`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- use aqua for gradle by [@jdx](https://github.com/jdx) in [#3903](https://github.com/jdx/mise/pull/3903)
- added completions to more commands by [@jdx](https://github.com/jdx) in [#3910](https://github.com/jdx/mise/pull/3910)
- panic when setting config value by [@roele](https://github.com/roele) in [#3823](https://github.com/jdx/mise/pull/3823)
- add hidden settings/task --complete option by [@jdx](https://github.com/jdx) in [#3902](https://github.com/jdx/mise/pull/3902)
- handle panic when task contains invalid template by [@jdx](https://github.com/jdx) in [#3904](https://github.com/jdx/mise/pull/3904)
- missing checksums in mise.run script by [@jdx](https://github.com/jdx) in [#3906](https://github.com/jdx/mise/pull/3906)
- active flag for symlinked tools in `mise ls --json` by …
=> chore: release 2025.1.0

docs/environments/index.md, docs/mise-cookbook/nodejs.md
Make Node.JS cookbook only recommend one style instead of both.
=> docs: clarity on relative paths vs config_root in _.path

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- add databricks-cli to registry by [@benberryallwood](https://github.com/benberryallwood) in [#3937](https://github.com/jdx/mise/pull/3937)
- add navi to registry by [@kit494way](https://github.com/kit494way) in [#3943](https://github.com/jdx/mise/pull/3943)
- added allurectl to registry by [@MontakOleg](https://github.com/MontakOleg) in [#3918](https://github.com/jdx/mise/pull/3918)
- Add setting description to mise settings --json-extended output by [@hverlin](https://github.com/hverlin) in [#3919](https://github.com/jdx/mise/pull/3919)
- improve mise generate bootstrap by [@hverlin](https://github.com/hverlin) in [#3939](https://github.com/jdx/mise/pull/3939)
- Fix broken link to environment variables doc by [@xcapaldi](https://github.com/xcapaldi) in …
=> chore: release 2025.1.1

src/aqua/aqua_registry.rs
Fixes #3977 
The [registry.yml](https://mise-versions.jdx.dev/aqua-registry/apache/maven-mvnd/registry.yaml) does not contain a field `asset` like the current code assumes. Instead a `url` is provided which can be used to derive the asset pattern from.
Could not find much information about the registry.yml format on https://aquaproj.github.io/docs/reference/registry-config though so i'm not sure if this fix might cause potential other issues and is the correct approach.
=> fix: maven-mvnd does not install with aqua

schema/mise-task.json, schema/mise.json
Updates inconsistency between the schema and the docs.
Not sure whether the description is good for `outputs.auto`.
`automatically touch an internal tracked file instead of specifying outputs`
https://mise.jdx.dev/tasks/task-configuration.html#outputs
=> fix(schema): fix task schema

e2e/tasks/test_task_deps, e2e/tasks/test_task_info, e2e/tasks/test_task_ls, mise.lock, src/cli/tasks/deps.rs, src/cli/tasks/info.rs, src/task/mod.rs
Related to https://github.com/jdx/mise/discussions/3980
I am not sure if these changes are correct but, I think we should either use `display_name` everywhere or report both `name` and `display_name` in the json. I prefer just reporting `display_name` while also supporting `name` internally?
This will make the following commands work
```sh
cargo run -- t deps aqua-tester
cargo run -- t info aqua-tester
```
which is consistent with what the autocompletion displays: (or `mise tasks ls`)
without this change, one will get:
```
mise tasks info aqua-tester 
mise ERROR Task not found: aqua-tester, use `mise tasks ls` to list all tasks
```
=> fix: use task display_name in more places

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- migrate asdf plugins to aqua/ubi by [@jdx](https://github.com/jdx) in [#3962](https://github.com/jdx/mise/pull/3962)
- migrate asdf plugins to aqua/ubi by [@jdx](https://github.com/jdx) in [#3978](https://github.com/jdx/mise/pull/3978)
- migrate asdf plugins to aqua/ubi by [@jdx](https://github.com/jdx) in [#3991](https://github.com/jdx/mise/pull/3991)
- replace asdf-spark plugin with mise-spark plugin by [@benberryallwood](https://github.com/benberryallwood) in [#3994](https://github.com/jdx/mise/pull/3994)
- add kubectx/kubens to registry by [@roele](https://github.com/roele) in [#3992](https://github.com/jdx/mise/pull/3992)
- added ktlint from aqua by [@jdx](https://github.com/jdx) in [#4004](https://github.com/jdx/mise/pull/4004)
- **(schema)** fix task sources and outputs schema by …
=> chore: release 2025.1.2

e2e/cli/test_alias, src/backend/aqua.rs
=> fix: aliases with aqua

e2e/tasks/test_task_depends_post, src/task/deps.rs, src/task/mod.rs
=> fix: allow using depends and depends_post on separate tasks

docs/troubleshooting.md
This way, it goes directly to the new GitHub classic token page with a prefilled description
=> docs: Add default description to github token link

src/aqua/aqua_registry.rs, src/backend/aqua.rs
Another follow up for #3890
It seems for `http` package types with a `raw` format we might need to add the `.exe` extension in some cases (e.g kubernetes/kubectl). Correct approach would be to fix the registry and provide an override for the windows OS with proper url but since aqua has fixed this in code we might have to follow this approach i assume.
TODO: needs to be tested on a Windows machine
=> fix: mise fails to install kubectl on windows from aqua registry

docs/cli/alias.md, docs/cli/backends.md, docs/cli/bin-paths.md, docs/cli/cache.md, docs/cli/config.md, docs/cli/doctor.md, docs/cli/generate.md, docs/cli/generate/git-pre-commit.md, docs/cli/generate/github-action.md, docs/cli/generate/task-docs.md, docs/cli/generate/task-stubs.md, docs/cli/install-into.md, docs/cli/ls-remote.md, docs/cli/plugins.md, docs/cli/plugins/ls-remote.md, docs/cli/self-update.md, docs/cli/settings.md, docs/cli/sync.md, docs/cli/tasks.md, mise.usage.kdl, src/assets/mise-extra.usage.kdl
=> docs: fix source code links

docs/tasks/file-tasks.md
The variables didn't quite match up with the usage.
=> fix: Example of a NodeJS file task with arguments

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- added gdu and dua to registry by [@sassdavid](https://github.com/sassdavid) in [#4052](https://github.com/jdx/mise/pull/4052)
- added prefix-dev/pixi by [@jdx](https://github.com/jdx) in [#4056](https://github.com/jdx/mise/pull/4056)
- added `mise cfg --tracked-configs` by [@jdx](https://github.com/jdx) in [#4059](https://github.com/jdx/mise/pull/4059)
- added `mise version --json` flag by [@jdx](https://github.com/jdx) in [#4061](https://github.com/jdx/mise/pull/4061)
- added `mise ls --prunable` flag by [@jdx](https://github.com/jdx) in [#4062](https://github.com/jdx/mise/pull/4062)
- switch jib back to asdf by [@jdx](https://github.com/jdx) in [#4055](https://github.com/jdx/mise/pull/4055)
- `mise unuse` bug not pruning if not in config file by [@jdx](https://github.com/jdx) in …
=> chore: release 2025.1.5

docs/lang/rust.md, src/cmd.rs, src/plugins/core/rust.rs
=> feat: allow to specify Rust profile

src/backend/external_plugin_cache.rs, src/config/config_file/mod.rs
Fixes #4071 
`String::truncate` seems to work on byte level which can cause issues with multi-byte characters. `String::chars() `handles multi-byte characters properly though.
=> fix: panic when directory name contains japanese characters

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add gup by [@scop](https://github.com/scop) in [#4107](https://github.com/jdx/mise/pull/4107)
- **(registry)** add aqua and cmdx by [@scop](https://github.com/scop) in [#4106](https://github.com/jdx/mise/pull/4106)
- use aqua for eza on linux by [@jdx](https://github.com/jdx) in [#4075](https://github.com/jdx/mise/pull/4075)
- allow to specify Rust profile by [@roele](https://github.com/roele) in [#4101](https://github.com/jdx/mise/pull/4101)
- use vars in [env] templates by [@hverlin](https://github.com/hverlin) in [#4100](https://github.com/jdx/mise/pull/4100)
- panic when directory name contains japanese characters by [@roele](https://github.com/roele) in [#4104](https://github.com/jdx/mise/pull/4104)
- incorrect config_root for project/.mise/config.toml by …
=> chore: release 2025.1.7

src/shell/bash.rs, src/shell/fish.rs, src/shell/snapshots/mise__shell__bash__tests__activate.snap, src/shell/snapshots/mise__shell__fish__tests__activate.snap, src/shell/snapshots/mise__shell__zsh__tests__activate.snap, src/shell/zsh.rs
This infinite loop bug is triggered when `mise` itself becomes not found, e.g., by deleting the directory `mise` is in.
Here's some output of the shell with `set -x` on when doing `rm -rf` on the directory (`workspace/`) containing `mise` in some subpath:
```
+ rm -rf workspace/
++ _mise_hook
++ local previous_exit_status=0
+++ mise hook-env -s bash
+++ local command
+++ command=hook-env
+++ '[' 3 = 0 ']'
+++ shift
+++ case "$command" in
+++ command mise hook-env -s bash
+++ mise hook-not-found -s bash -- mise
+++ local command
+++ command=hook-not-found
+++ '[' 5 = 0 ']'
+++ shift
+++ case "$command" in
+++ command mise hook-not-found -s bash -- mise
+++ mise hook-not-found -s bash -- mise
+++ local command
+++ command=hook-not-found
+++ '[' 5 = 0 ']'
+++ shift
+++ case "$command" in
+++ …
```
=> fix: Fixes infinite loop in auto install not found bash function

src/backend/spm.rs, src/git.rs
See https://github.com/jdx/mise/discussions/4042
Installs using spm backend works with some repos, but fails for other. For example
`mise install spm:nicklockwood/SwiftFormat@0.54.3` - ok
`mise install spm:realm/SwiftLint@0.57.1` - fails:
```
ERROR git failed: Cmd(["git", "-C", "/home/vscode/.cache/mise/spm-realm-swift-lint/0.57.1/repo", "-c", "safe.directory=/home/vscode/.cache/mise/spm-realm-swift-lint/0.57.1/repo", "fetch", "--prune", "--update-head-ok", "origin", "0.57.1:0.57.1"]) error: cannot update ref 'refs/heads/0.57.1': trying to write non-commit object bf3f358f09ca74dc7f031ed44f185fd7a874efe4 to branch 'refs/heads/0.57.1'
```
Looks like it does not work with annotated tags:
```sh
swiftlint (main)> git cat-file -t 0.57.1
tag
SwiftFormat (main)> git cat-file -t 0.54.3
commit
``` …
=> fix(spm): install from annotated tag

docs/configuration.md
Inline code in vitepress still got interpolated as vue template (ref: https://github.com/vuejs/vuepress/issues/2377). Wrap the paragraph with `::: v-pre` to avoid this.
=> docs: fix doc for MISE_GLOBAL_CONFIG_ROOT got interpolated

src/plugins/core/erlang.rs, src/plugins/core/mod.rs
Up to now `core:erlang` was not enabled for Windows. Precompiled Windows releases are provided at https://github.com/erlang/otp as ZIP file and can be installed similarly as for MacOS.
=> feat: enable erlang for Windows

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- upgrade ubi by [@jdx](https://github.com/jdx) in [#4078](https://github.com/jdx/mise/pull/4078)
- enable erlang for Windows by [@roele](https://github.com/roele) in [#4128](https://github.com/jdx/mise/pull/4128)
- use aqua for opentofu by [@jdx](https://github.com/jdx) in [#4129](https://github.com/jdx/mise/pull/4129)
- **(spm)** install from annotated tag by [@MontakOleg](https://github.com/MontakOleg) in [#4120](https://github.com/jdx/mise/pull/4120)
- Fixes infinite loop in auto install not found bash function by [@bnorick](https://github.com/bnorick) in [#4094](https://github.com/jdx/mise/pull/4094)
- installing with empty version fails by [@roele](https://github.com/roele) in [#4123](https://github.com/jdx/mise/pull/4123)
- correct link to gem.rs source by …
=> chore: release 2025.1.8

src/shell/fish.rs, src/shell/snapshots/mise__shell__fish__tests__activate.snap
An error for `fish_command_not_found` was introduce in #4094 because
glob misses do not work the same in fish as in other shells. As such,
we are getting the following error on an unknown function:
```
- (line 64): No matches for wildcard '"mise-"*'. See `help wildcards-globbing`.
if test "$argv[1]" != "mise" -a "$argv[1]" != "mise-"*
```
This has been replaced with a fish-specific implementation test that
prevents the error and is somewhat more idiomatic as well.
=> fix: Fixes fish_command_not_found glob error

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(aqua)** pass --verbose flag down to cosign and added aqua.cosign_extra_args setting by [@jdx](https://github.com/jdx) in [#4148](https://github.com/jdx/mise/pull/4148)
- **(doctor)** display redacted github token by [@jdx](https://github.com/jdx) in [#4149](https://github.com/jdx/mise/pull/4149)
- Fixes fish_command_not_found glob error by [@halostatue](https://github.com/halostatue) in [#4133](https://github.com/jdx/mise/pull/4133)
- completions for `mise use` by [@jdx](https://github.com/jdx) in [#4147](https://github.com/jdx/mise/pull/4147)
- **(ruby)** remove ruby/gem tests by [@jdx](https://github.com/jdx) in [#4130](https://github.com/jdx/mise/pull/4130)
- update dependency bun to v1.1.44 by [@renovate[bot]](https://github.com/renovate[bot]) in …
=> chore: release 2025.1.9

docs/configuration.md
fix broken link for `/tasks/#task-configuration`. it should be `tasks/task-configuration`
=> docs: fix broken link for `/tasks/task-configuration`

docs/ide-integration.md, docs/mise-cookbook/index.md, docs/mise-cookbook/neovim.md
From #3952, slightly improved code and explanation.
Not sure how to render the docs locally so hopefully it renders ok.
=> docs: neovim cookbook

src/shell/fish.rs, src/shell/snapshots/mise__shell__fish__tests__activate.snap
When a user enters a command starting with a dash (for example `-la`) they got an error like this.
```fish
string match: -la: unknown option
- (line 64): 
if string match -qrv '^(?:mise$|mise-)' $argv[1] &&
^
in function 'fish_command_not_found' with arguments '-ad'
in event handler: handler for generic event “fish_command_not_found”
(Type 'help string' for related documentation)
fish: Unknown command: -ad
```
For me this happened accidentally and no command will/should start with a dash. It just looked confusing. Now a clear separation between options to `string match` and the two strings to be matched is made.
For reference this is what vanilla fish shows:
```
❯ -ad
fish: Unknown command: -ad
```
=> fix: confusing error in fish_command_not_found

src/config/env_directive/venv.rs, src/plugins/core/mod.rs, src/plugins/core/python.rs
Python installations on windows do not have a bin directory. This is already taken into account in different places, but when automatically creating venvs bin is always used.
This change was my attempt to fix this as a non-rust developer with minimal code changes and reusing the existing python_path function. I had to make the python plugin public, which is probably not the way to do it. 😄 
So I am open to suggestions on how to properly fix this.
https://github.com/jdx/mise/discussions/4152
=> fix: use correct python path for venv creation in windows

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** use aqua for periphery by [@MontakOleg](https://github.com/MontakOleg) in [#4157](https://github.com/jdx/mise/pull/4157)
- split remote task by [@acesyde](https://github.com/acesyde) in [#4156](https://github.com/jdx/mise/pull/4156)
- **(docs)** environment variable MISE_OVERRIDE_TOOL_VERSIONS_FILENAME should be plural by [@roele](https://github.com/roele) in [#4183](https://github.com/jdx/mise/pull/4183)
- completions were missing non-asdf tools by [@jdx](https://github.com/jdx) in [55b31a4](https://github.com/jdx/mise/commit/55b31a452b807ada4e2ba40c8b5588b77b79642e)
- broken link for `/tasks/task-configuration` by [@134130](https://github.com/134130) in [#4155](https://github.com/jdx/mise/pull/4155)
- whitespace in mise.run script by [@jdx](https://github.com/jdx) in …
=> chore: release 2025.1.10

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add gron by [@MontakOleg](https://github.com/MontakOleg) in [#4204](https://github.com/jdx/mise/pull/4204)
- spurious semver warning on `mise outdated` by [@jdx](https://github.com/jdx) in [#4199](https://github.com/jdx/mise/pull/4199)
- lint issue in Dockerfile by [@jdx](https://github.com/jdx) in [47ad5d6](https://github.com/jdx/mise/commit/47ad5d67890188478cf8c8f2e6796b6752546e6c)
- fix some typos in markdown file by [@chuangjinglu](https://github.com/chuangjinglu) in [#4198](https://github.com/jdx/mise/pull/4198)
- pin aws-cli by [@jdx](https://github.com/jdx) in [f7311fd](https://github.com/jdx/mise/commit/f7311fd8fc85b6920c5a484862865adc9ef7261d)
- use arm64 runners for docker by [@jdx](https://github.com/jdx) in [#4200](https://github.com/jdx/mise/pull/4200)
- …
=> chore: release 2025.1.14

docs/getting-started.md
Executing `sudo dnf config-manager --add-repo https://mise.jdx.dev/rpm/mise.repo` in the latest Fedora release (v41) with dnf throws the following error (probably due to dnf5):
> Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.
=> docs: update Fedora install cmd to reflect dnf5 config-manager

src/cli/install.rs, src/cli/use.rs, src/env.rs, src/toolset/tool_request_set.rs
Fixes #4114 
The `dependency_toolset` function should not rely on dependencies in the Config to build the environment for the CmdLineRunner, especially when used with `install`.
Since this seems specific to Elixir so far and the method is used in other contexts, its probably best to keep the solution exclusive to elixir. If necessary we can move it up to the trait later. WDYT?
=> fix: elixir installation failed

docs/components/setting.vue, docs/settings.data.ts
The docs currently don't mentions how array values are parsed. This PR is adding a hint about either comma or colon separated string array values.
=> docs: add hint about environment variable parsing

src/cli/run.rs, src/task/task_file_providers/mod.rs, src/task/task_file_providers/remote_task_http.rs
improve code by using builder pattern
=> feat: use builder pattern

Cargo.lock, Cargo.toml, schema/mise.json, scripts/build-tarball.ps1, scripts/build-tarball.sh, settings.toml, src/env.rs, src/git.rs
this removes the runtime dependency on libgit2 shared objects
=> chore: switch from git2 to gix

Cargo.lock, Cargo.toml, src/build_time.rs, src/cli/version.rs
since we switched to gix it isn't worth compiling all of libgit2 for sometimes displaying the git sha in `mise -v`
=> chore: remove git2 from built

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- add http cache by [@acesyde](https://github.com/acesyde) in [#4160](https://github.com/jdx/mise/pull/4160)
- expose `test-tool` command by [@jdx](https://github.com/jdx) in [#4224](https://github.com/jdx/mise/pull/4224)
- elixir installation failed by [@roele](https://github.com/roele) in [#4144](https://github.com/jdx/mise/pull/4144)
- re-run tasks when files removed or permissions change by [@jdx](https://github.com/jdx) in [#4223](https://github.com/jdx/mise/pull/4223)
- use builder pattern by [@acesyde](https://github.com/acesyde) in [#4220](https://github.com/jdx/mise/pull/4220)
- **(how-i-use-mise)** switch to discussion by [@risu729](https://github.com/risu729) in [#4225](https://github.com/jdx/mise/pull/4225)
- add hint about environment variable parsing by …
=> chore: release 2025.1.15

Cargo.toml
these are enabled by default and seem like things we should have
=> chore: added some default reqwest features

src/plugins/core/swift.rs
The wrong download path is generated: 
The correct format is: 
```https://download.swift.org/swift-6.0.2-release/ubuntu2404-aarch64/swift-6.0.2-RELEASE/swift-6.0.2-RELEASE-ubuntu24.04-aarch64.tar.gz```
but mise was using:
```https://download.swift.org/swift-6.0.2-release/ubuntu2404/swift-6.0.2-RELEASE/swift-6.0.2-RELEASE-ubuntu24.04-aarch64.tar.gz```
=> fix:  Swift on Ubuntu 24.04 arm64 generates the incorrect download URL

e2e/cli/test_use, src/cli/use.rs
Fixes #4244 and issue mentioned in #4211
=> fix: path option should take precedence over global configuration

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add duckdb by [@swfz](https://github.com/swfz) in [#4248](https://github.com/jdx/mise/pull/4248)
- Swift on Ubuntu 24.04 arm64 generates the incorrect download URL by [@spyder-ian](https://github.com/spyder-ian) in [#4235](https://github.com/jdx/mise/pull/4235)
- Do not attempt to parse directories by [@adamcohen2](https://github.com/adamcohen2) in [#4256](https://github.com/jdx/mise/pull/4256)
- path option should take precedence over global configuration by [@roele](https://github.com/roele) in [#4249](https://github.com/jdx/mise/pull/4249)
- Add devtools.fm episode about mise to external-resources.md by [@CanRau](https://github.com/CanRau) in [#4253](https://github.com/jdx/mise/pull/4253)
- Update sections about idiomatic version files by …
=> chore: release 2025.1.16

docs/configuration.md, docs/lang/python.md, docs/mise-cookbook/python.md, e2e/core/test_python_precompiled, schema/mise.json, src/config/settings.rs
- Update python documentation. 
- Indicate how one might use it with `uv` in the cookbook (at least according to my understanding and after experimenting a bit with it)
- Re-order the sections in the python page with the section about `uv`, `.python-version` and virtual env first
- Update the `mise` json schema to match the documentation (and observed behavior)
=> docs: Update python documentation

docs/mise-cookbook/nodejs.md
Fix the error in hooks replace `post_install` with `postinstall`
=> docs: fix postinstall typo in nodejs cookbook

src/shims.rs
Fixes #4011 
Gave this a try but detection of `msys` or `cygwin` does not work via `$OSTYPE` as this is not available via `env` so `env::var()` does not return anything. Not sure how reliable my approach via `MSYSTEM` and `PWD` is though.
Another unresolved issue seems to be related to line breaks on cygwin. The `.bashrc` file does not source successfully until its opened and saved (without changes). Probably would require a `dos2unix` on cygwin, not sure why that is not an issue on msys.
```bash
$ source .bashrc
': not a valid identifiernctions
-bash: .bashrc: line 35: syntax error near unexpected token `$'\r''
'bash: .bashrc: line 35: `function __zsh_like_cd() {
```
=> fix: mise does not operate well under Git Bash on Windows

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** use aqua for duckdb by [@mangkoran](https://github.com/mangkoran) in [#4270](https://github.com/jdx/mise/pull/4270)
- mise does not operate well under Git Bash on Windows by [@roele](https://github.com/roele) in [#4048](https://github.com/jdx/mise/pull/4048)
- mise rm removes/reports wrong version of tool by [@roele](https://github.com/roele) in [#4272](https://github.com/jdx/mise/pull/4272)
- Update python documentation by [@hverlin](https://github.com/hverlin) in [#4260](https://github.com/jdx/mise/pull/4260)
- fix postinstall typo in nodejs cookbook by [@arafays](https://github.com/arafays) in [#4251](https://github.com/jdx/mise/pull/4251)
- Fix typo by [@henrebotha](https://github.com/henrebotha) in [#4277](https://github.com/jdx/mise/pull/4277)
- MISE_PROJECT_DIR -> …
=> chore: release 2025.1.17

docs/mise-cookbook/python.md
This is a `mise` command, yes? not `uv`?
=> Fix typo in the Python cookbook

docs/registry.md, registry.toml
Ref: https://github.com/kubernetes-sigs/kwok
Ref: https://github.com/aquaproj/aqua-registry/tree/9124d9fb77ded25d95ff22bde80624be5bbadc66/pkgs/kubernetes-sigs/kwok/kwokctl
`kwokctl.test` version template
```
❯ ./kwokctl-linux-amd64 --version
kwokctl version v0.6.1 go1.22.3 (linux/amd64)
```
Note: Please reword my commit message to include the two refs later when merging. Currently it's only one. Thank you.
=> feat(registry): add kwokctl

docs/components/registry.vue
Additional styling for the search input.
Remove the table style so table renders with horizontal scrollbar if necessary.
=> docs: fix registry table rendering for mobile

schema/mise-task.json, schema/mise.json
Resolves #4323. Since the default is explained by `default` property, just remove it from the `description`.
=> docs(schema): fix description of task.dir default

docs/cli/index.md, docs/cli/unuse.md, mise.usage.kdl, src/cli/unuse.rs, xtasks/fig/src/mise.ts
For consistency with the inverse command 'use'.
=> feat: add -g short version for unuse cmd

docs/external-resources.md, docs/ide-integration.md, docs/installing-mise.md, docs/lang/bun.md, docs/lang/deno.md, docs/lang/elixir.md, docs/lang/erlang.md, docs/lang/go.md, docs/lang/java.md, docs/lang/node.md, docs/lang/python.md, docs/lang/ruby.md, docs/lang/swift.md, docs/lang/zig.md, docs/mise-cookbook/nodejs.md
- Make each page a bit more consistent
- Re-order the sections so that the `settings` are always last
- Update pages with additional informations (for example, add information about Gradle toolchain detection discussed here: https://github.com/jdx/mise/discussions/4143#discussioncomment-11868502)
=> docs: Update documentation for core tools

src/aqua/aqua_registry.rs
While I was debugging for #4338, I found that the `versions` crate comparison logic was weird. It treated versions without prefixes larger than versions with prefixes.
As documented in the code, it should be an expected behaviour, but since many GitHub release tags contain prefixes, we should somehow trim them before comparing versions.
>  `nth_lenient` pulls a leading digit from the `Version`'s chunk if it could. If it couldn't, that chunk is some string (perhaps a git hash) and is considered as marking a beta/prerelease version. It is thus considered less than the `SemVer`.
https://github.com/fosskers/rs-versions/blob/efb1b0d16418b17a774e3e5572815367bc813bcd/src/semver.rs#L124-L130
However, we need to parse `version_constraint` to get `version_prefix` from `version_overrides`, so we …
=> fix(aqua): trim prefix before comparing versions

src/config/config_file/mod.rs
Fixes issue discussed in #4005
=> fix: wrong config file type for rust-toolchain.toml files

e2e/tasks/test_task_run_toml, src/cli/run.rs
Fixes #4070
@jdx I have tested it locally and everything seems to work fine, but before merging the PR I would like to have your opinion if everything seems ok. After that, I would like to add some e2e tests, but I do not know whether it is better to add them to e2e/tasks/test_task_run_toml, e2e/tasks/test_task_vars or to create a new test file just for this feature. Where do you think it is best to add them?
=> feat: set usage arguments and flags as environment variables for toml tasks

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add jd by [@risu729](https://github.com/risu729) in [#4318](https://github.com/jdx/mise/pull/4318)
- **(registry)** add jc by [@risu729](https://github.com/risu729) in [#4317](https://github.com/jdx/mise/pull/4317)
- **(registry)** Add qsv cli by [@vjda](https://github.com/vjda) in [#4334](https://github.com/jdx/mise/pull/4334)
- add support for idiomatic go.mod file by [@roele](https://github.com/roele) in [#4312](https://github.com/jdx/mise/pull/4312)
- add -g short version for unuse cmd by [@kimle](https://github.com/kimle) in [#4330](https://github.com/jdx/mise/pull/4330)
- add git remote task provider by [@acesyde](https://github.com/acesyde) in [#4233](https://github.com/jdx/mise/pull/4233)
- set usage arguments and flags as environment variables for toml tasks by …
=> chore: release 2025.2.2

src/shims.rs
This fixes a bug on macOS where we are searching for a shim name with one or more characters uppercased, e.g. Python. But on macOS the APFS (default file system) is case insensitive, so `mise doctor` will always report an error in this case.
See https://github.com/jdx/mise/discussions/4332
=> fix: lowercase desired shim names

src/hook_env.rs
=> fix(hook_env): don't exit early if watching files are deleted

src/aqua/aqua_registry.rs
The opts attribute on cosign check for aqua is optional. If not provided it will make the package resolution fail. This patch makes it optional and provide an empty array if key is not found.
This address the issue described here: https://github.com/jdx/mise/discussions/4092
=> fix: allow cosign opts to be empty in aqua

docs/installing-mise.md
Fedora 41+ is using `dnf5` which has slightly different commands.
=> docs: update Fedora install for dnf5

src/plugins/core/assets/rubygems_plugin.rb
Replace which ruby command with `RbConfig::CONFIG` check to ensure cross-platform compatibility, particularly for Windows environments where which is not available.
When running `bundle update` on Windows, the following error occurs:
```
❯ bundle update
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
--- ERROR REPORT TEMPLATE -------------------------------------------------------
Errno::ENOENT: No such file or directory - which ruby
<path_to_mise>/mise/current/mise/installs/ruby/3.4.1/lib/ruby/site_ruby/rubygems_plugin.rb:12:in 'Kernel#`'
```
The error occurs because the `which` command does not exist on Windows systems. This PR replaces the command with `RbConfig::CONFIG` check to make the Ruby detection more platform-agnostic.
=> fix(rubygems_plugin):  Replace which ruby check for Windows compatibility

docs/configuration.md
Fix a link in the documentation which was not displayed correctly.
Also make it easier to copy-paste the command, moving the link away from the actual command to use.
Screen:
=> docs: fix links to idiomatic version file option

src/plugins/core/zig.rs
This update makes `mise` smarter about finding specific Zig versions! I was personally frustrated trying to use a nominated Zig version and finding that `mise` couldn't grab it with the previous behavior. This change fixes that! Specifically, it improves how `mise` handles those in-between "dev" versions of Zig (like `0.14.0-dev.2577+271452d22`).
The main Zig website (`ziglang.org/download`) doesn't always keep older or development versions around. `machengine.org` does! So, this change tells `mise` to automatically grab those specific "dev" versions from `machengine.org` instead.
**Here's the key thing:** This only applies to Zig versions that look like `0.14.0-dev.2577+271452d22` (a number, then `-dev`, then more numbers and letters). If you're using a regular, stable Zig version (like …
=> feat: use `machengine.org` for downloading nominated zig versions

registry.toml
This PR adds [marksman](https://github.com/artempyanykh/marksman) to the Mise registry via the Aqua backend (see PR [#31906](https://github.com/aquaproj/aqua-registry/pull/31906), merged as of yesterday).
Marksman implements the Language Server Protocol for Markdown to be used in terminal- and non-terminal-based text editors. Marksman is developed in F# and distributed as a single binary for Linux, MacOS, and Windows. Installation using `mise` was tested successfully on Fedora and Ubuntu.
=> feat(registry): add 'marksman' via 'aqua:artempyanykh/marksman' backend

e2e/tasks/test_task_run_toml, e2e/tasks/test_task_usage, src/cli/run.rs
Reverts jdx/mise#4159
Fixes #4379
=> revert: "feat: set usage arguments and flags as environment variables for toml tasks"

e2e/env/test_env_profiles, e2e/tools/test_path_order, src/config/env_directive/mod.rs, src/config/env_directive/path.rs, src/config/mod.rs
=> fix: regression with env overriding

registry.toml
Adds `lychee` (https://github.com/lycheeverse/lychee) to the `mise` registry.
`lychee` is already in the aqua registry: https://github.com/aquaproj/aqua-registry/tree/main/pkgs/lycheeverse/lychee
=> feat(registry): add lychee to registry

docs/cli/alias.md, docs/cli/generate/git-pre-commit.md, docs/components/registry.vue, docs/dev-tools/aliases.md, docs/dev-tools/backends/asdf.md, docs/dev-tools/backends/index.md, docs/dev-tools/index.md, docs/dev-tools/shims.md, docs/environments/index.md, docs/plugins.md, docs/registry.md, man/man1/mise.1, mise.usage.kdl, src/cli/alias/mod.rs, xtasks/fig/src/mise.ts
- update env. vars page to indicate under which conditions they work
- small updates to backend/plugins/registry pages
- clarify that `mise alias` command is only for version aliases (not backend aliases)
=> docs: Add a section on how to use environment variables

docs/lang/zig.md, e2e-win/zig.Tests.ps1, e2e/core/test_zig, src/plugins/core/zig.rs
It installs latest nominated zig version from machengine
```
mise use zig@ref:mach-latest
```
I see it requires some improvements over `mise ls-remote zig` to show nightly versions.
We also need to install `zls` related to `zig version` as for now it uses just latest release (0.13) which is wrong
=> feat: Install latest nominated zig from https://machengine.org/zig/index.json

packaging/standalone/install.envsubst
Fix three issues with the tar version check in mise.run:
- period should be escaped in order to only match periods
- the 4-9 range needs to be put in `[]` not `{}`
- GNU grep (common on Linux) does not support `\d`
=> fix: bugs with grep in tar_supports_zstd in mise.run script

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add lychee to registry by [@eread](https://github.com/eread) in [#4181](https://github.com/jdx/mise/pull/4181)
- Install latest nominated zig from https://machengine.org/zig/index.json by [@tamadamas](https://github.com/tamadamas) in [#4451](https://github.com/jdx/mise/pull/4451)
- **(cli/run)** inherit stdio by --raw even when redactions are enabled by [@risu729](https://github.com/risu729) in [#4446](https://github.com/jdx/mise/pull/4446)
- **(task)** Running programs on windows without cmd.exe by [@NavyD](https://github.com/NavyD) in [#4459](https://github.com/jdx/mise/pull/4459)
- bugs with grep in tar_supports_zstd in mise.run script by [@glasser](https://github.com/glasser) in [#4453](https://github.com/jdx/mise/pull/4453)
- fix watch files hook example by …
=> chore: release 2025.2.7

e2e/cli/test_use, src/cli/use.rs
Fixes #4490 
Using `MISE_ENV` circumvents the option overrides, so `global`, `path` and `env` options should come before `MISE_ENV` in the loading priority.
=> fix: bug when using mise use -g when MISE_ENV is filled

docs/dev-tools/backends/ubi.md, src/backend/ubi.rs
Add a missing option for ubi backend.
Tested with this :
```bash
$ @mise use --global 'podman[exe=podman-remote-static-linux_amd64,rename_exe=podman]'
mise Installed executable into ~/.local/share/mise/installs/podman/5.4.0/podman
mise podman@5.4.0    ✓ installed
mise ~/.config/mise/config.toml tools: podman@5.4.0
$ which podman
~/.local/share/mise/installs/podman/5.4.0/podman
```
=> feat(ubi): add option `rename_exe`

e2e-win/shim.Tests.ps1, schema/mise.json, settings.toml, src/shims.rs
https://github.com/jdx/mise/discussions/4360
add setting `windows_shim_mode`
1. `file` default, current implement 
2. `hardlink`, require on same filesystem
3. `symlink`: Requires Windows Vista or later with admin privileges or enabling "Developer Mode" in Windows 10/11.
I am not familiar with Rust or the code base here
test on windows 11 24h2 with "Devloper Mode"
=> feat(shim): Windows shim add hardlink & symlink mode

registry.toml
[sops](https://github.com/getsops/sops) SOPS is an editor of encrypted files that supports YAML, JSON, ENV, INI and BINARY formats and encrypts with AWS KMS, GCP KMS, Azure Key Vault, age, and PGP
Tests :
```
mise use -g aqua:getsops/sops
```
```
mise aqua:getsops/sops@3.9.4 ✓ installed
mise ~/.config/mise/config.toml tools: aqua:getsops/sops@3.9.4
```
=> feat(registry): added sops from aqua registry

registry.toml
[k9s](https://github.com/derailed/k9s) K9s provides a terminal UI to interact with your Kubernetes clusters
Tests :
```
mise use -g aqua:derailed/k9s
```
```
mise aqua:derailed/k9s@0.40.5 ✓ installed
mise ~/.config/mise/config.toml tools: aqua:derailed/k9s@0.40.5
```
=> feat(registry): added k9s from aqua registry

registry.toml
[hadolint](https://github.com/hadolint/hadolint) ContainerFile linter 
Tests :
```
mise use -g aqua:hadolint/hadolint
```
```
mise aqua:hadolint/hadolint@2.12.0 ✓ installed
mise ~/.config/mise/config.toml tools: aqua:hadolint/hadolint@2.12.0
```
=> feat(registry): added hadolint from aqua registry

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add checkmake to registry by [@eread](https://github.com/eread) in [#4466](https://github.com/jdx/mise/pull/4466)
- **(registry)** added sops from aqua registry by [@ldrouard](https://github.com/ldrouard) in [#4457](https://github.com/jdx/mise/pull/4457)
- **(registry)** added k9s from aqua registry by [@ldrouard](https://github.com/ldrouard) in [#4460](https://github.com/jdx/mise/pull/4460)
- **(registry)** added hadolint from aqua registry by [@ldrouard](https://github.com/ldrouard) in [#4456](https://github.com/jdx/mise/pull/4456)
- **(shim)** Windows shim add hardlink & symlink mode by [@qianlongzt](https://github.com/qianlongzt) in [#4409](https://github.com/jdx/mise/pull/4409)
- **(ubi)** add option `rename_exe` by [@wlmitch](https://github.com/wlmitch) in …
=> chore: release 2025.2.8

registry.toml
Adding [cocogitto/cocogitto](https://github.com/cocogitto/cocogitto) (binary filename: `cog`) to the registry. 
Should (?) work:
```
❯ mise use aqua:cocogitto/cocogitto
mise aqua:cocogitto/cocogitto@6.2.0 ✓ installed                                                                                                                                                            mise ~/code/tools/my-project/.config/mise.toml tools: aqua:cocogitto/cocogitto@6.2.0
```
Hope this counts as obvious. ;)
=> feat(registry): add cocogitto

registry.toml
https://github.com/foundry-rs/foundry
Foundry has become the de facto standard tool to develop solidity and vyper contracts for EVM blockchains
The package actually consists of a suite of tools: forge, cast, chisel, and anvil. Thus, the `extract_all` flag is needed
=> feat(registry): Added foundry

docs/ide-integration.md
The link to the "mise.el" repository seems to have changed after the user changed their username. This PR updates the links in the "ide-integration" page.
=> docs: update mise.el repo link

registry.toml
[ast-grep](https://github.com/ast-grep/ast-grep) A CLI tool for code structural search, lint and rewriting
Tests :
```
$ cargo run --bin mise -- tool ast-grep                                                                                                  *1 [main] 12:19:10
Compiling mise v2025.2.7 (/Users/tony/Projects/oss/mise)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 18.47s
Running `target/debug/mise tool ast-grep`
Backend:            aqua:ast-grep/ast-grep
$ cargo run --bin mise -- use -g ast-grep                                                                                                *1 [main] 12:19:34
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.94s
Running `target/debug/mise use -g …
```
=> feat(registry): added ast-grep

registry.toml
Helmwave is helm3-native tool for deploy your Helm Charts. HelmWave is like docker-compose for helm.
```
$ cargo run --bin mise -- tool helmwave
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.34s
Running `target/debug/mise tool helmwave`
Backend:            aqua:helmwave/helmwave
Active Version:     0.41.8
Requested Version:  latest
Config Source:      ~/.config/mise/config.toml
$ cargo run --bin mise -- use -g helmwave
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.83s
Running `target/debug/mise use -g helmwave`
mise helmwave@0.41.8    install
mise helmwave@0.41.8    download helmwave_0.41.8_darwin_arm64.tar.gz
mise helmwave@0.41.8    checksum helmwave_0.41.8_darwin_arm64.tar.gz
mise helmwave@0.41.8 …
```
=> feat(registry): added helmwave

registry.toml
doggo - Command-line DNS Client for Humans. Written in Golang
Test
```
$ cargo run --bin mise -- tool doggo
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.77s
Running `target/debug/mise tool doggo`
Backend:            aqua:mr-karan/doggo
$ cargo run --bin mise -- use -g doggo
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.94s
Running `target/debug/mise use -g doggo`
mise doggo@1.0.5        install
mise doggo@1.0.5        download doggo_1.0.5_Darwin_arm64.tar.gz
mise doggo@1.0.5        checksum doggo_1.0.5_Darwin_arm64.tar.gz
mise doggo@1.0.5        extract doggo_1.0.5_Darwin_arm64.tar.gz
mise doggo@1.0.5      ✓ installed
mise ~/.config/mise/config.toml tools: doggo@1.0.5
$ cargo run --bin mise -- tool doggo …
```
=> feat(registry): added doggo

registry.toml
gokey - A simple vaultless password manager in Go
Test
```
$ cargo run --bin mise -- tool gokey
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.75s
Running `target/debug/mise tool gokey`
Backend:            ubi:cloudflare/gokey
$ cargo run --bin mise -- use -g gokey
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.87s
Running `target/debug/mise use -g gokey`
mise gokey@0.1.3        install
mise Installed executable into /Users/anton.solovev/.local/share/mise/installs/gokey/0.1.3/gokey
mise gokey@0.1.3        checksum generate gokey-macos-aarch64
mise gokey@0.1.3      ✓ installed
mise ~/.config/mise/config.toml tools: gokey@0.1.3
$ cargo run --bin mise -- tool gokey
Finished `dev` profile [unoptimized + …
```
=> feat(registry): added gokey

registry.toml
octosql - a query tool that allows you to join, analyse and transform data from multiple databases and file formats using SQL.
Test
```
$ cargo run --bin mise -- tool octosql
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.08s
Running `target/debug/mise tool octosql`
Backend:            ubi:cube2222/octosql
$ cargo run --bin mise -- use -g octosql
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.80s
Running `target/debug/mise use -g octosql`
mise octosql@0.13.0     install
mise Installed executable into /Users/tony/.local/share/mise/installs/octosql/0.13.0/octosql
mise octosql@0.13.0     checksum generate octosql-macos-aarch64
mise octosql@0.13.0   ✓ installed
mise ~/.config/mise/config.toml tools: …
```
=> feat(registry): added octosql

registry.toml
hexyl - A command-line hex viewer
Test
```
$ cargo run --bin mise -- tool hexyl
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.76s
Running `target/debug/mise tool hexyl`
Backend:            aqua:sharkdp/hexyl
$ cargo run --bin mise -- use -g hexyl
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.00s
Running `target/debug/mise use -g hexyl`
mise hexyl@0.16.0       install
mise hexyl@0.16.0       download hexyl-v0.16.0-x86_64-apple-darwin.tar.gz
mise hexyl@0.16.0       generate checksum hexyl-v0.16.0-x86_64-apple-darwin.tar.gz
mise hexyl@0.16.0       extract hexyl-v0.16.0-x86_64-apple-darwin.tar.gz
mise hexyl@0.16.0     ✓ installed
mise ~/.config/mise/config.toml tools: hexyl@0.16.0
$ cargo run --bin mise -- tool …
```
=> feat(registry): added hexyl

registry.toml
kubeone automate cluster operations on all your cloud, on-prem, edge, and IoT environments
Test
```
$ cargo run --bin mise -- tool kubeone
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.71s
Running `target/debug/mise tool kubeone`
Backend:            aqua:kubermatic/kubeone
$ cargo run --bin mise -- use -g kubeone
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.98s
Running `target/debug/mise use -g kubeone`
mise kubeone@1.8.6      install
mise kubeone@1.8.6      download kubeone_1.8.6_darwin_arm64.zip
mise kubeone@1.8.6      checksum kubeone_1.8.6_darwin_arm64.zip
mise kubeone@1.8.6      extract kubeone_1.8.6_darwin_arm64.zip
mise kubeone@1.8.6    ✓ installed
mise ~/.config/mise/config.toml tools: …
```
=> feat(registry): added kubeone

docs/continuous-integration.md
It seems MISE_DATA_DIR needs to be absolute, as per https://github.com/jdx/mise/discussions/4313
This change fixed it in my CI so perhaps the docs need to be updated.
=> docs: continuous-integration.md: fix gitlab caching example

docs/lang/rust.md, src/cmd.rs, src/plugins/core/rust.rs
This is an enhancement as per discussion in #4573.
Adds support for the `components`, `profile` and `targets` properties of the `rust-toolchain.toml` idiomatic file. Additionally adds the `components` and `targets` as (comma separated) tool options in the `mise.toml` file.
=> feat: add support for components property in rust-toolchain.toml

registry.toml
Test
```
$ cargo run --bin mise -- tool sampler                                                                                               *1 (sampler) 18:20:14
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.12s
Running `target/debug/mise tool sampler`
Backend:            aqua:sqshq/sampler
$ cargo run --bin mise -- use -g sampler                                                                                             *1 (sampler) 18:22:18
Compiling mise v2025.3.0 (/Users/tony/Projects/oss/mise)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 21.76s
Running `target/debug/mise use -g sampler`
mise sampler@1.1.0   install
mise sampler@1.1.0   download sampler-1.1.0-darwin-amd64
mise sampler@1.1.0   generate …
```
=> feat(registry): added sampler

docs/cli/ls.md, e2e/cli/test_ls, mise.usage.kdl, src/cli/ls.rs, xtasks/fig/src/mise.ts
Related to https://github.com/jdx/mise/discussions/4411 
Allow to get tools list, defined only in local mise.toml
```
~/Projects/oss/mise ✔ $ cargo run --bin mise -- ls                                                                                      (ls-local) 17:27:58
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.20s
Running `target/debug/mise ls`
Tool                    Version            Source                            Requested
bat                     0.25.0             ~/.config/mise/config.toml        latest
bun                     1.2.2 (missing)    ~/Projects/oss/mise/mise.toml     latest
cargo-binstall          1.10.22 (missing)  ~/Projects/oss/mise/mise.toml     latest
cargo:cargo-edit        0.13.1 (missing)   ~/Projects/oss/mise/mise.toml     latest …
```
=> feat: add --local flag for ls

registry.toml
Lazyjournal - A TUI for reading logs from journalctl, file system, Docker and Podman containers, as well Kubernetes pods for quick viewing and filtering with fuzzy find, regex support and coloring the output, written in Go with the gocui.
```
$ cargo run --bin mise -- tool lazyjournal                                                                                       *1 (lazyjournal) 13:43:04
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.76s
Running `target/debug/mise tool lazyjournal`
Backend:            aqua:Lifailon/lazyjournal
$ cargo run --bin mise -- use -g lazyjournal                                                                                     *1 (lazyjournal) 13:43:13
Finished `dev` profile [unoptimized + …
```
=> feat(registry): added lazyjournal

schema/mise.json, settings.toml
This PR improves the usage of `disable_default_registry` as explained in the discussion [4581](https://github.com/jdx/mise/discussions/4581)
=> docs(settings): clarify the usage of disable_default_registry

deny.toml
Ignores [RUSTSEC-2025-0014](https://rustsec.org/advisories/RUSTSEC-2025-0014.html) which is added on 10th March.
=> chore: ignore humantime unmaintained advisory

registry.toml
> #18 Added new flag -a/--audit to get summary and diagnostic information and the ability to load into the brew package manager. Now the flag -v/--version returns only the version without unnecessary text.
https://github.com/Lifailon/lazyjournal/releases/tag/0.7.5
=> test(registry): fix test of lazyjournal

src/toolset/mod.rs, src/uv.rs
Fixes #4600.
`UV_VENV` initialization somtimes cause a deadlock in some cases because it requires loading `path` or `env` to get the toolset.
This PR avoids the deadlock by using `Mutex` and returning `None` while initializing itself.
=> fix(uv): avoid deadlocks while initializing UV_VENV

.github/workflows/release.yml, .github/workflows/test.yml
For both `ubuntu-latest` and `macos-latest`, the Rust verison is updated to `1.85.0`.
https://github.com/actions/runner-images/pull/11704
https://github.com/actions/runner-images/pull/11726
=> chore: remove rustup update in github actions

e2e/tasks/test_task_deps_circular, src/cli/run.rs, src/task/deps.rs
refactor: the condition on when the task runner finishes.
refactor: use the insert boolean instead of a !contains
feature: infinitive loop detection
=> feat: cleanup the mutex use.

Cargo.lock, Cargo.toml, deny.toml, src/cli/settings/set.rs, src/config/settings.rs, src/duration.rs, src/http.rs, src/tera.rs
Follow up of #4612. `humantime` crate is now outdated, so migrate to [jiff](https://crates.io/crates/jiff) instead as `cargo-deny` suggests.
`jiff` is almost compatible with `humantime`, but is not 100% compatible as documented.
https://docs.rs/jiff/latest/jiff/fmt/friendly/index.html#comparison-with-the-humantime-crate
Notably, `1M` is parsed as `1 month` by `humantime` but cannot be parsed by `jiff`.
I used `2025-01-01` when converting `Span` to `SignedDuration` since we need a relative date to convert `months` or `years`, in which the duration differs depending on dates.
https://docs.rs/jiff/latest/jiff/struct.Span.html#integration-with-stdtimeduration-and-signedduration
=> refactor: migrate humantime to jiff

docs/cli/fmt.md, docs/cli/index.md, mise.usage.kdl, src/cli/fmt.rs, xtasks/fig/src/mise.ts
This allow to take input from stdin so it can be integrated in editors or shell pipelines
Also move format process into a function to be reusable for stdin process and regular file based process
=> feat: Add flag to fmt command to read from stdin

src/file.rs
Fixes a bug that surfaced with #4623
=> fix: handle error when getting modified duration in file::modified_duration

src/backend/spm.rs
Addresses [this discussion](https://github.com/jdx/mise/discussions/4613)
Swift introduced a breaking change in the package manifest dumped through stdout from the Swift toolchain version 6.0. That's causing the installation of packages through the `spm` backend to fail.
This PR fixes it.
=> fix: SwiftPM backend not working with the Swift 6 toolchain

src/config/env_directive/venv.rs
=> fix: Unable to find uv when first creating py venv

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(env)** support env files in toml by [@risu729](https://github.com/risu729) in [#4618](https://github.com/jdx/mise/pull/4618)
- **(registry)** add harper-ls and harper-cli by [@kit494way](https://github.com/kit494way) in [#4615](https://github.com/jdx/mise/pull/4615)
- **(registry)** add curlie by [@reitzig](https://github.com/reitzig) in [#4599](https://github.com/jdx/mise/pull/4599)
- cleanup the mutex use. by [@boris-smidt-klarrio](https://github.com/boris-smidt-klarrio) in [#4540](https://github.com/jdx/mise/pull/4540)
- Add flag to fmt command to read from stdin by [@erickgnavar](https://github.com/erickgnavar) in [#4594](https://github.com/jdx/mise/pull/4594)
- **(uv)** avoid deadlocks while initializing UV_VENV by [@risu729](https://github.com/risu729) in …
=> chore: release 2025.3.3

src/tera.rs
Fixes https://github.com/jdx/mise/discussions/4607.
I used `SETTINGS.default_inline_shell()` because the parsed scripts are executed with it, but `env::SHELL` should also be fine for this case.
=> fix(tera): use default inline shell to parse exec template

src/backend/ubi.rs
https://docs.rs/ubi/0.5.2/ubi/struct.UbiBuilder.html#method.forge
Without this, gitlab.com projects can be installed by specifying the full URL, but that's a bit unwieldy and doesn't work for other GitLab instances besides the gitlab.com one.
=> feat: ubi forge option support

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- unpin aws-cli by [@jdx](https://github.com/jdx) in [7fabed5](https://github.com/jdx/mise/commit/7fabed5c70fccfe095647c7b2220965ca2f1c07d)
- temporarily disable bootstrap test by [@jdx](https://github.com/jdx) in [599258a](https://github.com/jdx/mise/commit/599258aa4f5c0ab0b5581740b0c9eec17f1c7318)
=> chore: release 2025.3.6

Cargo.lock, src/task/mod.rs, src/task/task_script_parser.rs
This PR enables the use of `arg`, `option`, and `flag` in task templates within `if` conditions or similar syntaxes.
Currently, placeholders are replaced only after the Tera template is fully rendered. So, expressions like the following:
```toml
[tasks.test]
run = "echo {% if flag(name='test') == 'true' %}test is true{% endif %}"
```
would incorrectly render `mise test --test` as just `echo ` because `'MISE_TASK_ARG:test:MISE_TASK_ARG' != 'true'`.
Since we need to parse the usage spec before rendering the full Tera template, this PR adds the second rendering after the usage spec is processed. This ensures that expressions with nest like this are evaluated correctly.
```toml
[tasks.test]
run = "echo {% if flag(name=env.FLAG_NAME) == 'true' %}TRUE{% endif %}"
```
Re-rendering the template …
=> fix(task): allow args to be used with tera tests

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(node)** skip gpg verification of sig file not found by [@jdx](https://github.com/jdx) in [#4663](https://github.com/jdx/mise/pull/4663)
- **(task)** allow args to be used with tera tests by [@risu729](https://github.com/risu729) in [#4605](https://github.com/jdx/mise/pull/4605)
- Fix syntax error on `activate nu` when PATH contains shims by [@atty303](https://github.com/atty303) in [#4349](https://github.com/jdx/mise/pull/4349)
- **(registry)** use ubi for yamlscript by [@scop](https://github.com/scop) in [#4670](https://github.com/jdx/mise/pull/4670)
- Fix typo in java.md by [@hverlin](https://github.com/hverlin) in [#4672](https://github.com/jdx/mise/pull/4672)
- "chore: temporarily disable bootstrap test" by [@jdx](https://github.com/jdx) in …
=> chore: release 2025.3.7

docs/dev-tools/shims.md
Removes an incorrect `run` word in the docs and adjusts `rust` to `Rust`.
=> docs: small tidy of shims docs

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add aichat by [@kit494way](https://github.com/kit494way) in [#4691](https://github.com/jdx/mise/pull/4691)
- Update flake to fix nix build by [@akanter](https://github.com/akanter) in [#4686](https://github.com/jdx/mise/pull/4686)
- fix bash completion setup instructions by [@bestagi](https://github.com/bestagi) in [#3920](https://github.com/jdx/mise/pull/3920)
- small tidy of shims docs by [@AlecRust](https://github.com/AlecRust) in [#4693](https://github.com/jdx/mise/pull/4693)
- remove broken ripsecrets test by [@jdx](https://github.com/jdx) in [bb382aa](https://github.com/jdx/mise/commit/bb382aa783a2a1bfc44f02a5bb34f9397efb2e57)
- make awscli compatible with R2 by [@jdx](https://github.com/jdx) in [cad7fa2](https://github.com/jdx/mise/commit/cad7fa285e96483ba8d6aeb22f8 …
=> chore: release 2025.3.8

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- Set usage arguments and flag as environment variables before running the command by [@gturi](https://github.com/gturi) in [#4700](https://github.com/jdx/mise/pull/4700)
- **(registry)** use ubi for assh by [@scop](https://github.com/scop) in [#4713](https://github.com/jdx/mise/pull/4713)
- **(registry)** use ubi for opsgenie-lamp by [@scop](https://github.com/scop) in [#4712](https://github.com/jdx/mise/pull/4712)
- **(registry)** use ubi for auto-doc by [@scop](https://github.com/scop) in [#4714](https://github.com/jdx/mise/pull/4714)
- **(registry)** use ubi for getenvoy by [@scop](https://github.com/scop) in [#4715](https://github.com/jdx/mise/pull/4715)
- **(registry)** use ubi for mockolo by [@scop](https://github.com/scop) in [#4705](https://github.com/jdx/mise/pull/4705)
- …
=> chore: release 2025.3.9

registry.toml
Adds [protoc-gen-validate tool](https://github.com/bufbuild/protoc-gen-validate). As it is a protoc plugin, there's not a great way to test it off the bat.
```
mise use go:github.com/bufbuild/protoc-gen-validate 
go: downloading github.com/bufbuild/protoc-gen-validate v1.2.1
go: downloading github.com/iancoleman/strcase v0.3.0
go: downloading google.golang.org/protobuf v1.36.3
go: downloading github.com/lyft/protoc-gen-star/v2 v2.0.4-0.20230330145011-496ad1ac90a4
go: downloading github.com/spf13/afero v1.10.0
go: downloading golang.org/x/tools v0.21.1-0.20240508182429-e35e4ccd0d2d
go: downloading golang.org/x/mod v0.17.0
mise go:github.com/bufbuild/protoc-gen-validate@1.2.1 ✓ installed
mise ~/test/.mise.toml tools: go:github.com/bufbuild/protoc-gen-validate@1.2.1
```
```
mise use …
```
=> feat(registry): add protoc-gen-validate

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add protoc-gen-validate by [@akanter](https://github.com/akanter) in [#4703](https://github.com/jdx/mise/pull/4703)
- **(registry)** use aqua for swiftlint by [@scop](https://github.com/scop) in [#4726](https://github.com/jdx/mise/pull/4726)
- **(registry)** use ubi for opensearch-cli by [@scop](https://github.com/scop) in [#4725](https://github.com/jdx/mise/pull/4725)
- **(registry)** use ubi for mdbook-linkcheck by [@scop](https://github.com/scop) in [#4724](https://github.com/jdx/mise/pull/4724)
- **(registry)** use ubi for velad by [@scop](https://github.com/scop) in [#4727](https://github.com/jdx/mise/pull/4727)
=> chore: release 2025.3.11

docs/installing-mise.md
This fixes a simple omission when documenting the new dnf5 syntax for adding the mise repository to Fedora.
=> docs: mark code block for dnf5 install as shell code

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- s/runtimes/tools by [@jdx](https://github.com/jdx) in [#4754](https://github.com/jdx/mise/pull/4754)
- add clarification on RUSTUP_HOME and CARGO_HOME by [@lachieh](https://github.com/lachieh) in [#4759](https://github.com/jdx/mise/pull/4759)
- enhance confirmation logic to respect SETTINGS.yes by [@roele](https://github.com/roele) in [#4764](https://github.com/jdx/mise/pull/4764)
- **(registry)** use aqua for ubi by [@scop](https://github.com/scop) in [#4745](https://github.com/jdx/mise/pull/4745)
- **(registry)** use aqua for ksops by [@scop](https://github.com/scop) in [#4746](https://github.com/jdx/mise/pull/4746)
- mark code block for dnf5 install as shell code by [@sina-hide](https://github.com/sina-hide) in [#4747](https://github.com/jdx/mise/pull/4747)
- update demo by …
=> chore: release 2025.4.0

registry.toml
[localstack](https://github.com/localstack/localstack) LocalStack is a cloud software development framework to develop and test your AWS applications locally.
Tests:
```
$ cargo run --bin mise -- install localstack
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.26s
Running `target/debug/mise install localstack`
mise Installed executable into /Users/mnm/.local/share/mise/installs/localstack/4.3.0/localstack
mise localstack@4.3.0 ✓ installed
$ cargo run --bin mise -- tool localstack
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.26s
Running `target/debug/mise tool localstack`
Backend:            ubi:localstack/localstack-cli[exe=localstack]
Installed Versions: 4.3.0
Tool Options:       exe="localstack"
$ cargo run --bin mise -- uninstall localstack
Finished …
```
=> feat(registry): added localstack

registry.toml
[skeema](https://github.com/skeema/skeema)
Skeema is a tool for managing MySQL and MariaDB schema changes in a declarative fashion using pure SQL.
For the `skeema.tests`, the skeema version is a bit bloat-some.
```
$ skeema version
skeema version 1.12.3-community, commit 085259b2f833beb0588e72f9085c1f51bdfd5879, released 2025-02-27T22:12:38Z
```
I saw `doggo.test` used `awk`, so I did the same to pair it down
```
$ skeema version | awk -F, '{print $1}'
skeema version 1.12.3-community
```
Tests (using both aqua and ubi backends):
```
$ cargo run --bin mise -- install skeema
Compiling mise v2025.4.0 (/Users/mnm/mise)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.69s
Running `target/debug/mise install skeema`
mise skeema@1.12.3   ✓ installed
$ cargo run --bin mise -- tool …
```
=> feat(registry): added skeema

src/http.rs
=> fix: show gh rate limit reset time in local time

docs/external-resources.md
I wrote a blog post about using Mise secrets' capability to encrypt secrets in Swift app repositories and obfuscate them into the app binary at build time.
=> Include post about Mise secrets in the context of Swift app dev

registry.toml
Updates backend for aws-nuke to [aqua:ekristen/aws-nuke](https://github.com/aquaproj/aqua-registry/pull/34262).
This brings it in alignment with the asdf backend which [switched upstreams](https://github.com/bersalazar/asdf-aws-nuke/pull/1). 
Resolves https://github.com/jdx/mise/discussions/4814
=> feat(registry): update aws-nuke backend

e2e/cli/test_use_env, src/cli/use.rs, src/env.rs
I just hit a situation where I had set `MISE_ENV=macos` globally. This meant that `mise use` started writing to `mise.macos.toml` which I did not want.
I am not sure why I had this logic in the first place but it doesn't seem ideal. It seems to me if you specify `mise use -E macos` _that_ should write to `mise.macos.toml` but not if it's just an env var.
@roele I know you worked on this code a bit in https://github.com/jdx/mise/pull/4249 but I think it was more about making the `--path` flag work correctly. Any concerns about this change?
=> fix: do not default to writing to mise.$MISE_ENV.toml

Cargo.lock, src/cli/watch.rs
mise watch not forward --exts and --filter args to watchexec
=> fix: mise watch forward --exts and --filter to watchexec

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** update aws-nuke backend by [@StingRayZA](https://github.com/StingRayZA) in [#4815](https://github.com/jdx/mise/pull/4815)
- do not default to writing to mise.$MISE_ENV.toml by [@jdx](https://github.com/jdx) in [#4817](https://github.com/jdx/mise/pull/4817)
- mise watch forward --exts and --filter to watchexec by [@cmhms](https://github.com/cmhms) in [#4826](https://github.com/jdx/mise/pull/4826)
- Fixing typo in code for flags in toml-tasks.md by [@arafays](https://github.com/arafays) in [#4820](https://github.com/jdx/mise/pull/4820)
- branding by [@jdx](https://github.com/jdx) in [9ad2c17](https://github.com/jdx/mise/commit/9ad2c17ec75b7460ebea09a9f0601a561349cc7f)
- remove references to not-working docker: tasks by [@jdx](https://github.com/jdx) in …
=> chore: release 2025.4.2

src/aqua/aqua_registry.rs, src/backend/aqua.rs
https://github.com/aquaproj/aqua/blob/fdfe33db55f25db8d286f38e03a34e488ee15a1b/json-schema/registry.json#L625-L627
Only one corner case in the registry for now, `aqua:aquaproj/example-go-slsa-provenance@v0.1.0`
=> feat(aqua): support SLSA source_uri setting

src/aqua/aqua_registry.rs, src/backend/aqua.rs
For a bit tighter checking. aqua does it too.
Closes https://github.com/jdx/mise/discussions/4791
* https://github.com/aquaproj/aqua/blob/fdfe33db55f25db8d286f38e03a34e488ee15a1b/pkg/slsa/exec.go#L69-L79
* https://github.com/aquaproj/aqua/blob/fdfe33db55f25db8d286f38e03a34e488ee15a1b/pkg/installpackage/verify_slsa.go#L41-L44
=> feat(aqua): use source tag in SLSA verification

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(aqua)** support SLSA source_uri setting by [@scop](https://github.com/scop) in [#4833](https://github.com/jdx/mise/pull/4833)
- **(aqua)** use source tag in SLSA verification by [@scop](https://github.com/scop) in [#4836](https://github.com/jdx/mise/pull/4836)
- **(ubi)** add support for self-hosted GitHub/GitLab by [@roele](https://github.com/roele) in [#4765](https://github.com/jdx/mise/pull/4765)
- Update configuration.md by [@jdx](https://github.com/jdx) in [#4829](https://github.com/jdx/mise/pull/4829)
- correct `mise use` paths by [@jdx](https://github.com/jdx) in [c8374c0](https://github.com/jdx/mise/commit/c8374c00ca68e5722c28f9abfd2425b9722bdd83)
=> chore: release 2025.4.3

src/backend/ubi.rs, src/github.rs
=> fix(ubi): API URL for GitHub should not have /repos segement

src/cli/upgrade.rs
Key changes are as such:
`src/cli/upgrade.rs`
* Modified the upgrade process to update configuration files only for tools that were successfully installed.
* Changed the logic to uninstall old versions of tools only if their new versions were successfully upgraded.
* Adjusted the rebuild of shims and runtime symlinks to occur only for successful upgrades.
=> fix: removed possible single-point-of-failure while running `mise upgrade` 

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(ubi)** API URL for GitHub should not have /repos segement by [@roele](https://github.com/roele) in [#4848](https://github.com/jdx/mise/pull/4848)
- **(ubi)** URL syntax fails by [@roele](https://github.com/roele) in [#4859](https://github.com/jdx/mise/pull/4859)
- allow to install non-numeric elixir versions by [@roele](https://github.com/roele) in [#4850](https://github.com/jdx/mise/pull/4850)
- removed possible single-point-of-failure while running `mise upgrade` by [@hitblast](https://github.com/hitblast) in [#4847](https://github.com/jdx/mise/pull/4847)
- `#MISE tools=` in task header by [@jdx](https://github.com/jdx) in [#4860](https://github.com/jdx/mise/pull/4860)
- fix aqua tool test by [@jdx](https://github.com/jdx) in …
=> chore: release 2025.4.5

docs/dev-tools/backends/go.md, e2e/backend/test_go_install_slow, src/backend/go.rs
Allow installing tools like golang migrate that require people to pass -tags to work with specific databases.
I've been working on a go project and we managed to install all our tools with mise with the exception of golang migrate. The reason being that installing it to work in our setup required passing `-tags postgres`. I recently saw how `ubi` allow some specific tags for specifying the binary to extract and I realized I could do something similar for go. 
Hopefully you like it 😄
=> feat(go): support build tags

docs/dev-tools/backends/go.md
Fix a small typo I introduced in #4863 
Sorry xD
=> docs: fix typo in go backend tags option title

settings.toml
The link was broken because of this commit https://github.com/jdx/mise/commit/5bba86b03e7dd652a0958aa584e0a7322483f3e1.
=> docs: update link to faq in use_versions_host

src/cli/upgrade.rs
Fixes #4869.
This change allows users to proceed without selecting any options, but it doesn’t introduce a dedicated cancel operation.
=> fix: allow interactive upgrade to select nothing

src/config/config_file/mise_toml.rs
Fixes https://github.com/jdx/mise/discussions/4846.
=> fix: enable templates for shell of hooks

src/aqua/aqua_registry.rs, src/backend/aqua.rs
Fixes https://github.com/jdx/mise/discussions/4895.
ref: https://github.com/aquaproj/aqua/blob/a3e7356995673ed372b69d20dda148cd4b963171/pkg/config/registry/minisign.go#L3-L11
The following three packages use `minisign`.
However, `bufbuild/buf` signs a `sha256.txt` file, which is not supported, so I only checked for the other two:
- `ziglang/zig`
- `zigtools/zls`
- `bufbuild/buf`  
https://github.com/search?q=repo%3Aaquaproj%2Faqua-registry+minisign%3A&type=code
---
For SLSA, `type` is parsed as `String`, but for checksums it's parsed as the `AquaChecksumType` enum.  
I added `AquaMinisignType` enum for consistency, but if using `String` is preferred, I can update it.  
https://github.com/jdx/mise/blob/46a58953725853388aebfe4060e3ed18a80c32e4/src/aqua/aqua_registry.rs#L131-L133 …
=> feat(aqua): support github_release minisign type

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(aqua)** support github_release minisign type by [@risu729](https://github.com/risu729) in [#4897](https://github.com/jdx/mise/pull/4897)
- **(go)** support build tags by [@bamorim](https://github.com/bamorim) in [#4863](https://github.com/jdx/mise/pull/4863)
- **(registry)** added Signadot by [@joehorsnell](https://github.com/joehorsnell) in [#4868](https://github.com/jdx/mise/pull/4868)
- added `idiomatic_version_file_enable_tools` and deprecated `idiomatic_version_file_disable_tools` by [@jdx](https://github.com/jdx) in [#4902](https://github.com/jdx/mise/pull/4902)
- **(doctor)** redact gitlab/enterprise tokens by [@risu729](https://github.com/risu729) in [#4888](https://github.com/jdx/mise/pull/4888)
- **(task)** enable templates in shell and tools of tasks by …
=> chore: release 2025.4.6

registry.toml
[Oxipng](https://github.com/shssoichiro/oxipng) is a multithreaded lossless PNG/APNG compression optimizer
Tests :
```
mise use -g aqua:shssoichiro/oxipng
```
```
mise aqua:shssoichiro/oxipng@9.1.4 ✓ installed
mise ~/.config/mise/config.toml tools: aqua:shssoichiro/oxipng@9.1.4
```
=> feat(registry): added oxipng

docs/configuration.md, src/config/mod.rs
I think this period between the breaking changes is just going to cause more confusion so shortening it to 6 months
=> fix: move idiomatic version breaking change from 2026.1.1 to 2025.10.0

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** added oxipng by [@ldrouard](https://github.com/ldrouard) in [#4452](https://github.com/jdx/mise/pull/4452)
- `mise tasks --local|--global` by [@jdx](https://github.com/jdx) in [#4907](https://github.com/jdx/mise/pull/4907)
- added lockfile for pyenv by [@jdx](https://github.com/jdx) in [#4906](https://github.com/jdx/mise/pull/4906)
- move idiomatic version breaking change from 2026.1.1 to 2025.10.0 by [@jdx](https://github.com/jdx) in [#4909](https://github.com/jdx/mise/pull/4909)
- allow setting lists to be empty by [@jdx](https://github.com/jdx) in [#4912](https://github.com/jdx/mise/pull/4912)
- test registry changes by themselves by [@jdx](https://github.com/jdx) in [#4910](https://github.com/jdx/mise/pull/4910)
- test registry changes by themselves by …
=> chore: release 2025.4.7

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- hide idiomatic warning if no versions in idiomatic file by [@jdx](https://github.com/jdx) in [#4922](https://github.com/jdx/mise/pull/4922)
- clean up idiomatic deprecation message by [@jdx](https://github.com/jdx) in [c31aa2c](https://github.com/jdx/mise/commit/c31aa2cbd07a1f74049a0c6b72dfb91632ff5816)
- punctuation improvements to idiomatic deprecation message by [@glasser](https://github.com/glasser) in [#4915](https://github.com/jdx/mise/pull/4915)
=> chore: release 2025.4.8

mise.lock, registry.toml
[tusd](https://github.com/tus/tusd)
Reference server implementation in Go of tus: the open protocol for resumable file uploads.
```
$ tusd --version
Version: v2.8.0
Commit: 0e52ad650abed02ec961353bb0c3c8bc36650d2c
Date: Wed Apr  2 07:49:21 UTC 2025
```
Tests:
```
$ cargo run --bin mise -- install tusd
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.24s
Running `target/debug/mise install tusd`
mise Installed executable into /Users/mnm/.local/share/mise/installs/tusd/2.8.0/tusd
mise tusd@2.8.0      ✓ installed
$ cargo run --bin mise -- tool tusd
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.25s
Running `target/debug/mise tool tusd`
Backend:            ubi:tus/tusd
Installed Versions: 2.8.0
$ cargo run --bin mise -- uninstall tusd …
```
=> feat(registry): added tusd

src/cli/prune.rs, src/runtime_symlinks.rs
Currently after pruning on `unuse`, non-working symlinks are leftover.
```
mise use ubi:gitlab-org/cli[provider=gitlab,exe=glab]@latest
ls ~/.local/share/mise/installs/ubi-gitlab-org-cli
1@      1.56@   1.56.0/ latest@
mise unuse ubi:gitlab-org/cli
ls ~/.local/share/mise/installs/ubi-gitlab-org-cli
1@  1.56@  latest@
```
=> fix: remove missing symlinks on unuse when pruning

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** added tusd by [@mnm364](https://github.com/mnm364) in [#4928](https://github.com/jdx/mise/pull/4928)
- **(registry)** added fastfetch by [@sassdavid](https://github.com/sassdavid) in [#4932](https://github.com/jdx/mise/pull/4932)
- remove missing symlinks on unuse when pruning by [@roele](https://github.com/roele) in [#4930](https://github.com/jdx/mise/pull/4930)
- typo by [@jdx](https://github.com/jdx) in [314657f](https://github.com/jdx/mise/commit/314657fb6ee69646464c35ed4d8b72f0f2d551da)
- turn several of the list functions into parallel iters by [@lespea](https://github.com/lespea) in [#4924](https://github.com/jdx/mise/pull/4924)
- fix kwok by [@jdx](https://github.com/jdx) in [4516335](https://github.com/jdx/mise/commit/451633512b67d26f2b3263094826da7c7406c1da)
- …
=> chore: release 2025.4.9

docs/getting-started.md
This PR removes an outdated statement that said installing mise with Scoop would automatically activate it
As of ScoopInstaller/Main#6677 (April 23, 2025), the Scoop manifest for mise no longer:
- Forces `MISE_DATA_DIR` into Scoop-managed paths
- Automatically adds mise’s internal shims to the PATH
Users now must manually configure shell activation by adding `%LOCALAPPDATA%\mise\shims` to PATH or using `mise activate <shell>` as documented elsewhere.
This brings the installation instructions up-to-date with the current Scoop behavior.
Reference: https://github.com/ScoopInstaller/Main/pull/6677
=> docs: remove outdated note about automatic shim activation with Scoop

docs/cli/index.md, docs/cli/unuse.md, e2e/cli/test_unuse, mise.usage.kdl, src/cli/unuse.rs, xtasks/fig/src/mise.ts
=> fix(unuse): allow unusing any version if version not specified

registry.toml
Adding [aqua:barnybug/cli53](https://github.com/garysassano/aqua-registry/tree/main/pkgs/barnybug/cli53) to Mise registry.
=> feat(registry): add `cli53` backend

e2e/backend/test_pipx_custom_registry, schema/mise.json, settings.toml, src/backend/pipx.rs, src/http.rs
- Add new settings to configure a custom repository url
- Support of https://peps.python.org/pep-0503/ and https://peps.python.org/pep-0691/
#4938
=> feat: pipx custom repository url

docs/tasks/running-tasks.md, e2e/cli/test_doctor, e2e/cli/test_watch, e2e/generate/test_generate_bootstrap, src/cli/doctor/mod.rs, src/cli/mod.rs, src/cli/watch.rs
- Update two places where `mise` assumed that `mise` is on `PATH` (in `mise dr --json` and `mise watch`).
- Update documentation to indicate how one might run tasks in series and mention that using `{{mise_bin}}` might be a good idea in this case.
- Add tests
Related discussion: https://github.com/jdx/mise/discussions/4141
=> fix: Always use env::MISE_BIN when calling mise from itself (#4141)

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add `cli53` backend by [@garysassano](https://github.com/garysassano) in [#4937](https://github.com/jdx/mise/pull/4937)
- pipx custom repository url by [@acesyde](https://github.com/acesyde) in [#4945](https://github.com/jdx/mise/pull/4945)
- **(hook-env)** path order by [@jdx](https://github.com/jdx) in [#4946](https://github.com/jdx/mise/pull/4946)
- **(unuse)** allow unusing any version if version not specified by [@jdx](https://github.com/jdx) in [#4944](https://github.com/jdx/mise/pull/4944)
- Always use env::MISE_BIN when calling mise from itself by [@hverlin](https://github.com/hverlin) in [#4943](https://github.com/jdx/mise/pull/4943)
- remove outdated note about automatic shim activation with Scoop by [@jgutierrezre](https://github.com/jgutierrezre) in …
=> chore: release 2025.4.10

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(cargo)** allow customizable registry by [@acesyde](https://github.com/acesyde) in [#4948](https://github.com/jdx/mise/pull/4948)
- **(doctor)** show error if tool not installed by [@jdx](https://github.com/jdx) in [#4952](https://github.com/jdx/mise/pull/4952)
- added sd by [@jdx](https://github.com/jdx) in [#4950](https://github.com/jdx/mise/pull/4950)
- MISE_LOG_HTTP by [@jdx](https://github.com/jdx) in [#4951](https://github.com/jdx/mise/pull/4951)
- set prune age to 10y in dockerfile by [@jdx](https://github.com/jdx) in [9a521dc](https://github.com/jdx/mise/commit/9a521dc1e93e57567dcb262482a6a8d382fbebe8)
- brew update by [@jdx](https://github.com/jdx) in [641f3b3](https://github.com/jdx/mise/commit/641f3b3ef1c8c7b2e4931c5012c2b8dc94533070)
- brew sync repos by …
=> chore: release 2025.4.11

mise.lock, src/aqua/aqua_registry.rs, src/backend/aqua.rs
Fixes https://github.com/jdx/mise/discussions/4904.
For tools in a monorepo, we need to use the directory name instead of the repo name for `bin_path`.
e.g. `mimirtool`
```
packages:
- name: grafana/mimir/mimirtool
type: github_release
repo_owner: grafana
repo_name: mimir
description: Grafana Mimir provides horizontally scalable, highly available, multi-tenant, long-term storage for Prometheus
asset: mimirtool-{{.OS}}-{{.Arch}}
format: raw
version_prefix: mimir-
supported_envs:
- linux
- darwin
```
https://mise-versions.jdx.dev/aqua-registry/grafana/mimir/mimirtool/registry.yaml
=> fix(aqua): fix bin_path of tools in monorepo

schema/mise.json
ref: https://github.com/jdx/mise/discussions/4423
Allows an array of objects in `hooks`.
e.g.
```
[[hooks.cd]]
script = "echo 'I changed directories'"
[[hooks.cd]]
script = "echo 'I also directories'"
```
=> fix(schema): allow array of objects for hooks

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(aqua)** fix bin_path of tools in monorepo by [@risu729](https://github.com/risu729) in [#4954](https://github.com/jdx/mise/pull/4954)
- **(schema)** allow array of objects for hooks by [@risu729](https://github.com/risu729) in [#4955](https://github.com/jdx/mise/pull/4955)
- store tool version opts in .mise.backend by [@roele](https://github.com/roele) in [#4960](https://github.com/jdx/mise/pull/4960)
- add information about the DNF repository by [@acesyde](https://github.com/acesyde) in [#4956](https://github.com/jdx/mise/pull/4956)
- fix registry tools by [@jdx](https://github.com/jdx) in [#4959](https://github.com/jdx/mise/pull/4959)
- **(deny)** added CDLA-Permissive-2.0 by [@jdx](https://github.com/jdx) in [#4961](https://github.com/jdx/mise/pull/4961)
=> chore: release 2025.4.12

docs/configuration.md
The doc says:
> Paths which start with `mise` can be dotfiles, e.g.: `mise.toml` or `.mise/config.toml`.
where the first example doesn't actually contain a dot. This corrects that.
=> docs: Put dot in dotfile example

Cargo.lock, src/ui/prompt.rs
Set new `clear_screen` flag on confirm and dialog. 
Confirmation dialogs displayed in tasks might be overwritten by other tasks output running in parallel which leads to broken dialog renditions. Clearing the screen helps mitigate this.
=> chore: enable clearing screen for confirm and dialog

schema/mise.json, settings.toml, src/cli/hook_env.rs
Adds a `.status.truncate` to control the truncation of "show" status messages. 
Defaults to `true` for backward compatibility.
Example: 
With the default value:
```toml
status = { show_env = false, show_tools = true }
```
Navigating to a directory with some mise tools:
```console
cd /to/a/mise/dir
mise +aws@2.26.2 +gcloud@467.0.0 +helm@3.17.2 +helmfile@0.171.0 +jq@1.6 +kubeconform@v0.6.7 +kubectl@1.31.7 +sops@3.9.…
```
When setting `truncate = false`:
```toml
status = { show_env = false, show_tools = true, truncate = false }
```
Navigating to a directory with some mise tools:
```console
cd /to/a/mise/dir
mise +aws@2.26.2 +gcloud@467.0.0 +helm@3.17.2 +helmfile@0.171.0 +jq@1.6 +kubeconform@v0.6.7 +kubectl@1.31.7 +sops@3.9.4 +velero@1.13.0 +yq@4.45.1 +bats@1.11.1 +go@1.24.2 +gomplate@4.3.2 …
```
=> feat(status): add setting to control status message truncation

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add luau by [@rhanneken](https://github.com/rhanneken) in [#4993](https://github.com/jdx/mise/pull/4993)
- **(registry)** add numbat by [@risu729](https://github.com/risu729) in [#4980](https://github.com/jdx/mise/pull/4980)
- add check flag for the fmt command by [@roele](https://github.com/roele) in [#4972](https://github.com/jdx/mise/pull/4972)
- use aqua for btop by [@jdx](https://github.com/jdx) in [#4979](https://github.com/jdx/mise/pull/4979)
- **(java)** filter out JetBrains releases with features by [@roele](https://github.com/roele) in [#4970](https://github.com/jdx/mise/pull/4970)
- fix deadlocks caused by uv_venv_auto by [@risu729](https://github.com/risu729) in [#4900](https://github.com/jdx/mise/pull/4900)
- Put dot in dotfile example by …
=> chore: release 2025.5.0

e2e/env/test_env_cascading, src/config/env_directive/file.rs, src/config/env_directive/mod.rs
Hi 👋🏼 
I posted an issue I had in #4688 and never had a response, so I gave a try at fixing it.
The test case is simple and covers 2 broken use-cases:
- dotenv file referencing a variable declared in the `env` section
- dotenv file referencing a variable declared in a previous dotenv file
In both cases, the referenced variables were replaced by an empty string.
Given `dotenvy` doesn't allow providing an initial substitution map ([I created an issue for that](https://github.com/allan2/dotenvy/issues/149)), I used the only workaround I found as of today: concatenate the initial environment with the dotenv file to load.
=> fix(env): fix dotenv files cascading (fix #4688)

.github/workflows/registry.yml
`registry` workflow sometimes fails due to a timeout, even on the first attempt.
This PR increases the timeout from 20 mins to 30 mins to avoid failures.
Workflow logs: https://github.com/jdx/mise/actions/workflows/registry.yml
=> ci(registry): increaset timeout to 30 mins

docs/templates.md, e2e/env/test_env_profiles, src/tera.rs
Allows the user to query in a template what configuration environment a task is running in:
```bash
cat <<EOF >mise.toml
[tasks.print]
run = '{% if mise_env %}echo {{mise_env}}{% endif %}'
EOF
mise run print # output:
MISE_ENV=env1 mise run print # output: env1
mise --env env1,env2 run print # output: env1,env2
```
This can be useful when you want to `mise set` an environment variable for the current configuration environment:
```toml
[tasks.test]
run = "mise set --file mise.{{ mise_env | split(pat=',') | last }}.yaml KEY={{arg(name='value')}}"
```
=> feat: add mise_env tera variable for templates

e2e/env/test_env_cascading, src/config/env_directive/file.rs
Fix the poor escaping from #4996.
I was trying to avoid adding a new dependency, `shell-escape`, but it is already included, so I just rely on it instead of the poor uncomplete `replace()`
Fix #5008
=> fix(dotenv): properly escape values in generated dotenv

registry.toml, schema/mise.json
Fixes a regression with my previous PR to use aqua for taplo.
https://github.com/jdx/mise/pull/4991#issuecomment-2856241179
=> fix(registry): use full version of taplo

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(dotenv)** properly escape values in generated dotenv by [@noirbizarre](https://github.com/noirbizarre) in [#5010](https://github.com/jdx/mise/pull/5010)
- **(registry)** use full version of taplo by [@risu729](https://github.com/risu729) in [#5017](https://github.com/jdx/mise/pull/5017)
- hide rtx docs by [@jdx](https://github.com/jdx) in [90ae2ce](https://github.com/jdx/mise/commit/90ae2ce5abf4faa65ef2414385e587d97ff0ca2c)
- describe cache auto-prune by [@jdx](https://github.com/jdx) in [#5013](https://github.com/jdx/mise/pull/5013)
- mark idiomatic_version_file_disable_tools as deprecated by [@jdx](https://github.com/jdx) in [9bb80f3](https://github.com/jdx/mise/commit/9bb80f301e29fcc668f51de8e0a168a32c9ac8db)
- remove homebrew bump step by [@jdx](https://github.com/jdx) in …
=> chore: release 2025.5.2

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add coreutils by [@kit494way](https://github.com/kit494way) in [#5033](https://github.com/jdx/mise/pull/5033)
- unuse command does not support env, global and path options by [@roele](https://github.com/roele) in [#5021](https://github.com/jdx/mise/pull/5021)
- disable aqua for now due to bad version output by [@jdx](https://github.com/jdx) in [fa3daa2](https://github.com/jdx/mise/commit/fa3daa2cab09ba7e0140fcf2112375eef8427a85)
- fix python poetry test by [@jdx](https://github.com/jdx) in [c46a190](https://github.com/jdx/mise/commit/c46a190cb699b7700aa636a2bc888222ed7e9dbc)
- update rust crate nix to 0.30 by [@renovate[bot]](https://github.com/renovate[bot]) in [#5032](https://github.com/jdx/mise/pull/5032)
- update rust crate built to 0.8 by …
=> chore: release 2025.5.3

docs/mise-cookbook/neovim.md
The original queries only supported double quotes. Since `mise` supports using both single and double quotes in TOML tasks the queries should support them as well.
You might notice these regexes aren't technically correct as they would also allow quotations like '"' and '"" and other such nonsense. But since TOML parser will freak out if you try to mix and match quotation marks in funny ways it doesn't really matter.
=> docs: improve treesitter queries in neovim cookbook

registry.toml
Updates the `glab` ubi backend from `forge` to `provider`
Brings this in line with the documented api in https://mise.jdx.dev/dev-tools/backends/ubi.html#provider
I didn't find any other instances of `forge` in the registry
=> fix(registry): update glab ubi provider

build.rs, schema/mise.json, settings.toml, src/config/settings.rs
Fixes issues with string to boolean conversion for `CI` as discussed in #5053.
=> fix: mise panics if CI env var isn't a boolean

registry.toml
It seems that `aqua --version` is the correct command to check the version of `aqua`.
[Issue](https://github.com/aquaproj/aqua/issues/3867) opened with `aqua` for more details.
Also related fa3daa2cab09ba7e0140fcf2112375eef8427a85 and 4f2c0505502c1e3c7bf3478d61a2c352591f281c.
**Edit**: updated back to using the `version` command, now it's fixed in the latest version of `aqua`, [`v2.51.2`](https://github.com/aquaproj/aqua/releases/tag/v2.51.2)
=> fix: `aqua` version test

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add sshi by [@scop](https://github.com/scop) in [#5048](https://github.com/jdx/mise/pull/5048)
- **(registry)** added Neon CLI by [@joehorsnell](https://github.com/joehorsnell) in [#4994](https://github.com/jdx/mise/pull/4994)
- **(registry)** update glab ubi provider by [@StingRayZA](https://github.com/StingRayZA) in [#5052](https://github.com/jdx/mise/pull/5052)
- mise panics if CI env var isn't a boolean by [@roele](https://github.com/roele) in [#5059](https://github.com/jdx/mise/pull/5059)
- `aqua` version test by [@joehorsnell](https://github.com/joehorsnell) in [#5038](https://github.com/jdx/mise/pull/5038)
- run hook-env after trusting config file by [@jdx](https://github.com/jdx) in [#5062](https://github.com/jdx/mise/pull/5062)
- **(hooks)** remove duplicated …
=> chore: release 2025.5.4

docs/configuration.md
👋  Just noticed that go.mod support was removed in https://github.com/jdx/mise/discussions/4136 but was still mentioned in the docs. This PR removes the mention of go.mod from docs.
Thanks a lot for the project 🙇 !
=> docs: remove go.mod from idiomatic version files

docs/templates.md
You cannot apply `concat` to a string (as was done in the example): you have to make it an array first.
=> fix: Clarify some of the filters and fix the config_root filter example

scripts/release.sh
Sign the source tarball during each release as discussed [here](https://github.com/jdx/mise/discussions/4998).
Please have a look. It's - obviously? - untested but should work.
If it works I would like to do the same for [usage](https://github.com/jdx/usage).
=> chore: sign source tarball

src/config/config_file/mise_toml.rs
Closes https://github.com/jdx/mise/discussions/4620, see the failing `PROJECT_ROOT/.config/` and `PROJECT_ROOT/mise/` cases detailed in it.
=> fix(config): project root for files in .config/ or mise/

docs/tasks/toml-tasks.md
Ref https://github.com/jdx/mise/discussions/4620#discussioncomment-12499250
=> docs(tasks): point to `dir` config for task default cwd

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- using custom port with SSH based remote tasks by [@roele](https://github.com/roele) in [#5110](https://github.com/jdx/mise/pull/5110)
- update rabbitmq backend by [@SerhiiFesenko](https://github.com/SerhiiFesenko) in [#5115](https://github.com/jdx/mise/pull/5115)
- maven-mvnd does not install with aqua by [@roele](https://github.com/roele) in [#5117](https://github.com/jdx/mise/pull/5117)
- @SerhiiFesenko made their first contribution in [#5115](https://github.com/jdx/mise/pull/5115)
=> chore: release 2025.5.7

registry.toml
[astro](https://github.com/astronomer/astro-cli)
The Astro CLI is a command-line interface for data orchestration. It allows you to get started with Apache Airflow quickly and it can be used with all Astronomer products.
```
$ astro version
Astro CLI Version: 1.34.0
```
Tests:
```sh
$ cargo run --bin mise -- install astro
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
Running `target/debug/mise install astro`
mise Installed executable into /Users/mnm/.local/share/mise/installs/astro/1.34.0/astro
mise astro@1.34.0    ✓ installed
$ cargo run --bin mise -- tool astro
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
Running `target/debug/mise tool astro`
Backend:                                             ubi:astronomer/astro-cli[exe=astro]
Installed …
```
=> feat(registry): added astro

src/plugins/core/elixir.rs
Addresses https://github.com/jdx/mise/discussions/4711
This takes cues from [bun](https://github.com/jdx/mise/blob/8e0805b2d34312985b7173ebcb8ed23f117ec704/src/plugins/core/bun.rs#L135) and [swift](https://github.com/jdx/mise/blob/8e0805b2d34312985b7173ebcb8ed23f117ec704/src/plugins/core/swift.rs#L187) for referencing windows specific bin names.
=> fix: elixir bin name on windows

mise.lock, registry.toml
Fixes https://github.com/jdx/mise/discussions/5112.
Windows support in aqua-registry added in https://github.com/aquaproj/aqua-registry/pull/30735.
=> fix(registry): support editorconfig-checker in windows

mise.lock, src/task/task_file_providers/remote_task_git.rs
Fixes the issue discussed in #5101.
Loosens the constraints around `repo` named capture to allow (sub-)folders (GitLab supports nested folders) for SSH and HTTPS.
=> fix: SSH remote tasks do not support organizations in repository path

docs/faq.md
The `.tool-versions` file can be indented and contain multiple spaces before the version so we need to replace multiple adjacent spaces by a single space
=> docs: squeeze spaces when migrating from asdf

e2e/generate/test_generate_devcontainer, src/cli/generate/devcontainer.rs
Some VS Code extensions (e.g., Terraform) do not function properly within the DevContainer environment. Specifically, they do not provide an option to configure the path to the tool's binary, which leads to issues when the tool is installed in non-standard locations (e.g., via a version manager like mise).
=> feat: add shims in REMOTE ENV

Cargo.lock, Cargo.toml, docs/.vitepress/cli_commands.ts, docs/cli/index.md, docs/cli/search.md, e2e/cli/test_search, man/man1/mise.1, mise.usage.kdl, src/cli/mod.rs, src/cli/search.rs, xtasks/fig/src/mise.ts
Fixes #5084 
Adds a new `search` command to search the registry for tools. By default it matches the search term with a `fuzzy` match (to match the interactive behaviour) and displays the `tool` and `description` in a table. If no search term is provided all tools are listed. 
The `description` also contains the RegistryTool description and the preferred URL to the tool similar to https://mise.jdx.dev/registry.html. Backends that are disabled are filtered out beforehand.
```
❯ mise search jq
Tool  Description
jq    Command-line JSON processor. https://github.com/jqlang/jq
jqp   https://github.com/noahgorstein/jqp
jiq   https://github.com/fiatjaf/jiq
gojq  https://github.com/itchyny/gojq
```
Following arguments are supported.
* `--interactive` - Interactive mode using a filterable Select
* …
=> feat: mise search

docs/registry.data.ts
Mise registry links are currently broken for all tools that use ubi with an exe selector. 
https://mise.jdx.dev/registry.html
For example: astro uses `ubi:astronomer/astro-cli[exe=astro]` and incorrectly directs to 
> https://github.com/astronomer/astro-cli[exe=astro]
Test Plan: none
=> fix: mise registry links for ubi with exe selector

mise.lock, registry.toml
The latest taplo release, [0.10.0](https://github.com/tamasfe/taplo/releases/tag/0.10.0), no longer provides a full version. The lsp feature is now enabled by default in the standard release.
This change impacts users using `taplo@0.9.3` or older.
Previously, mise would fetch the full version for 0.9.3, but with this PR, `taplo@0.9.3` will now resolve to the non-full version.
This would cause a problem like https://github.com/jdx/mise/pull/5017.
However, the installation of `taplo@0.10.0` is currently failing, so I think we need to update the registry.
For users who require the full version of `taplo@0.9.3`, they will need to explicitly specify `aqua:tamasfe/taplo/full@0.9.3` in their configuration.
=> fix(registry): remove full from taplo

registry.toml
Adds VictoriaMetrics: https://github.com/VictoriaMetrics/VictoriaMetrics
VictoriaMetrics is an open-source, cost-effective monitoring solution and time series database.
```
$ cargo run --bin mise -- install victoria-metrics  
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.24s
Running `target/debug/mise install victoria-metrics`
mise victoria-metrics@1.117.1     ✓ installed 
$ cargo run --bin mise -- tool victoria-metrics
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
Running `target/debug/mise tool victoria-metrics`
Backend:                                         aqua:victoriametrics/victoriametrics/victoria-metrics                                                           
Description:                                     VictoriaMetrics: fast, …
```
=> feat(registry): add victoriametrics

build.rs, docs/cli/config/set.md, e2e/cli/test_settings_add, mise.usage.kdl, settings.toml, src/cli/config/set.rs, src/cli/settings/ls.rs, src/cli/settings/set.rs, src/config/settings.rs, src/toml.rs, xtasks/fig/src/mise.ts, xtasks/render/settings.ts
Fixes #4919 and replaces #4925
=> fix: mise settings add idiomatic_version_file_enable_tools stores duplicates in config

docs/cli/completion.md, docs/installing-mise.md, docs/mise.usage.kdl, mise.usage.kdl, src/cli/completion.rs
_Further information can be found [here](https://github.com/jdx/mise/discussions/5122)_
This pull request updates the default installation path for Bash shell completion scripts generated by the `mise` CLI tool. The changes ensure that the scripts are placed in user-specific directories instead of system-wide locations, improving compatibility and avoiding the need for elevated permissions.
* Updated examples in `docs/cli/completion.md` to redirect Bash completion scripts to `~/.local/share/bash-completion/mise` instead of `/etc/bash_completion.d/mise`.
* Modified installation instructions in `docs/installing-mise.md` to reflect the new user-specific path for Bash completion scripts.
* Adjusted examples in `mise.usage.kdl` to use the updated Bash completion script path. …
=> fix: infinite sourcing loop on bash-completion

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add victoriametrics by [@shikharbhardwaj](https://github.com/shikharbhardwaj) in [#5161](https://github.com/jdx/mise/pull/5161)
- **(registry)** remove full from taplo by [@risu729](https://github.com/risu729) in [#5160](https://github.com/jdx/mise/pull/5160)
- mise registry links for ubi with exe selector by [@mnm364](https://github.com/mnm364) in [#5156](https://github.com/jdx/mise/pull/5156)
- mise settings add idiomatic_version_file_enable_tools stores duplicates in config by [@roele](https://github.com/roele) in [#5162](https://github.com/jdx/mise/pull/5162)
- infinite sourcing loop on bash-completion by [@ken-kuro](https://github.com/ken-kuro) in [#5150](https://github.com/jdx/mise/pull/5150)
- disable mockolo since linux does not work anymore by …
=> chore: release 2025.5.11

src/cli/run.rs, src/task/deps.rs
Addresses an issue discussed in #5176 where remote tasks which are declared in `depends` are not properly resolved.
=> fix: remote task dependency does not work

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- output was silenced on task fail with keep-order by [@artemisart](https://github.com/artemisart) in [#5175](https://github.com/jdx/mise/pull/5175)
- avoid mapfile to run e2e tests on macOS (bash 3.2) by [@artemisart](https://github.com/artemisart) in [#5170](https://github.com/jdx/mise/pull/5170)
- flaky keep-order e2e test by [@artemisart](https://github.com/artemisart) in [#5178](https://github.com/jdx/mise/pull/5178)
- watch mise.lock for changes by [@jdx](https://github.com/jdx) in [#5184](https://github.com/jdx/mise/pull/5184)
- remote task dependency does not work by [@roele](https://github.com/roele) in [#5183](https://github.com/jdx/mise/pull/5183)
- rayon -> tokio by [@jdx](https://github.com/jdx) in [#5172](https://github.com/jdx/mise/pull/5172)
- cache results from version …
=> chore: release 2025.5.13

src/cli/args/backend_arg.rs, src/toolset/install_state.rs
According to the discussion #5001 the change #4960 to support GH Enterprise/GitLab is causing a regression for certain tools (e.g. aqua) because of the global ToolOption argument `postinstall`. To address this we should filter the global once on install arguments and only store ToolOptions for certain backends (`cargo`, `go`, `pipx`, `ubi`)
=> fix: installing tools with postinstall hooks fails

docs/contributing.md
I was trying to setup mise locally, and found `contributing.md` outdated, so I updated it.
1. remove [`just`](https://github.com/casey/just)
- The usage of `just` is removed in https://github.com/jdx/mise/pull/1948 
2. add [`node`](https://nodejs.org/ja)
- I guess that it's the npm part in `mise.toml` that required Node.js
https://github.com/jdx/mise/blob/ffb47799c69607ebc17e5dc9f2f0aa3bfaf80797/mise.toml#L19-L20
- I've received error about `npm:prettier` when I didn't have node available.
=> docs: update dependencies section in contributing.md

e2e-win/zig.Tests.ps1, e2e/core/test_zig, src/plugins/core/zig.rs
Fix: #5173
BREAKING CHANGE: To match mach version index, `*-mach` version schema is now used instead of `*-dev.*` e.g. `2024.11.0-mach` instead of `0.14.0-dev.2577+271452d22`
Co-authored-by: Julius Alphonso <12978899+JadeMaveric@users.noreply.github.com>
=> fix(zig): get tarball url from download index

docs/cli/completion.md, docs/installing-mise.md, docs/mise.usage.kdl, mise.usage.kdl, src/cli/completion.rs
TLDR: Turn out the FAQ of `bash-completion` section is [deprecated compared to the package's code](https://github.com/jdx/mise/discussions/5122#discussioncomment-13280275). Although it stills work on some machines (like mine), the new path would be more aligned with the `bash-completion` code 
This pull request updates the file paths for Bash shell completion scripts to align with standard directory structures for better compatibility and organization. The changes affect documentation, usage examples, and the implementation of the `mise completion` command.
* Updated examples in `docs/cli/completion.md` to save Bash completion scripts under `~/.local/share/bash-completion/completions/` instead of the parent directory.
* Adjusted instructions in `docs/installing-mise.md` to reflect the new …
=> fix: use a better completion dir for more compatibility

e2e/core/test_go, src/plugins/core/go.rs
Fixes an issue (discussed in #5210) where go installation will fail if there is a go.mod file with an incompatible version in the directory where mise is executed.
=> fix: prevent go installation failure on go.mod version mismatch

registry.toml
https://github.com/aquaproj/aqua-registry/blob/main/pkgs/apache/maven/pkg.yaml
Tested locally using alias:
mise checks latest versions from GitHub, so `@latest` works well. Verified not working with versions `<3.0.0 || >= 4.0.0` (need aqua-side changes)
=> feat(registry): add aqua backend for maven

e2e/cli/test_chdir, src/cli/run.rs, src/file.rs
Fixes #5214 and should also address absolute/relative as discussed in #4582.
=> fix: mise run --cd <dir> not working with latest mise

src/plugins/core/zig.rs
Follow up of https://github.com/jdx/mise/pull/5182
I also did small refactor of that PR by using HashMap for download index to make it a bit cleaner :)
Tested in local
```
14:01:04 ❯ mise ls-remote zig
0.11.0
0.12.0
0.12.1
0.13.0
0.14.0
0.14.1
14:01:04 ❯ mise cache clean
mise cache cleared
14:01:14 ❯ MISE_USE_VERSIONS_HOST=false cargo run --bin mise -- ls-remote zig
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.73s
Running `target/debug/mise ls-remote zig`
mach-latest
master
0.1.1
0.2.0
0.3.0-mach
0.3.0
0.4.0-mach
0.4.0
0.5.0
0.6.0
0.7.0
0.7.1
0.8.0
0.8.1
0.9.0
0.9.1
0.10.0
0.10.1
0.11.0
0.12.0
0.12.1
0.13.0
0.14.0
0.14.1
2024.1.0-mach
2024.3.0-mach
2024.5.0-mach
2024.10.0-mach
2024.11.0-mach
```
I'm not sure if the ordering should be like this (non semver e.g. master at …
=> fix(zig): get version list from download index

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add aqua backend for maven by [@ZeroAurora](https://github.com/ZeroAurora) in [#5219](https://github.com/jdx/mise/pull/5219)
- **(zig)** **breaking** get tarball url from download index by [@mangkoran](https://github.com/mangkoran) in [#5182](https://github.com/jdx/mise/pull/5182)
- **(zig)** get version list from download index by [@mangkoran](https://github.com/mangkoran) in [#5217](https://github.com/jdx/mise/pull/5217)
- use a better completion dir for more compatibility by [@ken-kuro](https://github.com/ken-kuro) in [#5207](https://github.com/jdx/mise/pull/5207)
- set handler for ctrlc on windows shell by [@L0RD-ZER0](https://github.com/L0RD-ZER0) in [#5209](https://github.com/jdx/mise/pull/5209)
- prevent go installation failure on go.mod version mismatch by …
=> chore: release 2025.5.15

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- ensure config is always wrapped in Result by [@jdx](https://github.com/jdx) in [#5223](https://github.com/jdx/mise/pull/5223)
- improve init performance by [@jdx](https://github.com/jdx) in [#5231](https://github.com/jdx/mise/pull/5231)
- remove hyperfine from main builds by [@jdx](https://github.com/jdx) in [#5226](https://github.com/jdx/mise/pull/5226)
=> chore: release 2025.5.16

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- add railway cli by [@jahands](https://github.com/jahands) in [#5083](https://github.com/jdx/mise/pull/5083)
- **(zig)** exclude mach version from version list by [@mangkoran](https://github.com/mangkoran) in [#5240](https://github.com/jdx/mise/pull/5240)
- refresh settings by [@jdx](https://github.com/jdx) in [#5252](https://github.com/jdx/mise/pull/5252)
- re-enable parallelism for `mise up` by [@jdx](https://github.com/jdx) in [#5249](https://github.com/jdx/mise/pull/5249)
=> chore: release 2025.5.17

docs/registry.data.ts
Fixes https://github.com/jdx/mise/discussions/5265.
`aqua:pipe-cd/pipecd/pipectl` linked to https://github.com/pipe-cd/pipecd/pipectl, so fixed it to only use the repo name instead of the full aqua package name: https://github.com/pipe-cd/pipecd
(This doesn't support aqua packages starting with `gitlab.com`, but there are no such packages in the registry now.)
Also, `asdf:https://gitlab.com/td7x/asdf/adr-tools` pointed https://github.com/https, so use `slug` as is if it's a url (starting with `http`).
=> docs(registry): fix links of registry

registry.toml
In https://github.com/jdx/mise/pull/5266, `tetratelabs/func-e` was added, but it didn't have the backend.
Since `aqua-registry` doesn't contain it, I guess it was meant to use `ubi`.
I confirmed it can be installed.
=> feat(registry): use ubi backend for func-e

docs/components/registry.vue, docs/registry.data.ts, registry.toml
My apologies, https://github.com/jdx/mise/pull/5266 didn't work, so this is the follow-up.
I confirmed all links (except for 1password) work with `mise exec lychee -- lychee docs/.vitepress/dist/registry.html` (with https://github.com/jdx/mise/pull/5271 and https://github.com/jdx/mise/pull/5273).
- Since `aqua:1password/cli` uses `http` type, we should link to https://developer.1password.com/ I guess, but didn't know where to declare it.
PR added the package: https://github.com/aquaproj/aqua-registry/pull/26217
https://github.com/aquaproj/aqua-registry/blob/main/pkgs/1password/cli/registry.yaml
- I switched to `kubernetes/kubernetes/kubectl-convert` from its alias `kubernetes/kubectl-convert`, to build the correct url.
https://github.com/aquaproj/aqua-registry/blob/main/pkgs/kubernetes/kub …
=> docs(registry): fix links to tools

mise.lock, src/aqua/aqua_registry.rs, src/backend/aqua.rs
Adds support for [`no_asset`](https://aquaproj.github.io/docs/reference/registry-config/no_asset/) and [`error_message`](https://aquaproj.github.io/docs/reference/registry-config/error_message) of aqua registry.
Fixes https://github.com/jdx/mise/discussions/5274
=> feat(aqua): support no_asset and error_message

src/task/task_script_parser.rs
Fixes https://github.com/jdx/mise/discussions/5308.
Uses `""` instead of `false` for the default value of `option` in tasks.
=> fix(task): use empty string for the default value of option

docs/mise-cookbook/nodejs.md
This is updating a `pnpm` recipe.
---
To be honest, I was looking at it while putting together a CI workflow for Yarn. It did not work without `experimental = true`.
Another problem, adding `yarn` to the `tools` did not work on Windows. Therefore I had to fall back to `corepack` as suggested in the recipe. The whole point why I wanted to use `mise` was to avoid using `corepack`. Why? Because `miss` is way better! I love it. But the CI has to pass on Ubuntu, macOS, and uff.. Windows.
Hopefully, I complain in the right place. See: https://github.com/mise-plugins/mise-yarn/issues/12
=> docs: update example with `pnpm`

src/ui/table.rs
Fixes `MISE_COLOR=false` for the `ls` command as discussed in #5315. Crate `comfy_table` requires a `force_no_tty` method call to disable colors.
=> fix: ls command does not respect MISE_COLOR value

docs/getting-started.md
Somehow formatting wasn't correct, now it is
=> refactor(getting-started): update powershell profile instructions

registry.toml
As described in https://github.com/houseabsolute/ubi/issues/124, ubi throws an error while installing `slimtoolkit/slim`.
We need to use `extract_all` because it contains symlinks, and also requires `mint-sensor` to be extracted.
Regarding the output of `slim --version`, I found that [slimtoolkit/slim](https://github.com/slimtoolkit/slim) has moved to [mintoolkit/mint](https://github.com/mintoolkit/mint), but `mint` was already mapped to [mint-lang/mint](https://github.com/mint-lang/mint).
=> fix(registry): use extract_all for docker-slim

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- support matching_regex from the ubi backend by [@yjoer](https://github.com/yjoer) in [#5320](https://github.com/jdx/mise/pull/5320)
- **(aqua)** parse templates in version_filter by [@risu729](https://github.com/risu729) in [#5341](https://github.com/jdx/mise/pull/5341)
- **(registry)** use extract_all for docker-slim by [@risu729](https://github.com/risu729) in [#5342](https://github.com/jdx/mise/pull/5342)
- **(getting-started)** update powershell profile instructions by [@Armaldio](https://github.com/Armaldio) in [#5340](https://github.com/jdx/mise/pull/5340)
- update docker/build-push-action digest to 2634353 by [@renovate[bot]](https://github.com/renovate[bot]) in [#5338](https://github.com/jdx/mise/pull/5338)
- update jdx/mise-action digest to 13abe50 by …
=> chore: release 2025.6.3

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** use aqua for checkov by [@risu729](https://github.com/risu729) in [#5343](https://github.com/jdx/mise/pull/5343)
- fix(aqua): parse templates in version_filter by [@risu729](https://github.com/risu729) in [#5345](https://github.com/jdx/mise/pull/5345)
=> chore: release 2025.6.4

registry.toml
Follow up of https://github.com/jdx/mise/pull/5342.
`aqua:mintoolkit/mint` is added in
https://github.com/aquaproj/aqua-registry/pull/37629.
Also, `slim --version` still prints weird mint version.
```
$ slim --version
mint version linux/amd64|ALP|x.1.42.2|29e62e7836de7b1004607c51c502537ffe1969f0|2025-01-16_07:48:54AM|x
```
The test should fail because `aqua-registry` in mise is not updated yet.
=> fix(registry): use mintoolkit/mint for docker-slim

src/toolset/tool_version.rs
The deprecation warning for `@system` was being shown for every usage, including in `.tool-versions` files where it's still valid for backward compatibility. This caused unnecessary warnings for users who have existing `.tool-versions` files with `@system` entries.
Modified the `tv_pathname` method in `src/toolset/tool_version.rs` to check the source of the tool request. The deprecation warning is now suppressed when `@system` is used in `.tool-versions` files, but still shown for other configuration sources like `.mise.toml`.
- Updated `ToolRequest::System` handling in `tv_pathname` method
- Added source checking to conditionally show deprecation warning
- Preserved backward compatibility for `.tool-versions` files
- Verified that warnings are suppressed for `.tool-versions` 
- Verified …
=> fix: only show deprecation if not using 'tools-version'

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** use mintoolkit/mint for docker-slim by [@risu729](https://github.com/risu729) in [#5351](https://github.com/jdx/mise/pull/5351)
- **(schema)** add missing tool options to schema by [@risu729](https://github.com/risu729) in [#5356](https://github.com/jdx/mise/pull/5356)
=> chore: release 2025.6.5

Cargo.lock
`cargo update` in the release workflow was disabled in https://github.com/jdx/mise/commit/3306f6ef726fe85d71163121497e1d5dd5cd73ca, so I ran `cargo update expr-lang` manually.
Required for https://github.com/jdx/mise/pull/5344.
=> chore: update expr-lang crate to v0.3.2

README.md
the powershell command inside not working, comparing to commands above for other envs, seems to because of multiple `mise activate`
=> docs: Fix typo in README.md - Install mise

e2e-win/symlink.Tests.ps1, src/file.rs, src/runtime_symlinks.rs
https://github.com/jdx/mise/discussions/5254
https://github.com/jdx/mise/discussions/5241
=> fix(shim): improve resolve_symlink for Windows

src/aqua/aqua_template.rs
Resolves https://github.com/jdx/mise/discussions/5382.
If the templates have multiple pipes, only the first and last functions are parsed correctly.
```
trimV .Version | replace "-RC" "-rc-" | replace "-M" "-milestone-"
```
This is parsed as `9.0.0-RC1` if `.Version` is `9.0.0-RC1`, but should be parsed as `9.0.0-rc-1`.
This PR fixes the issue by adding `in_pipe` state in the `parse` function.
=> fix(aqua): parse consecutive pipes in aqua templates

Cargo.lock, Cargo.toml
Should fix the self-update issue "Compression method not supported" on windows as discussed in #5367.
=> fix: add compression-zip-deflate feature on self_update crate for windows target

xtasks/release-plz
According to the action log output it seems that the `cargo search mise --limit 1` command breaks/fails to a new hint/note in stdout.
```
[release-plz] $ ~/work/mise/mise/xtasks/release-plz
+ git config user.name mise-en-dev
+ git config user.email release@mise.jdx.dev
++ cargo pkgid mise
++ cut -d# -f2
+ cur_version=2025.6.5
++ cargo search mise --limit 1
++ grep '^mise = "'
++ cut '-d"' -f2
note: to learn more about a package, run `cargo info <name>`
+ latest_version=
[release-plz] ERROR task failed
Error: Process completed with exit code 1.
```
=> fix: suppress hint on 'cargo search mise' command

xtasks/release-plz
I'm not sure if this will work, but it might work.
`--registry "crates-io"` avoids printing the local mise verison, and `--color never` avoids printing ANSI color codes.
```
cargo info --registry "crates-io" --color never --quiet mise | grep "^version:" | cut -d' ' -f2
```
=> ci: use cargo info to retrieve latest mise version

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add wash by [@jtakakura](https://github.com/jtakakura) in [#5386](https://github.com/jdx/mise/pull/5386)
- **(aqua)** parse consecutive pipes in aqua templates by [@risu729](https://github.com/risu729) in [#5385](https://github.com/jdx/mise/pull/5385)
- **(aqua)** use versions list to install correct version by [@risu729](https://github.com/risu729) in [#5371](https://github.com/jdx/mise/pull/5371)
- **(registry)** talosctl use aqua by [@mangkoran](https://github.com/mangkoran) in [#5348](https://github.com/jdx/mise/pull/5348)
- **(registry)** use aqua backend for watchexec by [@risu729](https://github.com/risu729) in [#5390](https://github.com/jdx/mise/pull/5390)
- **(shim)** improve resolve_symlink for Windows by [@qianlongzt](https://github.com/qianlongzt) in …
=> chore: release 2025.6.6

src/plugins/core/java.rs
With [b6bedc3](https://github.com/jdx/mise-java/commit/b6bedc3194a6382adcda382c8b2d879e7669a6c1) the new JDK vendor RedHat has been added. For Linux, only `tar.xz` archives are available, hence the extension to support this format.
=> feat(java): add support for tar.xz in Java core plugin to support RedHat JDKs

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(java)** add support for tar.xz in Java core plugin to support RedHat JDKs by [@roele](https://github.com/roele) in [#5354](https://github.com/jdx/mise/pull/5354)
- **(registry)** add osv-scanner by [@scop](https://github.com/scop) in [#5413](https://github.com/jdx/mise/pull/5413)
- **(registry)** add scorecard by [@scop](https://github.com/scop) in [#5410](https://github.com/jdx/mise/pull/5410)
- **(registry)** add docker cli by [@acesyde](https://github.com/acesyde) in [#5344](https://github.com/jdx/mise/pull/5344)
- **(registry)** add claude code by [@lelouvincx](https://github.com/lelouvincx) in [#5420](https://github.com/jdx/mise/pull/5420)
- **(registry)** add aws `cfn-lint` by [@garysassano](https://github.com/garysassano) in [#5434](https://github.com/jdx/mise/pull/5434)
- …
=> chore: release 2025.6.8

src/cli/exec.rs
- `parse_command` passes `-c` flag to cmd.exe (Windows) instead of `/c`.
- Using `#cfg(...)` because that's what `env::SHELL` depends upon.
=> fix: `parse_command` passing `-c` flag to cmd.exe

.github/workflows/test.yml
~~I'm not sure why `direnv` was installed, as it seems unused. https://github.com/jdx/mise/commit/d5bbfa42fc9e2747af3ca767005bb66fb2ec961c~~
~~Since it threw an error, maybe because the packages list is outdated, I just removed `direnv`.~~
If `direnv` is required, I think we need `sudo apt-get update` beforehand.
```
sudo apt-get install \
bison \
build-essential \
direnv \
fd-find \
fish \
pipx \
python3-venv \
zsh
shell: /usr/bin/bash -e {0}
env:
CARGO_TERM_COLOR: always
MISE_TRUSTED_CONFIG_PATHS: /home/runner/work/mise/mise
MISE_EXPERIMENTAL: 1
MISE_LOCKFILE: 1
RUST_BACKTRACE: 1
GITHUB_TOKEN: ***
Reading package lists...
Building dependency tree...
Reading state information...
bison is already the newest version (2:3.8.2+dfsg-1build2).
python3-venv is already the newest version …
```
=> ci(test): run `apt-get update` before `apt-get install`

src/plugins/core/erlang.rs
Fixes https://github.com/jdx/mise/discussions/5477.
We could also replace `#[cfg(linux)]` with `#[cfg(not(any(macos,windows))]`, but we needed to replace all codes depended by `install_precompiled`, so I just added `install_precompiled` for other OS that returns `Ok(None)`.
=> fix(erlang): add `install_precompiled` for unsupported os

registry.toml
About 3 weeks ago, aqua updated the casing for the victoria-metrics package here: https://github.com/aquaproj/aqua-registry/pull/37504/files
Updating the reference in `registry.toml`. Should fix the issue in #5250, although I wasn't able to get `cargo run` to use the updated registry locally, for some reason.
=> fix(aqua): update victoria-metrics package name casing

registry.toml, src/file.rs
Resolves #5419.
This PR fixes a bug that caused a `No such file or directory` error when extracting tar archives containing hard links.
The issue is caused by [`tar::Entry::unpack`](https://docs.rs/tar/latest/tar/struct.Entry.html#method.unpack), which resolves hard link paths relative to the current working directory instead of the intended destination directory.
When `Entry::unpack` calls the internal `EntryFields::unpack` method, it passes `None` as the `target_base`, so the hard links are resolved to the current working directory.
This resulted in `std::fs::hard_link` being called with an incorrect source path (implementation [here](https://github.com/alexcrichton/tar-rs/blob/a1c3036af48fa02437909112239f0632e4cfcfae/src/entry.rs#L509)), leading to the following error:
```
No such file …
```
=> fix(aqua): handle hard links in aqua packages

registry.toml
> This release is old and has many known issues. See "... commits to master since this release" above.
> You almost certainly want the [nightly build release](https://github.com/ytdl-org/ytdl-nightly/releases/), and not this one. The nightly build is created from the master branch of this repo if changes have been committed since the last build. Read about [Installation](https://github.com/ytdl-org/ytdl-nightly#user-content-installation) of the nightly build. Major fixes in the nightly build are listed https://github.com/ytdl-org/youtube-dl/issues/30839.
ref: https://github.com/ytdl-org/youtube-dl/releases/tag/2021.12.17
According to the latest release, we should use `ytdl-org/ytdl-nightly`.
However, the test fails since the versions host don't include the nightly build versions, I …
=> feat(registry): use ubi backend for youtube-dl nightly releases

registry.toml, src/file.rs
=> Revert "fix(aqua): handle hard links in aqua packages"

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** adds gemini-cli by [@risu729](https://github.com/risu729) in [#5447](https://github.com/jdx/mise/pull/5447)
- **(registry)** adds npm backended tools by [@risu729](https://github.com/risu729) in [#5446](https://github.com/jdx/mise/pull/5446)
- **(registry)** add powershell alias by [@risu729](https://github.com/risu729) in [#5449](https://github.com/jdx/mise/pull/5449)
- **(registry)** add dagu by [@yottahmd](https://github.com/yottahmd) in [#5476](https://github.com/jdx/mise/pull/5476)
- **(registry)** update aws-sam backends to include aqua source by [@yashikota](https://github.com/yashikota) in [#5461](https://github.com/jdx/mise/pull/5461)
- **(registry)** use ubi backend for youtube-dl nightly releases by [@risu729](https://github.com/risu729) in …
=> chore: release 2025.7.0

registry.toml
`package_type: cargo` is removed in https://github.com/aquaproj/aqua-registry/pull/30801.
Also, `platforms` for the ubi backend seem not to be required as other tools use `platforms`.
=> fix(registry): use aqua backend for bat

src/backend/aqua.rs, src/file.rs
Thank you for the project! It is my daily driver now.
This change adds support to the aqua backend for assets that are compressed with zst. Aqua already supports that but we miss that compression format.
Note that we already had support for zst compressed tarballs, but not single files.
=> feat(aqua): add support for zst compressed assets

src/plugins/core/erlang.rs
Fixes wrong method signature of fix #5479.
=> fix(erlang): fix install_precompiled method signature for unsupported os

src/cache.rs, src/config/settings.rs, src/plugins/core/java.rs
Resolves https://github.com/jdx/mise/discussions/5438.
Note that we still need to set `MISE_VERSIONS_HOST=false` to ignore the remote versions host.
=> fix: include arch and os settings in cache keys

src/plugins/core/java.rs
Fixes an issue with Java JetBrains version selection due to too strict filtering of non-release versions discussed in #5506 .
=> fix(java): relax version filter regex for JetBrains builds

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(aqua)** add support for zst compressed assets by [@andreabedini](https://github.com/andreabedini) in [#5495](https://github.com/jdx/mise/pull/5495)
- **(registry)** import package descriptions from aqua and add os specifier for tuist by [@matracey](https://github.com/matracey) in [#5487](https://github.com/jdx/mise/pull/5487)
- **(aqua)** handle hard links in aqua packages (attempt #2) by [@risu729](https://github.com/risu729) in [#5486](https://github.com/jdx/mise/pull/5486)
- **(aqua)** apply correct `version_override` by [@risu729](https://github.com/risu729) in [#5474](https://github.com/jdx/mise/pull/5474)
- **(erlang)** fix install_precompiled method signature for unsupported os by [@roele](https://github.com/roele) in [#5503](https://github.com/jdx/mise/pull/5503)
- **(java)** …
=> chore: release 2025.7.1

registry.toml
Added numbat in  https://github.com/aquaproj/aqua-registry/pull/38316.
Updated the registry to use the GitHub release assets in https://github.com/aquaproj/aqua-registry/pull/38317, https://github.com/aquaproj/aqua-registry/pull/38318.
=> fix(registry): use aqua for numbat, gokey, golines

scripts/build-tarball.ps1, scripts/build-tarball.sh
This is a follow-up to jdx/mise#5387, to fix the `self-update` command when using a traffic-inspecting/MITM firewall, such as Cloudflare WARP.
The previous PR broke the release build, so had to be reverted. I didn't realise that the [`reqwest`](https://crates.io/crates/reqwest) crate requirements are different on Linux (I use macOS), so OpenSSL is still needed.
I tried removing OpenSSL as a dependency completely, but it appears to not be straightforward, as many other crates also depend on `reqwest`.
The simplest thing I think is just to leave OpenSSL and add the `rustls-native-roots` feature.
I've tested `build-tarball.sh` locally on both macOS and Linux (using a VM) and verified that the resulting binaries can self-update correctly.
I don't have an easy way to test on Windows, but the …
=> fix: `self-update` on MITM firewall (attempt #2)

e2e/backend/test_aqua, registry.toml, src/backend/aqua.rs
Fixes https://github.com/jdx/mise/discussions/5533 and https://github.com/jdx/mise/discussions/5527.
I modified the version resolution in https://github.com/jdx/mise/pull/5474, but I forgot to use the resolved version in the later operations, `verify` and `install`.
This PR fixes that, and also adds a test for `aqua:gruntwork-io/terragrunt@0.77.22`, an older version, as the tag cannot be found in the latest 20 or 30 releases.
=> fix(aqua): use the version in url to verify and install

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add zizmor by [@risu729](https://github.com/risu729) in [#5519](https://github.com/jdx/mise/pull/5519)
- Add `self_update_available` to `mise doctor` output by [@joehorsnell](https://github.com/joehorsnell) in [#5534](https://github.com/jdx/mise/pull/5534)
- **(aqua)** use the version in url to verify and install by [@risu729](https://github.com/risu729) in [#5537](https://github.com/jdx/mise/pull/5537)
- **(registry)** use aqua for numbat, gokey, golines by [@risu729](https://github.com/risu729) in [#5518](https://github.com/jdx/mise/pull/5518)
- `self-update` on MITM firewall (attempt #2) by [@joehorsnell](https://github.com/joehorsnell) in [#5459](https://github.com/jdx/mise/pull/5459)
- mise panic in removed directory by [@roele](https://github.com/roele) in …
=> chore: release 2025.7.2

src/env.rs, src/plugins/asdf_plugin.rs
Fixes https://github.com/jdx/mise/issues/5524.
https://github.com/jdx/mise/pull/3114 introduced the overwrite behaviour to resolve https://github.com/jdx/mise/issues/2910 and https://github.com/jdx/mise/issues/3070.
It was to ignore an invalid `GITHUB_TOKEN` if `MISE_GITHUB_TOKEN` is set to an empty string, but it was necessary only because we used to call `ubi` from the CLI.
For asdf plugins, this should be enough to overwrite `GITHUB_TOKEN`.
https://github.com/jdx/mise/blob/ce78f04bfb338d218df90301a093b01b1d67d13a/src/plugins/asdf_plugin.rs#L426
I'm not sure about vfox plugins, but I don't think this PR will change any behaviours because it seems `vfox.rs` not using the tokens.
=> fix: do not overwrite github tokens environment variables

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** add vfox by [@risu729](https://github.com/risu729) in [#5551](https://github.com/jdx/mise/pull/5551)
- **(aqua)** show other backends suggestion for unsupported package types by [@risu729](https://github.com/risu729) in [#5547](https://github.com/jdx/mise/pull/5547)
- **(registry)** use aqua and fix ubi options for yamlscript by [@risu729](https://github.com/risu729) in [#5538](https://github.com/jdx/mise/pull/5538)
- **(registry)** add java and yq to android-sdk dependencies by [@risu729](https://github.com/risu729) in [#5545](https://github.com/jdx/mise/pull/5545)
- **(schema)** broken $schema ref by [@tpansino](https://github.com/tpansino) in [#5540](https://github.com/jdx/mise/pull/5540)
- auto_install_disable_tools env var by [@jdx](https://github.com/jdx) in …
=> chore: release 2025.7.3

.github/workflows/test.yml, docs/dev-tools/shims.md, e2e/shell/test_xonsh, e2e/shell/xonsh_script, hk.pkl, src/shell/snapshots/mise__shell__xonsh__tests__hook_init.snap, src/shell/snapshots/mise__shell__xonsh__tests__prepend_env.snap, src/shell/snapshots/mise__shell__xonsh__tests__set_env.snap, src/shell/snapshots/mise__shell__xonsh__tests__unset_env.snap, src/shell/snapshots/mise__shell__xonsh__tests__xonsh_deactivate.snap, src/shell/xonsh.rs
The Xonsh integration is currently broken. It doesn't output any errors when running `execx($(mise activate -s xonsh))`, but calling `mise` after doing so will raise an error:
```
joe@vingilot ~/Documents/code/mise main @ execx($(mise activate xonsh))
joe@vingilot ~/Documents/code/mise main @ mise
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
Exception in thread {'cls': 'ProcProxyThread', 'name': 'Thread-33', 'func': FuncAlias({'name': 'mise', 'func': '_mise', 'return_what': 'result'}), 'alias': 'mise', 'pid': None}
FileNotFoundError: [Errno 2] No such file or directory: 'command'
```
Ultimately this error is due to the activating script trying to execute `command mise ...`, and `command` isn't a proper executable. `command` is a Bash builtin (and maybe exists in other more …
=> fix: Xonsh integration

src/backend/aqua.rs
Aligns the version resolution logic (from canonicalised version to GitHub tag) in `list_bin_paths` with the one in `install_version_`.
I think this doesn't change the behaviour for offline introduced in https://github.com/jdx/mise/pull/5195.
> TODO: instead of caching it would probably be better to create this as part of installation
Regarding this TODO, I agreed with it and tried to work on it, but was not sure how to.
I'd like to ask for some advice.
I thought of storing `bin_paths.msgpack.z` in the installation path, `tv.install_path()`, while the installation, and reading it when `list_bin_paths` is called.
Not to break the installations with old versions, or just in case `bin_paths.msgpack.z` is removed somehow, I think we need to fall back to the current implementation if it's not …
=> fix(aqua): align version resolution logic in list_bin_paths

src/backend/aqua.rs
=> Revert "fix(aqua): align version resolution logic in list_bin_paths"

.github/workflows/release.yml, mise.lock, scripts/release.sh
This marks the release as a draft until the assets are successfully added.
However, since `release-r2.sh` runs before it, `https://mise.run` will still fail.
I think we need to move it to `post-release.sh` and run it after the assets creation.
=> chore(release): mark a release as draft until assets are added

.cursor/rules/conventional_commits.mdc
Fix the formatting issues in the conventional commits cursor rule file, including proper frontmatter and removing line break issues.
=> docs(cursor): fix conventional commits rule formatting

.cursor/rules/testing.mdc
Add a new cursor rule file for testing the mise codebase with instructions on how to run various test and linting commands.
=> docs(cursor): add testing rule for mise codebase

CHANGELOG.md, Cargo.lock, Cargo.toml
- add static backends (Github, GitLab, and HTTP) by [@jdx](https://github.com/jdx) in [#5602](https://github.com/jdx/mise/pull/5602)
- blake3 support by [@jdx](https://github.com/jdx) in [#5605](https://github.com/jdx/mise/pull/5605)
- **(e2e)** simplify test path handling logic by [@jdx](https://github.com/jdx) in [#5600](https://github.com/jdx/mise/pull/5600)
- skip gh release edit on dry run in release workflow by [@jdx](https://github.com/jdx) in [#5603](https://github.com/jdx/mise/pull/5603)
- **(cursor)** fix conventional commits rule formatting by [@jdx](https://github.com/jdx) in [#5597](https://github.com/jdx/mise/pull/5597)
- **(cursor)** add testing rule for mise codebase by [@jdx](https://github.com/jdx) in [#5598](https://github.com/jdx/mise/pull/5598)
- disable cmake test …
=> chore: release 2025.7.5

e2e/config/test_config_alias_github_edit, src/backend/github.rs
This PR fixes a bug where GitHub aliases were not being resolved correctly, causing the wrong repository name to be used when fetching releases.
- **Fix BackendArg::tool_name()**: Now extracts the tool name from the resolved alias instead of the original argument
- **Update GitHub backend**: Uses the `tool_name()` method to ensure proper alias resolution
- **Add platform-specific asset patterns**: Test now includes proper TOML configuration for all available assets
- **Skip test on macOS**: Test skips on macOS where no compatible asset is available
- **Improve error messages**: Shows available assets for better debugging
- Added comprehensive e2e test that verifies alias resolution works correctly
- Test includes platform-specific asset patterns for all supported platforms
- Test properly …
=> fix: resolve GitHub alias tool name parsing and add platform-specific asset support

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(shim)** prevent mise-specific flags from interfering with shim execution by [@jdx](https://github.com/jdx) in [#5616](https://github.com/jdx/mise/pull/5616)
- github asset auto-detection by [@jdx](https://github.com/jdx) in [#5622](https://github.com/jdx/mise/pull/5622)
- resolve GitHub alias tool name parsing and add platform-specific asset support by [@jdx](https://github.com/jdx) in [#5621](https://github.com/jdx/mise/pull/5621)
=> chore: release 2025.7.9

docs/dev-tools/backends/github.md, docs/dev-tools/backends/gitlab.md
This PR adds documentation for the asset autodetection functionality in the GitHub and GitLab backends.
- Added Asset Autodetection section to GitHub backend docs
- Added Asset Autodetection section to GitLab backend docs  
- Included links to source code implementation
- Added usage examples showing how to install tools without specifying patterns
When no `asset_pattern` is specified, mise automatically selects the best asset for your platform by scoring assets based on:
- OS compatibility (linux, macos, windows)
- Architecture compatibility (x64, arm64, x86, arm) 
- Archive format preference (tar.gz, zip, etc.)
- Build type (avoids debug/test builds)
This makes it much easier for users to install tools from GitHub/GitLab releases without needing to specify complex asset patterns.
=> docs: add asset autodetection documentation to GitHub/GitLab backends

e2e/backend/test_github_ripgrep, e2e/backend/test_github_tools, src/backend/aqua.rs, src/backend/static_helpers.rs, src/file.rs, src/plugins/core/bun.rs, src/plugins/core/deno.rs, src/plugins/core/elixir.rs, src/plugins/core/erlang.rs, src/plugins/core/go.rs, src/plugins/core/java.rs, src/plugins/core/node.rs
Fixes https://github.com/jdx/mise/discussions/5604#discussioncomment-13750422.
~~It's a bit weird, but only `file::untar` supports `strip_components` option.
It internally calls `file::unzip`, so some codes call `file::untar` even for `.zip`.~~
~~However, `inspect_tar_contents`, or `open_tar` in it, doesn't support `.zip`, so the auto detection doesn't work.~~
~~Can I refactor it to support `strip_components` by `file::unzip`?~~
=> fix(static): support `strip_components` for zip files

src/backend/aqua.rs
Fix inaccurate warning message `no aqua registry found for aqua:gitea.com/gitea/tea`.
`repo_owner` and/or `repo_name` are sometimes missing for `type: http` packages.
The warnings used to be:
```
DEBUG ARGS: mise install aqua:gitea.com/gitea/tea@0.10.1 --debug
DEBUG config: ~/.config/mise/mise.local.toml
DEBUG config: ~/.config/mise/config.toml
DEBUG install_some_versions: aqua:gitea.com/gitea/tea@0.10.1
WARN  no aqua registry found for aqua:gitea.com/gitea/tea
WARN  No versions found for aqua:gitea.com/gitea/tea
INFO  aqua:gitea.com/gitea/tea@0.10.1     install
```
With this change, it will be:
```
DEBUG ARGS: target/debug/mise install aqua:gitea.com/gitea/tea@0.10.1 --debug
DEBUG $ /home/risu/.local/share/mise/plugins/asdf-maven/bin/list-legacy-filenames 
DEBUG $ …
```
=> fix(aqua): improve warnings for packages without repo_owner and repo_name

e2e-win/7z.Tests.ps1, src/file.rs, src/plugins/core/ruby_windows.rs
This update uses file::un7z, which is currently gated behind Windows. ~Another known limitation of this approach is that strip_components is not supported.~
=> feat: support extracting 7z archives for static backends

src/backend/aqua.rs
I'm sorry I didn't notice that `validate` handles such things. Follow up of https://github.com/jdx/mise/pull/5303.
=> refactor(aqua): move no_aset and error_message checks into validate

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- support extracting 7z archives for static backends by [@yjoer](https://github.com/yjoer) in [#5632](https://github.com/jdx/mise/pull/5632)
- **(aqua)** improve warnings for packages without repo_owner and repo_name by [@risu729](https://github.com/risu729) in [#5644](https://github.com/jdx/mise/pull/5644)
- **(generate)** fix task docs inject by [@risu729](https://github.com/risu729) in [#5651](https://github.com/jdx/mise/pull/5651)
- **(static)** support `strip_components` for zip files by [@risu729](https://github.com/risu729) in [#5631](https://github.com/jdx/mise/pull/5631)
- private forges by [@hamnis](https://github.com/hamnis) in [#5650](https://github.com/jdx/mise/pull/5650)
- **(aqua)** move no_aset and error_message checks into validate by …
=> chore: release 2025.7.11

src/backend/npm.rs
Resolves https://github.com/jdx/mise/discussions/5654.
Even if `--cwd` is used, bun seems to read `bun.lock` in the current directory, which is `~` by default.
To avoid this, run `bun` in the `tv.install_path()` directly.
=> fix(npm): run bun in install_path instead of using --cwd flag of bun

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(npm)** run bun in install_path instead of using --cwd flag of bun by [@risu729](https://github.com/risu729) in [#5656](https://github.com/jdx/mise/pull/5656)
- **(nushell)** fix `get -i` deprecation by [@JoaquinTrinanes](https://github.com/JoaquinTrinanes) in [#5666](https://github.com/jdx/mise/pull/5666)
- Revert "fix(aqua): improve warnings for packages without repo_owner and repo_name " by [@jdx](https://github.com/jdx) in [#5668](https://github.com/jdx/mise/pull/5668)
- update deps by [@risu729](https://github.com/risu729) in [#5657](https://github.com/jdx/mise/pull/5657)
- update usage by [@risu729](https://github.com/risu729) in [#5661](https://github.com/jdx/mise/pull/5661)
- @JoaquinTrinanes made their first contribution in [#5666](https://github.com/jdx/mise/pull/5666)
=> chore: release 2025.7.12

src/file.rs
Follow up of https://github.com/jdx/mise/pull/5662.
The copilot suggestion was wrong; `path.metadata()` follows symlinks, so use [`path.symlink_metadata()`](https://doc.rust-lang.org/beta/std/fs/fn.symlink_metadata.html) to return the metadata of the path itself.
=> fix: don't follow symlink to ignore symlinks from deletion

docs/lang/rust.md
See:
- https://rust-lang.github.io/rustup/environment-variables.html#environment-variables
- https://github.com/jdx/mise/blob/c49082d1097e5cd65334f61254e6315ceefd225d/src/plugins/core/rust.rs#L170
=> docs: fix typo in RUSTUP_TOOLCHAIN env variable name

src/plugins/core/assets/rubygems_plugin.rb
👋 Hi, thanks to develop and maintain `mise`.
I'm a Ruby and RubyGems maintainer. I always faced redefinition warnings with RubyGems test suite like:
```
❯ ruby -Ilib:test test/rubygems/test_gem_gem_runner.rb
Loaded suite test/rubygems/test_gem_gem_runner
Started
-/Users/hsbt/.local/share/mise/installs/ruby/3.4-dev/lib/ruby/site_ruby/rubygems_plugin.rb:3: warning: method redefined; discarding old debug?
/Users/hsbt/.local/share/mise/installs/ruby/3.4-dev/lib/ruby/site_ruby/rubygems_plugin.rb:3: warning: previous definition of debug? was here
/Users/hsbt/.local/share/mise/installs/ruby/3.4-dev/lib/ruby/site_ruby/rubygems_plugin.rb:7: warning: method redefined; discarding old log_debug
/Users/hsbt/.local/share/mise/installs/ruby/3.4-dev/lib/ruby/site_ruby/rubygems_plugin.rb:7: warning: …
```
=> Suppress redefinition warning of rubygems_plugin.rb

completions/_mise, completions/mise.bash, completions/mise.fish, mise.lock
Sorry, I missed updating `usage` version in `mise.toml` in https://github.com/jdx/mise/pull/5657.
Since `mise completion` calls `usage` via CLI, it didn't fix the completions.
Resolves https://github.com/jdx/mise/discussions/5659.
=> fix: update completions

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- update rust crate tabled to 0.20 by [@renovate[bot]](https://github.com/renovate[bot]) in [#5688](https://github.com/jdx/mise/pull/5688)
- update rust crate indicatif to 0.18 by [@renovate[bot]](https://github.com/renovate[bot]) in [#5687](https://github.com/jdx/mise/pull/5687)
=> chore: release 2025.7.14

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- added .release-skip-e2e functionality by [@jdx](https://github.com/jdx) in [#5698](https://github.com/jdx/mise/pull/5698)
=> chore: release 2025.7.15

registry.toml
`maven` test fails because `mise-versions` doesn't include the latest `3.9.11`, but the maven only provides the latest download link.
Should we remove it from `mise-versions` to avoid errors?
https://dlcdn.apache.org/maven/maven-3/
https://github.com/jdx/mise-versions/commits/main/docs/maven
=> test(registry): enable disabled tests

registry.toml
Please add the `jsonschema` CLI tool. It was just included to the aqua registry: https://github.com/aquaproj/aqua-registry/pull/39066
=> feat(registry): add `jsonschema` CLI tool

src/shell/pwsh.rs, src/shell/snapshots/mise__shell__pwsh__tests__activate.snap, src/shell/snapshots/mise__shell__pwsh__tests__deactivate.snap
- It also resets to previous encoding at exit.
=> fix(pwsh): set console encoding to UTF-8 to prevent Unicode garbling

docs/contributing.md
While dealing with https://github.com/jdx/mise/pull/5736 I got mildly confused as to what the documentation conventional commit prefix is used for this repo, as the docs said `doc:` while the PR check said `docs:`. I changed the docs to match the PR check.
=> docs: fix typo in contributing commit message prefixes

docs/environments/index.md
This commit removes an invalid array declaration from the redactions section in the environments documentation. Including the array as is causes a panic:
```
=== Async Backtrace (panic occurred in tokio runtime) ===                             
0: Location { name: Some("mise::config::Config::load::{{closure}}"), rest: ("src/config/mod.rs", 106, 5) }
------- TASK DUMP TREE -------
╼ mise::config::Config::load::{{closure}} at src/config/mod.rs:106:5
=== End Async Backtrace ===
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src/config/config_file/mise_toml.rs:1238
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
Removing the array notation from the …
=> docs: Removes invalid array in redaction example

docs/plugin-lua-modules.md
Summary:
- `archiver` doesn't have compress or 7z support
- `file` doesn't have read/write/exists/list_dir/mkdir/mkdir_all
- `file` does have "Create Symbolic Links"
- `env` uses `env.setenv()` not `env.set()`
- `env` doesn't have `env.get()` instead reference `os.getenv()`
=> docs: fix plugin-lua-modules docs to match the vfox lua_mod functions

docs/dev-tools/backends/http.md
Fix example commands as tool options should be defined before the `@VERSION`.
For example
```bash
mise use http:lua@5.4.8[url=http://www.lua.org/ftp/lua-5.4.8.tar.gz]
error: invalid value 'http:lua@5.4.8[url=http://www.lua.org/ftp/lua-5.4.8.tar.gz]' for '[TOOL@VERSION]...': invalid prefix: 5.4.8[url=http
mise use http:lua[url=http://www.lua.org/ftp/lua-5.4.8.tar.gz]@5.4.8
```
=> docs: fix http backend tool options example

src/http.rs
> If the `retry-after` response header is present, you should not retry your request until after that many seconds has elapsed. If the `x-ratelimit-remaining` header is `0`, you should not retry your request until after the time, in UTC epoch seconds, specified by the `x-ratelimit-reset` header. Otherwise, wait for at least one minute before retrying.
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit
=> feat(http): show retry after for github rate limit

registry.toml
(try 2 - forgot to follow-up last time after tests were fixed)
This is a nice shell completion tool: https://github.com/carapace-sh/carapace-bin
It has support for many tools: https://carapace-sh.github.io/carapace-bin/completers.html
And a completion format that's easier to use than typical zsh completions: https://carapace-sh.github.io/carapace-bin/spec.html
=> feat(registry): add carapace

e2e/generate/test_generate_tool_stub_archive, src/cli/generate/tool_stub.rs, src/file.rs
Fixes tool-stub generation failures when using archive URLs like .tar.gz files.
- **Filename preservation**: Archive temporary files now retain original filenames with extensions, enabling proper format detection
- **Duplicate downloads**: Combined checksum detection and binary path detection into single download operation
- **Progress reporting**: Unified download and extraction into one continuous progress indicator
- **Binary path detection**: Fixed paths to account for automatic \`strip_components=1\` application
- **HTTP infrastructure**: Replaced direct reqwest usage with mise's HTTP client for consistency
- Modified \`analyze_url()\` to download once and return checksum, size, and binary path
- Enhanced \`extract_and_find_binary()\` to predict \`strip_components\` behavior and …
=> fix: tool-stub generation with archive downloads

docs/directories.md, docs/troubleshooting.md
This PR adds a section on `Path` environment variable limitations on Windows. Also see [#5790](https://github.com/jdx/mise/pull/5790#issuecomment-3126474031).
=> docs(troubleshooting): path limits on Windows

e2e/backend/test_pipx_custom_registry, src/cli/args/backend_arg.rs
Fixes: https://github.com/jdx/mise/discussions/5646
Issue introduced here:
https://github.com/jdx/mise/compare/v2025.7.7..v2025.7.8#diff-666bb9d34c6ca6727005c50be93f02d720e77f525dcef4d8d286344c1f0d21f1R101-R126
The new backend logic was causing the `versions_hash` in `get_leaf_dependencies` to always include "pipx" when testing with a pipx tool. This causes issues when pipx is not part of the requested tools to install. It essentialy prevented the tool from being considered a leaf dependency.
=> fix: misidentifying built-in backend as a plugin backend 

docs/dev-tools/backends/dotnet.md, src/backend/dotnet.rs
Some NuGet endpoints (like Artifactory) don’t expose the `SearchQueryService/3.5.0` type, just the plain `SearchQueryService`.
I also added a note indicating that the .NET backend requires a compatible .NET runtime to be installed.
=> fix: dotnet SearchQueryService fallback

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, docs/dev-tools/tool-stubs.md, packaging/rpm/mise.spec
- **(tool-stubs)** append to existing tool-stub files instead of overwriting by [@jdx](https://github.com/jdx) in [#5835](https://github.com/jdx/mise/pull/5835)
- **(tool-stubs)** add auto-platform detection from URLs by [@jdx](https://github.com/jdx) in [#5836](https://github.com/jdx/mise/pull/5836)
- Add sops.strict setting for non-strict decryption mode by [@pepicrft](https://github.com/pepicrft) in [#5378](https://github.com/jdx/mise/pull/5378)
- **(tool-stub)** use URL hash as version for HTTP backend with "latest" by [@jdx](https://github.com/jdx) in [#5828](https://github.com/jdx/mise/pull/5828)
- **(tool-stubs)** fix -v and --help flags by [@jdx](https://github.com/jdx) in [#5829](https://github.com/jdx/mise/pull/5829)
- **(tool-stubs)** use 'checksum' field instead of 'blake3' in …
=> chore: release 2025.7.31

src/aqua/aqua_registry.rs
Aqua supports multiple constraints in `semver` separated with `,`.
https://aquaproj.github.io/docs/reference/upgrade-guide/v2/change-semver/
However, [`versions`](https://github.com/fosskers/rs-versions) crate doesn't support it.
[`semver`](https://github.com/dtolnay/semver) crate supports it, but since we depend on the fuzzy parse of messed semvers, I couldn't migrate to it.
e.g.
```
DEBUG error parsing semver("<= 7.4.7") || (semver(">= 7.5.0-preview.1, <= 7.5.1")) || (semver(">= 7.6.0-preview.1, <= 7.6.0-preview.4")): invalid semver
```
https://github.com/risu729/aqua-registry/blob/main/pkgs/PowerShell/PowerShell/registry.yaml
=> fix(aqua): support `AND` operator in semver

src/backend/go.rs
This PR refactors https://github.com/jdx/mise/pull/1583 by guessing the root module.
Since many go modules use `github.com/owner/repo` or `github.com/owner/repo/v0`, we can first try them and fall back to the original behaviour.
This will reduce `go list -m -versions -json <module>` call, which is relatively slow.
e.g.
Current behaviour:
```
$ mise ls-remote go:github.com/go-task/task/v3/cmd/task --debug
DEBUG $ go list -m -versions -json github.com/go-task/task/v3/cmd/task
DEBUG $ go list -m -versions -json github.com/go-task/task/v3/cmd
DEBUG $ go list -m -versions -json github.com/go-task/task/v3
```
With this PR:
```
$ mise ls-remote go:github.com/go-task/task/v3/cmd/task --debug
DEBUG $ go list -m -versions -json github.com/go-task/task/v3
```
=> fix(go): implement heuristic-based go module find logic

docs/lang/python.md
Hey, disclaimer is I am a noob with `uv`, but when setting uv up following the mise + uv configurations, I kept having errors with `uv_create_args`, it appears to me that it is a typo and should actually be `uv_venv_create_args`.
Hopefully this is helpful for others. Feel free to merge or close if this is incorrect, no worries.
Thanks for this awesome tool. Been using since the rtx days.
=> docs: fix uv_venv_create_args reference for python

registry.toml
Resolves https://github.com/jdx/mise/discussions/5855.
However, the `bin` directory contains `node` itself, so it might override other `node` installations.
See https://github.com/jdx/mise/pull/5788#issuecomment-3119966306 and https://github.com/jdx/mise/discussions/4675.
We can use `npm:balena-cli` instead, but it didn't work with `npm.bun=true`.
I think adding a tool option to override it per tool would be a solution, as in https://github.com/jdx/mise/discussions/4816, but it would cause another issue in `list_bin_paths`.
For the asdf plugin, they transffered the repository from an organization to an indivisual, so I followed it.
=> fix(registry): fix balena ubi backend options

docs/environments/index.md
I've seen a few people use `[[env]]` tables when it's not necessary because they didn't know they could just use an array.
It's not clear from the current docs that all the env directives can be `string | object | array[ string | object ]`. 
In this PR each directive has the following section:
```
List of supported features (file formats, directive options, absolute/relative paths, 
Example 1 - simple string
Example 2 - object
Example 3 - list with strings and objects
```
This PR is mostly adding, I've tried to delete as little as possible.
=> docs: expand on env directive examples and formats

src/backend/pipx.rs
The HTML‐based pipx backend now correctly follows PEP 503 when constructing
package index URLs. In particular, this change:
- Fixes the URL assignment logic so that custom registry URLs are respected. (linked #4945)
- Ensures that `mise use pipx:my-package` will now pull from your specified registry.
- Propagates the pip index URL correctly to both `uvx` and `pipx` in the proper format.
> [!NOTE]
> The helper functions `latest_stable_version` and `_list_remote_versions` currently
query the API endpoint directly and cannot handle authenticated feeds. It would be a good improvement to refine these functions in the future
to support authenticated registries.
=> fix(pipx): align HTML backend with PEP 503 registry URL assignment

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(registry)** use npm backend for yarn by [@mrazauskas](https://github.com/mrazauskas) in [#5745](https://github.com/jdx/mise/pull/5745)
- **(registry)** add codebuff tool by [@zacheryph](https://github.com/zacheryph) in [#5856](https://github.com/jdx/mise/pull/5856)
- **(go)** implement heuristic-based go module find logic by [@risu729](https://github.com/risu729) in [#5851](https://github.com/jdx/mise/pull/5851)
- **(node)** Add NodeJS maintainer Antoine du Hamel's new GPG key by [@chadlwilson](https://github.com/chadlwilson) in [#5862](https://github.com/jdx/mise/pull/5862)
- **(pipx)** align HTML backend with PEP 503 registry URL assignment by [@acesyde](https://github.com/acesyde) in [#5853](https://github.com/jdx/mise/pull/5853)
- **(registry)** fix balena ubi backend options by …
=> chore: release 2025.8.0

registry.toml
Add trunk code quality tool configuration to the registry with aqua
backend support from trunk-io/launcher. Includes description and
version test commands to ensure proper installation and functionality.
Sorry to have opened and closed this PR a few times. Now we're using the `npm` backend, `latest` should work, CI should pass, and we can consider this final from my end.
---
This pull request adds a new backend configuration for the `trunk` tool in the `registry.toml` file. The changes include specifying the backend details, a description, and test commands for the `trunk` tool.
* Added `trunk.backends` with the value `["npm:@trunkio/launcher"]` to specify the backend source for the `trunk` tool.
* Added `trunk.description` to provide a description of the `trunk` tool, highlighting its …
=> feat(registry): add trunk metalinter

cliff.toml
Add postprocessor to git-cliff config to automatically convert backend references (aqua:, github:, gitlab:, ubi:) to hyperlinks pointing to their respective GitHub repositories.
This ensures that changelog entries like 'add tool via aqua:owner/repo backend' are automatically converted to clickable links.
=> docs(changelog): automate backend links in changelog

docs/configuration.md, registry.toml
Resolves https://github.com/jdx/mise/discussions/5329.
`.terragrunt-version` is supported by [`tgenv`](https://github.com/tgenv/tgenv).
It doesn't seem to be that common, but I think it would be nice if we support it.
=> registry: support `.terragrunt-version`

src/plugins/core/elixir.rs
It has been documented but was not supported by the core.
https://github.com/jdx/mise/blob/11529f77d9eeae9fed2bfc086fd1bd3ba1771885/docs/configuration.md#L317
=> fix(elixir): support `.exenv-version`

docs/configuration.md, registry.toml
Sorry, I didn't notice the author hadn't updated the PR to use the aqua backend in https://github.com/jdx/mise/pull/5745.
I didn't notice that the registry supports `idiomatic_files`, but it does, so `.yvmrc` will still be supported.
`.yarnrc` was in the docs, but it had never been supported by the asdf plugin, so I guess it was a mistake.
yarn v1 is no longer supported since https://github.com/jdx/mise/pull/5745, but we can still install it with `asdf:yarn` (not on Windows).
=> registry: use aqua backend for yarn

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- add tlrc ([aqua:tldr-pages/tlrc](https://github.com/tldr-pages/tlrc)) by [@TyceHerrman](https://github.com/TyceHerrman) in [#5895](https://github.com/jdx/mise/pull/5895)
- support `.terragrunt-version` by [@risu729](https://github.com/risu729) in [#5903](https://github.com/jdx/mise/pull/5903)
- add lnav ([aqua:tstack/lnav](https://github.com/tstack/lnav)) by [@TyceHerrman](https://github.com/TyceHerrman) in [#5896](https://github.com/jdx/mise/pull/5896)
- use aqua backend for yarn by [@risu729](https://github.com/risu729) in [#5902](https://github.com/jdx/mise/pull/5902)
- add dotenvx ([aqua:dotenvx/dotenvx](https://github.com/dotenvx/dotenvx)) by [@TyceHerrman](https://github.com/TyceHerrman) in [#5915](https://github.com/jdx/mise/pull/5915)
- update kubecolor …
=> chore: release 2025.8.5

.github/workflows/registry.yml
Resolves https://github.com/jdx/mise/pull/5914#issuecomment-3160707479.
It failed with a mise error, and I didn't set `pipefail`, so it continued with an error.
The mise error seems to occur when `mise exec` is called with a `<` redirect, or `mise exec` is called twice in a row.
I don't have any ideas what's happening and I don't think it's a common problem, so I fix the workflow by installing the tools before `mise exec`, which works fine as a workaround.
<details>
<summary>action log</summary>
```
+++ mise x yj -- yj -t
DEBUG Version: 2025.8.7 linux-x64 (2025-08-06)
DEBUG Version: 2025.8.7 linux-x64 (2025-08-06)
DEBUG Version: 2025.8.7 linux-x64 (2025-08-06)
DEBUG ARGS: mise x yj -- yj -t
DEBUG ARGS: mise x jd -- jd -f merge /dev/fd/63 /dev/fd/62
DEBUG ARGS: mise x yj -- yj -t
DEBUG …
```
=> chore: fix registry test filter

.github/workflows/registry_comment.yml
Currently, PRs that add new registries are checked by github actions for their titles, but the current check fails because npm's scoped modules contain `@` (like `npm:@anthropic-ai/claude-code`).
This PR adds `@` to the regex pattern to fix the validation.
You can see this failed action in #5967, which I created
(this PR has been closed as it was unnecessary).
=> chore(ci): accept @ in regular expressions for new registry PR titles

registry.toml
convert back to plugin for yarn. I'm working on making this a vfox plugin so windows support will come back
Fixes https://github.com/mise-plugins/mise-yarn/issues/14
=> registry: revert back to plugin for yarn to bring back v1 compat

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- add bob ([aqua:MordechaiHadad/bob](https://github.com/MordechaiHadad/bob)) by [@TyceHerrman](https://github.com/TyceHerrman) in [#5914](https://github.com/jdx/mise/pull/5914)
- support usage on FreeBSD by [@risu729](https://github.com/risu729) in [#5973](https://github.com/jdx/mise/pull/5973)
- filter out installer for podman by [@risu729](https://github.com/risu729) in [#5974](https://github.com/jdx/mise/pull/5974)
- use pipx aqua backend by [@itochan](https://github.com/itochan) in [#5971](https://github.com/jdx/mise/pull/5971)
- add documentation for os field in tool configuration by [@jdx](https://github.com/jdx) in [#5947](https://github.com/jdx/mise/pull/5947)
- **(ci)** accept @ in regular expressions for new registry PR titles by [@mst-mkt](https://github.com/mst-mkt) in …
=> chore: release 2025.8.8

docs/installing-mise.md
[This PR](https://github.com/jdx/mise/pull/3592) should have fixed the path issues, but the problem described in [this discussion](https://github.com/jdx/mise/discussions/3555) was not fixed. 
The issue doesn't persist if the file is autoloaded, but the documentation currently describes the old way of importing the file with use. This updates the docs to write the autoload-way into the nu config
=> docs: Update install instructions for nushell

docs/installing-mise.md
Reverts jdx/mise#5981
reverted until we can sort out the best way to handle this
=> Revert "docs: Update install instructions for nushell"

src/backend/aqua.rs
When extracting binaries from zip archives in the aqua backend, the files were not being marked as executable. This caused tools like [CQLabs/homebrew-dcm](https://github.com/CQLabs/homebrew-dcm) to fail with permission errors when trying to execute them.
This fix adds a call to file::make_executable() after extracting zip files, matching the behavior of other archive formats (gz, xz, zst, bz2) which already set executable permissions.
Fixes permission denied errors when using aqua backend with zip-packaged tools.
Current mise:
```bash
% mise exec aqua:CQLabs/homebrew-dcm -- dcm --version
mise aqua:CQLabs/homebrew-dcm@1.30.1 ✓ installed
mise ERROR "dcm" couldn't exec process: Permission denied
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```
This PR changes: …
=> fix(aqua): add executable permissions for zip-extracted binaries

e2e/core/test_python_uv_venv_x_tiny, src/toolset/mod.rs
Fixes https://github.com/jdx/mise/discussions/5999
=> fix(uv_venv): fixes PATH ordering with `mise x`

registry.toml
Follow up for https://github.com/jdx/mise/pull/5973.
Sorry, I didn't remember we need to use `platforms` instead of `os` here.
=> registry: fix os specific backends for usage

registry.toml, src/backend/aqua.rs
Reapplies https://github.com/jdx/mise/pull/5998 (reverted in https://github.com/jdx/mise/pull/6004) with some changes.
Some tools don't set `+x` permissions to their executable files in the archives:
- [`powershell`](https://github.com/PowerShell/PowerShell) (https://github.com/jdx/mise/discussions/5552)
- [`bob`](https://github.com/MordechaiHadad/bob)
- [`gitu`](https://github.com/altsem/gitu)
- [`mirrord`](https://github.com/metalbear-co/mirrord)
- [`CQLabs/homebrew-dcm`](https://github.com/CQLabs/homebrew-dcm) (#5998)
Since both `.tar` and `.zip` can include permissions in the archive, this is not a mise bug, but their issues.
However, I think supporting them would be beneficial for some users.
`aqua` supports this because they use shims. `ubi` backend also supports this but I'm not …
=> feat(aqua): make bin paths executable

docs/tasks/file-tasks.md, src/task/mod.rs
Resovles https://github.com/jdx/mise/discussions/5499.
mise currently supports:
- `# mise`
- `// mise`
- `#MISE`
- `//MISE`
- `::MISE`
This PR supports more patterns by making a space between `#` and `mise` optional for both cases.
- `#mise`
- `//mise`
- `::mise`
- `:: mise`
- `# MISE`
- `// MISE`
- `:: MISE`
---
Sorry, I found `# mise` is now deprecated. Was it because spaces caused problems?
https://github.com/jdx/mise/pull/2694
=> feat(task): allow more #MISE comments patterns

schema/mise.json, settings.toml
=> docs(settings): use php as an example for `disable_default_registry`

docs/ide-integration.md
removed some old stuff no longer useful, added some clarification around login scripts, show an example of using    terminal.integrated.automationProfile.osx to get the login script to work on macos.
=> docs: Update ide-integration.md

registry.toml
I've added prek to aqua-registry, so I will use it with mise.
[aquaproj/aqua-registry#39978](https://github.com/aquaproj/aqua-registry/pull/39978)
=> registry: add prek (aqua:j178/prek)

docs/contributing.md
Thank you for maintaining mise.
The mise repo does not allow creation of new issues by anyone other than @jdx. New issues will be automatically closed.
https://github.com/jdx/mise/blob/67dbc039b5e3dbe4cbd5b77bc1db9b5e19a0d9ab/.github/workflows/issue-closer.yml#L10-L13
However, the contributing docs still recommend opening issues.
https://github.com/jdx/mise/blob/67dbc039b5e3dbe4cbd5b77bc1db9b5e19a0d9ab/docs/contributing.md?plain=1#L6-L12
This PR will update `contributing.md` to explain that contributors should create discussions and not issues.
- https://github.com/jdx/mise/issues/3859
=> docs: update `contributing.md` for discussions

src/aqua/aqua_registry.rs, src/logger.rs
- Add PREFER_OFFLINE check in fetch_latest_repo to skip aqua registry updates
- Add PREFER_OFFLINE check in fetch_package_yaml to skip downloading individual package metadata
- When PREFER_OFFLINE is set, use cached metadata even if it's older than DAILY threshold
- Return error if no cached metadata exists and PREFER_OFFLINE is set
=> feat: respect PREFER_OFFLINE for aqua package metadata fetching

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- support tenv idiomatic files by [@risu729](https://github.com/risu729) in [#6050](https://github.com/jdx/mise/pull/6050)
- respect PREFER_OFFLINE for aqua package metadata fetching by [@jdx](https://github.com/jdx) in [#6058](https://github.com/jdx/mise/pull/6058)
- fix backend_architecture docs by [@risu729](https://github.com/risu729) in [#6027](https://github.com/jdx/mise/pull/6027)
- update amannn/action-semantic-pull-request digest to e32d7e6 by [@renovate[bot]](https://github.com/renovate[bot]) in [#6031](https://github.com/jdx/mise/pull/6031)
- update actions/checkout digest to 08eba0b by [@renovate[bot]](https://github.com/renovate[bot]) in [#6030](https://github.com/jdx/mise/pull/6030)
- update actions/cache digest to 0400d5f by …
=> chore: release 2025.8.12

schema/mise.json
The JSON schema is missing a type for the `settings` key.
https://github.com/jdx/mise/blob/57c2b1c0eb5fd1f277f2dab10ce65ed45d2eb999/schema/mise.json#L225
To reproduce this, create a `mise.toml` with a `[settings]` key and lint the file using the JSON schema.
```sh
printf '[settings]\n' >mise.toml
uvx --from "tombi>=0.5,<0.6" tombi lint --no-cache mise.toml
```
```text
Error: invalid json pointer: #/$defs/settings,
schema_uri: https://mise.jdx.dev/schema/mise.json
```
This PR will add `"type": "object"` to the `settings` key in the JSON schema.
- https://github.com/tombi-toml/tombi/issues/858
=> fix(schema): add missing `settings` type

src/sysconfig/mod.rs
Fixes an issue discussed in #6053
=> fix(python): patching sysconfig data fails for RC versions

Cargo.toml, docs/cli/install.md, docs/cli/use.md, e2e/cli/test_install_dry_run, e2e/cli/test_use, e2e/cli/test_use_dry_run, mise.lock, mise.usage.kdl, src/backend/mod.rs, src/backend/vfox.rs, src/cli/install.rs, src/cli/install_into.rs, src/cli/latest.rs, src/cli/ls_remote.rs, src/cli/plugins/install.rs, src/cli/use.rs, src/install_context.rs, src/plugins/asdf_plugin.rs, src/plugins/mod.rs, src/plugins/vfox_plugin.rs, src/toolset/mod.rs, src/ui/multi_progress_report.rs, src/ui/progress_report.rs, xtasks/fig/src/mise.ts, xtasks/test/perf
This PR adds a `--dry-run` flag to the `mise install` command, allowing users to preview what would be installed without actually performing the installation.
- **CLI**: Added `--dry-run` flag with short form `-n` to the install command
- **Logic**: Skip actual installation, plugin installation, and post-install hooks in dry-run mode
- **Display**: 
- Shows "would install" for new tools and "already installed" for existing ones
- Uses circle icon (○) instead of checkmark (✓) to indicate skipped actions
- Fixed TTY display issues by forcing verbose text output for dry-run mode
- **Progress Icons**: Added `ProgressIcon` enum with Success, Skipped, Warning, and Error variants
- **Tests**: Added comprehensive e2e tests for dry-run functionality
- **Documentation**: Updated help text with …
=> feat(install): add --dry-run flag to show what would be installed

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, mise.lock, packaging/rpm/mise.spec
- **(release-plz)** get `git status` by [@jdx](https://github.com/jdx) in [#6083](https://github.com/jdx/mise/pull/6083)
- add libbz2-dev to e2e test dependencies by [@jdx](https://github.com/jdx) in [#6080](https://github.com/jdx/mise/pull/6080)
- replace submodule with subtree by [@risu729](https://github.com/risu729) in [#6082](https://github.com/jdx/mise/pull/6082)
- fix aqua-registry subtree by [@jdx](https://github.com/jdx) in [522f7f5](https://github.com/jdx/mise/commit/522f7f591dbfa01e537c294647ffdc2a2357c32c)
=> chore: release 2025.8.15

schema/mise.json, settings.toml, src/aqua/aqua_registry.rs, src/cli/doctor/mod.rs
The aqua registry is now always baked in, so the fallback is not required.
https://github.com/jdx/mise/pull/6082
=> fix(aqua): remove mise-versions aqua registry

registry.toml
In https://github.com/aquaproj/aqua-registry/pull/35837, the aqua registry moved the `kubectl` tool from `kubernetes/kubectl` to `kubernetes/kubernetes/kubectl`.
This is a regression as of `v2025.8.17` (`v2025.8.16` works).
The error for the current version (`v2025.8.18` as of the time of this PR creation):
```
❯ mise install kubectl
mise ERROR Failed to install tool: kubectl@latest
kubectl@latest:
0: failed to install aqua:kubernetes/kubectl@1.33.4
1: no aqua-registry found for kubernetes/kubectl
Location:
src/aqua/aqua_registry.rs:257
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
mise mise 2025.8.18 by @jdx –       install
``` …
=> registry: update kubectl aqua alias

Cargo.toml, build.rs
Resolves https://github.com/jdx/mise/discussions/6102.
`aqua.registry_url` doesn't work with aliases, but I'll fix it later.
=> fix(aqua): bake in aliased registries

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, aqua-registry/.github/workflows/count-pkgs.yaml, aqua-registry/pkgs/Songmu/maltmill/pkg.yaml, aqua-registry/pkgs/cargo-bins/cargo-binstall/pkg.yaml, aqua-registry/pkgs/crates.io/cargo-deb/pkg.yaml, aqua-registry/pkgs/dag-andersen/argocd-diff-preview/pkg.yaml, aqua-registry/pkgs/ekristen/aws-nuke/pkg.yaml, aqua-registry/pkgs/github/github-mcp-server/pkg.yaml, aqua-registry/pkgs/google/wire/pkg.yaml, aqua-registry/pkgs/jdx/hk/pkg.yaml, aqua-registry/pkgs/jdx/mise/pkg.yaml, aqua-registry/pkgs/okteto/okteto/pkg.yaml, aqua-registry/pkgs/ziglang/zig/pkg.yaml, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- update kubectl aqua alias by [@malept](https://github.com/malept) in [#6107](https://github.com/jdx/mise/pull/6107)
- remove asdf plugin for watchexec by [@risu729](https://github.com/risu729) in [#6106](https://github.com/jdx/mise/pull/6106)
- **(aqua)** bake in aliased registries by [@risu729](https://github.com/risu729) in [#6105](https://github.com/jdx/mise/pull/6105)
=> chore: release 2025.8.19

src/shell/fish.rs, src/shell/snapshots/mise__shell__fish__tests__prepend_env.snap
Fixes issues discussed in #6072. Untested, hence draft.
=> fix: use fish_add_path when activating mise for fish shell

docs/installing-mise.md
I tend to hit the copy button, but it pulls in both the commands whereas I need just one. Split the code block in two.
=> docs: Split run command so that copy button is useful

src/backend/aqua.rs
Fixes https://github.com/jdx/mise/discussions/6132
The bug was caused by prioritising `universal` over `x86_64`. We should use `universal` as a fallback, not the first choice.
=> fix(aqua): respect order of asset_strs

src/shell/nushell.rs, src/shell/snapshots/mise__shell__nushell__tests__hook_init.snap
This addresses the issue in discussion #5472.
Mise on nushell on windows doesn't properly convert the path to a nushell-native list. Most of the time this works fine, as long as the path stays a string. However, if anything else adds a value to the path (like manually activating a python venv), you end up with a list of 2 items: the big, `;` delimited string that was $env.PATH, and one entry for whatever was just added (now the only valid item in the path list).
The problem comes from this function in the activate script:
```nu
def --env "update-env" [] {
if $var.name == 'PATH' {
$env.PATH = ($var.value | split row (char esep))
} else {
}
```
`$env.PATH` is case-insensitive in nushell [1] (actually, all environment variables are, regardless of OS [2]). Mise matches whatever capitalization …
=> fix(nushell/windows): Fix $env.PATH getting converted to a string

src/backend/github.rs, src/backend/static_helpers.rs, src/backend/ubi.rs
Moved `try_with_v_prefix` from `github.rs` to `static_helper.rs` and used it from `ubi` backend too.
=> fix(ubi): show relevent error messages for v-prefixed tags

docs/cli/alias.md, docs/cli/alias/set.md, docs/cli/alias/unset.md, docs/cli/index.md, e2e/cli/test_alias, mise.usage.kdl, src/cli/alias/set.rs, src/cli/alias/unset.rs, src/config/config_file/mise_toml.rs, xtasks/fig/src/mise.ts
I was just trying to set a backend alias for `maven` (since aqua is mostly behind with latest versions) and figured that i am not able to do so with the `alias set` command. While `config set` works, it is not obvious and does not allow for removal.
=> feat: allow set/unset backend aliases

src/shell/pwsh.rs, src/shell/snapshots/mise__shell__pwsh__tests__activate.snap
Reworked some portions of the script for `mise activate pwsh` so it works as expected with powershell v5 as well as pwsh v7.
- Now works with Default Powershell Vendored with Windows
- Added an environment variable, `$env:MISE_PWSH_CHPWD_WARNING`, which can be set to disable warning
- Needed to disable chpwd for v5 powershell due to limitations of powershell itself.
- Reworked argument parsing to avoid powershell v5 causing issue where when it tries to get currently issued command, it breaks.
v5 Before:
v5 After:
v7 Before:
v7 After
=> fix: mise activate not working on powershell v5

e2e/env/test_env_path, src/config/env_directive/mod.rs
As discovered  https://github.com/jdx/mise/discussions/4510 and https://github.com/jdx/mise/issues/4515 , the nested python venv path is incorrect.
I locate the code below, the code origin target is prepend reversed paths to `r. env_paths`, but the `r. env_paths` is already reversed outside.
=> fix: python nested venv path order

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, aqua-registry/pkgs/crazywhalecc/static-php-cli/pkg.yaml, aqua-registry/pkgs/gruntwork-io/terragrunt/pkg.yaml, aqua-registry/pkgs/speakeasy-api/speakeasy/pkg.yaml, aqua-registry/pkgs/weaviate/weaviate/pkg.yaml, cliff.toml, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(ci)** set required environment variables for npm publishing by [@jdx](https://github.com/jdx) in [#6189](https://github.com/jdx/mise/pull/6189)
- **(release)** clean up extra newlines in release notes formatting by [@jdx](https://github.com/jdx) in [#6190](https://github.com/jdx/mise/pull/6190)
- **(release)** add proper newline after New Contributors section in cliff template by [@jdx](https://github.com/jdx) in [#6194](https://github.com/jdx/mise/pull/6194)
- **(release)** fix changelog formatting to remove extra blank lines by [@jdx](https://github.com/jdx) in [#6195](https://github.com/jdx/mise/pull/6195)
- **(release)** restore proper newline after New Contributors section by [@jdx](https://github.com/jdx) in [#6196](https://github.com/jdx/mise/pull/6196)
- **(ci)** split …
=> chore: release 2025.9.2

src/backend/http.rs, src/backend/static_helpers.rs, src/toolset/tool_version_options.rs
- Improve error when no 'url' and no matching platform URL
- Show available platforms detected from options
- Helper moved to backend/static_helpers.rs and reused
This enhances UX by pointing users to valid platform keys when the current platform is unsupported.
=> feat(backend): improve http error when platform url missing; list available platforms

src/backend/static_helpers.rs
Fixes incorrect conversion of platform key underscores to dashes in flat keys.\n\n- Preserves arch underscores (e.g., x86_64) while still normalizing os_arch to os-arch.\n- Adds unit test to prevent regression.\n\nThis resolves mismatches with expected platform keys and improves suggestion accuracy.
=> fix(http): preserve arch underscores in platform keys

src/config/settings.rs, src/plugins/core/node.rs
I was trying to use in Alpine the following build:
https://unofficial-builds.nodejs.org/download/release/v24.5.0/node-v24.5.0-linux-x64-musl.tar.gz
So I set:
```sh
export MISE_NODE_MIRROR_URL=https://unofficial-builds.nodejs.org/download/release/
export MISE_NODE_FLAVOR=musl
export MISE_NODE_COMPILE=false
mise settings set node.mirror_url https://unofficial-builds.nodejs.org/download/release/
mise settings set node.flavor musl
mise settings set node.compile 0
```
But `mise install` would **always** fail trying to download `https://unofficial-builds.nodejs.org/download/release/v24.5.0/node-v24.5.0.tar.gz` that don't exist.
The main issue was that my `settings.node.compile false` was being overridden by the distro `all_compile` override, and it would then try to download the source code for …
=> fix: couldn't download node binary in Alpine, even if it exists in the mirror url

docs/environments/index.md, e2e/env/test_env_path_resolution, src/config/config_file/config_root.rs, src/config/config_file/mise_toml.rs, src/config/config_file/mod.rs, src/config/env_directive/mod.rs, src/config/env_directive/path.rs, src/config/settings.rs
The behavior and docs for env._.path predates config_root as well as config files outside of the root like `.config/mise.toml`. This has been a bug and should have been fixed when support was added for files outside the project root but was not. This change modifies the behavior of env._.path to behave the same as other parts of mise that are relative to config_root and not the parent directory of the config file making mise behave consistently in regards to relative paths.
Fixes https://github.com/jdx/mise/discussions/6203
BREAKING CHANGE: env._.path directories are now relative to the config_root and not the parent directory of the config file. This only affects config files that use env._.path that are outside the config_root (e.g.: `.config/mise.toml` will use `.` and not `.config` …
=> fix: use config_root for env._.path

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, aqua-registry/pkgs/cargo-bins/cargo-binstall/pkg.yaml, aqua-registry/pkgs/cloudfoundry/bosh-cli/pkg.yaml, aqua-registry/pkgs/realm/SwiftLint/pkg.yaml, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, packaging/rpm/mise.spec
- **(task)** add timeout support for task execution by @jdx in [#6216](https://github.com/jdx/mise/pull/6216)
- **(task)** sub-tasks in run lists by @jdx in [#6212](https://github.com/jdx/mise/pull/6212)
- fix npm publish action by @jdx in [14f4b09](https://github.com/jdx/mise/commit/14f4b09982cfa09139f172f302939f46d2cb0872)
- fix cloudflare release action by @jdx in [00afa25](https://github.com/jdx/mise/commit/00afa2563d4368963bcacce11ebddbe05f45b4d7)
- fix git-cliff for release notes by @jdx in [15a9aed](https://github.com/jdx/mise/commit/15a9aede95c8ad953842c206df3b6c9a3960100f)
=> chore: release 2025.9.5

src/config/config_file/toml.rs
Not necessary, but might be used in the future. Feel free to discard.
=> refactor: allow any collection types in deserialize_arr

schema/mise-task.json, schema/mise.json, xtasks/render/schema.ts
Fixes https://github.com/jdx/mise/discussions/6240
=> chore(schema): fix schema for subtasks

docs/lang/rust.md
https://github.com/jdx/mise/blob/669c83c723e26199aa3970fbe132152d9d1aef54/src/plugins/core/rust.rs#L111-L112
It doesn't default to `default`, but respects the default of `rustup` if not set.
=> docs: fix rust profile default

src/github.rs
Currently, authentication headers are not preserved when paginating GitHub releases or tags when `MISE_LIST_ALL_VERSIONS` is set. This results in `mise` failing with an HTTP error.
<details>
<summary>mise output before PR</summary>
```
❯ MISE_VERBOSE=1 MISE_LIST_ALL_VERSIONS=1 MISE_GITHUB_TOKEN=$(gh auth token) /usr/bin/mise ls-remote ubi:private/repo
DEBUG Version: 2025.9.12 linux-x64 (2025-09-16)
DEBUG ARGS: /usr/bin/mise ls-remote ubi:private/repo
DEBUG config: ~/.config/mise/config.toml
DEBUG GET https://api.github.com/repos/private/repo/releases
DEBUG starting new connection: https://api.github.com/
DEBUG GET https://api.github.com/repos/private/repo/releases 200 OK
DEBUG GET https://api.github.com/repositories/123456789/releases?page=2
DEBUG GET …
```
=> fix(github): correctly paginate releases/tags for private repos

docs/mise-cookbook/python.md
A small change to the docs to reflect that `hello.py` has been renamed to `main.py` in current versions of uv. See
* https://github.com/astral-sh/uv/pull/10369
=> docs: change 'hello.py' to 'main.py' in python.md

CHANGELOG.md, crates/aqua-registry/aqua-registry/pkgs/Songmu/maltmill/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/cnosuke/kushi/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/goark/depm/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/ipld/go-car/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/kudobuilder/kuttl/registry.yaml, docs/dev-tools/backends/ubi.md, e2e/generate/test_generate_bootstrap, e2e/tasks/test_task_run_output, registry.toml, src/cli/self_update.rs
=> chore: fixing typos

crates/vfox/src/lua_mod/file.rs, docs/plugin-lua-modules.md
The [tool plugin docs](https://mise.jdx.dev/tool-plugin-development.html) reference a `file.read` function in multiple examples, but none currently exist in the `file` module that comes with the `vfox` crate. This PR implements it so that the docs are more accurate, in addition to its general utility.
=> feat(vfox): add file.read lua function

src/plugins/core/swift.rs
Hi there! First and foremost, thank you for creating and maintaining this fantastic tool. I use it every day and really appreciate it.
I've read the [Contribution Guidelines](https://mise.jdx.dev/contributing.html) and believe this qualifies as a "something obvious" fix, so I've opened this PR. This is my first time contributing to this repository, so I'd appreciate it if you could point out any mistakes or areas for improvement.
I noticed that `mise install swift` fails on arm64 Ubuntu.
From my investigation, this issue seems to be caused by #5629, which changed the return value of `Settings::get().arch()` from `aarch64` to `arm64`.
I've adjusted the code to generate the correct download URL for Swift on arm64 Ubuntu, taking the new architecture name into account.
I couldn't find any …
=> fix: fix an issue where Swift could not be installed on arm64 Ubuntu

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, crates/aqua-registry/aqua-registry/pkgs/akiomik/mado/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/dyne/zenroom/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/fish-shell/fish-shell/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/jpillora/chisel/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/rvben/rumdl/registry.yaml, crates/vfox/Cargo.toml, default.nix, mise.lock, packaging/rpm/mise.spec
- fix an issue where Swift could not be installed on arm64 Ubuntu by @lish82 in [#6348](https://github.com/jdx/mise/pull/6348)
- use cross to build on linux by @jdx in [#6346](https://github.com/jdx/mise/pull/6346)
- @lish82 made their first contribution in [#6348](https://github.com/jdx/mise/pull/6348)
=> chore: release 2025.9.14

packaging/standalone/install.envsubst
This allows for the use case of setting an environment variable in CI to always install `-musl` binaries in Linux CI workers, regardless of the presence of a musl-based `libc`, when multiple arches are used in workflows.
Tested by downloading the `install.sh` asset from the `2025.9.14` release and patching it with this change:
```shell
mkdir /tmp/foo
MISE_INSTALL_PATH=/tmp/foo/mise MISE_INSTALL_MUSL=1 ./install.sh
file /tmp/foo/mise
ldd /tmp/foo/mise
```
Expected output of `file` and `ldd`:
```
❯ file /tmp/foo/mise
/tmp/foo/mise: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, not stripped
❯ ldd /tmp/foo/mise
statically linked
```
=> chore(install.sh): add `MISE_INSTALL_MUSL` to force installing musl variants on Linux

e2e/backend/test_backend_missing_deps
Fixes CI failure in PR #6352 where the e2e test `backend/test_backend_missing_deps` assumed mise would be in `target/debug`, causing failures in release e2e tests.
**Changes:**
- Updated `e2e/backend/test_backend_missing_deps` to use `command -v mise` to resolve the binary from PATH
- This works for both local development builds and release e2e tests where mise is installed
**Testing:**
- ✅ Verified the specific failing test now passes locally
- ✅ Test still validates all backend dependency error scenarios
**Related:**
- Fixes failure in https://github.com/jdx/mise/pull/6352
=> test(e2e): resolve mise via PATH in backend missing deps test

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, docs/.vitepress/stars.data.ts, mise.lock, packaging/rpm/mise.spec
- add missing cargo backends by @jayvdb in [#6307](https://github.com/jdx/mise/pull/6307)
- add env propagation by @Its-Just-Nans in [#6342](https://github.com/jdx/mise/pull/6342)
- **(aqua)** improve GitHub token handling for sigstore verification by @jdx in [#6351](https://github.com/jdx/mise/pull/6351)
- **(backend)** change dependency checks to warnings instead of errors by @jdx in [#6363](https://github.com/jdx/mise/pull/6363)
- **(npm)** improve error message when npm/bun is not installed by @jdx in [#6359](https://github.com/jdx/mise/pull/6359)
- **(vfox)** enable TLS support for reqwest to fix CI tests by @jdx in [#6356](https://github.com/jdx/mise/pull/6356)
- **(registry)** convert to nested TOML sections format by @jdx in [#6361](https://github.com/jdx/mise/pull/6361)
- …
=> chore: release 2025.9.15

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, crates/aqua-registry/aqua-registry/pkgs/k1LoW/concrun/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/shinagawa-web/gomarklint/registry.yaml, default.nix, packaging/rpm/mise.spec
- use npm backend for zbctl by @risu729 in [#6379](https://github.com/jdx/mise/pull/6379)
- **(aqua)** remove blake3 support from aqua checksum algorithms by @risu729 in [#6370](https://github.com/jdx/mise/pull/6370)
- **(aqua)** remove cosign and slsa-verifier dependencies by @risu729 in [#6371](https://github.com/jdx/mise/pull/6371)
- **(aqua)** remove cosign.experimental by @risu729 in [#6376](https://github.com/jdx/mise/pull/6376)
- minisign doesn't require cli by @risu729 in [#6369](https://github.com/jdx/mise/pull/6369)
- ignore renovate new bot name by @risu729 in [#6364](https://github.com/jdx/mise/pull/6364)
=> chore: release 2025.9.16

e2e-win/uv.Tests.ps1, src/uv.rs
Hi there! Regarding #6315, this is what I came up with, and I'm _very_ open to feedback, especially on the test. I don't know if we really need the `an-test` test, seems slightly superfluous.
Seems like a super simple fix and trickier to write the test :wink:
=> uv venv should use Scripts dir on Windows

e2e/backend/test_ubi, registry.toml
Currently, `mise use amplify-cli` installs `amplify-pkg-macos` / `amplify-pkg-linux` / `amplify-pkg-linux-arm64` instead of `amplify`.
Therefore, I modified it to be renamed to `amplify`.
=> registry: replace amplify-cli github backend with ubi

crates/aqua-registry/src/types.rs, src/backend/aqua.rs
It's currently now used, but might be used in the future to ignore it.
=> fix(aqua): support github_artifact_attestations.enabled

src/backend/mod.rs, src/cli/exec.rs, src/env.rs
Fixes https://github.com/jdx/mise/discussions/6388
=> fix: use /c instead of -c on windows in postinstall hook

docs/dev-tools/backends/github.md, docs/dev-tools/backends/gitlab.md, src/backend/github.rs
This is to fix `bitwarden-secrets-manager` in the registry.
https://github.com/jdx/mise-versions/blob/main/docs/bitwarden-secrets-manager
I believe this is okay for most cases, and this matches with `tag_regex` behaviour in the ubi backend.
=> feat(github): filter remote versions by version_prefix

src/cli/doctor/mod.rs
Fixes https://github.com/jdx/mise/discussions/6416
=> fix(doctor): exclude tools not supported on current os

src/file.rs
`mv .../age-plugin-yubikey/age-plugin-yubikey .../age-plugin-yubikey` fails, so we need to rename the dir before moving the file.
=> fix: allow strip_archive_path_components to strip a dir containing the same filename

schema/mise.json
=> fix(json-schema): remove settings/additionalProperties

registry.toml
Resolves https://github.com/jdx/mise/discussions/6402.
Neither works with the GitHub backend because the releases have archives, but we need to download non-archive files.
https://github.com/ocaml/opam/releases/tag/2.4.1
https://github.com/rancher/k3k/releases/tag/v0.3.4
We should fix it, but I don't have a good idea how to fix it.
Maybe we can only exclude small non-archive files (text files) when archive files exist, but I think this also causes some bugs.
=> registry: revert opam/k3kcli backends to ubi

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, crates/aqua-registry/aqua-registry/pkgs/GitGuardian/ggshield/registry.yaml, default.nix, mise.lock, packaging/rpm/mise.spec
- use version_prefix for github backends by @risu729 in [#6409](https://github.com/jdx/mise/pull/6409)
- fix hivemind by @mnm364 in [#6431](https://github.com/jdx/mise/pull/6431)
- revert opam/k3kcli backends to ubi by @risu729 in [#6406](https://github.com/jdx/mise/pull/6406)
- **(spm)** add support for self-hosted and GitLab repositories by @roele in [#6358](https://github.com/jdx/mise/pull/6358)
- add instructions for self-update by @jdx in [#6433](https://github.com/jdx/mise/pull/6433)
- **(doctor)** exclude tools not supported on current os by @risu729 in [#6422](https://github.com/jdx/mise/pull/6422)
- **(json-schema)** remove settings/additionalProperties by @tpansino in [#6420](https://github.com/jdx/mise/pull/6420)
- **(task)** prevent hang when nested tasks fail by @jdx in …
=> chore: release 2025.9.20

registry.toml
~~Also reverts https://github.com/jdx/mise/pull/6406~~
=> registry: re-enable tests

registry.toml
I tried using the new `github` backend, but k3s has strange release artifacts :D
=> registry: prefer k3s from Aqua over ASDF plugin

snapcraft.yaml
This is a follow-up PR for #6472.
Sorry, there was a bug in the snap package.
As I mentioned in #6472, Snap packages can only access the explicitly allowed resources.
I found that I did not allow access to the home directory, and this PR adds `home` interface (permission) to `plugs`.
This `home` interface allows mise to access files under the home directory except for hidden files (i.e., dot files).
[The permissions to `$HOME/.cache/mise` and `$HOME/.local/share/mise` are already configured, and I added `$HOME/.config/mise` in this PR](https://github.com/jdx/mise/pull/6525/files#diff-e68b9afd67bb77dec8eda77796d3e0b784c7011203114996383eed6533be0cefR67-R72).
Does mise need file access permission to other hidden directories?
If mise needs access to other hidden directories, I want to add …
=> fix(snapcraft): add missing home plug for the home directory access permission

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, default.nix, docs/.vitepress/stars.data.ts, packaging/rpm/mise.spec, snapcraft.yaml
- **(shell)** prevent infinite loop in zsh command-not-found handler by @yordis in [#6516](https://github.com/jdx/mise/pull/6516)
- **(snapcraft)** add missing home plug for the home directory access permission by @phanect in [#6525](https://github.com/jdx/mise/pull/6525)
- **(vfox)** implement headers support on http mod by @BasixKOR in [#6521](https://github.com/jdx/mise/pull/6521)
- set MIX_HOME and MIX_ARCHIVES when using the elixir plugin by @numso in [#6504](https://github.com/jdx/mise/pull/6504)
- update docker/login-action digest to 5e57cd1 by @renovate[bot] in [#6522](https://github.com/jdx/mise/pull/6522)
- update fedora:43 docker digest to 2c0d72b by @renovate[bot] in [#6523](https://github.com/jdx/mise/pull/6523)
- verify macOS binary signature during self-update by @jdx in …
=> chore: release 2025.10.2

docs/lang/java.md, docs/lang/python.md, docs/lang/ruby.md, e2e/cli/test_latest, src/plugins/core/java.rs
Adds support for `-latest` suffix in Java, Python and Ruby core plugins which have vendor builds. So `mise latest ruby@truffleruby` and `mise latest ruby@truffleruby-latest` are equivalent while the later is a bit more expressive in its intent.
=> feat: support latest suffix for Java, Python and Ruby flavoured versions

docs/installing-mise.md
Found a broken link to the fish automatic activation env variable section. :)
=> fix(installing-mise.md): broken link

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, crates/aqua-registry/aqua-registry/pkgs/borgbackup/borg/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/flutter/flutter/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/grafana/grafanactl/registry.yaml, default.nix, docs/.vitepress/stars.data.ts, mise.lock, packaging/rpm/mise.spec, snapcraft.yaml
- add jules by @alefteris in [#6568](https://github.com/jdx/mise/pull/6568)
- **(docs)** improve favicon support for Safari by @jdx in [#6567](https://github.com/jdx/mise/pull/6567)
- **(github)** download assets via API to respect GITHUB_TOKEN by @roele in [#6496](https://github.com/jdx/mise/pull/6496)
- **(task)** load toml tasks in `task_config.includes` in system/global config and monorepo subdirs by @risu729 in [#6545](https://github.com/jdx/mise/pull/6545)
- **(task)** handle dots in monorepo directory names correctly by @jdx in [#6571](https://github.com/jdx/mise/pull/6571)
- **(readme)** add GitHub Issues & Discussions section by @rsyring in [#6573](https://github.com/jdx/mise/pull/6573)
- **(tasks)** create dedicated monorepo tasks documentation by @jdx in …
=> chore: release 2025.10.5

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, completions/_mise, completions/mise.bash, completions/mise.fish, crates/aqua-registry/aqua-registry/pkgs/linkerd/linkerd2/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/minio/mc/registry.yaml, crates/aqua-registry/aqua-registry/pkgs/walles/moor/registry.yaml, default.nix, docs/.vitepress/stars.data.ts, mise.lock, packaging/rpm/mise.spec, snapcraft.yaml
- add vfox-mongod by @blaubaer in [#6586](https://github.com/jdx/mise/pull/6586)
- add OSC 9;4 terminal progress indicators by @jdx in [#6584](https://github.com/jdx/mise/pull/6584)
- make progress bar a footer by @jdx in [#6590](https://github.com/jdx/mise/pull/6590)
- **(task)** preserve ubi tool options during auto-install by @jdx in [#6600](https://github.com/jdx/mise/pull/6600)
- unify project_root and config_root resolution by @risu729 in [#6588](https://github.com/jdx/mise/pull/6588)
- **(exec)** remove redundant tty check for auto-install by @jdx in [#6589](https://github.com/jdx/mise/pull/6589)
- remove duplicated task loads by @risu729 in [#6594](https://github.com/jdx/mise/pull/6594)
- @blaubaer made their first contribution in [#6586](https://github.com/jdx/mise/pull/6586)
=> chore: release 2025.10.6
