jdx/mise

src/config/config_file/tool_versions.rs

handle colon in .tool-versions

---

src/cli/mod.rs
src/cli/plugins/install.rs
src/cli/plugins/snapshots/rtx__cli__plugins__install__test__plugin_install_invalid_url.snap
src/shorthand_repository.rs

show better error message on url parse failure

---

src/cli/latest.rs
src/cli/snapshots/rtx__cli__local__test__local-4.snap
src/cli/snapshots/rtx__cli__local__test__local-5.snap

This was showing "truffleruby-" before

fix `rtx latest ruby`

---

README.md
src/cli/alias/ls.rs
src/config/config_file/rtxrc.rs
test/config/config.toml

rename aliases -> alias (what it should have been)

---

src/cli/snapshots/rtx__cli__activate__test__activate_zsh.snap
src/shell/bash.rs
src/shell/fish.rs
src/shell/mod.rs
src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap
src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap
src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap
src/shell/zsh.rs

only add rtx to PATH if it is not already on it

---

.github/workflows/rtx.yml
README.md
src/cli/alias/ls.rs
src/cli/local.rs
src/cli/mod.rs
src/cli/render_help.rs
src/cli/settings/get.rs
src/cli/settings/ls.rs
src/cli/settings/mod.rs
src/cli/settings/set.rs
src/cli/settings/snapshots/rtx__cli__settings__ls__test__settings_ls.snap
src/cli/settings/snapshots/rtx__cli__settings__set__test__settings_set-2.snap
src/cli/settings/snapshots/rtx__cli__settings__set__test__settings_set.snap
src/cli/settings/unset.rs
src/config/config_file/rtxrc.rs
src/config/mod.rs
src/config/settings.rs
src/test.rs

A few things got commingled together here:
* added `rtx settings ls|get|set|unset` commands (I want to do the same for aliases, this is a good thing to contribute if someone wants to help out)
* Documented legacy version file in readme
* Changed legacy version file parsing to default to true (this is a breaking change)

settings management

---

Cargo.toml

unfortunately I don't have a way to verify this works without publishing a release. So we'll see if this actually works.

[chore] fix cargo-binstall config

---

scripts/release.sh

I want to make a script for updating the aur repo and this will make that easy

[chore] add VERSION and SHA512SUMS to releases

---

README.md
src/cli/render_help.rs
src/config/config_file/tool_versions.rs
src/config/mod.rs
src/env.rs
src/logger.rs
src/main.rs

this will help diagnosing issues since we can log to the file at trace level but not litter the screen

[feat] added RTX_LOG_FILE_LEVEL

---

CONTRIBUTING.md
justfile
src/cli/snapshots/rtx__cli__activate__test__activate_zsh_legacy.snap
src/cli/snapshots/rtx__cli__deactivate__test__deactivate_zsh_legacy.snap

Also made `just test-update-snapshots` delete
snapshots that are no longer used.

[chore] document justfile

---

Cargo.toml

chore: set debug=0 for release

---

README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
e2e/cd/test_bash
e2e/cd/test_bash_legacy_activate
e2e/cd/test_zsh
e2e/direnv/no_tool_versions/test_direnv
e2e/direnv/system_version/test_direnv_system_version
src/cli/activate.rs
src/cli/hook_env.rs
src/hook_env.rs
src/shell/bash.rs
src/shell/fish.rs
src/shell/mod.rs
src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap
src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap
src/shell/snapshots/rtx__shell__xonsh__tests__hook_init.snap
src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap
src/shell/xonsh.rs
src/shell/zsh.rs

This changes the behavior of activate to default to not displaying the status line.
Fixes #154

feat: added `rtx activate --status`

---

README.md
completions/_rtx
completions/rtx.bash
src/cli/ls_remote.rs
src/cli/mod.rs
src/cli/plugins/ls_remote.rs
src/cli/snapshots/rtx__cli__ls_remote__tests__list_remote.snap
src/cli/snapshots/rtx__cli__ls_remote__tests__ls_remote_prefix-2.snap
src/cli/snapshots/rtx__cli__ls_remote__tests__ls_remote_prefix.snap

feat: `rtx ls-remote` prefix support

---

.tool-versions
e2e/.e2e-tool-versions
e2e/test_local
src/cli/local.rs
src/cli/snapshots/rtx__cli__global__tests__global-4.snap
src/cli/snapshots/rtx__cli__local__tests__local_multiple_versions.snap
src/cli/snapshots/rtx__cli__local__tests__local_remove-2.snap
src/cli/snapshots/rtx__cli__local__tests__local_remove-3.snap
src/cli/snapshots/rtx__cli__local__tests__local_remove.snap
src/config/config_file/tool_versions.rs
test/.test-tool-versions

feat: add padding to .tool-versions output

---

Cargo.lock
Cargo.toml
completions/_rtx
src/toolset/tool_version_list.rs
test/data/plugins/dummy/bin/list-all

something this was hit and sometimes not during coverage making it misleading to read the codecov reports on PRs. Now we'll hit it every time.

test: added test for tool_version resolve failure

---

README.md
completions/_rtx
completions/rtx.bash
e2e/test_shims
src/cli/asdf.rs
src/cli/exec.rs
src/cli/reshim.rs
src/fake_asdf.rs

plugins like nodejs call `asdf reshim` after installing packages with `npm i -g`. This should make that work.

bug: enable reshims in fake-asdf

---

src/cli/deactivate.rs
src/cli/hook_env.rs
src/cli/snapshots/rtx__cli__activate__tests__activate_zsh.snap
src/cli/snapshots/rtx__cli__activate__tests__activate_zsh_legacy.snap
src/cli/snapshots/rtx__cli__deactivate__tests__deactivate-2.snap
src/cli/version.rs
src/hook_env.rs
src/shell/bash.rs
src/shell/fish.rs
src/shell/mod.rs
src/shell/snapshots/rtx__shell__bash__tests__deactivate.snap
src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap
src/shell/snapshots/rtx__shell__fish__tests__deactivate.snap
src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap
src/shell/snapshots/rtx__shell__xonsh__tests__xonsh_deactivate.snap
src/shell/snapshots/rtx__shell__zsh__tests__deactivate.snap
src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap
src/shell/xonsh.rs
src/shell/zsh.rs

before this would only reset PATH

bug: clear exec-env vars in deactivate

---

src/config/settings.rs
src/env.rs

chore: added RTX_EXPERIMENTAL env var

---

README.md
completions/_rtx
completions/rtx.fish
e2e/.gitignore
e2e/cd/test_bash
e2e/cd/test_fish
e2e/cd/test_zsh
e2e/test_doctor
src/cli/current.rs
src/cli/exec.rs
src/cli/global.rs
src/cli/install.rs
src/cli/local.rs
src/cli/plugins/install.rs
src/cli/plugins/ls.rs
src/cli/plugins/ls_remote.rs
src/cli/render_help.rs
src/cli/reshim.rs
src/cli/snapshots/rtx__cli__activate__tests__activate_zsh.snap
src/cli/snapshots/rtx__cli__activate__tests__activate_zsh_legacy.snap
src/cli/where.rs
src/fake_asdf.rs
src/shell/bash.rs
src/shell/fish.rs
src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap
src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap
src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap
src/shell/zsh.rs

Prevent reshim loop

---

completions/_rtx
completions/rtx.bash
completions/rtx.fish
e2e/.e2e.rtx.toml
e2e/cd/test_bash
e2e/test_local
e2e/test_lua
man/man1/rtx.1
src/cli/args/install_missing.rs
src/cli/args/mod.rs
src/cli/mod.rs
src/plugins/script_manager.rs

added --install-missing flag

---

src/config/mod.rs
src/runtimes.rs
src/toolset/mod.rs
src/toolset/tool_version.rs

needed for https://github.com/jdxcode/rtx-python/pull/3

feat: added RTX_PROJECT_ROOT

---

.github/workflows/test-plugins.yml
src/plugins/script_manager.rs

this fixes plugin install failures in 1.22.0

bug: wait for threads to finish

---

.github/workflows/rtx.yml
.github/workflows/test-plugins.yml
src/plugins/script_manager.rs

I believe with how the code was before a race condition might cause some output to be truncated

bug: fix potential race condition in script execution

---

README.md
e2e/test_zigmod
src/cli/install.rs
src/cli/latest.rs
src/plugins/mod.rs
src/plugins/script_manager.rs
src/toolset/tool_version.rs

feat: support bin/latest-stable

---

src/shims.rs
src/toolset/mod.rs

display better error message when shim has no active version

---

src/cli/doctor.rs

added plugin url + sha to `rtx doctor` output

---

e2e/test_log_level
man/man1/rtx.1
src/cli/args/log_level.rs
src/cli/mod.rs
src/env.rs

feat: added --log-level option

---

e2e/test_bang
src/toolset/tool_version.rs

bug: fix latest!-1

---

README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
e2e/test_exec
src/cli/exec.rs
src/shims.rs

feat: added `rtx x --cd` option

---

e2e/test_local
src/cli/local.rs

bug: install missing runtimes on `rtx global/local

---

.env
.rtx.toml
Cargo.lock
Cargo.toml
README.md
e2e/.e2e.rtx.toml
e2e/.test-env
e2e/test_env
e2e/test_local
src/config/config_file/rtx_toml.rs

feat: dotenv support

---

.rtx.toml
Cargo.lock
Cargo.toml
README.md
src/config/config_file/rtx_toml.rs
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_plugin.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__replace_versions.snap

feat: env var templating

---

src/config/mod.rs

this makes it so parsing errors show up when not in debug

chore: make toml parsing errors more visible

---

.github/workflows/rtx.yml
Cargo.lock
Cargo.toml
build.rs
justfile
src/build_time.rs
src/cli/doctor.rs
src/cli/version.rs
src/snapshots/rtx__build_time__tests__render_outdated_message.snap

also added build info to `rtx doctor`

added git commit to `rtx -v`

---

README.md
src/cli/local.rs
src/cli/settings/snapshots/rtx__cli__settings__ls__tests__settings_ls.snap
src/cli/settings/snapshots/rtx__cli__settings__set__tests__settings_set.snap
src/cli/settings/unset.rs
src/config/config_file/mod.rs
src/config/config_file/rtx_toml.rs
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-2.snap
src/config/config_file/tool_versions.rs
src/config/mod.rs
src/config/settings.rs
src/env.rs
src/file.rs

feat: added RTX_TRUSTED_CONFIG_PATHS setting

---

src/plugins/mod.rs
src/plugins/rtx_plugin_toml.rs
src/plugins/snapshots/rtx__plugins__rtx_plugin_toml__tests__fixture.snap

enables https://github.com/rtx-plugins/rtx-nodejs/pull/2

use rtx.plugin.toml for aliases/legacy-filenames

---

src/cli/version.rs

reproduced the issue with:
rtx cache clean && RTX_TRACE=1 rtx -v
and running the link conditioner with 100% loss
Fixes #394

bug: fix timeout on version check

---

src/cli/hook_env.rs

bug: fix path_env for activate

---

src/cli/install.rs
src/config/config_file/mod.rs
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-4.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_plugin.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__replace_versions.snap
src/plugins/mod.rs
src/toolset/builder.rs
src/toolset/mod.rs
src/toolset/tool_version.rs
src/toolset/tool_version_list.rs

use most recent install for @latest and other aliases

---

src/cli/hook_env.rs
src/config/config_file/legacy_version.rs
src/config/config_file/mod.rs
src/config/config_file/rtx_toml.rs
src/config/config_file/tool_versions.rs
src/config/mod.rs
src/hook_env.rs

watch for changes on dotenv file change

---

Cargo.lock
Cargo.toml
src/cli/exec.rs
src/test.rs

these were incompatible with debian

removed unneeded crates

---

src/cli/current.rs
src/cli/doctor.rs
src/cli/install.rs
src/cli/plugins/ls_remote.rs
src/cli/plugins/uninstall.rs
src/cli/plugins/update.rs
src/config/mod.rs
src/plugins/external_plugin.rs
src/plugins/mod.rs
src/toolset/mod.rs

this code is specific to external plugins and not for core plugins

move external plugin-specific functionality

---

src/cli/local.rs

only prompt for missing tools once on local/global

---

.github/workflows/rtx.yml
README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
src/cli/doctor.rs
src/cli/ls_remote.rs
src/cli/plugins/ls.rs
src/cli/plugins/mod.rs
src/cmd.rs
src/config/mod.rs
src/env.rs
src/plugins/core/mod.rs
src/plugins/core/python.rs
src/plugins/external_plugin.rs
src/plugins/mod.rs
src/plugins/script_manager.rs
src/tool.rs

adds python as a core plugin built in rust

core plugin: python

---

.rtx.dev.toml
.rtx.local.toml
README.md
src/config/mod.rs
src/env.rs
src/file.rs

feat: added config environments

---

src/cli/exec.rs
src/cli/global.rs
src/cli/install.rs
src/cli/local.rs
src/cli/mod.rs
src/cli/plugins/uninstall.rs
src/cli/shell.rs
src/cli/uninstall.rs
src/cli/version.rs
src/cmd.rs
src/config/mod.rs
src/env.rs
src/http.rs
src/lib.rs
src/main.rs
src/plugins/core/python.rs
src/plugins/external_plugin.rs
src/plugins/mod.rs
src/plugins/script_manager.rs
src/ui/multi_progress_report.rs
src/ui/progress_report.rs

- feat: added config environments
- patch support for python core plugin

python patches

---

.github/workflows/rtx.yml
.rtx.toml
README.md
docs/python.md
src/cmd.rs
src/config/mod.rs
src/env.rs
src/plugins/core/python.rs
src/plugins/script_manager.rs

this also enables the core plugin if experimental mode is on since it is the last feature to hit parity with the bash plugin

python core plugin venv support

---

README.md
e2e/test_uninstall
justfile
src/cli/ls.rs
src/cli/uninstall.rs

this was not working if you did not specify the version

bug: fix bug with uninstalling

---

src/plugins/core/python.rs

this parses it as a requirements.txt file instead
Fixes #469

allow comments in python default packages file

---

src/env.rs
src/file.rs

replace ~/ with $HOME/ for env var paths

---

src/shell/nushell.rs
src/shell/snapshots/rtx__shell__nushell__tests__hook_init.snap

simple fix that addresses #470.

fixes bug/typo

---

src/shell/nushell.rs
src/shell/snapshots/rtx__shell__nushell__tests__hook_init.snap

simple fix that addresses #471

fixes nushell unsupporte closures bug #471

---

src/config/config_file/legacy_version.rs
src/toolset/builder.rs

support multiple versions in legacy files and env vars

---

src/cli/alias/snapshots/rtx__cli__alias__set__tests__alias_set.snap
src/cli/alias/snapshots/rtx__cli__alias__unset__tests__alias_unset.snap
src/config/mod.rs
src/plugins/core/nodejs.rs

added node -> nodejs "alias" for core plugin

node alias

---

src/plugins/core/assets/nodejs_npm_shim
src/plugins/core/nodejs.rs

this will make `npm i -g` automatically reshim
https://github.com/rtx-plugins/rtx-nodejs/issues/6

added npm shim

---

src/config/mod.rs
src/env_diff.rs
src/fake_asdf.rs
src/file.rs
src/shims.rs

make `rtx env` work in a clean environment

---

README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
src/cli/env.rs
src/cli/ls.rs
src/cli/snapshots/rtx__cli__env__tests__env_json.snap

added --json flag for `rtx env`

---

src/cli/ls.rs

Fixes a bug that showed tools that were not installed or specified.
Also fixes a panic with rendering

bug fixes with `rtx ls`

---

README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
src/cli/snapshots/rtx__cli__which__tests__which_tool.snap
src/cli/which.rs
src/plugins/script_manager.rs

added --tool flag to `rtx which`

---

src/config/config_file/rtx_toml.rs
src/env_diff.rs
src/plugins/script_manager.rs
src/toolset/tool_version_list.rs
test/data/plugins/dummy/bin/latest-stable

- added --tool flag to `rtx which`
- add some test coverage to fix flaky coverage count

test coverage

---

src/cli/install.rs
src/cli/local.rs
src/cli/ls_remote.rs
src/cli/plugins/install.rs
src/cli/plugins/uninstall.rs
src/cli/prune.rs
src/cli/uninstall.rs
src/cli/upgrade.rs
src/config/config_file/mod.rs
src/config/mod.rs
src/config/settings.rs
src/plugins/core/python.rs
src/toolset/builder.rs
src/ui/progress_report.rs

This was done to show the plain progress report

do not automatically enable verbose if not tty

---

Cargo.toml

update msrv to rust 1.65.0

---

src/config/mod.rs
src/file.rs

display_path was not working correctly if HOME was "/"

fix debug output

---

scripts/release-aur-bin.sh
scripts/release-aur.sh

Nice that you generate them as files, nicer still if we can get them added to the package!

Completions for aur/aur-bin and man pages for aur releases.

---

scripts/update-shorthand-repo.sh

- add plugin name to legacy file cache
- set golang source

set golang repo to rtx-golang

---

src/plugins/external_plugin.rs

add plugin name to legacy file cache

---

src/logger.rs

show target always. Show thread/location if level is set to trace for all levels

improve logging output

---

README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
src/cli/ls.rs
src/cli/snapshots/rtx__cli__ls__tests__ls_missing.snap

added --missing flag to ls

---

src/toolset/mod.rs

added install command to "Tool not installed" warning

---

src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-4.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_plugin.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__replace_versions.snap
src/toolset/builder.rs
src/toolset/mod.rs

fix bug with RTX_DISABLE_TOOLS

---

src/config/config_file/legacy_version.rs
src/config/mod.rs

allow multiple plugins to use the same legacy filename

---

src/plugins/core/ruby.rs

skip parsing gemfile when not parseable

---

src/env.rs
src/plugins/core/python.rs

https://github.com/jdxcode/rtx/discussions/677

add envs for rtx python core plugin

---

docs/node.md
src/env.rs
src/plugins/core/node.rs

https://github.com/jdxcode/rtx/discussions/677

add envs for rtx node core plugin

---

src/config/config_file/tool_versions.rs
src/env_diff.rs

See https://github.com/jdxcode/rtx/pull/664#issuecomment-1639576230

save unaliased name back to .tool-versions

---

README.md
packaging/standalone/install.envsubst
src/cli/activate.rs

Unsurprisingly, I'm noticing people getting stuck here—even from very experienced engineers. Hopefully this improves things a bit.
https://github.com/jdxcode/rtx/discussions/703

clarify activate instructions a bit

---

src/cli/doctor.rs

add rtx data directory information to `rtx doctor`

add rtx_data_dir info to rtx doctor

---

e2e/ruby/test_ruby_install
src/cli/asdf.rs
src/cli/install.rs
src/cli/use.rs
src/config/config_file/mod.rs
src/test.rs
src/tool.rs
src/toolset/mod.rs
src/toolset/tool_version.rs

this is mostly a refactor but it happens to fix #688

refactor version installs

---

README.md
e2e/test_java
src/plugins/core/java.rs

References https://github.com/halcyon/asdf-java/issues/183

added support for .java-version and .sdkmanrc legacy files

---

src/plugins/core/go.rs

fix RTX-GO-SKIP-CHECKSUM

---

src/shims.rs

fix symlink shims

---

src/shims.rs

This makes it only add/remove changed shims rather than rebuilding it every time

refactor reshim logic

---

src/runtime_symlinks.rs

This modifies the logic to only remove existing symlinks if they conflict rather than rebuild all of them every time

refactor symlink rebuilds

---

src/config/config_file/rtx_toml.rs

require trusted config for [plugins] section

---

Cargo.toml

default to openssl unless building for alpine

---

README.md
src/plugins/core/bun.rs
src/plugins/core/deno.rs
src/plugins/core/go.rs
src/plugins/core/java.rs
src/plugins/core/node.rs
src/plugins/core/python.rs
src/plugins/core/ruby.rs
src/tool.rs

This just cleans up install output a bit

show version check command

---

src/plugins/core/node.rs

added node lts/* alias

---

src/shell/bash.rs
src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap
src/shell/snapshots/rtx__shell__bash__tests__hook_init_nix.snap

Remove unnecessary use of a regex, match stricter.

Improve bash _rtx_hook PROMPT_COMMAND insertion

---

src/git.rs

reuse existing branch on plugin-update

---

e2e/test_go

this one is failing for some reason it seems

use a different sample go package

---

src/shims.rs

in the event that a not-installed tool version was selected rtx
was complaining no global version selected which was not the case
This fixes that by displaying all of the tools with shim names that match

improve shim error message

---

src/cli/implode.rs
src/cli/prune.rs

confirmation message for implode and prune

---

.rtx.toml
e2e/test_go
src/plugins/core/go.rs

Sadly, I cannot remember why I added this assertion in the first place.
Fixes #787

fix prefix: scope for golang

---

src/runtime_symlinks.rs

fix versioning for raku plugin

---

src/env.rs
src/plugins/core/java.rs
src/plugins/core/mod.rs
src/plugins/external_plugin.rs

Since this does not get run often now, I think hourly is more reasonable

set fetch remove versions cache to hourly

---

src/cli/local.rs
src/cli/snapshots/rtx__cli__global__tests__global-2.snap
src/cli/snapshots/rtx__cli__global__tests__global-3.snap
src/cli/snapshots/rtx__cli__global__tests__global-4.snap
src/cli/snapshots/rtx__cli__global__tests__global.snap
src/cli/snapshots/rtx__cli__local__tests__local_multiple_versions-2.snap
src/cli/snapshots/rtx__cli__local__tests__local_remove-2.snap
src/cli/snapshots/rtx__cli__local__tests__local_remove-3.snap
src/cli/snapshots/rtx__cli__local__tests__local_remove.snap

this matches installation output better

tweak output of `rtx use` status

---

docs/python.md

update python doc

---

src/cache.rs
src/cli/link.rs
src/cli/plugins/link.rs
src/cli/version.rs
src/config/config_file/mod.rs
src/fake_asdf.rs
src/file.rs
src/migrate.rs
src/plugins/core/bun.rs
src/plugins/core/deno.rs
src/plugins/core/java.rs
src/plugins/external_plugin.rs
src/tool.rs

- show trace output when renaming
- show trace output when renaming and doing create_dir_all

show trace logs when performing rename/create_dir_all

---

docs/python.md

Thought it'd be easier to create a PR over issue.

fix node typo

---

README.md

fixes the documentation link for [tera](https://github.com/Keats/tera)

fix(readme): documentation

---

default.nix

fix(build): Fix Darwin build

---

src/cli/implode.rs
src/cli/prune.rs

implode|prune: support --yes

---

src/tool.rs

do not fail when regex version parsing fails

---

src/git.rs

This avoids permission failures if the user that created the
git repo is not the same as the current user

set safe.directory when using git

---

src/config/config_file/mod.rs
src/migrate.rs

I have had trouble deciding where to put this but I realized config is not a great place since it cannot really be shared on multiple machines

trusted-configs: move directory to data

---

Cargo.lock
Cargo.toml
README.md
docs/node.md
src/env.rs

Fixes https://github.com/jdx/rtx/issues/719

added RTX_ALL_FORCE_COMPILE config

---

src/cli/upgrade.rs

If a version was completely missing it would install, then uninstall it

upgrade: fix bug with missing versions

---

.github/workflows/rtx.yml
Cargo.toml
src/timeout.rs

also updated msrv to clap minimum and verification of msrv in CI

fix compatibility with rust 1.70.0

---

src/plugins/external_plugin.rs

fix deadlock

---

README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
src/cli/ls_remote.rs
src/shell/completions/fish_complete.rs

this improves the performance of the fish completer a ton

ls-remote: added `--all` flag

---

src/plugins/core/mod.rs

node: use non-node-build plugin by default

---

src/plugins/core/node.rs

this is only a slight performance increase but I plan to use this for all of the plugins and it should speed up fetching for sure. This has become an issue for fish shell completion which needs to fetch all versions of all plugins.

node: use metadata.rtx.pub for version fetching

---

src/env.rs
src/plugins/core/bun.rs
src/plugins/core/deno.rs
src/plugins/core/go.rs
src/plugins/core/java.rs
src/plugins/core/mod.rs
src/plugins/core/node.rs
src/plugins/core/node_build.rs
src/plugins/core/python.rs
src/plugins/core/ruby.rs
src/plugins/external_plugin.rs

added RTX_USE_VERSIONS_HOST

---

completions/_rtx
completions/rtx.fish
src/cli/uninstall.rs
src/shell/completions/fish_complete.rs
src/shell/completions/zsh_complete.rs

completions: improve completions for ls-remote and uninstall

---

completions/rtx.fish
src/shell/completions/fish_complete.rs

completions: improve fish tool completions

---

README.md
completions/_rtx
completions/rtx.bash
completions/rtx.fish
src/cli/settings/get.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/shell/completions/fish_complete.rs
src/shell/completions/zsh_complete.rs

completions: complete setting names

---

Cargo.lock
Cargo.toml
src/file.rs

zip: do not require "unzip" utility to unzip archives

---

src/ui/progress_report.rs

fix indicatif progress bars in dev mode

---

src/plugins/core/java.rs

java: disable rtx-versions

---

src/config/settings.rs
src/plugins/core/python.rs

Fixes #1199, happy for this to be modified/closed if it's not the correct solution :+1:.

Change warning for rtx config set experimental

---

e2e/cd/test_bash
src/cli/bin_paths.rs
src/cli/direnv/snapshots/rtx__cli__direnv__envrc__tests__direnv_envrc.snap
src/cli/env.rs
src/cli/snapshots/rtx__cli__env__tests__env_json.snap
src/cli/snapshots/rtx__cli__local__tests__local_multiple_versions-3.snap
src/plugins/external_plugin.rs
src/plugins/external_plugin_cache.rs

export short paths

---

e2e/test_use
src/cli/env.rs
src/cli/exec.rs
src/cli/install.rs
src/cli/shell.rs
src/cli/upgrade.rs
src/cli/use.rs
src/config/config_file/mod.rs
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-4.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_plugin.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__replace_versions.snap
src/toolset/builder.rs
src/toolset/mod.rs

use: fix calling with no version set

---

e2e/run_test
src/cli/implode.rs
src/cli/version.rs
src/config/config_file/mod.rs
src/config/tracking.rs
src/dirs.rs
src/env.rs
src/file.rs
src/hook_env.rs
src/migrate.rs
src/plugins/external_plugin_cache.rs
src/test.rs
test/.gitignore

Used for tracked configs and trusted configs
Fixes #1218

use XDG_STATE_HOME

---

README.md
src/dirs.rs
src/env.rs

make system directory configurable

---

src/cli/bin_paths.rs
src/cli/env.rs
src/cli/exec.rs
src/cli/hook_env.rs
src/cli/outdated.rs
src/cli/shell.rs
src/cli/upgrade.rs
src/toolset/mod.rs

Disable by setting RTX_DISABLE_PLUGINS or running with --quiet

show missing version message on more commands

---

src/cli/mod.rs
src/cli/version.rs
src/main.rs
src/output.rs
src/shims.rs

shims: do not assume something is a shim

---

src/cli/hook_env.rs
src/config/mod.rs

This is no longer needed in the config object

hook-env: move exit-early logic into function

---

README.md
completions/_rtx
completions/rtx.bash
src/cli/hook_env.rs
src/cli/hook_not_found.rs
src/cli/mod.rs
src/cli/settings/snapshots/rtx__cli__settings__ls__tests__settings_ls.snap
src/cli/settings/snapshots/rtx__cli__settings__set__tests__settings_set.snap
src/cli/settings/unset.rs
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__env-5.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-2.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__fixture-6.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__path_dirs-5.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_alias-4.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__remove_plugin-4.snap
src/config/config_file/snapshots/rtx__config__config_file__rtx_toml__tests__replace_versions-4.snap
src/config/settings.rs
src/shell/bash.rs
src/shell/fish.rs
src/shell/snapshots/rtx__shell__bash__tests__hook_init.snap
src/shell/snapshots/rtx__shell__bash__tests__hook_init_nix.snap
src/shell/snapshots/rtx__shell__fish__tests__hook_init.snap
src/shell/snapshots/rtx__shell__fish__tests__hook_init_nix.snap
src/shell/snapshots/rtx__shell__zsh__tests__hook_init.snap
src/shell/snapshots/rtx__shell__zsh__tests__hook_init_nix.snap
src/shell/zsh.rs
src/shims.rs
src/toolset/mod.rs

not-found handler

---

scripts/update-shorthand-repo.sh
src/cli/plugins/install.rs
src/default_shorthands.rs
src/plugins/external_plugin.rs

see https://github.com/rtx-plugins for more on how this works

plugins: add support for "trusted" plugins

---

src/cli/run.rs

task: read RTX_TASK_OUTPUT as lowercase

---

docs/cli-reference.md
src/cli/use.rs

use: fix MISE_ASDF_COMPAT=1

---

src/logger.rs

logging: prevent loading multiple times

---

src/config/mod.rs

fixed config load order

---

src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__env-5.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__fixture-2.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__fixture-6.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__path_dirs-5.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__remove_alias-4.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__remove_plugin-4.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__replace_versions-4.snap
src/config/settings.rs
src/plugins/external_plugin.rs

added paranoid setting

---

e2e/test_shims

found while testing in the dev container

add path separator

---

src/http.rs

handle 404s

---

e2e/.gitignore
e2e/test_python
src/path_env.rs
src/toolset/mod.rs

Correct PATH for python venvs

---

.idea/inspectionProfiles/Project_Default.xml
src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/settings.rs
src/env.rs
src/plugins/core/python.rs

python: fix some precompiled issues

---

completions/mise.bash
completions/mise.fish
src/cli/task/deps.rs

@jdx Forgot to add the completions for the new `task deps` command 🙄

feat: add completions for task deps command

---

src/config/mod.rs

Fix/followup to #1462. Global/system configuration is not ignored anymore if `current_dir` fails.

fix: always load global configs

---

.idea/mise.iml
src/env.rs
src/plugins/script_manager.rs

rename internal MISE_BIN env var to __MISE_BIN

---

.mise/tasks/filetask
src/cli/task/edit.rs
src/config/config_file/toml.rs
src/config/mod.rs
src/task.rs

allow using templates in task files

---

.mise.local.toml
src/config/config_file/mise_toml.rs

tasks: support array of commands directly

---

e2e/test_go_install
src/plugins/external_plugin.rs

* only call it if the plugin was actually updated
* set the ASDF_PLUGIN_PREV_REF and ASDF_PLUGIN_POST_REF env vars

plugins: improve post-plugin-update script

---

src/plugins/core/bun.rs
src/plugins/core/python.rs

bun|python: use target_feature to use correct precompiled runtimes

---

src/config/config_file/mod.rs

config: do not follow symbolic links for trusted paths

---

.idea/mise.iml
Cargo.lock
Cargo.toml
src/cli/doctor.rs
src/cli/render_mangen.rs
src/cli/version.rs
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__env-3.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__env-5.snap
src/config/mod.rs
src/http.rs

starting to move logic out of parsing

config: refactor min_version logic

---

src/forge/mod.rs
src/plugins/core/deno.rs
src/plugins/core/go.rs
src/plugins/core/java.rs
src/plugins/core/python.rs
src/plugins/core/ruby.rs
src/plugins/external_plugin.rs
src/plugins/external_plugin_cache.rs

Better than randomized with HashMap

env: sort env vars coming back from exec-env

---

.mise.toml
Cargo.lock
Cargo.toml
src/cli/run.rs
src/cli/upgrade.rs
src/cmd.rs
src/ui/ctrlc.rs
src/ui/mod.rs
src/ui/progress_report.rs
src/ui/prompt.rs
test/fixtures/signal-test.js

this change forwards any signals mise receives to underlying tasks

pass signals to tasks

---

.shellcheckrc
e2e/test_global
src/cli/global.rs
src/config/settings.rs
src/task.rs
src/toolset/mod.rs

fix global config with asdf_compat

---

man/man1/mise.1
src/config/settings.rs

read system and local config settings

---

.mise.toml
e2e/test_bin_paths
e2e/test_go
justfile
src/plugins/core/deno.rs
src/plugins/core/go.rs
src/toolset/mod.rs

hide system versions from env/bin_paths

---

man/man1/mise.1
src/shell/bash.rs
src/shell/snapshots/mise__shell__bash__tests__activate.snap

fix bash command not found override

---

src/task.rs

fix(tasks): prevent dependency cycles

---

schema/mise.json

add to schema
- env.mise.source

add env.mise.source to schame

---

src/hash.rs
src/http.rs
src/plugins/core/bun.rs
src/plugins/core/deno.rs
src/plugins/core/erlang.rs
src/plugins/core/go.rs
src/plugins/core/java.rs
src/plugins/core/node.rs
src/plugins/core/python.rs
src/ui/progress_report.rs

download progress bars

---

.mise/config.toml
src/toolset/mod.rs

https://github.com/mise-plugins/mise-poetry/issues/7

install tools in order listed in config file when --jobs=1

---

src/config/mod.rs
src/config/settings.rs

env-file: add dotenv paths to watch files

---

src/http.rs

on my current hotel internet http does not work

automatically try https if http fails

---

.idea/inspectionProfiles/Project_Default.xml
src/cli/run.rs
src/cli/tasks/deps.rs
src/cli/tasks/edit.rs
src/cli/tasks/ls.rs
src/config/mod.rs
src/file.rs
src/task.rs

Fixes #1593
This also makes it possible to have tasks in directories without a config file.

tasks: fix loading precedence

---

src/config/mod.rs

also general refactoring and hardening around task loading
Fixes #1640

tasks: ignore non-executable tasks

---

e2e/test_env
e2e/test_python
src/config/config_file/mise_toml.rs

fix support for tera templates in tool version strings

---

.mise.toml
e2e/gopath/test_gopath
e2e/test_go
e2e/test_go_install
src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/settings.rs
src/env.rs
src/forge/go.rs
src/plugins/core/go.rs
src/ui/ctrlc.rs

See https://github.com/jdx/mise/discussions/1638

go: GOROOT/GOBIN/GOPATH changes

---

.devcontainer/devcontainer.json
src/shell/fish.rs
src/shell/snapshots/mise__shell__fish__tests__activate.snap

fish command_not_found handler fix

---

README.md

Fixes https://github.com/jdx/mise/actions/runs/7996273619/job/21838430877

docs: add missing alt text

---

schema/mise.json

Add `hide=true` to schema as requested in #1731.  Also see https://github.com/jdx/mise-docs/pull/43

fix(task): document task.hide

---

src/config/mod.rs

Fix https://github.com/jdx/mise/issues/1769

fix: watch env._.source files

---

src/forge/npm.rs

Attempts to fix #1740 by overriding `Forge::latest_stable_version` and using `npm view <pkg> dist-tags --json` to fetch and cache the latest version tag or fall back to old behaviour using the largest/last version.

fix(npm): mise use -g npm:yarn@latest installs wrong version

---

src/config/mod.rs

Attempts to fix #1715. Tasks are currently only loaded from project and global config locations but not from the system config location.

fix(task): tasks not working in system config

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
docs/cli-reference.md
man/man1/mise.1
mise.usage.kdl
packaging/rpm/mise.spec
src/default_shorthands.rs

- **(task)** tasks not working in system config (#1803) - [d5df98c](https://github.com/jdx/mise/commit/d5df98cd0b05a5bc0f0cb1cb83883138f56a109d) - [@roele](https://github.com/roele)
- **(xonsh)** `shell` subcommand for xonsh (#1801) - [9153411](https://github.com/jdx/mise/commit/9153411b1e8a5bff8de4f71dda5656e297d4b79e) - [@yggdr](https://github.com/yggdr)
- jq Installed Using x86_64 on Apple Silicon using mise (#1804) - [2ea978d](https://github.com/jdx/mise/commit/2ea978d0f16ae06fa0749dcbee837662dc0484e6) - [@roele](https://github.com/roele)
- **(changelog)** improve styling - [403033d](https://github.com/jdx/mise/commit/403033d269f88aa0c1e571e5613231eca84fbaac) - [@jdx](https://github.com/jdx)
- **(changelog)** improve styling - …

Release 2024.3.7

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec
src/cli/args/cd_arg.rs
src/default_shorthands.rs

---
- use correct type for --cd by [@jdx](https://github.com/jdx) in [cf4f03e](https://github.com/jdx/mise/commit/cf4f03ed0145c5678e1ecbdb98c4426c9428d29a)
- completions command by [@jdx](https://github.com/jdx) in [#1838](https://github.com/jdx/mise/pull/1838)
- improve CHANGELOG by [@jdx](https://github.com/jdx) in [#1839](https://github.com/jdx/mise/pull/1839)
- improve CHANGELOG by [@jdx](https://github.com/jdx) in [#1841](https://github.com/jdx/mise/pull/1841)
- remove duplicate PR labels in CHANGELOG by [@jdx](https://github.com/jdx) in [a3b27ef](https://github.com/jdx/mise/commit/a3b27efc37191f8be106345586cab08055ea476f)

Release 2024.3.10

---

src/plugins/core/python.rs

chore(python): added debug info when no precompiled version is found

---

src/plugins/core/bun.rs
src/plugins/core/deno.rs
src/plugins/core/java.rs
src/plugins/core/ruby.rs

fix: mise panics if prefix: is used on certain core plugins

---

src/cli/args/forge_arg.rs
src/forge/mod.rs

feat: add option to list installed (backend) binaries

---

src/cli/doctor.rs

Adding a `doctor` check to warn if a plugin overrides a core plugin. Overridden plugins might lead to issues if the used (external) plugin is no longer maintained for example or if the plugin is a migration left over from an earlier mise/rtx version.
Resolves #1876.

feat(doctor): warn if a plugin overwrites a core plugin

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- **(zig)** make zig core plugin experimental by [@jdx](https://github.com/jdx) in [45274bc](https://github.com/jdx/mise/commit/45274bc1415ac5dc307a82a93db952a1cf811210)

chore: release 2024.4.7

---

src/plugins/core/java.rs

Fixes #1887 by not matching minor/patch versions while fuzzy matching when the query version is a major version (e.g `openjdk-17`)
**Incorrect version resolution with command `use`**
When "using" a major version after a patch version has been installed, the patch version is set in `.mise.toml`.
```bash
❯ mise use java@sapmachine-17.0.11
mise java@sapmachine-17.0.11 ✓ installed
mise ~/foo/.mise.toml tools: java@sapmachine-17.0.11
❯ mise use java@sapmachine-17
mise ~/foo/.mise.toml tools: java@sapmachine-17.0.11
```
After the fix the missing tool is downloaded properly and set in the `.mise.toml`
```bash
❯ mise use java@sapmachine-17.0.11
mise java@sapmachine-17.0.11 ✓ installed
mise ~/foo/.mise.toml tools: java@sapmachine-17.0.11
❯ mise use java@sapmachine-17
mise java@sapmachine-17    ✓ …
```

fix(java): inconsistent version resolution

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- **(self_update)** downgrade to fix signature verification issue by [@jdx](https://github.com/jdx) in [dbe1971](https://github.com/jdx/mise/commit/dbe1971c337a29f2e92fd1b765436e67abf7f04e)

chore: release 2024.4.12

---

src/cli/trust.rs

fix: mise trust doesn't handle relative paths

---

src/cmd.rs
src/forge/cargo.rs
src/forge/go.rs
src/forge/npm.rs
src/forge/pipx.rs
src/forge/ubi.rs
src/toolset/mod.rs

Fixes #2053 
Fixes #2046 
Fixes #2029
Fixes #2028 
Fixes #2000
Fixes #1999

fix: resolve bug with backends not resolving mise-installed tools

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec
registry/.github/workflows/semantic-pr.yml

- add cargo-binstall as dependency for cargo backend by [@jdx](https://github.com/jdx) in [94868af](https://github.com/jdx/mise/commit/94868afcca9731c43fb48670ed0d7d4f40a4fab8)
- performance fix for _.file/_.path by [@jdx](https://github.com/jdx) in [76202de](https://github.com/jdx/mise/commit/76202ded1bb47ecf9c1a5a7e6f71216aca26c68e)
- **(cargo)** improve cargo-binstall check by [@jdx](https://github.com/jdx) in [d1432e0](https://github.com/jdx/mise/commit/d1432e0316a1e1b335022372ef0896c5b5b7b0df)
- **(e2e)** fix mise path by [@jdx](https://github.com/jdx) in [f6de41a](https://github.com/jdx/mise/commit/f6de41af71e7ad03d831bf602c291f38dd6c0fd8)
- isolation of end-to-end tests by [@Adirelle](https://github.com/Adirelle) in [#2047](https://github.com/jdx/mise/pull/2047)
- simplify release …

chore: release 2024.5.6

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- add coverage report summary by [@jdx](https://github.com/jdx) in [#2065](https://github.com/jdx/mise/pull/2065)
- fix release job by [@jdx](https://github.com/jdx) in [a491270](https://github.com/jdx/mise/commit/a49127029b67d39f80708e47cfc20351faca941f)
- fix release job by [@jdx](https://github.com/jdx) in [90268db](https://github.com/jdx/mise/commit/90268dbdbb71f6e0ba51dbc657536029c2aac099)

chore: release 2024.5.7

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- use correct url for aur-bin by [@jdx](https://github.com/jdx) in [a683c15](https://github.com/jdx/mise/commit/a683c1593d3c83660a42e4e6685522edb20e0480)
- handle race condition when initializing backends with dependencies by [@jdx](https://github.com/jdx) in [#2071](https://github.com/jdx/mise/pull/2071)

chore: release 2024.5.8

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec
registry/plugins/R
registry/plugins/luaJIT
src/default_shorthands.rs

- fixed misc bugs with ubi+pipx backends by [@jdx](https://github.com/jdx) in [#2083](https://github.com/jdx/mise/pull/2083)
- updated reqwest by [@jdx](https://github.com/jdx) in [d927085](https://github.com/jdx/mise/commit/d92708585b62d65a838e37c022a3796de5fefe1d)
- update rust crate xx to v1 by [@renovate[bot]](https://github.com/renovate[bot]) in [#2081](https://github.com/jdx/mise/pull/2081)

chore: release 2024.5.10

---

Cargo.lock
Cargo.toml
src/cli/doctor.rs
src/config/mod.rs
src/file.rs
src/git.rs
src/shims.rs
src/toolset/builder.rs

turns out getting file metadata is super slow in rust (at least on my machine)

perf: various performance tweaks

---

src/plugins/core/ruby.rs

it's my first try on rust, I'm very grateful for jdx's advice.
closes #2054

feat: raise warning instead if install default gems failed

---

src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/settings.rs
src/plugins/core/python.rs

feat(python): make python_compile 3-way switch

---

src/config/mod.rs

feat: support non-hidden configs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec
src/default_shorthands.rs

- support non-hidden configs by [@jdx](https://github.com/jdx) in [#2114](https://github.com/jdx/mise/pull/2114)
- handle sub-0.1 in new resolving logic by [@jdx](https://github.com/jdx) in [fd943a1](https://github.com/jdx/mise/commit/fd943a184bcc64866b761514788b5a0e4be07ac0)
- ToolVersionRequest -> ToolRequest by [@jdx](https://github.com/jdx) in [45caece](https://github.com/jdx/mise/commit/45caece3517792b02444620edb96c18c2d7513c2)
- fail-fast by [@jdx](https://github.com/jdx) in [2338376](https://github.com/jdx/mise/commit/23383760900ede666865e073acb680dced37d8fc)
- update deno version by [@jdx](https://github.com/jdx) in [71f5480](https://github.com/jdx/mise/commit/71f5480e780953e03aa97682535a58767956a927)
- check plugin dependencies with python and pipx. by …

chore: release 2024.5.15

---

mise.usage.kdl
src/cli/tasks/ls.rs
src/cli/tasks/snapshots/mise__cli__tasks__ls__tests__task_ls_json.snap
src/cli/tasks/snapshots/mise__cli__tasks__ls__tests__task_ls_json_extended.snap

feat(tasks): add --json flag

---

docs/cli-reference.md
src/cli/args/forge_arg.rs
src/main.rs
src/registry.rs

initial registry implementation as discussed in https://github.com/jdx/mise/discussions/2122

feat(registry): map ubi -> cargo:ubi

---

src/toolset/mod.rs

Fixes #1748 by ignoring `Error:PluginNotInstalled` errors, allowing the installation process to continue with other tools.

feat: allow ignore missing plugin

---

src/cache.rs
src/forge/cargo.rs
src/forge/go.rs
src/forge/npm.rs
src/forge/pipx.rs
src/forge/ubi.rs
src/plugins/core/java.rs
src/plugins/core/mod.rs
src/plugins/core/python.rs
src/plugins/external_plugin.rs
src/plugins/external_plugin_cache.rs

fix: add target and other configs to cache key logic

---

.mise.toml
e2e/forge/test_go_install_slow
src/cli/install.rs
src/forge/go.rs

fix: handle issue running `mise install` with existing tools

---

.github/workflows/release.yml
.github/workflows/test.yml
.mise.toml
.mise/tasks/lint-fix
Cross.toml
scripts/build-tarball.ps1
scripts/build-tarball.sh
scripts/get-version.ps1
scripts/release.sh
scripts/sccache.sh
src/cli/exec.rs
src/cli/run.rs
src/cli/use.rs
src/fake_asdf_windows.rs
src/file.rs
src/main.rs

Nothing works yet, but at least cargo build runs

chore: compile on windows

---

src/forge/pipx.rs

fix(pipx): version ordering

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- use all tera features by [@jdx](https://github.com/jdx) in [48ca740](https://github.com/jdx/mise/commit/48ca74043e21fe12de18a8457e4554ac2cadb17b)
- turn asdf into a forge by [@jdx](https://github.com/jdx) in [#2219](https://github.com/jdx/mise/pull/2219)
- clean cwd in unit tests by [@jdx](https://github.com/jdx) in [#2211](https://github.com/jdx/mise/pull/2211)
- windows by [@jdx](https://github.com/jdx) in [#2216](https://github.com/jdx/mise/pull/2216)
- add reset() to more tests by [@jdx](https://github.com/jdx) in [#2217](https://github.com/jdx/mise/pull/2217)
- added reset() to more tests by [@jdx](https://github.com/jdx) in [a22c9dd](https://github.com/jdx/mise/commit/a22c9dd1f0eb8c057046e23807abe3c5352faf66)
- fix build-tarball call by [@jdx](https://github.com/jdx) in …

chore: release 2024.5.25

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec
scripts/build-tarball.sh

- normalize remote urls by [@jdx](https://github.com/jdx) in [#2221](https://github.com/jdx/mise/pull/2221)
- added reset() to more tests by [@jdx](https://github.com/jdx) in [f9f65b3](https://github.com/jdx/mise/commit/f9f65b39214c9341bf44ad694c6659b6a17fdf9c)
- remove armv6 targets by [@jdx](https://github.com/jdx) in [90752f4](https://github.com/jdx/mise/commit/90752f4f08a8ca4095fb464edd79a7aed2b07e54)

chore: release 2024.5.26

---

src/cli/settings/unset.rs

fix: settings unset does not work

---

src/cli/settings/unset.rs
src/cli/use.rs
src/config/config_file/mod.rs
src/toolset/mod.rs

fix: correct `mise use` ordering

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- download keeps failing if it takes more than 30s by [@roele](https://github.com/roele) in [#2224](https://github.com/jdx/mise/pull/2224)
- settings unset does not work by [@roele](https://github.com/roele) in [#2230](https://github.com/jdx/mise/pull/2230)
- cleaner community-developed plugin warning by [@jdx](https://github.com/jdx) in [8dcf0f3](https://github.com/jdx/mise/commit/8dcf0f3a746fcae74d944412b6f0e141ded88860)
- correct `mise use` ordering by [@jdx](https://github.com/jdx) in [#2234](https://github.com/jdx/mise/pull/2234)
- forge -> backend by [@jdx](https://github.com/jdx) in [#2227](https://github.com/jdx/mise/pull/2227)
- added reset() to more tests by [@jdx](https://github.com/jdx) in [5a6ea6a](https://github.com/jdx/mise/commit/5a6ea6afb9855827b5e6216aa20760dd45f5502f)

chore: release 2024.5.28

---

src/cli/run.rs
src/task.rs

fix: group prefix not applied for script tasks

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec
src/cli/version.rs

- allow glob patterns in task outputs and sources by [@adamdickinson](https://github.com/adamdickinson) in [#2286](https://github.com/jdx/mise/pull/2286)
* @adamdickinson made their first contribution in [#2286](https://github.com/jdx/mise/pull/2286)

chore: release 2024.6.4

---

default.nix
flake.lock

fix: Fixes nix flake build failure on Linux and macOS

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- improve error message for missing plugins by [@jdx](https://github.com/jdx) in [#2313](https://github.com/jdx/mise/pull/2313)
- Update configuration.md by [@jdx](https://github.com/jdx) in [a2f19cb](https://github.com/jdx/mise/commit/a2f19cbc655058472009d000c77d1fc8df8612fd)
- Update index.md by [@jdx](https://github.com/jdx) in [d9ef467](https://github.com/jdx/mise/commit/d9ef467ee9ef026039fa2220163f21a2214ebbfc)
- Update index.md by [@jdx](https://github.com/jdx) in [63739c8](https://github.com/jdx/mise/commit/63739c880dbfefdecab282736710d496d7e88dbc)
- bump curve25519-dalek from 4.1.2 to 4.1.3 by [@dependabot[bot]](https://github.com/dependabot[bot]) in [#2306](https://github.com/jdx/mise/pull/2306)

chore: release 2024.6.6

---

docs/dev-tools/aliases.md
docs/plugins.md
docs/templates.md
src/cli/alias/ls.rs
src/cli/alias/set.rs
src/cli/alias/unset.rs
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs
src/config/mod.rs

feat: support env vars in plugin urls

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- Use correct capitalization of GitHub by [@jahands](https://github.com/jahands) in [#2372](https://github.com/jdx/mise/pull/2372)
- loosen git2 requirements by [@jdx](https://github.com/jdx) in [#2374](https://github.com/jdx/mise/pull/2374)
* @jahands made their first contribution in [#2372](https://github.com/jdx/mise/pull/2372)

chore: release 2024.7.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- clean up global config test by [@jdx](https://github.com/jdx) in [c9f2ec5](https://github.com/jdx/mise/commit/c9f2ec514082c6b1816c52378ce5c29d24aa73cc)
- set extra alpine key by [@jdx](https://github.com/jdx) in [c6b152b](https://github.com/jdx/mise/commit/c6b152bd1864b49c392ad64becbff1b1722be52f)
- test alpine releases by [@jdx](https://github.com/jdx) in [08f7730](https://github.com/jdx/mise/commit/08f77301c772eb55cee376908f9d907e42c7fe4b)
- perform alpine at the very end by [@jdx](https://github.com/jdx) in [7c31e17](https://github.com/jdx/mise/commit/7c31e17cc6ff612298c8bdb335d86cab95c9473b)
- chmod by [@jdx](https://github.com/jdx) in [a3fe85b](https://github.com/jdx/mise/commit/a3fe85b7b71faecb220b33d6cc3b630884b4343a)
- added jq/gh to alpine docker by …

chore: release 2024.8.3

---

src/main.rs

feat: show friendly errors when not in verbose/debug mode

---

e2e/run_test
packaging/standalone/install.envsubst
tests/cli/global.rs
tests/cli/install.rs

found via `typos --hidden --format brief`

docs: fix typos again

---

Cargo.lock
Cargo.toml
src/cli/run.rs
src/cmd.rs

fix: wait for spawned tasks to die before exiting

---

.mise/tasks/.hidden-executable
.mise/tasks/.hidden/bar/baz/hidden-executable
src/config/mod.rs
src/test.rs

this makes it possible to have hidden subdirs in the tasks directory

fix: hide file tasks starting with "."

---

src/config/config_file/legacy_version.rs
src/config/config_file/mod.rs

Legacy files are not yet handled properly on `prune`. Parsing in `Config#get_tracked_config_files` returns an empty default config for legacy files.
Fixes #2438

fix: mise prune removes tool versions which are in use

---

schema/mise.json
src/cli/settings/set.rs

fix: cargo_binstall missing from set commands

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
docs/registry.md
man/man1/mise.1
packaging/rpm/mise.spec
registry/README.md
registry/plugins/aapt2
registry/plugins/arduino-cli
src/default_shorthands.rs

- python on windows by [@jdx](https://github.com/jdx) in [2d4cee2](https://github.com/jdx/mise/commit/2d4cee239f8e7d53f7be176369f6e2502f3c3032)
- hide non-working core plugins on windows by [@jdx](https://github.com/jdx) in [16a08fc](https://github.com/jdx/mise/commit/16a08fc0fa00fc8f9751f7a25cc4f5f5fc87b94d)
- windows compat by [@jdx](https://github.com/jdx) in [2084a37](https://github.com/jdx/mise/commit/2084a37436fd7f7af8958501adc7b6535f608816)
- vfox tweaks by [@jdx](https://github.com/jdx) in [c260ab2](https://github.com/jdx/mise/commit/c260ab220a31241eaca971d6ddf4046f1f57865b)
- remove windows warning by [@jdx](https://github.com/jdx) in [9be937e](https://github.com/jdx/mise/commit/9be937e15dece684c574bcccd6f66499361cb935)
- windows by [@jdx](https://github.com/jdx) in …

chore: release 2024.8.10

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- bump xx by [@jdx](https://github.com/jdx) in [9a9d3c1](https://github.com/jdx/mise/commit/9a9d3c11e46028bcea0c7ec2fee10bf5c9b1fbe6)

chore: release 2024.8.11

---

Cargo.toml
scripts/build-tarball.ps1
scripts/build-tarball.sh

I figure if we are already vending openssl we should do it here as well

fix: vendor git2 openssl

---

src/plugins/core/python.rs

Fixes https://github.com/jdx/mise/issues/2480
fat finger 🖐️

fix: python-compile setting

---

docs/dev-tools/backends/pipx.md
e2e/backend/test_pipx_uvx
schema/mise.json
src/backend/pipx.rs
src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/settings.rs

feat: add support for using uv tool (uvx) as a replacement for pipx

---

src/backend/cargo.rs
src/backend/pipx.rs
src/path_env.rs

Fixes https://github.com/jdx/mise/issues/1635

feat(cargo): allow specifying features via tool options

---

README.md

docs(readme): remove failing green color

---

src/backend/mod.rs
src/toolset/tool_request.rs

this manifested in e2e/backend/test_go_install_slow

fix: resolve issue with prefixed dependencies

---

docs/lang/zig.md

docs: Create zig.md

---

e2e/plugins/core/test_python_precompiled
src/output.rs

fix: cannot disable hints during Zsh completion

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
docs/registry.md
man/man1/mise.1
packaging/rpm/mise.spec
registry/README.md
registry/plugins/esc
src/default_shorthands.rs

- implement a few tera functions for mise toml config by [@erickguan](https://github.com/erickguan) in [#2561](https://github.com/jdx/mise/pull/2561)
- ruby ls-remote not showing alternative implementations by [@roele](https://github.com/roele) in [#2555](https://github.com/jdx/mise/pull/2555)
- cannot disable hints during Zsh completion by [@roele](https://github.com/roele) in [#2559](https://github.com/jdx/mise/pull/2559)
- Create zig.md by [@MustCodeAl](https://github.com/MustCodeAl) in [#2563](https://github.com/jdx/mise/pull/2563)

chore: release 2024.9.2

---

docs/getting-started.md

Adds -L flag to curl command otherwise won't download file.

docs: getting-started.md

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- Look for `-P` or `--profile` to get mise environment. by [@fiadliel](https://github.com/fiadliel) in [#2566](https://github.com/jdx/mise/pull/2566)
- use consistent names for tera platform information by [@jdx](https://github.com/jdx) in [#2569](https://github.com/jdx/mise/pull/2569)
- added contributors to readme by [@jdx](https://github.com/jdx) in [16cccdd](https://github.com/jdx/mise/commit/16cccdd821a2b78f6a2144ea82ea16f09cacf84f)
- pdate getting-started.md by [@fesplugas](https://github.com/fesplugas) in [#2570](https://github.com/jdx/mise/pull/2570)
* @fesplugas made their first contribution in [#2570](https://github.com/jdx/mise/pull/2570)

chore: release 2024.9.3

---

src/tera.rs

fix: fix a few tera filter error messages

---

docs/profiles.md
src/config/mod.rs

feat: support for global configuration profiles

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- change win -> windows by [@jdx](https://github.com/jdx) in [e45623c](https://github.com/jdx/mise/commit/e45623c88662a11f08db93068ac765efb3813855)

chore: release 2024.9.5

---

.github/workflows/test.yml
docs/lang/ruby.md
schema/mise.json
src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/settings.rs
src/env.rs
src/plugins/core/ruby.rs
src/plugins/core/ruby_windows.rs

fix(ruby): fixed MISE_RUBY_BUILD_OPTS

---

docs/tasks/toml-tasks.md
src/cli/run.rs
src/main.rs
src/task_parser.rs

this allows you to define the arguments/options used for tasks
Fixes #1959

feat: task arguments

---

src/backend/go.rs

Seems bailing was a bit harsh, just allow both variants but keep the fallback.
Fixes #2634

fix: release 2024.9.7 breaks configurations that were using v in version names with go backend

---

.github/workflows/release-plz.yml
.github/workflows/test.yml
.markdownlintignore
.mise.toml
.mise/tasks/lint-fix
.mise/tasks/lint/settings
.mise/tasks/render/settings
Cargo.toml
build.rs
docs/.vitepress/config.ts
docs/configuration.md
docs/contributing.md
docs/package.json
docs/settings.data.ts
docs/settings.md
docs/settings.toml
package.json
schema/mise.json
schema/mise.json.hbs
settings.toml
src/backend/mod.rs
src/config/settings.rs
src/registry.rs
src/toolset/mod.rs

feat: codegen settings

---

.github/workflows/docs.yml
docs/.vitepress/cli_commands.ts
docs/cli/index.md
docs/cli/toml/get.md
docs/cli/toml/set.md
man/man1/mise.1
mise.usage.kdl
src/cli/mod.rs
src/cli/toml/get.rs
src/cli/toml/mod.rs
src/cli/toml/set.rs

feat: added toml cli commands

---

src/cli/run.rs
src/config/mod.rs

feat: offer to chmod non-executable tasks

---

docs/dev-tools/backends/cargo.md

Added information on how to install using cargo git with mise.

docs: Update cargo.md

---

docs/dev-tools/backends/ubi.md

docs: ubi cargo install instruction incorrect

---

docs/tasks/toml-tasks.md
schema/mise.json
src/cli/config/snapshots/mise__cli__config__get__tests__toml_get.snap
src/cli/run.rs
src/cli/tasks/deps.rs
src/cli/tasks/ls.rs
src/cli/tasks/snapshots/mise__cli__tasks__ls__tests__task_ls_json.snap
src/cli/tasks/snapshots/mise__cli__tasks__ls__tests__task_ls_json_extended.snap
src/cli/use.rs
src/task/mod.rs
src/test.rs
test/config/config.toml

feat: task shell

---

.mise.toml
docs/lang/python.md
e2e/plugins/core/test_python_uv_venv
schema/mise.json
settings.toml
src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/env_directive.rs

feat: use uv to create venv by default

---

src/plugins/core/java.rs

fix: issue with java@latest and metadatas (currently 23.0.0)

---

src/registry.rs

https://github.com/jdx/mise/pull/2724#issue-2580418120

refactor: remove duplicates in vfox registry

---

src/cli/exec.rs

This should prevent issues where we are calling shims in infinite loops such as #2254. There shouldn't be any need to have the shims directory at that point since all the tools are already loaded. `mise x` is called by the shims.
There may be more work to be done here but it should at least prevent looping and show a better error message

fix: remove shims directory when running `mise x`

---

docs/dev-tools/backends/cargo.md
docs/dev-tools/backends/pipx.md
docs/lang/go.md
docs/lang/java.md
docs/lang/node.md
docs/lang/python.md
docs/lang/ruby.md
schema/mise.json
settings.toml
src/backend/cargo.rs
src/backend/pipx.rs
src/cli/settings/ls.rs
src/cli/settings/set.rs
src/cli/settings/unset.rs
src/config/settings.rs

feat: allow passing arbitrary args to pipx/uvx

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- remove some non-working vfox plugins by [@jdx](https://github.com/jdx) in [7248fcc](https://github.com/jdx/mise/commit/7248fcccb43361979f112268fc15ecd54f2a7344)
- use asdf by default unless on windows by [@jdx](https://github.com/jdx) in [b525a84](https://github.com/jdx/mise/commit/b525a84b816a418d3e7bfcca5fc03446d539c63a)
- snapshots by [@jdx](https://github.com/jdx) in [2817482](https://github.com/jdx/mise/commit/2817482678d38999ba9b866d1f5c7e47808ba13a)
- bump vfox by [@jdx](https://github.com/jdx) in [8549727](https://github.com/jdx/mise/commit/85497276a86067f3e1e7cf281840e4de968a0174)

chore: release 2024.10.5

---

Cargo.lock
Cargo.toml
e2e/cli/test_log_level
src/cli/run.rs
src/cmd.rs
src/config/settings.rs
src/logger.rs
src/output.rs
src/ui/style.rs

This logger wont screw up the output coming from vfox/ubi installs on progress bars

feat: created custom logger

---

docs/cli/tasks/run.md
e2e/cli/test_outdated
src/cli/outdated.rs
src/cli/upgrade.rs
src/output.rs

docs: added hint about --bump flag for upgrade/outdated

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- remove schema/settings.json from release script by [@jdx](https://github.com/jdx) in [3086cae](https://github.com/jdx/mise/commit/3086cae4c8874ec85b8af776cafdd85a69dc80b5)

chore: release 2024.10.7

---

src/git.rs

A test with `mitmproxy` showed that cloning during plugin installation would not use the proxy if set via `https_proxy` environment variable. Proxy needs to be set for the `git2::Repository` when cloning.
Fixes #2781

fix: installing from behind a proxy shows git clone errors and does not work

---

src/backend/ubi.rs

Fixes #2764 
@jdx I wonder if we should loosen the regex in the default implementation instead or keep this backend specific.

fix: installing jq via new built-in ubi fails

---

src/plugins/core/java.rs
src/toolset/mod.rs

fix: java core plugin reports wrong latest version

---

src/file.rs
src/hint.rs
src/main.rs
src/output.rs

I think this is better than having users manually disable. Downside is they may miss the hint.

feat: automatically hide hints after displayed once

---

Cargo.lock
docs/cli/activate.md
docs/cli/completion.md
docs/cli/config/set.md
docs/cli/env.md
docs/cli/generate/task-docs.md
docs/cli/tasks.md
docs/cli/tasks/ls.md
docs/cli/tasks/run.md
e2e/tasks/test_task_run_file
e2e/tasks/test_task_run_toml
mise.usage.kdl
src/task/mod.rs
src/task/task_script_parser.rs
tasks.md

fix: parsing default task arg/flags

---

src/cli/self_update.rs
src/env.rs
src/http.rs
src/task/task_script_parser.rs

---------
Co-authored-by: mise[bot] <123107610+mise-en-dev@users.noreply.github.com>

fix: use GITHUB_API_TOKEN or GITHUB_TOKEN

---

src/backend/cargo.rs

fix: added sccache as a dependency for cargo backend

---

mise.usage.kdl
src/cli/alias/ls.rs
src/cli/alias/set.rs
src/cli/alias/unset.rs
src/plugins/core/node.rs

New LTS release is being cut right now.
https://github.com/nodejs/node/commit/4354a1de0eba63fbfcfe35eed27c7dc30f6e5339
https://nodejs.org/en/blog/release/v22.11.0

feat(node): update aliases for latest LTS release (jod/v22)

---

docs/configuration.md
schema/mise.json
schema/mise.json.hbs

fix: update json schema

---

docs/continuous-integration.md
docs/getting-started.md

See https://github.com/jdx/mise/discussions/2879

docs: Add GitLab CI example

---

src/shell/bash.rs
src/shell/fish.rs
src/shell/nushell.rs
src/shell/snapshots/mise__shell__bash__tests__activate.snap
src/shell/snapshots/mise__shell__fish__tests__activate.snap
src/shell/snapshots/mise__shell__nushell__tests__hook_init.snap
src/shell/snapshots/mise__shell__zsh__tests__activate.snap
src/shell/zsh.rs

Fixes #2900 (invalidates PR #2860)
Thanks for the fix @powerman!

fix: wrong alias in shell implementations

---

docs/cli/activate.md
docs/cli/env.md
mise.usage.kdl
src/cli/usage.rs

feat: add autocompletion for tasks run

---

schema/mise.json
schema/mise.json.hbs

https://github.com/jdx/mise/pull/2896#issuecomment-2453455977

docs: add [tasks.*.file] to json schema

---

e2e/tasks/test_task_run_file

test: added e2e test for js task

---

e2e/backend/test_cargo_binstall_token
src/env.rs

fix: allow setting MISE_GITHUB_TOKEN to empty string to not use any gh token

---

src/backend/external_plugin_cache.rs
src/cache.rs
src/cli/uninstall.rs

triggers hook-env execution
Fixes #2876

fix: touch MISE_DATA_DIR after uninstall

---

e2e/cli/test_upgrade
src/cli/args/backend_arg.rs
src/cli/upgrade.rs
src/cli/use.rs
src/config/config_file/legacy_version.rs
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs
src/config/config_file/tool_versions.rs

fix: upgrade with options

---

src/backend/mod.rs
src/cli/args/backend_arg.rs
src/cli/registry.rs
src/registry.rs
src/shorthands.rs
src/versions_host.rs

fix: explode backend dependencies

---

docs/cli/ls.md
mise.usage.kdl
src/cli/ls.rs
src/plugins/asdf_plugin.rs
src/plugins/vfox_plugin.rs

feat: added --offline flag to ls

---

src/plugins/core/go.rs

fix(go): remove old GOPATH bin dir

---

docs/registry.md
src/versions_host.rs

fix: use versions host for core plugins

---

docs/about.md
docs/configuration.md
docs/continuous-integration.md
docs/direnv.md
docs/environments.md
docs/faq.md
docs/how-i-use-mise.md
docs/ide-integration.md
docs/lang/go.md
docs/lang/node.md
docs/lang/python.md
docs/lang/ruby.md
docs/plugins.md
docs/profiles.md
docs/registry.md
docs/templates.md
docs/tips-and-tricks.md
e2e/tasks/test_task_run_toml
schema/mise.json
settings.toml
src/backend/asdf.rs
src/cli/set.rs
src/cli/unset.rs
src/cli/use.rs
src/config/mod.rs
src/env.rs
src/toolset/builder.rs
src/toolset/tool_request_set.rs

* use MISE_PROFILE instead of MISE_ENV (MISE_ENV still supported for backwards compatibility)
* simplified docs for config precedence
* fix bug with MISE_PROFILE not working in tasks #2595

fix: MISE_PROFILE fixes

---

src/plugins/core/mod.rs

feat: make zig non-experimental

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- add postgis plugin to registry by [@knu](https://github.com/knu) in [#3002](https://github.com/jdx/mise/pull/3002)
- added --backend arg for registry command by [@jdx](https://github.com/jdx) in [#3004](https://github.com/jdx/mise/pull/3004)
- support more aqua tools by [@jdx](https://github.com/jdx) in [#3000](https://github.com/jdx/mise/pull/3000)

chore: release 2024.11.9

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- added hyperfine test by [@jdx](https://github.com/jdx) in [#3016](https://github.com/jdx/mise/pull/3016)
- Update mise.toml by [@jdx](https://github.com/jdx) in [35c55e0](https://github.com/jdx/mise/commit/35c55e070a20dde64ee9b669c8cad35d33714499)
- added tasks.toml by [@jdx](https://github.com/jdx) in [8a02900](https://github.com/jdx/mise/commit/8a029005d52ba337a6850ded9ddde3f82903b3c6)
- reuse CI cache on jobs by [@jdx](https://github.com/jdx) in [#3018](https://github.com/jdx/mise/pull/3018)
- remove cargo-deny warning by [@jdx](https://github.com/jdx) in [a1479b6](https://github.com/jdx/mise/commit/a1479b63fc478a14add5991657a9c8986e43407c)
- improve CI caching by [@jdx](https://github.com/jdx) in [0ffe565](https://github.com/jdx/mise/commit/0ffe565227cb68b814f3e1937b347b72de3700a3)

chore: release 2024.11.11

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- added more aqua tools by [@jdx](https://github.com/jdx) in [#3021](https://github.com/jdx/mise/pull/3021)
- build mise for coverage tests by [@jdx](https://github.com/jdx) in [#3020](https://github.com/jdx/mise/pull/3020)
- build during windows-unit by [@jdx](https://github.com/jdx) in [995907f](https://github.com/jdx/mise/commit/995907f43266972292dd32a4751fc3ee3d7677d2)
- fix lint error by [@jdx](https://github.com/jdx) in [924592a](https://github.com/jdx/mise/commit/924592aeb9732b0064072b601fb2e058610fc6b5)

chore: release 2024.11.12

---

src/backend/aqua.rs

fix(aqua): allow environment validation for arch-only matches

---

e2e/cli/test_use
src/cli/use.rs

fix: mise use -p . panics

---

.github/workflows/release.yml
.github/workflows/test.yml
docs/registry.md
registry.toml

Fixes https://github.com/jdx/mise/issues/3050

fix: disable 1password on non-windows

---

src/backend/mod.rs

fix: prevent infinite recursion listing dependencies

---

docs/dev-tools/comparison-to-asdf.md

- add link to faq: migration from asdf

docs: update comparison-to-asdf.md - add link to faq: migration from asdf

---

e2e/tasks/test_task_deps
src/task/mod.rs

fix: allow tasks to depend on themselves

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- checksums in lockfile by [@jdx](https://github.com/jdx) in [#3096](https://github.com/jdx/mise/pull/3096)
- allow specifying asdf plugins with full urls by [@jdx](https://github.com/jdx) in [#3067](https://github.com/jdx/mise/pull/3067)
- use aqua for etcd by [@jdx](https://github.com/jdx) in [#3101](https://github.com/jdx/mise/pull/3101)
- sort some information in `mise dr` by [@jdx](https://github.com/jdx) in [#3093](https://github.com/jdx/mise/pull/3093)
- lockfile with "latest" versions by [@jdx](https://github.com/jdx) in [#3088](https://github.com/jdx/mise/pull/3088)
- allow tasks to depend on themselves by [@jdx](https://github.com/jdx) in [#3100](https://github.com/jdx/mise/pull/3100)
- update comparison-to-asdf.md - add link to faq: migration from asdf by …

chore: release 2024.11.19

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- optional dependencies by [@jdx](https://github.com/jdx) in [#3104](https://github.com/jdx/mise/pull/3104)
- reorder methods by [@jdx](https://github.com/jdx) in [aef623e](https://github.com/jdx/mise/commit/aef623eff21b42635128d34fd26a2e0e9d8f9eed)

chore: release 2024.11.20

---

src/plugins/vfox_plugin.rs

fix(vfox): handle bug when plugin is removed from registry

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- fix windows-unit job by [@jdx](https://github.com/jdx) in [#3123](https://github.com/jdx/mise/pull/3123)
- Update lockfile.rs by [@jdx](https://github.com/jdx) in [3184c40](https://github.com/jdx/mise/commit/3184c40ee8f3f5acf4ebda2f0781c81cd1e2f56d)

chore: release 2024.11.22

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- skip lockfile methods when experimental is disabled by [@jdx](https://github.com/jdx) in [91c30da](https://github.com/jdx/mise/commit/91c30da1575ba05166a097b3aede3b622d17e90e)

chore: release 2024.11.23

---

docs/cli/trust.md
e2e/cli/test_settings_set
e2e/config/test_config_ignore
mise.usage.kdl
schema/mise.json
settings.toml
src/cli/alias/ls.rs
src/cli/config/mod.rs
src/cli/current.rs
src/cli/link.rs
src/cli/settings/get.rs
src/cli/snapshots/mise__cli__trust__tests__trust-2.snap
src/cli/snapshots/mise__cli__trust__tests__trust-3.snap
src/cli/snapshots/mise__cli__trust__tests__trust-4.snap
src/cli/snapshots/mise__cli__trust__tests__trust-5.snap
src/cli/snapshots/mise__cli__trust__tests__trust.snap
src/cli/trust.rs
src/cli/usage.rs
src/cli/watch.rs
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs
src/config/mod.rs
src/config/settings.rs
src/dirs.rs
src/env.rs
tasks/fig/src/mise.ts

feat: ignore config files after not trusting them

---

docs/templates.md

From https://github.com/jdx/mise/discussions/1264#discussioncomment-11348037

docs: note that mise.toml files are not templated, only config values

---

docs/dev-tools/backends/cargo.md
src/backend/cargo.rs
src/cmd.rs

Fixes #2753
Fixes #3143
Fixes #2963

fix(cargo): added extra tool opts

---

mise.toml
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs

fix: keep tools sorted

---

.idea/vcs.xml
src/config/config_file/mise_toml.rs

fix: trust config files written by mise

---

docs/direnv.md
docs/templates.md
settings.toml

docs: typos

---

src/cli/hook_env.rs

fix: use tv.short in show_tools

---

e2e/plugins/core/test_python_uv_venv
registry.toml
schema/mise.json
settings.toml
src/config/env_directive.rs
src/config/settings.rs
src/main.rs
src/toolset/mod.rs
src/uv.rs

feat: automatic uv venv activation

---

docs/registry.md
registry.toml

https://github.com/aquaproj/aqua-registry/pull/29256

feat: add committed

---

src/cli/hook_env.rs
src/env.rs
src/hook_env.rs

Fixes https://github.com/jdx/mise/pull/3258

fix: run `hook-env` on directory change

---

src/config/env_directive.rs

fix: make _.file and _.source optional if the file is missing

---

.github/workflows/test.yml
README.md
flake.nix
packaging/dev/Dockerfile
xtasks/test/coverage

it makes things slow and I dont look at it anyways

chore: remove coverage

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- fragmented configs by [@jdx](https://github.com/jdx) in [#3273](https://github.com/jdx/mise/pull/3273)
- hooks by [@jdx](https://github.com/jdx) in [#3256](https://github.com/jdx/mise/pull/3256)
- added MISE_TASK_DISABLE_PATHS setting by [@jdx](https://github.com/jdx) in [9c2e6e4](https://github.com/jdx/mise/commit/9c2e6e40f3a98f352fbf03107e1901dec445a7f5)
- gpg verification for node by [@jdx](https://github.com/jdx) in [#3277](https://github.com/jdx/mise/pull/3277)
- make _.file and _.source optional if the file is missing by [@jdx](https://github.com/jdx) in [#3275](https://github.com/jdx/mise/pull/3275)
- prevent deadlock when resetting by [@jdx](https://github.com/jdx) in [8e6d093](https://github.com/jdx/mise/commit/8e6d09377de81c65203684725fa9dfc2140db520)
- prevent deadlock when …

chore: release 2024.11.34

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- mise i by [@jdx](https://github.com/jdx) in [8150732](https://github.com/jdx/mise/commit/81507327e7f1c9f2137b3dadcf35a8245d43a8ba)

chore: release 2024.11.36

---

docs/registry.md
registry.toml

https://github.com/aquaproj/aqua-registry/pull/29257

feat: add black

---

docs/registry.md
registry.toml

https://github.com/aquaproj/aqua-registry/pull/29366

feat: add upctl

---

docs/registry.md
registry.toml

I recently added it to aqua
https://github.com/aquaproj/aqua-registry/pull/29463

add ripsecrets to registry.toml

---

docs/configuration.md
docs/tasks/index.md

docs: fix `Environment variables passed to tasks` section

---

.cargo/config.toml
build.rs
e2e/backend/test_terraform
e2e/shell/test_bash
registry.toml
src/backend/mod.rs
src/registry.rs

fix: .terraform-version

---

e2e/config/test_config_alias
src/backend/mod.rs

fix: bug with aliasing core tools

---

src/cli/activate.rs

fix: remove shims directory before activating

---

docs/cli/index.md
docs/cli/ls.md
e2e/cli/test_upgrade
man/man1/mise.1
mise.usage.kdl
schema/mise.json
settings.toml
src/backend/asdf.rs
src/backend/go.rs
src/backend/mod.rs
src/backend/npm.rs
src/backend/vfox.rs
src/cli/ls.rs
src/cli/mod.rs
src/plugins/core/ruby.rs
xtasks/fig/src/mise.ts

This made more sense before the dedicated `mise outdated` command and before
backends since now people have a lot more tools generally
Fixes #3408

perf: make `ls --offline` default behavior

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
man/man1/mise.1
packaging/rpm/mise.spec

- add danger-swift by [@msnazarow](https://github.com/msnazarow) in [#3406](https://github.com/jdx/mise/pull/3406)
- **(backend)** fix git url syntax example by [@risu729](https://github.com/risu729) in [#3404](https://github.com/jdx/mise/pull/3404)
- update dev-tools overview documentation by [@hverlin](https://github.com/hverlin) in [#3400](https://github.com/jdx/mise/pull/3400)
- increase performance of watch_files by [@jdx](https://github.com/jdx) in [#3407](https://github.com/jdx/mise/pull/3407)
- make `ls --offline` default behavior by [@jdx](https://github.com/jdx) in [#3409](https://github.com/jdx/mise/pull/3409)
- Update environments.md by [@jdx](https://github.com/jdx) in [aa5eeff](https://github.com/jdx/mise/commit/aa5eeff161a8b01435c87dcae124fd54f8ddcf4d)
- @msnazarow made …

chore: release 2024.12.3

---

docs/tips-and-tricks.md

https://github.com/jdx/mise/issues/3434
I've updated the mention of `slsa-verify` to `slsa-verifier`

fix: mention of slsa-verifier in documentation

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- add staged files to `mise generate git-pre-commit` by [@jdx](https://github.com/jdx) in [#3410](https://github.com/jdx/mise/pull/3410)
- shell hooks by [@jdx](https://github.com/jdx) in [#3414](https://github.com/jdx/mise/pull/3414)
- added cowsay by [@jdx](https://github.com/jdx) in [#3420](https://github.com/jdx/mise/pull/3420)
- add openbao by [@phyrog](https://github.com/phyrog) in [#3426](https://github.com/jdx/mise/pull/3426)
- add gocryptfs by [@phyrog](https://github.com/phyrog) in [#3427](https://github.com/jdx/mise/pull/3427)
- use aqua for flyctl by [@jdx](https://github.com/jdx) in [f7ed363](https://github.com/jdx/mise/commit/f7ed363b3eebb82e6242061e78f9ebfdf050d154)
- do not set debug mode when calling `mise -v` by [@jdx](https://github.com/jdx) in …

chore: release 2024.12.4

---

src/backend/spm.rs
src/file.rs

fix: retain spm artifacts

---

Cargo.lock
e2e/run_test
e2e/tasks/test_task_shell
src/cli/run.rs
src/config/settings.rs
src/shell/mod.rs
src/task/mod.rs
src/task/task_script_parser.rs

fix: shell-escape arg() in tasks

---

e2e/config/test_config_ignore
src/cli/trust.rs
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs
src/config/config_file/tool_versions.rs
src/config/mod.rs
src/config/settings.rs
src/errors.rs

feat: make `mise trust` act on directories instead of files

---

Cargo.lock
Cargo.toml
docs/.vitepress/cli_commands.ts
docs/cli/format.md
docs/cli/index.md
man/man1/mise.1
mise.usage.kdl
src/cli/format.rs
src/cli/mod.rs
xtasks/fig/src/mise.ts

Fixes https://github.com/jdx/mise/issues/3422

feat: `mise format`

---

src/plugins/core/python.rs

fix: allow "~" in python.default_packages_file

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- added descriptions to `mise run` by [@jdx](https://github.com/jdx) in [#3460](https://github.com/jdx/mise/pull/3460)
- `mise format` by [@jdx](https://github.com/jdx) in [#3461](https://github.com/jdx/mise/pull/3461)
- `mise fmt` (renamed from `mise format`) by [@jdx](https://github.com/jdx) in [#3465](https://github.com/jdx/mise/pull/3465)
- `mise format` by [@jdx](https://github.com/jdx) in [d18b040](https://github.com/jdx/mise/commit/d18b040b8ae8eea16ed98b7f7b884a6f52797edc)
- **(swift)** remove clang bins by [@jdx](https://github.com/jdx) in [#3468](https://github.com/jdx/mise/pull/3468)
- use 7zip for windows zip by [@jdx](https://github.com/jdx) in [475ae62](https://github.com/jdx/mise/commit/475ae62d209795cf8fe9cc846f258755e1092918)
- disable filtering by default on `mise run` by …

chore: release 2024.12.6

---

src/config/mod.rs

fix: skip reading ignored config dirs

---

docs/tasks/index.md
docs/templates.md
src/backend/asdf.rs
src/config/config_file/mod.rs
src/config/env_directive.rs
src/config/mod.rs
src/env_diff.rs

fix: use config_root for env._.source

---

src/task/task_script_parser.rs

Allows the use of args multiple times.

Adds support for multi-use args

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(registry)** use pipx for pdm by [@risu729](https://github.com/risu729) in [#3504](https://github.com/jdx/mise/pull/3504)
- added pitchfork by [@jdx](https://github.com/jdx) in [bac731e](https://github.com/jdx/mise/commit/bac731e47f00245ce13e7eec5716509704519d71)
- Adds support for multi-use args by [@bnorick](https://github.com/bnorick) in [#3505](https://github.com/jdx/mise/pull/3505)
- make task completion script POSIX by [@jdx](https://github.com/jdx) in [b92b560](https://github.com/jdx/mise/commit/b92b5603bb23d55b58e7ee8effe8d6293036c5a9)
- Add more examples for toml tasks by [@hverlin](https://github.com/hverlin) in [#3491](https://github.com/jdx/mise/pull/3491)
- Fix README link. by [@biggusbeetus](https://github.com/biggusbeetus) in …

chore: release 2024.12.8

---

docs/tasks/toml-tasks.md
src/cli/run.rs
src/task/mod.rs

feat: added quiet field to tasks

---

src/git.rs

I really have no clue what I am doing here but this seems to function
Fixes #3517

fix: make plugin update work with libgit2

---

src/cli/tasks/edit.rs
src/task/mod.rs

fix: bug with `mise task edit` and new tasks

---

e2e/assert.sh
e2e/tasks/test_task_run_sources
src/cli/run.rs
src/logger.rs

fix: task source bug fixes

---

docs/tasks/task-configuration.md
e2e/tasks/test_task_redactions
src/cli/run.rs
src/cmd.rs
src/config/config_file/mise_toml.rs
src/config/config_file/mod.rs
src/config/mod.rs
src/main.rs
src/redactions.rs
src/wildcard.rs

Fixes https://github.com/jdx/mise/discussions/3524

feat: redactions

---

src/git.rs

fix: disable libgit2 for updating plugin repos for now

---

e2e/cli/test_use_latest
e2e/lockfile/test_lockfile_backend
e2e/lockfile/test_lockfile_use
mise.lock
src/cli/args/backend_arg.rs
src/lockfile.rs

fix: add backend to lockfile

---

src/backend/go.rs

fix(go): only use "v" prefix if version is semver-like

---

Cargo.lock
Cargo.toml
docs/lang/python.md
schema/mise.json
settings.toml
src/file.rs
src/plugins/core/python.rs
tasks.md

Fixes https://github.com/jdx/mise/issues/2149

feat(python): add other indygreg flavors

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(python)** add other indygreg flavors by [@jdx](https://github.com/jdx) in [#3565](https://github.com/jdx/mise/pull/3565)
- redactions by [@jdx](https://github.com/jdx) in [#3529](https://github.com/jdx/mise/pull/3529)
- show unload messages/run leave hook by [@jdx](https://github.com/jdx) in [#3532](https://github.com/jdx/mise/pull/3532)
- update demand and default `mise run` to filtering by [@jdx](https://github.com/jdx) in [48c366d](https://github.com/jdx/mise/commit/48c366d4d2256f6b12aabcbe82abe429622b120e)
- **(go)** only use "v" prefix if version is semver-like by [@jdx](https://github.com/jdx) in [#3556](https://github.com/jdx/mise/pull/3556)
- **(go)** fix non-v installs by [@jdx](https://github.com/jdx) in [36e7631](https://github.com/jdx/mise/commit/36e7631e26445f9f2bc34fd09a …

chore: release 2024.12.10

---

schema/mise.json
settings.toml
src/plugins/core/swift.rs

related to https://github.com/jdx/mise/issues/3581 but doesn't resolve it

fix(swift): prevent swift from using linux platforms that are not available

---

e2e/cli/test_status
mise.usage.kdl
src/backend/asdf.rs
src/backend/external_plugin_cache.rs
src/backend/vfox.rs
src/cli/hook_env.rs
src/cli/run.rs
src/config/config_file/mise_toml.rs
src/config/env_directive.rs
src/env.rs
src/env_diff.rs
src/hook_env.rs
src/hooks.rs
src/test.rs
src/toolset/builder.rs
src/toolset/mod.rs

fix: some bugs with status.show_tools and status.show_env

---

Cargo.lock
Cargo.toml
docs/.vitepress/config.ts
docs/configuration.md
docs/dev-tools/comparison-to-asdf.md
docs/environments/index.md
docs/environments/secrets.md
docs/getting-started.md
docs/plugins.md
docs/walkthrough.md
e2e/backend/test_pipx_deep_dependencies
e2e/cli/test_settings_ls
e2e/secrets/test_secrets
schema/mise.json
settings.toml
src/backend/pipx.rs
src/config/env_directive/file.rs
src/config/settings.rs
src/main.rs
src/sops.rs

feat: encrypted secrets with sops

---

src/config/settings.rs
src/env.rs
src/ui/table.rs

fix: respect CLICOLOR_FORCE

---

docs/templates.md
e2e/env/test_env_tmpl_cache
src/config/env_directive/mod.rs
src/tera.rs

feat: added cache feature to templates

---

docs/.vitepress/cli_commands.ts
docs/cli/index.md
docs/cli/tasks.md
docs/cli/tasks/add.md
e2e/tasks/test_task_add
mise.usage.kdl
src/cli/tasks/add.rs
src/cli/tasks/mod.rs
xtasks/fig/src/mise.ts

feat: `mise task add`

---

e2e/config/test_hooks
src/cli/install.rs

fix: always run postinstall hook

---

docs/dev-tools/index.md
src/backend/asdf.rs
src/backend/external_plugin_cache.rs
src/cli/tool.rs
src/config/config_file/mise_toml.rs
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__fixture-3.snap
src/config/config_file/snapshots/mise__config__config_file__mise_toml__tests__replace_versions.snap
src/toolset/mod.rs

feat: added install_env tool option

---

src/plugins/core/python.rs

fix: correct python precompiled urls for freebsd

---

e2e/env/test_env_tools
src/cli/direnv/envrc.rs
src/cli/doctor/path.rs
src/cli/env.rs
src/cli/exec.rs
src/cli/hook_env.rs
src/toolset/mod.rs

fix: bug fixes with tools=true in env

---

docs/registry.md
registry.toml

https://github.com/jesseduffield/lazydocker

feat(registry): Add lazydocker

---

docs/core-tools.md
docs/environments/secrets.md
docs/tasks/task-configuration.md

docs: mark new features as experimental

---

mise.usage.kdl
src/assets/mise-extra.usage.kdl

fix: completions getting wrapped in quotes

---

docs/lang/python.md
e2e/core/test_python_venv
e2e/env/test_env_file
src/plugins/core/python.rs

test: add test cases for venv templates

---

docs/cli/index.md
docs/cli/run.md
docs/cli/tasks/run.md
e2e/tasks/test_task_unnest
man/man1/mise.1
mise.usage.kdl
src/cli/mod.rs
src/cli/run.rs
src/cmd.rs
src/env.rs
src/output.rs
src/task/mod.rs
src/test.rs
xtasks/fig/src/mise.ts

Fixes https://github.com/jdx/mise/issues/3674

feat: unnest task prefixes in output

---

docs/tasks/file-tasks.md
e2e/tasks/test_task_default
src/cli/tasks/add.rs
src/task/mod.rs

feat: added *:_default task name

---

docs/cli/run.md
docs/cli/tasks/run.md
mise.usage.kdl
src/cli/mod.rs
src/cli/run.rs
xtasks/fig/src/mise.ts

feat: `mise run --continue-on-error

---

e2e/tasks/test_task_project_root
src/cli/run.rs

fix: ensure MISE_PROJECT_ROOT is set with no mise.toml

---

src/cli/doctor/mod.rs
src/config/mod.rs

feat: added ignored_config_paths to `mise dr`

---

Cargo.lock
Cargo.toml
src/env.rs

home is apparently not to be used outside of cargo

chore: switch from home -> homedir crate

---

docs/dev-tools/backends/index.md

Fix missing documentation entry point

fix: dotnet backend doc

---

docs/cli/run.md
docs/cli/tasks/run.md
e2e/tasks/test_task_keep_order
mise.usage.kdl
schema/mise.json
settings.toml
src/cli/config/set.rs
src/cli/mod.rs
src/cli/run.rs
src/cli/tasks/mod.rs
src/cmd.rs
src/output.rs

feat: added keep-order task output type

---

docs/plugins.md

Noticed this when going through the docs!

docs: Correct link to aqua registry

---

schema/mise.json
settings.toml
src/config/env_directive/venv.rs

fix: type issue in docs/JSON schema for python_create_args and uv_create_args

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- colorize banner by [@jdx](https://github.com/jdx) in [ad3a5f0](https://github.com/jdx/mise/commit/ad3a5f040013bad046f2ca3abb9eebc941301368)
- add `:` escaping for tasks with multiple colons by [@eitamal](https://github.com/eitamal) in [#3853](https://github.com/jdx/mise/pull/3853)
- type issue in docs/JSON schema for python_create_args and uv_create_args by [@roele](https://github.com/roele) in [#3855](https://github.com/jdx/mise/pull/3855)
- **(settings)** fix link to precompiled python binaries by [@scop](https://github.com/scop) in [#3851](https://github.com/jdx/mise/pull/3851)
- Fix cargo install examples by [@orf](https://github.com/orf) in [#3862](https://github.com/jdx/mise/pull/3862)
- Delete .github/ISSUE_TEMPLATE/blank.md by [@jdx](https://github.com/jdx) in …

chore: release 2024.12.22

---

docs/plugins.md

Old one was archived with a README link to new locaton

Update registry link

---

build.rs
docs/cli/settings.md
docs/cli/settings/ls.md
docs/dev-tools/comparison-to-asdf.md
mise.usage.kdl
src/assets/mise-extra.usage.kdl
src/cli/config/set.rs
src/cli/settings/ls.rs
src/cli/settings/mod.rs
src/cli/tasks/ls.rs
src/config/settings.rs
xtasks/fig/src/mise.ts

fix: add hidden settings/task --complete option

---

src/task/task_script_parser.rs

fix: handle panic when task contains invalid template

---

docs/tasks/task-configuration.md

Very minor. 
Thanks for mise, Jeff!

docs: Fix tiny typo

---

schema/mise-task.json
schema/mise.json

https://mise.jdx.dev/tasks/toml-tasks.html#usage-spec
https://mise.jdx.dev/tasks/task-configuration.html#usage

docs: Add usage property to mise schema

---

docs/registry.md
registry.toml

Add [navi](https://github.com/denisidoro/navi) to registry using aqua and ubi backends.

feat: add navi to registry

---

e2e-win/go.Tests.ps1
e2e-win/python.Tests.ps1
e2e-win/rust.Tests.ps1
src/plugins/core/rust.rs

Draft for discussion #3960.
I currently don't have the setup (yet) to compile and test this properly.

fix: mise install rust failed on windows

---

docs/registry.md
registry.toml

feat: add kubectx/kubens to registry

---

schema/mise-task.json
schema/mise.json

Follow up of #3988.
ref: https://mise.jdx.dev/tasks/task-configuration.html

fix(schema): update task schema

---

src/plugins/core/rust.rs
tasks.md

fix(rust): respect RUSTUP_HOME/CARGO_HOME

---

.cargo/config.toml
Cargo.lock
Cargo.toml
completions/mise.bash
completions/mise.fish
e2e/tasks/test_task_deps
e2e/tasks/test_task_info
e2e/tasks/test_task_usage
mise.lock
mise.usage.kdl
src/assets/mise-extra.usage.kdl
xtasks/fig/src/mise.ts

this uses kdl 2.0 which has slightly different syntax see https://github.com/jdx/usage/pull/218 and https://github.com/kdl-org/kdl/blob/main/CHANGELOG.md#200-2024-12-21

feat!: bump usage to 2.x

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- update JSON output for task info/ls by [@hverlin](https://github.com/hverlin) in [#4034](https://github.com/jdx/mise/pull/4034)
- **breaking** bump usage to 2.x by [@jdx](https://github.com/jdx) in [#4049](https://github.com/jdx/mise/pull/4049)
- ignore github releases marked as draft by [@jdx](https://github.com/jdx) in [#4030](https://github.com/jdx/mise/pull/4030)
- `mise run` shorthand with tasks that have an extension by [@jdx](https://github.com/jdx) in [#4029](https://github.com/jdx/mise/pull/4029)
- use consistent casing by [@jdx](https://github.com/jdx) in [a4d4133](https://github.com/jdx/mise/commit/a4d41338139355b0dd86a068fd89790eb7e34584)
- support latest ansible packages by [@jdx](https://github.com/jdx) in [#4045](https://github.com/jdx/mise/pull/4045)
- use go backend for …

chore: release 2025.1.4

---

docs/registry.md
registry.toml

fix: switch jib back to asdf

---

src/cli/version.rs

fix: Panic when run without arguments with bootstrapped script

---

docs/tasks/toml-tasks.md

Fixes https://github.com/jdx/mise/issues/4002

docs: fix TOML-based Tasks usage spec example

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- Panic when run without arguments with bootstrapped script by [@jdx](https://github.com/jdx) in [#4065](https://github.com/jdx/mise/pull/4065)
- use better rust syntax by [@jdx](https://github.com/jdx) in [#4072](https://github.com/jdx/mise/pull/4072)
- fix TOML-based Tasks usage spec example by [@gturi](https://github.com/gturi) in [#4067](https://github.com/jdx/mise/pull/4067)
- eza by [@jdx](https://github.com/jdx) in [5a80cbf](https://github.com/jdx/mise/commit/5a80cbf9e0b37be800bc6f6f0404bcf86cbe3bd9)
- removed bit about verifying with asdf by [@jdx](https://github.com/jdx) in [d505486](https://github.com/jdx/mise/commit/d505486fbbe49af0f7bf6029569812441c1e3fdc)
- added more getting started installers by [@jdx](https://github.com/jdx) in …

chore: release 2025.1.6

---

e2e/env/test_env_template
src/config/env_directive/mod.rs

https://github.com/jdx/mise/discussions/4099

fix: use vars in [env] templates

---

docs/registry.md
registry.toml

Makes it easier to contribute to aqua registry.

feat(registry): add aqua and cmdx

---

docs/registry.md
registry.toml

Refs https://github.com/aquaproj/aqua-registry/pull/30887

refactor(registry): use aqua for powerline-go

---

src/config/config_file/mise_toml.rs

fix: incorrect config_root for project/.mise/config.toml

---

src/cli/args/tool_arg.rs

fix: installing with empty version fails

---

src/plugins/core/ruby.rs

These do not play nice with some security software and they have always seemed to cause more trouble than they're worth

fix(ruby): remove ruby/gem tests

---

mise.usage.kdl
src/assets/mise-extra.usage.kdl
xtasks/fig/src/mise.ts

fix: completions for `mise use`

---

Cargo.lock
Cargo.toml
src/cli/run.rs
src/task/file_providers/http_file_provider.rs
src/task/file_providers/local_file_provider.rs
src/task/file_providers/mod.rs
src/task/mod.rs

@jdx  what do you think about that ?
step one : refine the feth_tasks function <= we are here
step two : add cache system to avoid re-downloading tasks
step three : add more task providers

feat: split remote task

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
mise.toml
packaging/rpm/mise.spec

- pin aws-cli by [@jdx](https://github.com/jdx) in [ca16daf](https://github.com/jdx/mise/commit/ca16daf5e5dbb9159d853570528087b24f63500b)

chore: release 2025.1.11

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- setup mise for release task by [@jdx](https://github.com/jdx) in [78d3dfb](https://github.com/jdx/mise/commit/78d3dfb164776cfb39a1920485c21fcd6ecd3ebe)

chore: release 2025.1.12

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- fixing aws-cli in release.sh by [@jdx](https://github.com/jdx) in [5b4a65a](https://github.com/jdx/mise/commit/5b4a65a84e07141de9ed69798921b4b0ef69aa02)
- fixing aws-cli in release.sh by [@jdx](https://github.com/jdx) in [4c67db5](https://github.com/jdx/mise/commit/4c67db59ecfb55eb724dc05bca7eb7281a625929)

chore: release 2025.1.13

---

e2e/tasks/test_task_run_sources
src/cli/run.rs

fix: re-run tasks when files removed or permissions change

---

docs/.vitepress/cli_commands.ts
docs/cli/index.md
docs/cli/test-tool.md
man/man1/mise.1
mise.usage.kdl
schema/mise.json
scripts/render-registry.js
settings.toml
src/cli/test_tool.rs
src/registry.rs
xtasks/fig/src/mise.ts

Also added --all-config option

feat: expose `test-tool` command

---

Cargo.toml
src/cli/mod.rs
src/cli/self_update_stub.rs

needed to remove homebrew dependency on openssl

chore: make self_update optional

---

docs/registry.md
registry.toml

add duckdb command
Please let me know if there is anything missing.

feat(registry): add duckdb

---

src/config/mod.rs

Fixes https://github.com/jdx/mise/discussions/4191

fix: Do not attempt to parse directories

---

.gitignore
docs/components/settings.vue
docs/configuration.md
docs/lang/go.md
docs/lang/java.md
docs/lang/node.md
docs/lang/python.md
docs/lang/ruby.md
mise.lock

- Apply suggestion from https://github.com/jdx/mise/pull/4178.
- Make each section a bit more consistent

docs: Update sections about idiomatic version files

---

docs/hooks.md

Found minor discrepancy in var name. This is the correct one, right?
PS. Mise rocks! :P

hooks.md: MISE_PROJECT_DIR -> MISE_PROJECT_ROOT

---

docs/registry.md
registry.toml

Ref: https://github.com/aquaproj/aqua-registry/tree/1b78f46b6dd03d96fd16a9ea2c4bfdda533aaab7/pkgs/duckdb

feat(registry): use aqua for duckdb

---

e2e/cli/test_unuse
src/cli/unuse.rs

fix: mise rm removes/reports wrong version of tool

---

docs/components/registry.vue

Return early on filtering/highlighting to improve filtering performance issues which were not showing in dev mode.

docs: improve registry filtering performance

---

registry.toml

- add aqua and ubi for gitools/gitversion
- bump aqua-registry

feat: add gittool/gitversion

---

mise.lock
src/plugins/core/go.rs

feat: add support for idiomatic go.mod file

---

docs/external-resources.md

We recently wrote a guide for Swift developers interested in using Mise, so I added a link to that resource to this page.

Include "A Mise guide for Swift developers"

---

docs/bun.lock
docs/package.json
tasks.md
tasks.toml

docs: Update vitepress to fix search

---

schema/mise.json
src/config/env_directive/mod.rs
src/config/env_directive/module.rs

fix(env_directive): apply redactions only to env with redact

---

registry.toml

Easily Manage AWS ECS Resources in Terminal(~k9s for ECS)
https://github.com/keidarcy/e1s
https://github.com/tbobm/asdf-e1s

feat(registry): add e1s

---

e2e/tools/test_path_order
src/config/mod.rs

fix: path env order with subdirs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- properly replace non set flags with "false" by [@IxDay](https://github.com/IxDay) in [#4410](https://github.com/jdx/mise/pull/4410)
- path env order with subdirs by [@jdx](https://github.com/jdx) in [#4412](https://github.com/jdx/mise/pull/4412)
- "feat: set usage arguments and flags as environment variables for toml tasks" by [@jdx](https://github.com/jdx) in [#4413](https://github.com/jdx/mise/pull/4413)

chore: release 2025.2.5

---

.github/workflows/autofix.yml
Cargo.lock
e2e/tasks/test_task_usage
src/task/mod.rs

Fixes jdx/mise#4294
Fixes jdx/mise#4295

fix: short flag with value and var=#true bug

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- add devcontainer generator by [@acesyde](https://github.com/acesyde) in [#4355](https://github.com/jdx/mise/pull/4355)
- added hk by [@jdx](https://github.com/jdx) in [#4422](https://github.com/jdx/mise/pull/4422)
- short flag with value and var=#true bug by [@jdx](https://github.com/jdx) in [#4419](https://github.com/jdx/mise/pull/4419)
- regression with env overriding by [@jdx](https://github.com/jdx) in [#4421](https://github.com/jdx/mise/pull/4421)
- **(shims)** clarify `activate` only removes shims from `PATH` by [@risu729](https://github.com/risu729) in [#4418](https://github.com/jdx/mise/pull/4418)
- Update shims page by [@hverlin](https://github.com/hverlin) in [#4414](https://github.com/jdx/mise/pull/4414)

chore: release 2025.2.6

---

docs/installing-mise.md

mise is now available through the official Arch Linux repository

docs: Update installation for archLinux

---

src/cli/self_update.rs

Closes #4468
A quick fix for this discussion

fix: fix the behavior of .disable-self-update

---

e2e/generate/test_generate_devcontainer
src/cli/generate/devcontainer.rs

- 🐞 Bad naming serialisation
- 🐞 Missing permissions
- 🐞 Wrong environment variable
- 🚀 Add recommended vscode extension by default

fix: devcontainer

---

e2e/cli/test_outdated
src/cli/outdated.rs

fix: mise outdated --json does not return json if all tools are up-to-date

---

src/config/tracking.rs

fix: config of symlink tracked on windows is not respected

---

registry.toml

feat: add bazel-watcher to registry

---

docs/mise-cookbook/shell-tricks.md

Fairly specific and mostly trivial, but there was a gotcha so I thought I'd share and document this after setting it up today.

docs(cookbook): add shell powerline-go config env recipe

---

e2e/assert.sh
e2e/tasks/test_task_remote_git_https
e2e/tasks/test_task_remote_git_ssh
src/cli/generate/devcontainer.rs
src/git.rs
src/task/task_file_providers/remote_task_git.rs

- 🐛 Fix devcontainer parent folder creation
- 🐛 Fix remote tasks when using gix or libgit2

fix: remote tasks and devcontainer

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(registry)** added helmwave by [@tony-sol](https://github.com/tony-sol) in [#4542](https://github.com/jdx/mise/pull/4542)
- **(registry)** added doggo by [@tony-sol](https://github.com/tony-sol) in [#4545](https://github.com/jdx/mise/pull/4545)
- **(registry)** Add Boilerplate by [@ZachGoldberg](https://github.com/ZachGoldberg) in [#4530](https://github.com/jdx/mise/pull/4530)
- **(registry)** added htmlq by [@tony-sol](https://github.com/tony-sol) in [#4548](https://github.com/jdx/mise/pull/4548)
- **(registry)** added gokey by [@tony-sol](https://github.com/tony-sol) in [#4546](https://github.com/jdx/mise/pull/4546)
- **(registry)** added octosql by [@tony-sol](https://github.com/tony-sol) in [#4549](https://github.com/jdx/mise/pull/4549)
- **(registry)** added hexyl by …

chore: release 2025.3.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(registry)** added sampler by [@tony-sol](https://github.com/tony-sol) in [#4577](https://github.com/jdx/mise/pull/4577)
- add support for components property in rust-toolchain.toml by [@roele](https://github.com/roele) in [#4579](https://github.com/jdx/mise/pull/4579)
- add --local flag for ls by [@tony-sol](https://github.com/tony-sol) in [#4565](https://github.com/jdx/mise/pull/4565)
- favor aqua backend over asdf by [@dud225](https://github.com/dud225) in [#4558](https://github.com/jdx/mise/pull/4558)
- continuous-integration.md: fix gitlab caching example by [@nafg](https://github.com/nafg) in [#4576](https://github.com/jdx/mise/pull/4576)
- edition 2024 by [@jdx](https://github.com/jdx) in [#4541](https://github.com/jdx/mise/pull/4541)
- @nafg made their first contribution in …

chore: release 2025.3.1

---

src/config/env_directive/file.rs

Resolves https://github.com/jdx/mise/discussions/4372.
Since sops doesn't yet support toml (https://github.com/getsops/sops/pull/812), I ignored it for `toml`.

feat(env): support env files in toml

---

registry.toml
src/task/deps.rs

Adding [rs/curlie][1] (binary filename: `curlie`) to the registry.
[1]: https://github.com/rs/curlie

feat(registry): add curlie

---

src/config/env_directive/venv.rs

During the first installation for multiple pipx packages to be installed, it is possible to run multiple uv processes to create the venv directory and cause an error: `Failed to create virtualenv: The directory .venv exists, but it's not a virtual environment`
This commit uses file locks to avoid running multiple processes to create venv

fix: Failed to create venv at the same time by multiple uv processes

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- Failed to create venv at the same time by multiple uv processes by [@NavyD](https://github.com/NavyD) in [#4640](https://github.com/jdx/mise/pull/4640)

chore: release 2025.3.4

---

src/plugins/core/node.rs

fix(node): skip gpg verification if sig file not found

---

flake.lock

See:
https://github.com/jdx/mise/discussions/4685
From https://github.com/jdx/mise/pull/4541

fix: Update flake to fix nix build

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(registry)** added localstack by [@mnm364](https://github.com/mnm364) in [#4785](https://github.com/jdx/mise/pull/4785)
- **(registry)** added skeema by [@mnm364](https://github.com/mnm364) in [#4786](https://github.com/jdx/mise/pull/4786)
- **(registry)** add television by [@mangkoran](https://github.com/mangkoran) in [#4778](https://github.com/jdx/mise/pull/4778)
- show gh rate limit reset time in local time by [@someoneinjd](https://github.com/someoneinjd) in [#4799](https://github.com/jdx/mise/pull/4799)
- all experimental note for lockfile by [@zeitlinger](https://github.com/zeitlinger) in [#4781](https://github.com/jdx/mise/pull/4781)
- update deps to fix deny check by [@jdx](https://github.com/jdx) in [432023b](https://github.com/jdx/mise/commit/432023b2cd04d2ea7f590d7b338054944 …

chore: release 2025.4.1

---

docs/tasks/toml-tasks.md

Fix typo in toml-tasks documentation

docs: Fixing typo in code for flags in toml-tasks.md

---

e2e/backend/test_ubi
src/backend/ubi.rs

fix(ubi): URL syntax fails

---

src/cli/doctor/mod.rs

Fixes https://github.com/jdx/mise/discussions/4880.

fix(doctor): redact gitlab/enterprise tokens

---

src/task/mod.rs

Fixes https://github.com/jdx/mise/discussions/4885.

fix(task): enable templates in shell and tools of tasks

---

src/plugins/core/python.rs

Fixes https://github.com/jdx/mise/issues/2962

fix: added lockfile for pyenv

---

registry.toml

added [fastfetch](https://github.com/fastfetch-cli/fastfetch) to registry

feat(registry): added fastfetch

---

e2e/tools/test_path_order
src/toolset/tool_request_set.rs

fix(hook-env): path order

---

docs/installing-mise.md

Add information related to #4929

docs: add information about the DNF repository

---

registry.toml

Add [Luau](https://github.com/luau-lang/luau) to the registry, using an Aqua back end. Feedback is welcome.

feat(registry): add luau

---

registry.toml

A CLI scientific calculator, or even a language.
https://github.com/sharkdp/numbat

feat(registry): add numbat

---

registry.toml

Add [coreutils](https://github.com/uutils/coreutils) to registry.

feat(registry): add coreutils

---

registry.toml

The number of starts might be smaller than other existing tools. Please close if it's not common enough to add to the default registry.
https://github.com/suzuki-shunsuke/ghalint

feat(registry): add ghalint

---

Cargo.lock
Cargo.toml
mise.lock

chore: bump zip-rs version

---

docs/tasks/file-tasks.md
docs/tasks/toml-tasks.md

Untested, but I suppose this could work.

docs: add some missing vue interpolation escapes

---

src/plugins/core/java.rs

This is draft to use a new Java version data source. Its output is currently tailored to `mise` but could provide more extensive data (architectures, properties etc.) if need be. 
It is using [roele/roast](https://github.com/roele/roast), a rewrite of [jdx/rtx-java-metadata](https://github.com/jdx/rtx-java-metadata) respectively [joschi/java-metadata](https://github.com/joschi/java-metadata).
Improvements:
* contains only `mise` relevant data/properties
* more consistent versioning
* uses proper vendor provided checksums
Possible breaking changes:
* removed AdoptOpenJDK (has been replaced by Temurin in 2021)
* few patch versions are missing as they are not provided by the vendors anymore
Question is if we should fork/move the repository for `mise` purpose to somewhere else and if we …

feat: use new Java metadata source

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(registry)** add oauth2c by [@kklee998](https://github.com/kklee998) in [#5056](https://github.com/jdx/mise/pull/5056)
- use new Java metadata source by [@roele](https://github.com/roele) in [#5089](https://github.com/jdx/mise/pull/5089)
- **(config)** project root for files in .config/ or mise/ by [@scop](https://github.com/scop) in [#5102](https://github.com/jdx/mise/pull/5102)
- Clarify some of the filters and fix the config_root filter example by [@afranchuk](https://github.com/afranchuk) in [#5086](https://github.com/jdx/mise/pull/5086)
- **(registry)** use aqua for rclone by [@scop](https://github.com/scop) in [#5096](https://github.com/jdx/mise/pull/5096)
- **(tasks)** point to `dir` config for task default cwd by [@scop](https://github.com/scop) in …

chore: release 2025.5.6

---

src/task/task_file_providers/remote_task_git.rs

fix: using custom port with SSH based remote tasks

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(registry)** added astro by [@mnm364](https://github.com/mnm364) in [#5106](https://github.com/jdx/mise/pull/5106)
- **(registry)** use aqua for delta by [@risu729](https://github.com/risu729) in [#5116](https://github.com/jdx/mise/pull/5116)
- elixir bin name on windows by [@arilence](https://github.com/arilence) in [#5107](https://github.com/jdx/mise/pull/5107)
- create a detached signature when signing the source tarball by [@digital-wonderland](https://github.com/digital-wonderland) in [#5108](https://github.com/jdx/mise/pull/5108)
- @arilence made their first contribution in [#5107](https://github.com/jdx/mise/pull/5107)

chore: release 2025.5.8

---

docs/tasks/toml-tasks.md
e2e/tasks/test_task_remote_git_ssh
src/task/task_file_providers/mod.rs
src/task/task_file_providers/remote_task_git.rs

Align docs and tests with recent fix.

fix: SSH remote tasks do not support organizations in repository path

---

registry.toml

Adding [`microsoft/edit`](https://github.com/microsoft/edit) CLI text editor.

feat(registry): add microsoft `edit`

---

src/aqua/aqua_registry.rs
src/backend/aqua.rs

fix(aqua): use complete_windows_ext

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- read global/system config file tasks properly by [@jdx](https://github.com/jdx) in [#5169](https://github.com/jdx/mise/pull/5169)
- typo in time! parallelize_tasks by [@artemisart](https://github.com/artemisart) in [#5171](https://github.com/jdx/mise/pull/5171)
- disable non-working zig test by [@jdx](https://github.com/jdx) in [2ffb7ea](https://github.com/jdx/mise/commit/2ffb7eaa22e3623363dd153d581bb1a17da78483)
- @artemisart made their first contribution in [#5171](https://github.com/jdx/mise/pull/5171)

chore: release 2025.5.12

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- installing tools with postinstall hooks fails by [@roele](https://github.com/roele) in [#5191](https://github.com/jdx/mise/pull/5191)
- prefer offline when executing shims by [@jdx](https://github.com/jdx) in [#5195](https://github.com/jdx/mise/pull/5195)
- multi-line task output is shown in bold by [@roele](https://github.com/roele) in [#5197](https://github.com/jdx/mise/pull/5197)
- improve tool loading performance in async code by [@jdx](https://github.com/jdx) in [#5198](https://github.com/jdx/mise/pull/5198)

chore: release 2025.5.14

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- race condition with uv_venv by [@jdx](https://github.com/jdx) in [#5262](https://github.com/jdx/mise/pull/5262)
- disable victoria-metrics test by [@jdx](https://github.com/jdx) in [11bda4b](https://github.com/jdx/mise/commit/11bda4bda97bd02f6a8cae2c7f345846769ff776)

chore: release 2025.6.0

---

registry.toml

https://github.com/XcodesOrg/xcodes/

feat(registry): add xcodes

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(aqua)** support cosign bundle option by [@risu729](https://github.com/risu729) in [#5314](https://github.com/jdx/mise/pull/5314)
- **(registry)** add xcodes by [@MontakOleg](https://github.com/MontakOleg) in [#5321](https://github.com/jdx/mise/pull/5321)
- **(registry)** add typstyle by [@3w36zj6](https://github.com/3w36zj6) in [#5319](https://github.com/jdx/mise/pull/5319)
- **(cli/doctor)** reduce severity of new version to warnings by [@risu729](https://github.com/risu729) in [#5317](https://github.com/jdx/mise/pull/5317)
- **(doctor)** ignored config roots not displaying by [@jdx](https://github.com/jdx) in [#5336](https://github.com/jdx/mise/pull/5336)
- ls command does not respect MISE_COLOR value by [@roele](https://github.com/roele) in …

chore: release 2025.6.2

---

src/aqua/aqua_registry.rs

Reverts jdx/mise#5341
My apologies, I didn't check well and misunderstood that it fixed the issue. However, the warnings were just suppressed because there was a versions cache.

revert:  fix(aqua): parse templates in version_filter

---

schema/mise.json

Resolves https://github.com/jdx/mise/discussions/5355.

fix(schema): add missing tool options to schema

---

.github/workflows/hyperfine.yml
.github/workflows/registry.yml
.github/workflows/registry_comment.yml
.github/workflows/release-fig.yml
.github/workflows/release-plz.yml
.github/workflows/release.yml
.github/workflows/semantic-pr-lint.yml
.github/workflows/test-plugins.yml
.github/workflows/test.yml
.github/workflows/winget.yml

Revert "chore(deps): pin dependencies"

---

registry.toml

- [cspell](https://cspell.org/)
- [json5](https://json5.org/#cli)
- [ni](https://github.com/antfu-collective/ni)
- [prettier](https://prettier.io/)

feat(registry): adds npm backended tools

---

src/cli/self_update.rs

Should fix self-update issues as mentioned in #5500.

fix: enhance self-update for musl targets

---

registry.toml

I added it to the aqua registry in https://github.com/aquaproj/aqua-registry/pull/38315.

feat(registry): add zizmor

---

e2e/config/test_config_auto_install_disable_tools
settings.toml

Fixes https://github.com/jdx/mise/discussions/5539

fix: auto_install_disable_tools env var

---

registry.toml

Need to wait for https://github.com/aquaproj/aqua-registry/pull/38565.

fix(registry): use aqua and fix ubi options for yamlscript

---

src/backend/github.rs
src/github.rs
src/gitlab.rs
src/http.rs

* Github with also headers for private repo or private enterprise version
* Gitlab with private repo or private enterprise version
* Add download_file_with_headers

fix: private forges

---

Cargo.lock

Includes revert commit https://github.com/jdx/usage/pull/301.

chore: update usage

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(registry)** add `jsonschema` CLI tool by [@mrazauskas](https://github.com/mrazauskas) in [#5714](https://github.com/jdx/mise/pull/5714)
- mise up parallel execution by [@jdx](https://github.com/jdx) in [#5591](https://github.com/jdx/mise/pull/5591)
- add comprehensive CLAUDE.md for Claude Code guidance by [@jdx](https://github.com/jdx) in [#5718](https://github.com/jdx/mise/pull/5718)
- ubuntu ppa by [@jdx](https://github.com/jdx) in [#5715](https://github.com/jdx/mise/pull/5715)

chore: release 2025.7.18

---

.github/workflows/ppa-publish.yml

chore(ppa): wait for gh rate limit

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(pwsh)** set console encoding to UTF-8 to prevent Unicode garbling by [@IMXEren](https://github.com/IMXEren) in [#5732](https://github.com/jdx/mise/pull/5732)
- **(registry)** set matching_regex for glab on Windows to pick the correct asset by [@risu729](https://github.com/risu729) in [#5727](https://github.com/jdx/mise/pull/5727)
- **(config)** fix alias section name by [@malept](https://github.com/malept) in [#5736](https://github.com/jdx/mise/pull/5736)
- fix typo in contributing commit message prefixes by [@malept](https://github.com/malept) in [#5737](https://github.com/jdx/mise/pull/5737)
- **(ppa)** wait for gh rate limit by [@jdx](https://github.com/jdx) in [#5721](https://github.com/jdx/mise/pull/5721)
- @malept made their first contribution in …

chore: release 2025.7.19

---

src/shell/pwsh.rs
src/shell/snapshots/mise__shell__pwsh__tests__activate.snap

- Removed the hardcoded path to mise.
- I apologise for the mistake in #5732

fix(pwsh): resolve issue caused by previous #5732 patch (hardcoded path)

---

docs/tasks/task-configuration.md

fix `running tasks this will _will_ have`

task-configuration.md: typo

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(copr)** disable self-update by [@jdx](https://github.com/jdx) in [#5780](https://github.com/jdx/mise/pull/5780)
- **(link.md)** correct example comment in mise link documentation by [@mmurdockk](https://github.com/mmurdockk) in [#5760](https://github.com/jdx/mise/pull/5760)
- use github releases in install.sh for non-current version by [@jdx](https://github.com/jdx) in [c2b1ef1](https://github.com/jdx/mise/commit/c2b1ef1c53d736e14fb64365aa1339dc955d6c59)
- @mmurdockk made their first contribution in [#5760](https://github.com/jdx/mise/pull/5760)

chore: release 2025.7.27

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(http)** show retry after for github rate limit by [@risu729](https://github.com/risu729) in [#5803](https://github.com/jdx/mise/pull/5803)
- **(registry)** add carapace by [@jahands](https://github.com/jahands) in [#5804](https://github.com/jdx/mise/pull/5804)
- **(registry)** add `hatch` by [@hasansezertasan](https://github.com/hasansezertasan) in [#5788](https://github.com/jdx/mise/pull/5788)
- tool-stubs by [@jdx](https://github.com/jdx) in [#5795](https://github.com/jdx/mise/pull/5795)
- used shared cache for http backend by [@jdx](https://github.com/jdx) in [#5808](https://github.com/jdx/mise/pull/5808)
- **(aqua)** avoid unnecessary head requests in version resolution by [@risu729](https://github.com/risu729) in [#5800](https://github.com/jdx/mise/pull/5800)
- **(toolset)** use …

chore: release 2025.7.28

---

registry.toml

[Amp](https://ampcode.com/manual) is a really good AI coding tool built by [Sourcegraph](https://sourcegraph.com/)

feat(registry): add amp

---

docs/lang/python.md

Revert "docs: fix uv_venv_create_args reference for python"

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(python)** Windows OS no longer suffixed with `-shared` by [@malept](https://github.com/malept) in [#5879](https://github.com/jdx/mise/pull/5879)

chore: release 2025.8.2

---

registry.toml

Adding the atuin package: https://atuin.sh/

feat(registry): add atuin package to registry

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- add git-lfs ([aqua:git-lfs/git-lfs](https://github.com/git-lfs/git-lfs)) by [@TyceHerrman](https://github.com/TyceHerrman) in [#5885](https://github.com/jdx/mise/pull/5885)
- **(registry)** add atuin package to registry by [@TyceHerrman](https://github.com/TyceHerrman) in [#5883](https://github.com/jdx/mise/pull/5883)
- introduce registry commit type for new tool additions by [@jdx](https://github.com/jdx) in [#5884](https://github.com/jdx/mise/pull/5884)
- **(aqua,github)** make asset name matching case-insensitive by [@jdx](https://github.com/jdx) in [#5886](https://github.com/jdx/mise/pull/5886)
- **(ci)** separate Alpine release into its own workflow by [@jdx](https://github.com/jdx) in [#5868](https://github.com/jdx/mise/pull/5868)
- **(changelog)** automate backend links in …

chore: release 2025.8.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(tasks)** **breaking** Add environment variable directives for mise tasks by [@jdx](https://github.com/jdx) in [#5638](https://github.com/jdx/mise/pull/5638)

chore: release 2025.8.4

---

registry.toml

Add dotenvx package: dotenvx.com/docs

registry: add dotenvx (aqua:dotenvx/dotenvx)

---

registry.toml

Add oxlint package: https://oxc.rs/docs/guide/usage/linter.html

registry: add oxlint (aqua:oxc-project/oxc/oxlint)

---

registry.toml

Add apple container package: https://apple.github.io/container/documentation/

registry: add container (aqua:apple/container)

---

registry.toml

Add resvg package: https://github.com/linebender/resvg

registry: add resvg (aqua:linebender/resvg)

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- add python to gcloud dependencies by [@risu729](https://github.com/risu729) in [#5936](https://github.com/jdx/mise/pull/5936)
- **(toolset)** properly handle MISE_ADD_PATH from plugins by [@jdx](https://github.com/jdx) in [#5937](https://github.com/jdx/mise/pull/5937)

chore: release 2025.8.7

---

registry.toml

Add container-use package: [https://container-use.com/](https://container-use.com/)

registry: add container-use (aqua:dagger/container-use)

---

docs/installing-mise.md

Added openSUSE `zypper` install instructions.

docs: added openSUSE zypper install instructions

---

.github/workflows/registry.yml
.github/workflows/registry_comment.yml

It's added in https://github.com/jdx/mise/issues/5067, but the comment is moved to another workflow so this is no longer required.

chore: remove unused permissions in registry test

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- add container-use ([aqua:dagger/container-use](https://github.com/dagger/container-use)) by [@TyceHerrman](https://github.com/TyceHerrman) in [#6029](https://github.com/jdx/mise/pull/6029)
- add prek ([aqua:j178/prek](https://github.com/j178/prek)) by [@HenryZhang-ZHY](https://github.com/HenryZhang-ZHY) in [#6023](https://github.com/jdx/mise/pull/6023)
- **(task)** allow more #MISE comments patterns by [@risu729](https://github.com/risu729) in [#6011](https://github.com/jdx/mise/pull/6011)
- prevent panic with task tera errors by [@jdx](https://github.com/jdx) in [#6046](https://github.com/jdx/mise/pull/6046)
- **(settings)** use php as an example for `disable_default_registry` by [@risu729](https://github.com/risu729) in [#6025](https://github.com/jdx/mise/pull/6025)
- Update …

chore: release 2025.8.11

---

mise.lock
xtasks/release-plz

- **chore(release-plz): get `git status`**
- **chore(release-plz): add `mise.lock`**

chore(release-plz): add mise.lock

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
aqua-registry/pkgs/aquasecurity/kube-bench/pkg.yaml
aqua-registry/pkgs/bahdotsh/wrkflw/pkg.yaml
aqua-registry/pkgs/fujiwara/maprobe/pkg.yaml
aqua-registry/pkgs/gruntwork-io/terragrunt/pkg.yaml
aqua-registry/pkgs/jdx/mise/pkg.yaml
aqua-registry/pkgs/jenkins-x/jx/pkg.yaml
aqua-registry/pkgs/tstack/lnav/pkg.yaml
aqua-registry/pkgs/tstack/lnav/registry.yaml
aqua-registry/pkgs/ziglang/zig/pkg.yaml
aqua-registry/pkgs/ziglang/zig/registry.yaml
aqua-registry/registry.yaml
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- **(env)** add --redacted and --values flags to env command by [@jdx](https://github.com/jdx) in [#6103](https://github.com/jdx/mise/pull/6103)

chore: release 2025.8.18

---

registry.toml

follow up of https://github.com/jdx/mise/pull/6100

registry: remove asdf plugin for watchexec

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
aqua-registry/pkgs/block/goose/pkg.yaml
aqua-registry/pkgs/encoredev/encore/pkg.yaml
aqua-registry/pkgs/kyverno/chainsaw/pkg.yaml
aqua-registry/pkgs/linkerd/linkerd2/pkg.yaml
aqua-registry/pkgs/openfaas/faas-cli/pkg.yaml
aqua-registry/pkgs/projectdiscovery/nuclei/pkg.yaml
aqua-registry/pkgs/rclone/rclone/pkg.yaml
aqua-registry/pkgs/sourcemeta/jsonschema/pkg.yaml
aqua-registry/pkgs/speakeasy-api/speakeasy/pkg.yaml
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
mise.lock
packaging/rpm/mise.spec

- use fish_add_path when activating mise for fish shell by [@roele](https://github.com/roele) in [#6074](https://github.com/jdx/mise/pull/6074)

chore: release 2025.8.20

---

src/cli/run.rs

Fixes issue mentioned in #6121

fix: task confirmation does not handle SIGINT appropriately

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
aqua-registry/pkgs/alexellis/arkade/pkg.yaml
aqua-registry/pkgs/syncthing/syncthing/pkg.yaml
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- python nested venv path order by [@elvismacak](https://github.com/elvismacak) in [#6124](https://github.com/jdx/mise/pull/6124)
- resolve immutable release workflow and VERSION file timing issues by [@jdx](https://github.com/jdx) in [#6187](https://github.com/jdx/mise/pull/6187)
- @elvismacak made their first contribution in [#6124](https://github.com/jdx/mise/pull/6124)

chore: release 2025.9.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
aqua-registry/pkgs/altsem/gitu/pkg.yaml
aqua-registry/pkgs/crates.io/gitu/pkg.yaml
aqua-registry/pkgs/nao1215/sqly/pkg.yaml
aqua-registry/pkgs/redpanda-data/redpanda/pkg.yaml
aqua-registry/pkgs/suzuki-shunsuke/tfcmt/pkg.yaml
completions/_mise
completions/mise.bash
completions/mise.fish
default.nix
packaging/rpm/mise.spec

- fix git-cliff on release by @jdx in [3c388f2](https://github.com/jdx/mise/commit/3c388f28e6cce6084f86e1805ace3aede594405b)

chore: release 2025.9.4

---

default.nix

fix: nix flake build failure on macOS

---

test/fixtures/mise-test-tool/README.md
test/fixtures/mise-test-tool/bin/mise-test-tool
test/fixtures/mise-test-tool/bin/mise-test-tool.cmd
test/fixtures/mise-test-tool/package.json

Squashed 'test/fixtures/mise-test-tool/' content from commit 0b8c5db0c
git-subtree-dir: test/fixtures/mise-test-tool
git-subtree-split: 0b8c5db0c8e74fd3db4324875174cc408f495a9b
Merge commit 'dba66ecaa33c05b9eedffe6d67a08c0fed0e3549' as 'test/fixtures/mise-test-tool'

Squashed 'test/fixtures/mise-test-tool/' content from commit 0b8c5db0c

---

registry.toml

Add just-every/code to registry: https://github.com/just-every/code

registry: add code

---

src/cli/cache/prune.rs

Fixes https://github.com/jdx/mise/discussions/6514

fix(cache): remove duplicate bytes in prune output

---

registry.toml

This is the cli tool for managing [Cloudflare Workers](https://developers.cloudflare.com/workers/wrangler/)

registry: added cloudflare wrangler

---

docs/lang/python.md

docs: Update Python virtual environment documentation

---

Cargo.toml

It shows verbose logs.
```
DEBUG ignoring /home/risu/.ghr/github.com/risu729/aqua-registry/.prettierrc.json: Ignore(IgnoreMatch(Hidden))
DEBUG ignoring /home/risu/.ghr/github.com/risu729/aqua-registry/.github: Ignore(IgnoreMatch(Hidden))
DEBUG ignoring /home/risu/.ghr/github.com/risu729/aqua-registry/docker/aqua-policy.yaml: Ignore(IgnoreMatch(Gitignore(Glob { from: Some("/home/risu/.ghr/github.com/risu729/aqua-registry/.gitignore"), original: "docker/aqua-policy.yaml", actual: "docker/aqua-policy.yaml", is_whitelist: false, is_only_dir: false })))
DEBUG opened gitignore file: /home/risu/.ghr/github.com/risu729/renovate/.gitignore
DEBUG glob converted to regex: Glob { glob: "config.js*", re: "(?-u)^config\\.js[^/]*$", opts: GlobOptions { case_insensitive: false, literal_separator: true, …
```

fix: suppress ignore crate logs
